### ISSUE TITLE
epic(admin-donor): improve donor UI

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#1206]
## Issue Overview

Right now when you view the donor UI it can be confusing for first time users. Here's a screenshot:

![2016-11-02_20-17-21](https://cloud.githubusercontent.com/assets/1571635/19954935/2fc21a12-a13a-11e6-948e-0358a2b3366e.png)

I propose we research how we can improve the UI, determine which donor specific stats and reports and valuable on this screen, create a wireframe, review the wireframe, agree on the layout, design it and move forward with implementation.

**Comment by mehul0810** [comment]
I have reviewed all the referenced issues and based on which I have improved the Donor UI to make sure that each tab in existing view can be managed from a single view. Also, I have attached 2 variations of Improved Donor UI having minor changes in both the variations.

# **Variation 1**
![updated_donor_ui_version_1](https://cloud.githubusercontent.com/assets/1852711/25094158/7c7d8656-23b3-11e7-85c3-d83617f3d929.png)

# **Variation 2**
![updated_donor_ui_version_2](https://cloud.githubusercontent.com/assets/1852711/25094170/8783d500-23b3-11e7-89ae-43ab86ed544e.png)

@DevinWalker Please check and let me know, if there are any further suggestions or improvements.

**Workflow of Delete Donor button:** On click, it will open up a popup which will show content of Delete Donor tab from the existing view. 

**Even the ordering of the accordions should be changed as below:**
1. Recent Donations
2. Donor Notes
3. Completed Forms
4. Donor Emails

Also, I think Donor UI requires improvement in responsive layouts as well. This will help users to have better UX of admin settings. Do let me know your thoughts on this as well.

**Comment by DevinWalker** [comment]
Closing as we've created a Feedback item for this: https://givewp.canny.io/feature-requests/p/improve-admin-donor-profile-view

Feel free to upvote if you feel this would be a great addition!
