### ISSUE TITLE
Replace the use of `type="tel"` on CC inputs for `pattern=”[0-9]*”` for better semantics

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#1310]
## Issue Overview
This support topic brought up an interesting perspective: https://wordpress.org/support/topic/give-amount-inputtypetel/

Links of interest:
http://bradfrost.com/blog/mobile/better-numerical-inputs-for-mobile-forms/

Nifty demo for testing:
http://bradfrost.com/demo/tel/

## Expected Behavior
When on mobile, you tap the credit card field and the numerical keyboard opens.

## Current Behavior
The numerical keyboard opens but it we use type="tel" which isn't the best semantically and could cause complications down the road. 

## Possible Solution
Replace the usage throughout all fields including CC#, CVC, Expiration, Amount.

## Steps to Test (for bugs)

1. Android and iOS mobile browsers
2. Click on all numerical fields
3. Review which keyboard opens

## Related PRs
List related PRs against other branches:

## Todos
- [ ] Tests
- [ ] Development

**Comment by DevinWalker** [comment]
Closing due to conversation here: https://github.com/WordImpress/Give/issues/2269#issuecomment-341333790

`tel` seems to be acceptable and widely used on the interwebs.

**Comment by mathetos** [comment]
@DevinWalker Is this resolved actually?

**Comment by DevinWalker** [comment]
I don't understand the question. We decided to leave `tel` as the field type. That's how the issue has been resolved.

**Comment by Benunc** [comment]
We get a request about this about once per quarter. Is this something where we can add a filter to give to devs who insist on the other method?

**Comment by mathetos** [comment]
[Mobile recommendation from Stripe](https://github.com/stripe-archive/jquery.payment#mobile-recommendations) is still to use `tel` ... and @JasonTheAdams keeps pushing us to avoid filters for extending things like this. 

I think we can have a canned response for the devs that need more info to understand this choice. 

Just my two cents.

**Comment by kevinwhoffman** [comment]
[inputmode](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inputmode) is a more modern solution to the problem and it is supported by the mobile browsers where it's actually needed.

```html
// 0-9 digits only (GoFundMe currently uses this)
<input type="text" inputmode="numeric">

// 0-9 digits with decimal separator
<input type="text" inputmode="decimal">
```

With that said, the only reason I would change from `tel` at this time is if we wanted to display the decimal (`.`) separator on mobile devices. From an accessibility perspective, the `tel` input type is announced like any other text field when I tested VoiceOver just now.

If you continue to see requests to change this, please pass along the rationale from the customer so we can understand why they want it changed.

**Comment by kevinwhoffman** [comment]
This topic came up again today in free support:
https://wordpress.org/support/topic/unable-to-use-decimal-point-in-donation-box/

The trend of feedback that I see is that they want to see a `.` decimal point on iOS. This could be solved by using `inputmode="decimal"` like so:
```html
// 0-9 digits with decimal separator
<input type="text" inputmode="decimal">
```

Just make sure we are validating the input server side because some older browsers like IE11 may not limit the input to numbers and decimals.

**Comment by DevinWalker** [comment]
Closing as I've brought this into Canny for further votes and consideration: https://givewp.canny.io/feature-requests/p/replace-the-use-of-typetel-on-cc-inputs
