### ISSUE TITLE
fix: improper values and validation in admin settings

### ISSUE THREAD

**Issue by mehul0810** [impress-org/givewp#1800]
## Issue Overview
This issue is generated while settings a success and failure page for donation.

## Expected Behavior
1. There should not be any empty value in dropdown of `Success Page` and `Failed Donation Page`.
2. When saving empty values for both dropdowns give an error `You cannot set the success and failed pages to the same page` which should not be the case as those empty values are not pages.
3. Error shown on saving empty values should be a error notice in red, not the success notice in green.

## Current Behavior
1. There exists first option element in dropdown as empty value.
2. When saving with empty values in both the dropdown gives error.
3. Error shown on saving with empty values is with success notice.

## Possible Solution
Seems like a improper values and validation issue. Need to investigate in detail.

## Steps to Reproduce (for bugs)
1. Go to `Donations > Settings > General`
2. Change value of `Success Page` and `Failed Donation Page` to first element with empty values for both.
3. On saving it will show error with success notice.

## Todos
- [ ] Investigate Issue
- [ ] Fix
- [ ] Test

**Comment by ravinderk** [comment]
@DevinWalker As, I discuss this with you about date validation also.

**Comment by DevinWalker** [comment]
This has not been a common admin issue and with our new onboarding wizard it should become less so. Closing.
