### ISSUE TITLE
doc: clarify usage of payment ID versus transaction ID

### ISSUE THREAD

**Issue by mathetos** [impress-org/givewp#2306]
## Issue Overview
We currently have two main types of IDs that we reflect in our donation receipts:

* Payment/Donation ID
* Transaction ID

In our email tags and donation confirmation page we call those very different things both in Give core and in PDF Receipts in particular. We need to be consistent to avoid confusion with our users.

## Expected Behavior
That each time the donation id or transaction id is used that the language is consistent.

## Current Behavior
It's currently very inconsistent. I'll try to explain clearly here:

**PAYMENT/DONATION ID**
On the Donation Confirmation/History page it's "Donation ID"
![image](https://user-images.githubusercontent.com/930724/32526204-f9e8e882-c3dc-11e7-84f4-dc098d900ad4.png)

On the email donation receipt it's called "Payment ID" and the email tag is also `{payment_id}`
![image](https://user-images.githubusercontent.com/930724/32526233-1ebdd0fa-c3dd-11e7-8ea8-7ec9bb0802c2.png)

In PDF Receipts it's both the `{payment_id}` and the `{transaction_id}`
![image](https://user-images.githubusercontent.com/930724/32526265-47192dc4-c3dd-11e7-8d96-13c71417f88e.png)

In the Donation Details screen its "Donation ID"
![image](https://user-images.githubusercontent.com/930724/32526337-a7034a30-c3dd-11e7-9e55-e4f2ce37c3e4.png)

**TRANSACTION ID**
On the Donation Details screen it's called "Key"
![image](https://user-images.githubusercontent.com/930724/32526392-e588165a-c3dd-11e7-9991-c8ceeeee6a1e.png)

On the Email Notification it's called "Receipt ID" and `{receipt_id}`
![image](https://user-images.githubusercontent.com/930724/32526422-0c6a4da6-c3de-11e7-8540-3e9009931799.png)

In PDF Receipts it's called "Transaction Key" and `{transaction_key}`
![image](https://user-images.githubusercontent.com/930724/32526476-488bfec4-c3de-11e7-95b5-e6e9020da6d8.png)

**MY RECOMMENDATION**
Payment ID should ALWAYS be called "Donation ID" and the email tag should ALWAYS be `{donation_id}` only.

The Transaction Key should always be "Transaction Key" and the email tag should ALWAYS be `{transaction_key}`

**Comment by DevinWalker** [comment]
Closing this one out because no users have requested it and donors don't seem to be confused. Ideally the email and PDF receipts would follow suit by calling it `Donation ID` but I think it works fine calling it `Payment ID` because it appears below the `Payment Method` line item. As well, you point our the transaction key a number of times. That's only an internal hash key we use and is entirely separate from the donation ID.
