### ISSUE TITLE
fix: improve and refactor donor profile

### ISSUE THREAD

**Issue by mehul0810** [impress-org/givewp#2414]
## Issue Overview
There are some of the sections in `give_profile_editor` shortcode which needs to be refactored.

- Add Tooltips similar to each form fields of donation forms in front end.
- We have Server side validation. But, Add Client Side validations as well similar to donation forms in front end.
- Simplify Email Validation code with existing fn `give_validate_user_email`. For Ref: https://github.com/WordImpress/Give/blob/release/1.8.17/includes/shortcodes.php#L443

Tooltips and Client Side Validation of donation forms:
![image](https://user-images.githubusercontent.com/1852711/33264288-ee4f460e-d392-11e7-82c4-8e48ba7f0b8b.png)

## Todos
- [ ] Tests
- [ ] Documentation

## WordPress Environment
<details>

### WordPress Environment ###

Home URL: http://givebase.local
Site URL: http://givebase.local
WP Version: 4.9
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /blog/%category%/%postname%/
Show on Front: posts
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Inaccessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: givebase.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.1
PHP Version: ❌ 5.3.29 - We recommend a minimum PHP version of 5.6. See: PHP Requirements in Give
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.2h - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 1.8.17
Upgraded From: 1.8.17
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://givebase.local/donation-confirmation/
Failure Page: http://givebase.local/donation-failed/
Donation History Page: http://givebase.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Admin Email Notifications: Disabled
Donor Email Access: Disabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Other Active Plugins ###

Give - Payfast Payment Gateway: by WordImpress – 1.0
Query Monitor: by John Blackbourn – 2.17.0

### Inactive Plugins ###

Duplicate Post: by Enrico Battocchi – 3.2
Give - Form Field Manager: by WordImpress – 1.2.4
Give - Manual Donations: by WordImpress – 1.2
Give - Recurring Donations: by WordImpress – 1.4
Mehul Customization: by  – 1.0
WP Default Notices: by  – 1.0.0

### Active MU Plugins ###

Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.3
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by mathetos** [comment]
I think there's a few more items that need to be added here. Essentially, anything that we collect during donation, or that appears on the Donor profile screen in the backend, should also be available in the `give_profile_editor` to edit as well. 

Currently, here are the items that are NOT implemented in the editor at all:

* Address
* Company Name
* Title
* Add secondary email addresses

**Comment by mehul0810** [comment]
@DevinWalker @mathetos 

## Why we need to improve donor profile?
We need to improve the donor profile to ensure that we provide a better card management experience for donors as currently with Stripe and Recurring it is the incorrect way we are providing to our users which automatically assigns the recently used card as default card. This should not be the ideal behavior. Check more details on the issue https://github.com/impress-org/give/issues/4108

## Donor Profile Designs

Please find the 2 different versions of mockup design samples for donor profile.

### Version 1
1. Default View after login
![Donor Profile 1 - Default](https://user-images.githubusercontent.com/1852711/58468186-b974f380-815a-11e9-9304-15c47933da0e.png)

2. Edit Profile
![Donor Profile 1 - Edit Profile](https://user-images.githubusercontent.com/1852711/58468189-b974f380-815a-11e9-9053-7648d6ab28bb.png)

3. Change Password
![Donor Profile 1 - Change Password](https://user-images.githubusercontent.com/1852711/58468190-ba0d8a00-815a-11e9-8bc3-56e3e810f294.png)

4. Secondary Emails
![Donor Profile 1 - Secondary Emails](https://user-images.githubusercontent.com/1852711/58468794-dcec6e00-815b-11e9-8bca-bc63968d58f5.png)

5. Manage Donor Addresses
![Donor Profile 1 - Addresses](https://user-images.githubusercontent.com/1852711/58468811-e4ac1280-815b-11e9-9602-a388009968f1.png)

6. Manage Cards - Use an existing card to set default.
![Donor Profile 1 - Use existing cards](https://user-images.githubusercontent.com/1852711/58468193-baa62080-815a-11e9-92dd-5bd6923def84.png)

7. Manage Cards - Enter a new card to change the card to set default.
![Donor Profile 1 - Enter a new card](https://user-images.githubusercontent.com/1852711/58468194-baa62080-815a-11e9-93ab-d6b983a601a2.png)

### Version 2 

I've created few samples for this version as the only change with this mockup is utilizing the vertical tabs layout. Let me know if you like this mockup design then I'll create all of them as shown in version.

1. Default Layout
![Donor Profile 2 - Default](https://user-images.githubusercontent.com/1852711/58468576-6c455180-815b-11e9-8fb9-b43aa4e1aa68.png)

2. Manage Cards
![Default Profile 2 - Card Information](https://user-images.githubusercontent.com/1852711/58468575-6c455180-815b-11e9-81c8-2060ca5bd169.png)

3. Change Password
![Donor Profile 2 - Change Password](https://user-images.githubusercontent.com/1852711/58468898-11602a00-815c-11e9-9627-61e19779918b.png)

Overall, I've collectively used the related issues and comments available on the issue to prepare these mockups to provide better user experience to donors.

Let me know your thoughts.

**Comment by DevinWalker** [comment]
Moved to Canny, closing as feedback has been added.
