### ISSUE TITLE
feat: add tools to assist with GDPR compliance

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#2458]
## Issue Overview
We need to ensure compliance with the EU General Data Protection Regulation regulation coming in May 2018.

## Questions

1. How do we best comply?
2. What does this mean for data handling?
3. How will this best be implemented for donors and admins?
4. What are other plugins like Woo and Yoast doing?

## Related

- https://www.eugdpr.org/eugdpr.org.html
- https://en.wikipedia.org/wiki/General_Data_Protection_Regulation
- https://pagely.com/blog/gdpr-wordpress-2018-resources/
- https://woocommerce.wordpress.com/2018/05/04/woocommerce-3-4-gdpr-features/

## Relevant Customer Tickets
_Internal Links only Give Team Members can view_
- https://secure.helpscout.net/conversation/569458449/17616/
- https://secure.helpscout.net/conversation/573649700/17882/
- https://secure.helpscout.net/conversation/571223995/17689/

**Comment by kevinwhoffman** [comment]
@ravinderk Here is the proposal that @mathetos put together. Please use it as a guide to break this epic into smaller issues and correspond with Matt if you need clarification.

https://docs.google.com/document/d/1AxR4IpdGLkzVxjazq1hTxATrvb3SSBEH7a1UacVLick/edit#

Matt describes 4 aspects in the proposal. The first 3 should be addressed in Give `2.2.0`.

1. Privacy Policy (2.2.0)
2. Personal Data Access (2.2.0)
3. Personal Data Erasure (2.2.0)
4. Data Retention (TBD)

**Comment by kevinwhoffman** [comment]
Moving this out of 2.3 since @ravinderk is focusing on Stats API and cannot take on both large issues in one release.

**Comment by DevinWalker** [comment]
Closing as we've created a Canny feedback here: https://givewp.canny.io/feature-requests/p/gdpr-compliance
