### ISSUE TITLE
feat: add custom data to Donation Details screen

### ISSUE THREAD

**Issue by mathetos** [impress-org/givewp#2471]
## Issue Overview
Admins often want to add additional information into their Donation Details. Sometimes it's historical data from donations they have imported, or that the donor calls in to say they want that donation done in Honor of someone. No matter the use-case, it would benefit our users to allow them to add Custom Data into the Donation Details screen.

A very specific use-case is customizing an Offline donation with Tribute data. A check comes in the mail and it says that it's in honor of someone. They could enter it via the front-end, but customizing donation details via the Admin is what accountants and other admins are most accustom to.

## Possible Solution
I think there's three routes we can take on this:

1) That our existing "Donation Notes" metabox get revamped to be a bit more powerful. Meaning that it could be tied to existing donation meta, like choosing that the note is part of the Tribute, and that they would be included in the Exports (this is the biggest reason why Notes don't already suit this purpose).

2) We create a new Custom Metabox that allows you to add specifically available custom meta that is tied to available Core meta or Addon meta. 

3) The third route is that this doesn't go into Core at all, but instead we support ALL our Add-ons meta data in our Manual Donations Add-on. This might be ideal, but I also see a lot of use in doing this in Core.

The goal of all of this is flexibility for our customers to be able to customize their donations details as much as they need to.

**Comment by DevinWalker** [comment]
Related to #959

**Comment by mathetos** [comment]
This came up again with a customer here:
https://secure.helpscout.net/conversation/842556980/38500?folderId=672194

I think what we need to do is when users use the Donation Import, that when they choose "Import as Meta" that those fields appear in the Donation Details screen automatically just like the Form Field Manager custom fields do currently as well. 

![image](https://user-images.githubusercontent.com/930724/57048058-7725c880-6c27-11e9-899b-c0aa45ae87e0.png)

**Comment by DevinWalker** [comment]
Closing as we've created a new Canny feedback for it here: https://givewp.canny.io/feature-requests/p/add-custom-data-to-donations-and-donors
