### ISSUE TITLE
build(phpcs): automate validation of WPCS prior to commit

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#2793]
## Issue Overview

I reviewed many pull request for `Give` and found that most of the developers forget to fix code formatting issue in php.

To resolve this issue we can sniff files change on commit. To achieve that we can create `hooks` folder inside `.github` ( move existing template to `template` folder ) and write step to set developer environment for `Give`.

Ref:
https://www.viget.com/articles/two-ways-to-share-git-hooks-with-your-team/
https://gist.github.com/wesbos/8aec9d2ff7f7cf9dd65ca2c20d5dfc23

**Note:** This process at least reduces one cycle of review and save time too 💯

**Comment by DevinWalker** [comment]
We're not going to be using WP coding standards in the future so I'm closing this issue. In Campaigns we are using Husky and PSR-4 and that will be the future of Core and add-ons.
