### ISSUE TITLE
doc(admin-setting): clarify language of PayPal IPN option

### ISSUE THREAD

**Issue by Benunc** [impress-org/givewp#2808]
## Issue Overview
The language of the help text below the "PayPal IPN Verification" does say whether enabling or disabling the IPN verification is "less secure."

## Expected Behavior
The Language should clearly state which option is the less secure one.

## Current Behavior
`If donations are not getting marked as complete, use a slightly less secure method of verifying donations.`

## Possible Solution
Change this line:
https://github.com/WordImpress/Give/blob/master/includes/admin/class-give-settings.php#L363

Change the string to:

`If donations are not getting marked as complete, select "Disabled" here to use a slightly less secure method of verification.`

**Comment by Benunc** [comment]
I'm 90% sure that the "less secure" option is "Disabled" and the default is "Enabled" but verify that before fixing.

**Comment by DevinWalker** [comment]
Fixed here: https://github.com/impress-org/givewp/commit/0810ee0f6929e1f6307c77d819a60aa80088e1a4
