### ISSUE TITLE
epic(admin-report): overhaul admin reports with Give dashboard

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/givewp#2889]
## User Story

As a current Give user, I want a more intuitive report experience so that I can quickly gather the information I need to gauge success and get excited about coming back tomorrow.

As a developer...

As a potential Give user...

## Current Behavior

I currently have to navigate through several screens to gather information from reports that are difficult to read. While the information is available, it is difficult to gather and lacks high-level reporting metrics. The current experience is not something that invites be back day after day with excitement. Instead it is something I interact with only when I _have_ to in order to gather data.

## Expected Behavior

I expect a robust dashboard experience that allows me to quickly gauge the performance of my campaigns with the ability to drill down into specific reports at the form, donation, and donor levels.

**Comment by DevinWalker** [comment]
Closing as we've revamped reports and now it's time to improve and iterate.
