### ISSUE TITLE
feat(donation): support Text-to-Donation

### ISSUE THREAD

**Issue by mathetos** [impress-org/givewp#3025]
## User Story
As a Give Admin and a nonprofit organization, I want my donors to be able to make quick donations simply by texting us. This is a proven strategy for large NGOs like the Red Cross or for faith-based congregations and I want to be able to provide that functionality for my members.

## Current Behavior
I currently cannot do this with any existing feature of Give. If I wanted to develop this on my own, I'd need to first make the Give API have write-access (it's currently only a read-access API). 

## Expected Behavior
I expect to either have an Add-on that does this, or have a write-access API which will enable me to build this on my own.

## Possible Solution
This isn't a solution, but suggestions for what this might look like within the Give plugin.

1. A settings screen to integrate with an existing SMS service (Twilio is probably the best example: https://www.twilio.com/docs/api )

2. Each form would  have settings available that would allow the Admin to do two things:
    a. Ask donors in the form whether they want to enable "text-to-give" for future contributions. If "Yes" then ask for their mobile number.
    b. Set the hashtag and/or keyword that must be in the texted message in order to trigger the donation when the text is received.

3. On the donor screen, there should be a mobile number field, and it should show whether the donor has opted into text-to-give or not.

4. There should be a dedicated report on the amounts received via text-to-give

5. There should be a dedicated export for donations given over text-to-give

6. The import tool should support importing donations an indicating whether it was a text-to-give donation or not and optionally what the hashtag or keyword was when giving.

## Customer Requests
- https://secure.helpscout.net/conversation/551321929/16141?folderId=1823994
- https://secure.helpscout.net/conversation/551315825/16139/?folderId=1836751
- There are many more, but these are the recent ones.

**Comment by kevinwhoffman** [comment]
This looks like a good add-on to me, and I think Twilio is the way to go with its established, well-documented API.

@DevinWalker if you agree, I think we should do the following:

1. Create `epic: make Give API writable` since that is a prerequisite for donating via text.
2. Create an add-on repo and move this issue to it so that we don't lose Matt's request.

**Comment by allienimmons** [comment]
Another customer request! https://secure.helpscout.net/conversation/933348233/45506/

**Comment by kevinwhoffman** [comment]
Moving to Canny for further validation and to collect use cases more easily: https://givewp.canny.io/feature-requests/p/text-to-give
