### ISSUE TITLE
feat: allow for splitting donations across multiple causes

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#3054]
@Benunc commented on [Wed Jun 14 2017](https://github.com/WordImpress/Give-Snippet-Library/issues/34)

## Issue overview

This is a much-requested feature. Donors are far more likely to give once than they are 4 or 5 times back-to-back, so giving them a way to support multiple causes in one transaction would be preferable. 

The best way to describe it is with this example:

### Use Case: churches 
A church as 4 causes, all with separate forms for accounting to be able to keep the data separate.
1. General Fund
2. Missionary A
3. Missionary B
4. Homeless ministry

If a donor wants to give in one donation to all 4 causes, that's not currently possible. This is extremely common in church giving, where the memo line of the check denotes a portion of the giving to each fund.

## Proposed solution:
This will likely require the data restructuring that is coming in 2.0, but some sort of process that sits in between the submission of the donation from the front end and the processing of it on the back end, that splits the donation out to multiple forms, with options to enable receipts for each individual form, or just a receipt for the parent form. 

In this case, we would be creating not even a "form" in the way we think of them, but a sort of "pre-form" that routes donations through forms. 

#### Considerations:
It's likely that sending individual donations through to the gateway back-to-back will cause fraud warnings to go up (either at the gateway, or at the donor's credit card company), so sending money all at once would be preferable (the donor should only see one receipt from the payment gateway, after all. To them, it was one transaction.)

This would create a discrepancy between the gateway logs and the give logs, and would be especially problematic for recurring donations. 

---

@mathetos commented on [Wed Jun 14 2017](https://github.com/WordImpress/Give-Snippet-Library/issues/34#issuecomment-308558427)

The biggest complication with this isn't assigning multiple "funds" but reporting on that in the backend. Because the reporting is crucial for Accounting to know how to divvy up that lump sum and digging through the Donation Details of every donation isn't realistic.

---

@Benunc commented on [Wed Dec 06 2017](https://github.com/WordImpress/Give-Snippet-Library/issues/34#issuecomment-349696337)

another request for this today

---

@Benunc commented on [Mon Feb 05 2018](https://github.com/WordImpress/Give-Snippet-Library/issues/34#issuecomment-363192051)

Another request for this today.

---

@Benunc commented on [Fri Feb 16 2018](https://github.com/WordImpress/Give-Snippet-Library/issues/34#issuecomment-366325300)

a request from Facebook for this:

> Its Great Overview, Just want to Know, If some one want to Donate 2 campaign together, will it add that to the cart like easy digital download do. so that Donation for Water 10$ and Donation for River 20$  in total 30$ can be paid in total together , is this supported with this plugin

Related Help Scout tickets:
https://secure.helpscout.net/conversation/671724408/26295?folderId=672197
https://secure.helpscout.net/conversation/919662995/44562
https://secure.helpscout.net/conversation/923015749/44785
https://secure.helpscout.net/conversation/923844128/44836
https://secure.helpscout.net/conversation/927974826/45142/

**Comment by mathetos** [comment]
We added new and relevant customer requests above in the original ticket above just to show that this continues to be a common customer concern.

**Comment by kevinwhoffman** [comment]
Moving to Canny for further validation. In reviewing the feedback, I identified two separate jobs and believe we should track them separately because they have different implications for a possible solution:

- [Split Donations](https://givewp.canny.io/feature-requests/p/split-donations) - splitting a single donation across multiple funds
- [Donation Designations](https://givewp.canny.io/feature-requests/p/donation-designations) - designating the entirety of one donation to a single fund
