### ISSUE TITLE
fix(CLI): change the default gateway when disabling test-mode via CLI

### ISSUE THREAD

**Issue by Benunc** [impress-org/givewp#3065]
## User Story

As a `developer`, I want `use the test-mode Give CLI subcommand with a flag of --disable and have the test gateway not remain "default" and also "off"` so that `when I turn off test-mode via CLI my site contimues to function correctly.

## Current Behavior
I currently, from the terminal, use the command `wp give test-mode --enable` which enables the test gateway, and makes it the default gateway. Then when I go to reverse the process, it leaves it as default, but disables it. This is a process that is causght via JS on the GUI, but not caught via CLI.  

## Expected Behavior

I expect for any change that `--enable` makes, `--disable` should do the opposite. 

## Possible Solution
If test mode is initiated via CLI, save a transient with which gateway was previously default and return to that.

Or, abandon the procedure of making Test gateway default during "enable"

## Steps to Reproduce
1. Fresh install, ssh into the box.
2. cd to any directory within WP.
3. run `wp give test-mode --enable`
4. run `wp give test-mode --disable`
5. In the browser, navigate to Donations > Settings > Payment Gateways (tab)

Test Gateway is still set as default, even though it it not active. It may require repeating steps 3 and 4 while already on the page to replicate.

## Visuals
![screen shot 2018-04-18 at 4 57 33 pm](https://user-images.githubusercontent.com/9629102/38957899-b5de5c54-4329-11e8-8afb-e1345f1d197f.png)

## Related
- #2878

## Tasks

- [ ] 

## Environment

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://betagive.local
Site URL: http://betagive.local
WP Version: 4.9.5
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: betagive.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.10 (Debian)
PHP Version: 7.1.4
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.1.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Email access
Upgraded From: –
Test Mode: Disabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://betagive.local/donation-confirmation/
Failure Page: http://betagive.local/donation-failed/
Donation History Page: http://betagive.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Offline Donation
Default Payment Gateway: Offline Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Session Configuration ###

Give Use Sessions: Enabled
Session: Disabled

### Theme ###

Name: Twenty Seventeen
Version: 1.5
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by DevinWalker** [comment]
It's a nice request but I don't see us getting to this anytime soon. It would be a nice weekend project for you though @Benunc 😉
