### ISSUE TITLE
feat(admin-tools): Add documentation links programatically to Tools tabs

### ISSUE THREAD

**Issue by mathetos** [impress-org/givewp#3136]
## User Story
As a Give Admin, if I have questions about the Tools panel, I'd like to be able to easily get to documentation on these features so that I can inform myself on all these options proactively.

## Current Behavior
I currently have to go to the website and search for the docs manually. 

## Expected Behavior
I expect to be directed to the relevant docs with just a click.

## Possible Solution
I'd suggest it be implemented in a very similar manner to our Settings pages, but I'd prefer the link to be at the top of the page, not the bottom where it can easily be missed or ignored.

Like so:

![image](https://user-images.githubusercontent.com/930724/39454524-b74da4e4-4c90-11e8-9bb3-0b958b9bd92c.png)

**Comment by kevinwhoffman** [comment]
@mathetos Please add a list of doc URLs and Call to Actions that will be used for each tab.

**Comment by kevinwhoffman** [comment]
Moving to Canny as a request for contextual documentation: https://givewp.canny.io/documentation/p/tools
