### ISSUE TITLE
fix: clarify the UI for custom field exports

### ISSUE THREAD

**Issue by Benunc** [impress-org/givewp#3197]
## User Story

As a `give user`, I want `to be made aware of the process for exporting custom field data` so that `my exports are as accurate as possible`.

The UI is currently a bit unclear
from @slewisma:

> custom fields are only exportable if you choose a specific form. Probably need a UI cue somewhere on the exporter screen. The title says "Export Donation History and Custom Fields to CSV". then right below that in an almost unreadable light gray on gray it says "Download an export of donors for specific donation forms with the option to include custom fields.".
> 
> It never says "You won't see any custom fields to export unless you first choose a specific form in the Filter by Donation Form dropdown". or, more positively, "To export custom fields, first choose a specific form with the Filter by Donation Form filter."
> 
> This would be a very helpful UI tweak.
> 

## Expected Behavior

I expect to be made aware of the process for exporting custom fields

## Possible Solution
Change the wording at https://github.com/WordImpress/Give/blob/release/2.1.3/includes/admin/tools/export/class-give-export-donations.php#L132 to include specifically how to see the custom fields data. 

## Tasks

- [ ] modify the language

**Comment by kevinwhoffman** [comment]
Moving to Canny as a request for contextual documentation. I included Scott's insight as an internal comment: https://givewp.canny.io/documentation/p/exporting-custom-fields
