### ISSUE TITLE
fix: add test for give_verify_minimum_price fn

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#3232]
## Description

Add PHPUnit test for `give_verify_minimum_price` and use strict comparison here: 
https://github.com/WordImpress/Give/blob/release/2.1.3/includes/process-donation.php#L477

**Comment by DevinWalker** [comment]
@henryholtgeerts this would be a good one to get you started on unit testing. @ravinderk can help walk you through how this works.
