### ISSUE TITLE
refactor: remove duplicate code for fetching donor address

### ISSUE THREAD

**Issue by mehul0810** [impress-org/givewp#3253]
## User Story
As a developer, I want to achieve a functionality with unique code/fn so that it looks consistent, easy to search, optimised code, and performant

## Current Behavior
I currently can see that `get_donor_address` within `Give_Donor` class and `give_get_donor_address` helper function both are having same functionality due to which code is duplicated.

## Expected Behavior
I expect to see no duplicate code. 

**Note:** Also, to make the code more performant, I would prefer the practice to get the return value of the function in a variable and then use the variable. Calling function frequently will make the code more resource hungry.

Example: `get_current_user_id` fn is called thrice rather we would have used the variable `$donor_data` to use the already fetched value. Check the screenshot for more details: 
![image](https://user-images.githubusercontent.com/1852711/40419391-d2dc0380-5ea2-11e8-9b2c-e046684c526f.png)

## Related
- https://github.com/WordImpress/Give/issues/2935
- https://givewp.slack.com/archives/C0FAGC83C/p1527070381000216

## Tasks
- [ ] Remove duplicate functions and extend any of the function for better performance
- [ ] Make sure any function is not called multiple times rather use it with a variable.
- [ ] Testing

**Comment by DevinWalker** [comment]
@henryholtgeerts I'm assigning this one to you because I think it will give you a good opportunity to dig into the code more and refactor for optimization purposes.
