### ISSUE TITLE
feat: add notice regarding add-on to add-on dependency

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#3416]
## User Story
As an `admin`, I want to addon update only when I pass all dependency.

We have logic in the core for `Give` core dependency check but we can expend that for add-ons also. Like if stripe dependents on any version of recurring add-on then it must not update till we do not have required version of the recurring addon.

Related to https://github.com/WordImpress/Give/issues/3217

**Comment by DevinWalker** [comment]
I don't see a real need for this as support hasn't been bringing this to our attention and I haven't seen any user requests. I can also see an issue with adding too much complexity whereas one add-on version depends on another add-on version and neither is able to update. Closing out.
