### ISSUE TITLE
refactor: remove notes column from donor table

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#3632]
@ravinderk commented on [Mon Aug 27 2018](https://github.com/WordImpress/Give-Recurring-Donations/issues/738)

## User Story
After `2.3.0`, we store donor notes to custom comment table. We left notes column only for backward compatibility and after 2.3.0, it is safe to remove notes column:

ref: https://github.com/WordImpress/Give/issues/3627

**Comment by kevinwhoffman** [comment]
Similarly to https://github.com/impress-org/give/issues/3641, we need to decide if/how long it makes sense to leave data in place after a DB migration.

**Comment by kevinwhoffman** [comment]
Iceboxing until we confirm the 2.3.0 upgrade goes smoothly before removing the notes column.
