### ISSUE TITLE
feat: improve user registration password UX

### ISSUE THREAD

**Issue by samsmith89** [impress-org/givewp#3695]
## User Story

As a site admin, I want to make the user registration for my donors less complicated. When they register as a new user they are sent an email that directs them to the WordPress admin login to change their password. I wish to simplify this process if possible.

## Related
https://secure.helpscout.net/conversation/665538496/25743

## Acceptance Criteria

- [ ] A User is registered when either a password is input into a field or is sent a temporary password.

**Comment by kevinwhoffman** [comment]
We should re-examine the new user experience for a donor who creates an account through the donation form. The customer is reporting that they are sent an email with link to reset their password, which then logs them into the WP admin afterwards. I can see why this is not a great experience. Ideally we would redirect them to the Donation History page after setting a password.

**Comment by DevinWalker** [comment]
Closing this as part of the Consolidated Donor Profile feedback: https://givewp.canny.io/feature-requests/p/consolidated-donor-profile
