### ISSUE TITLE
feat: auto-populate full billing address based on street address

### ISSUE THREAD

**Issue by marutim** [impress-org/givewp#3712]
# Feature Request

## User Story
As a user, I would like the option to reduce as many steps as possible for my donors to complete the donation to increase the chances of donations.

I would like an option to auto-populate most of the billing address based on the street address been entered.

This was a request from a user from UK and he has shared a list of charities whose website does it.
https://humanappeal.org.uk/donate
https://www.islamic-relief.org.uk/donation/index.php
https://www.islamicaid.com/

## Related
HS link: https://secure.helpscout.net/conversation/673706358/26435?folderId=672199

## Acceptance Criteria
- [ ] When the street address is entered, it auto-populates the rest of the Billing address

**Comment by davidamarek** [comment]
+1

**Comment by kevinwhoffman** [comment]
Moving to Canny for further validation: https://givewp.canny.io/feature-requests/p/address-autocomplete
