### ISSUE TITLE
feat: log spam donations

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/givewp#3772]
# Feature Request

## User Story

As a Give admin, I want to know when a donation is blocked as spam so that that I can verify whether donations are being blocked as the result of a false positive.

There is currently no record created when a donation is blocked as spam. The only notification is on the front end for the donor, but the admin is not aware of when or how many donations are being blocked. This could be problematic if Akismet is blocking false positives without the admin's knowledge.

## Possible Solution

A new log type could be added to `Donations > Tools > Logs > Spam`.

**Questions**
1. How much information should be added to the log? Is name and email enough?
2. Are there performance concerns with adding too many logs if a site is being targeted by a bot?
3. Should there be some type of admin notification if `X` number of spam logs are generated in a given time period?

## Acceptance Criteria

- [ ] When a donation is flagged as spam by Akismet, a log is added in `Donations > Tools > Logs > Spam`.

More criteria will be added once we discuss the implementations with @DevinWalker, @mathetos, @ravinderk .

**Comment by kevinwhoffman** [comment]
Removing from 2.4.0 until we've had a chance to discuss further. Spam reports also seem to have become less frequent so I'm not sure there would be as much of a demand for this type of feature.

**Comment by mathetos** [comment]
I think this is an important feature. Users often ask us WHY a donation doesn't go through and giving them a LOG of potential spam should also allow for the ability to whitelist an email address from legit donors who got blocked incorrectly. 

Totally agree punting from 2.4.0 but I don't want it to get iceboxed without more detailed discussion and perhaps examples from other plugins.

**Comment by mathetos** [comment]
We have a tag in HelpScout for "donor spam" and I see roughly a dozen over the past three weeks, and I'm pretty sure we aren't tagging all of them that come in.

Additionally, we have data via our Docs Search Engine and I do not find ANY searches of "Akismet" or "Spam" in our docs search at all within the last 30 days.

Just adding useful data

**Comment by kevinwhoffman** [comment]
Moved to Canny for further validation: https://givewp.canny.io/feature-requests/p/spam-donation-logs
