### ISSUE TITLE
chore: add php 7.2 and 7.3 support for unit test with travis

### ISSUE THREAD

**Issue by mehul0810** [impress-org/givewp#3794]
# Feature Request

## User Story
As a user, I want to see Give works properly with PHP 7.2 and 7.3 so that there are no errors.

**Note:** We can work on this issue in mid-December this year as PHP 7.3 is scheduled to release in December 2018, so that we can add support for both PHP versions at the same time without wasting any additional time.

## Visuals
PHP Versions supported with Travis currently
![image](https://user-images.githubusercontent.com/1852711/47336384-24ce8280-d6ad-11e8-9915-624fbfebf0c2.png)

## Acceptance Criteria
- [x] Drop PHP 5.3 test.
- [x] Add PHP 7.2 support to Travis with and without multisite
- [x] Add PHP 7.3 support to Travis with and without multisite

**Comment by DevinWalker** [comment]
I added 7.2 and 7.3 testing but now we're running into some PHPunit compatibility issues:

![2019-01-28_13-54-59.png](https://images.zenhubusercontent.com/573e05b6bf93871ccd9b4d55/b5b7e949-52fc-4ad1-9f9f-527007a51c1d)![2019-01-28_13-59-03.png](https://images.zenhubusercontent.com/573e05b6bf93871ccd9b4d55/8c15efa3-fcea-45b7-b2ca-564fcf7c2737)

**Comment by DevinWalker** [comment]
I did some research and it looks like this is a WP Core PHPUnit testing issue that is set to be resolve in release `5.1`: https://core.trac.wordpress.org/ticket/43218

I'm going to remove the code to test PHP `7.2` and `7.3` in place for now unit WP Core `5.1` version is released: https://core.trac.wordpress.org/query?status=reopened&status=assigned&status=reviewing&status=new&status=accepted&group=status&milestone=5.1

**Comment by DevinWalker** [comment]
Now that WP supports PHPUnit 7.x we now have a new release of PHPUnit 8.x which WP does not support. This results in the following issue now with my recent changes:

![2019-04-03_01-17-37](https://user-images.githubusercontent.com/1571635/55463611-4ada4600-55ae-11e9-9d1b-28217bb8d13c.png)

**Comment by koconder** [comment]
@DevinWalker as per my last messages. You can see an example here from my boilerplate repo https://github.com/koconder/wordpress-test-template

Test results: https://travis-ci.org/koconder/wordpress-test-template/builds/547591604
Working across all key PHP versions with PHP 7.x, with PHPUnit tests across WP 5.0, 5.1, and 5.2 on low and high PHP versions. Btw WP latest can fail as the development branch is not always passing tests.

![Screenshot 2019-06-19 18 07 49](https://user-images.githubusercontent.com/25068/59747853-2e040380-92bd-11e9-9235-bb794bc46f34.png)

@DevinWalker @mehul0810 @kevinwhoffman - I'm happy to jump in and resolve

**Comment by DevinWalker** [comment]
@koconder that looks passing for sure. I wasn't able to achieve that but it's been a few months since I tried. If you would like to contribute towards getting this issue resolved we'd love to have a PR! Thanks for the follow up.

**Comment by koconder** [comment]
@DevinWalker i'll give it a go for you guys!

**Comment by mikejhale** [comment]
@koconder If you're still interested in giving another look at this one it would be appreciated.

**Comment by JasonTheAdams** [comment]
We no longer use Travis and are testing for these versions upon release.
