### ISSUE TITLE
feat: improve Markdown support in Bug Report details

### ISSUE THREAD

**Issue by salcode** [impress-org/givewp#3812]
# Feature Request

## User Story

As a developer, I want to submit a bug report with markdown so that it takes less time.

## Possible Solution

Modify [bug_report.md](https://github.com/impress-org/give/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)

replacing

```
<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X | Microsoft Windows | Linux | Android | iOS</li>
        <li>Version: X.X.X</li>
    </ul>
</details>
```

with

```
<details>
<summary>Operating System</summary>

- Platform: Mac OS X | Microsoft Windows | Linux | Android | iOS
- Version: X.X.X

</details>
```

#### Whitespace

The whitespace before and after the unordered list must be included for the list to be rendered as HTML. (In my own work, this caught me off-guard at first in that my markdown as not parsing).

#### Indentation

I recognize the `<summary>` tag should be indented as it is nested inside the `<details>` tag, however since the unordered list (and any other markdown) will be treated as a code block if indented, this markdown can **not** be indented.

Since the markdown is not indented, I advocate also not indenting the `<summary>` tag.

## Related

@kevinwhoffman is awesome and a Twitter conversation with him led me to open this issue

**Comment by kevinwhoffman** [comment]
Thanks @salcode! I'll keep this in mind the next time we update our issue templates. It's a bit of a chore to update them across 30+ repos, so I'm going to hold off on the markdown improvement until I work out a script for updating those templates across many repos.

Here is Sal's post on the formatting for future reference:
https://salferrarello.com/collapsible-section-in-github-issue/

**Comment by kevinwhoffman** [comment]
Following up here to say we've implemented an organization-wide [.github repository](https://github.com/impress-org/.github) which makes use of `details` in the issue templates.
