### ISSUE TITLE
feat: add dashboard GiveWP news widget

### ISSUE THREAD

**Issue by mathetos** [impress-org/givewp#3870]
# Feature Request

## User Story

As a Give user, I want to be informed of Give News and Updates. The WordPress Dashboard is a nice place to see those updates. 

## Visuals

The code below creates the following widget:
![image](https://user-images.githubusercontent.com/930724/48963779-1ba43000-ef4f-11e8-951c-71fdad8d3dde.png)

## Possible Solution

This is just some starting code, it would need to be styled much more nicely and not with inline styles. I think styling in a similar fashion to the WP News and Event widget would be good. 

```
/**
 * Register all dashboard metaboxes
 *
 * @access      public
 * @since       1.0
 * @return      void
 */

function givewp_dashboard_news_widget() {
    global $wp_meta_boxes;

    wp_add_dashboard_widget('widget_freelanceswitch', __('<i class="dashicons dashicons-give" style="color: #66BC6B;"></i> GiveWP News', 'give'), 'givewp_create_dashboard_rss_widget');
}

add_action('wp_dashboard_setup', 'givewp_dashboard_news_widget');

/**
 * Creates the RSS metabox
 *
 * @access      public
 * @since       1.0
 * @return      void
 */

function givewp_create_dashboard_rss_widget() {

    // Get RSS Feed(s)
    include_once(ABSPATH . WPINC . '/feed.php');

    // Get a SimplePie feed object from the specified feed source.
    $rss = fetch_feed('https://givewp.com/feed/');

    if (!is_wp_error($rss)) : // Checks that the object is created correctly
        // Figure out how many total items there are, and choose a limit
        $maxitems = $rss->get_item_quantity(3);

        // Build an array of all the items, starting with element 0 (first element).
        $rss_items = $rss->get_items(0, $maxitems);

        // Get RSS title
        $rss_title = '<a href="' . $rss->get_permalink() . '" target="_blank">' . strtoupper($rss->get_title()) . '</a>';
    endif;

    // Display the container
    echo '<div class="rss-widget">';

    // Starts items listing within <ul> tag
    echo '<ul>';

    // Check items
    if ($maxitems == 0) {
        echo '<li>' . __('No items', 'give') . '.</li>';
    } else {
        // Loop through each feed item and display each item as a hyperlink.
        foreach ($rss_items as $item) :
            // Uncomment line below to display non human date
            //$item_date = $item->get_date( get_option('date_format').' @ '.get_option('time_format') );

            // Get human date (comment if you want to use non human date)
            $item_date = human_time_diff($item->get_date('U'), current_time('timestamp')) . ' ' . __('ago', 'give');

            // Start displaying item content within a <li> tag
            echo '<li>';
            // create item link
            echo '<a href="' . esc_url($item->get_permalink()) . '" title="' . $item_date . '">';
            // Get item title
            echo '<i class="dashicons dashicons-calendar-alt" style="margin-right: 10px;"></i>' . esc_html($item->get_title());
            echo '</a>';
            // Display date
            echo ' <span class="rss-date">' . $item_date . '</span><br />';
            // Get item content
            $content = '<p class="give-blog-description" style="margin: 5px 0 0 30px;">' . $item->get_description() . '</p>';
            // Display content
            echo $content;
            // End <li> tag
            echo '</li>';

        endforeach;
    }
    // End <ul> tag
    echo '</ul>'; ?>

    <p class="givewp-news-footer"><a href="https://givewp.com/addons" target="_blank" rel="noopener noreferrer"><i class="dashicons dashicons-products" style="margin-right: 10px;"></i>Get Add-ons</a><a href="https://givewp.com/documentation" target="_blank" rel="noopener noreferrer"><i class="dashicons dashicons-media-document" style="margin-right: 10px;"></i>Read Docs</a><a href="https://givewp.com/support" target="_blank" rel="noopener noreferrer"><i class="dashicons dashicons-editor-help" style="margin-right: 10px;"></i>Get Support</a></p>

    </div>

<?php
}
```

One thing that should be added to this, is a simple email opt-in form so users can opt into our emails from within this Dashboard widget. The Name and Email address should be auto-populated from the user account who is logged in. 

## Acceptance Criteria

- [ ] The Dashboard widget appears correctly in the Dashboard
- [ ] The Dashboard widget can be removed via the "Screen Options" tab just like any other Dashboard widget
- [ ] The Dashboard widget includes a MailChimp optin form that is auto-populated with the user name/email address
- [ ] When new posts are posted on the GiveWP website, the Dashboard widget updates correctly -- meaning the results are not cached in a way that prevents new posts from appearing and the performance of the widget is still excellent.

**Comment by DevinWalker** [comment]
## Review Feedback

I also think it's a good idea that this be included in core and _disabled_ for existing installations but _enabled by default for new installations_. The advanced settings makes sense as well. 

### Considerations

1. The concept by Matt is a good start, I think it just needs some more polish.
2. Should the MailChimp opt-in save a usermeta flag so it doesn't display if the user has already subscribed. This would be tricky if it were double opt-in in MailChimp because we would need a webhook to detect whether the user actually subscribed. As well, if they subscribed then unsubscribed and the usermeta flag was still there it wouldn't display. I think a webhook mailchimp integration is overboard and would be fine with just keeping the form single opt in and if the user unsubscribes and the MC opt in doesn't appear because of the usermeta then oh well. 
3. I also think it should only display for Editor roles and above. Subscribers shouldn't have to see it.

**Comment by kirklandharrell** [comment]
Design updates for this feature. Visual changes include: 

1. Bolding the article titles to assist visual hierarchy 
2. Changing icon colors for more variation
3. Added a light background to the second entry to break up the white 
4. better spacing and alignment
5. Added a lower bar to separate content

First image shows the widget on its own, second is on the dashboard in a more confined space.

<img width="741" alt="screen shot 2018-11-28 at 12 23 53 pm" src="https://user-images.githubusercontent.com/15900661/49180073-9763fb00-f308-11e8-841b-8168654e3c9b.png">
<img width="640" alt="screen shot 2018-11-28 at 12 24 29 pm" src="https://user-images.githubusercontent.com/15900661/49180075-9763fb00-f308-11e8-8612-af1a7bfc8b7f.png">

**Comment by mathetos** [comment]
@kirklandharrell I agree with Kevin's input. I didn't like the Calendar icon that I suggested in the first place, but I do think it needs some sort of icon.

If we can keep the icons to just Dashicons or our already built in font-icons in Give that would be best. 

The padding around all the elements also feel not consistent.

Lastly, the design needs to include the MailChimp opt-in, first|last|email|submit all need to be there somehow.

**Comment by kirklandharrell** [comment]
@mathetos You and @DevinWalker have differing opinions on the need for post icons.

I will make sure that all padding is consistent.

I don't understand what you mean with the MailChimp opt-in, can you explain further?

**Comment by mathetos** [comment]
@kirklandharrell Devin's feedback on icons is more important than mine.

See the original post above about the Mailchimp opt-in, and Devin's response above as well mentioning it should be included. It was not included in my original design but it needs to be somehow.

**Comment by kevinwhoffman** [comment]
@DevinWalker and I just came back to this issue and want to consider integrating it with an updated stats widget on the dashboard once reports are updated.

**Comment by kevinwhoffman** [comment]
Here are two examples we looked at for inspiration. The idea would be to display news alongside relevant stats or reports.

![image](https://user-images.githubusercontent.com/1938671/51710066-0c486e00-1ff6-11e9-80c4-cad882f9701e.png)

**Comment by mathetos** [comment]
I'd like to revive this old issue and get it in a roadmap. Here's another really striking example from Elementor:

![image](https://user-images.githubusercontent.com/930724/68152260-2b1a5000-fef8-11e9-98fb-d10ca10550f4.png)


Also notice that each of their links use UTM attributes so they have data on whether that dashboard is effective or not. 

We also know that many user find out about local WordPress Meetups and WordCamps specifically from the Dashboard, so we know users look there regularly. I think this issue is long overdue.

**Comment by mikejhale** [comment]
## Related
https://give.productboard.com/feature-board/879919-givewp-feature-hierarchy/features/3229672/detail

**Comment by kevinwhoffman** [comment]
Closing. Since this issue was created, the GiveWP dashboard widget was updated to display a new reports UI. I'm not migrating it to Canny because I don't see any user requesting a news widget.

If there's still interest in a news widget, a pitch should be provided with likely a 2-week appetite.
