### ISSUE TITLE
feat: show company name on donor wall

### ISSUE THREAD

**Issue by mathetos** [impress-org/givewp#3878]
# Feature Request

## User Story

As a Give Admin, I want donors who donate with a Company Name to be reflected as their Company Name in the Donor Wall. 

## Visuals

This was custom implemented here in a nice clean manner:
![image](https://user-images.githubusercontent.com/930724/49174204-8ad8a600-f2fa-11e8-8fbb-9e86c5f32bc3.png)
https://wpcampus.org/2018/11/fundraising-for-wpcampus-gutenberg-accessibility-audit/#donors

## Possible Solution

Add the company name, directly below the donor name exactly as shown in the image above.

Add a shortcode attribute to enable/disable it.

## Related

* [live example](https://wpcampus.org/2018/11/fundraising-for-wpcampus-gutenberg-accessibility-audit/#donors)
* [User request on .org](https://wordpress.org/support/topic/display-company-name-on-donor-wall/)

## Acceptance Criteria

- [ ] Company name appears by default under the donor name on the donor wall whenever present.
- [ ] A shortcode attribute is present which allows admins to disable the company name appearing if they prefer, but it is enabled by default.
- [ ] A control is provided for company name in the Gutenberg block settings. It is enabled by default.

**Comment by kevinwhoffman** [comment]
Per dev team call, moving this out of 2.4.0 and back to Product Backlog. We need to decide how company name should be handled and whether it should display by default. The image example provided was confusing because some of the donors used the company name as the donor name. We will revisit once we have better direction.

**Comment by kevinwhoffman** [comment]
Moving to Canny for further validation: https://givewp.canny.io/feature-requests/p/company-name-on-donor-wall
