### ISSUE TITLE
fix: php notice with SiteOrigin page builder plugin

### ISSUE THREAD

**Issue by nishitlangaliya** [impress-org/givewp#3962]
# Bug Report

## User Story
As a admin I want to place form using site origin page builder widget on my page.

## Current Behavior
Adding a Give form using site origin page builder causing php notices on front and functionality breaks.

## Expected Behavior

Form should display on front without any issue build with site origin page builder

## Bug Type

- [X] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1.  Add site origin page builder plugin.
2. Add form in page using site origin page builder.
3. Update page and go to front side.

## Visual for reproduce issue.

https://www.useloom.com/share/07488ed4a1fc44feb0492cc27ee9453f

## Visuals

![screencapture-annualreceipt-local-siteoriging-2019-01-28-16_37_21](https://user-images.githubusercontent.com/11435772/51833106-87729280-231c-11e9-9822-f15fecd180f8.png)

## Related

https://wordpress.org/support/topic/php-notice-undefined-index-post_type/

## Acceptance Criteria
- [ ] I can add give form using site origin page builder without any issue and php notice.

<details>
    <summary>WordPress System Info</summary>
  ### WordPress Environment ###

Home URL: http://annualreceipt.local
Site URL: http://annualreceipt.local
WP Version: 5.0.3
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: annualreceipt.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.1
PHP Version: 7.2.0
PHP Post Max Size: 1,000 MB
PHP Time Limit: 900
PHP Max Input Vars: 3000
PHP Max Upload Size: 1,000 MB
cURL Version: ❌ 7.38.0, OpenSSL/1.0.1t - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: 5.6.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.4.0
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donor Note✔Email access
Upgraded From: 2.4.0
Test Mode: Enabled
Currency Code: GBP
Currency Position: After
Decimal Separator: .
Thousands Separator: ,
Success Page: http://annualreceipt.local/donation-confirmation/
Failure Page: http://annualreceipt.local/donation-failed/
Donation History Page: http://annualreceipt.local/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation, PayPal Standard
Default Payment Gateway: Offline Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Other Active Plugins ###

Classic Editor: by WordPress Contributors – 1.3
Page Builder by SiteOrigin: by SiteOrigin – 2.10.0

### Inactive Plugins ###

Elementor: by Elementor.com – 2.3.8
Give - Annual Receipts: by GiveWP – 1.0.0
Give - Currency Switcher: by GiveWP – 1.3.1
Give - Donation Plugin: by GiveWP – 2.3.0
Give - Fee Recovery: by GiveWP – 1.7.2
Give - Fee Recovery: by GiveWP – 1.7.4
Give - Gift Aid: by GiveWP – 1.2.0
Give - Moneris: by GiveWP – 1.0.0
Give - Recurring Donations: by GiveWP – 1.8.2
Give - Stripe Gateway: by GiveWP – 2.1.2
Give - Tributes: by GiveWP – 1.5.2
Query Monitor: by John Blackbourn & contributors – 3.2.2

### Active MU Plugins ###

Local by Flywheel Relative URL (for Live Links): by Flywheel – 1.0

### Theme ###

Name: Twenty Seventeen
Version: 1.9
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying Give on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by mikejhale** [comment]
This occurs when the Donation form option `Display Content (optional):` is set to Above or Below. It is likely related to the issue with `the_content` filter described in #3363. 

I was able to correct this when using a SiteOrigin page builder page by going to Give Settings > Advanced and setting `the_content filter` to Disabled. With that setting set to Disabled the page displays the donation form as expected without any exceptions or notices.
