### ISSUE TITLE
feat: add "{goal} remaining" as a donation goal option.

### ISSUE THREAD

**Issue by Benunc** [impress-org/givewp#3993]
# Feature Request

## User Story

As a Give admin, I want to create a form that essentially counts down to closed based on the donation goal. For example, if a goal is 15 donations, instead of showing a donation goal meter counting up to 15, we show one counting down. 

"14 donations remaining to reach our goal"

This would work with all of the types of goals that we currently have: 

*Amount raised* -- "$3,500 remaining to reach our goal"
*Percentage Raised* -- "We are 15% away from being fully funded"
*Number of Donations* -- "14 donations remaining"
*Number of Donors* -- "16 donors remaining"

## Related
https://secure.helpscout.net/conversation/772584094/33984?folderId=1457790

## Acceptance Criteria
- [ ] a new option for counting down toward "nothing left in the goal" is an option
- [ ] the language output on the front of forms is concise, translatable, and has a snippet in the snippet library for folks who want to change the wording.
- [ ] the recurring goal functionality is included in the feature, or at least not broken by it.

**Comment by kevinwhoffman** [comment]
Iceboxing until further requests. We don't want to clutter the UI for goals any more as we already have several options to choose from.

**Comment by DevinWalker** [comment]
I haven't heard of a request for this so closing. If more come in we can add them to Canny.
