### ISSUE TITLE
feat: add logic to calculate donor count stat

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#3999]
# Feature Request

## User Story
As an admin, I want to get donor stat on basis of donation form and date range.

## Acceptance Criteria
- [ ] Add `get_donors_count` function to `Give_Donor_Stats` class.
- [ ] `get_donors_count` calculates donor count for date range.
- [ ] `get_donors_count` calculates donor count for specific or mutiple donation form.
- [ ] Above two point works together.

**Comment by DevinWalker** [comment]
Closed as this is the last remaining issue attached to the old epic #3917
