### ISSUE TITLE
feat: Support Sagepay payment gateway

### ISSUE THREAD

**Issue by mathetos** [impress-org/givewp#4031]
# Feature Request

## User Story

As a Give user in the UK, I want to be able to use Sagepay for my donations with Give. 

**Online Docs for Integration**
https://www.sagepay.co.uk/support/integration-kits-protocols-document

## Acceptance Criteria

- [ ] Integrating my account with Sagepay works easily and intuitively
- [ ] Donations process correctly
- [ ] Critical Give addons work seamlessly when used in combination with Sagepay donations 
- [ ] Recurring support is available as well
- [ ] Refunds work as expected

**Comment by DevinWalker** [comment]
Canny Feedback created: https://givewp.canny.io/feature-requests/p/sage-pay-payment-gateway 

Anyone is welcome to upvote this!
