### ISSUE TITLE
refactor: migrate from travis.org to travis.com

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#4061]
# Feature Request

## User Story
As Travis is migrating all their customers to the new domain, we can also adapt to that change.

ref:
https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com
https://github.com/WordPress/gutenberg/pull/14250

## Acceptance Criteria
- [ ] Setup accout on travis-ci.com.
- [ ] Integrate github repositary with travis-ci.com.
- [ ] All tests are running on travis-ci.com without any issue.
- [ ] Change travis-ci-org badge ot travis-ci-com.

**Comment by ravinderk** [comment]
@DevinWalker We have to send an email to `travis-ci` to migrate us to `travis-ci.com`. check more Details here: https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg

**Comment by ravinderk** [comment]
As discussed on the call,  @DevinWalker will take care of email and after that, I will implement changes if any.

**Comment by DevinWalker** [comment]
Closing as there doesn't seem to be a good enough reason to do this. We may also eventually switch to CircleCI.

**Comment by ravinderk** [comment]
@DevinWalker Currently I am noticing slow progress on every build that means we have to wait for 2 hours or more on every PR to check if it passes all tests or not.  I found this reason from Travis: https://travis-ci.community/t/build-delays-for-open-source-project/10272/26. This solid reason for moving to travis-ci.com or switch to another service.

ref: https://travis-ci.community/t/build-delays-for-open-source-project/10272/16

cc: @JasonTheAdams @kjohnson

**Comment by JasonTheAdams** [comment]
We've recently switched GitHub plans, so we have Github Actions available to us on all repositories. If we're having issues with Travis CI, I would like to switch to Github Actions and drop Travis altogether (also, GiveWP core has unlimited Github Action minutes since it's open-source). We can discuss this more on the call today.
