### ISSUE TITLE
fix: add support for multisite updates

### ISSUE THREAD

**Issue by JasonTheAdams** [impress-org/givewp#4083]
# Bug Report

## User Story
As a multisite super admin, I want to manage my GiveWP licenses within the Network dashboard so that I can provide updates to subsites without having to network activate the plugins.

## Current Behavior
Presently, if GiveWP is installed on a subsite within a multisite the licenses are managed on that site. The problem is that updates don't come from subsites within a multisite, they come from the parent (main) site. So even though the licenses are entered in the site, trying to update the plugins will fail due to authentication.

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [x] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Set up a WordPress multisite
2. Add a subsite
3. Add GiveWP plugins to that subsite
4. Set up the licenses for the plugins
5. Attempt to update a plugin

## Visuals
![Update error](https://cl.ly/8e710c6e7988/Image%2525202019-04-19%252520at%25252011.55.51%252520AM.png)

## Possible Solution
Plugins are not independent within a multisite; if a plugin is updated its updated for every site within the multisite. Therefore plugin licensing needs to happen on a multisite network level (see WP Migrate DB Pro as an example).

What GiveWP needs to do, therefore, is check whether the site the plugin is active for is part of a multisite or not. If it is, then add a "GiveWP" settings page to the Network > Settings section and handle the licenses there.

It will also be helpful to the user to notify them upon activation in a subsite that the licenses will need to be activated in the Network settings from a super admin.

I do not recommend requiring that the plugin be network activated as it's a content plugin and you'd not want to forcefully activate it on every site within the network. Allow the multisite to select which sites have it activated, but manage the licenses on a network level.

## Acceptance Criteria

- [ ] License settings are managed from the network admin
- [ ] GiveWP can be limited to specific subsites
- [ ] It is not required that the main site has GiveWP activated
- [ ] Updates work within the multisite

### WordPress Environment ###

Home URL: https://serving.world
Site URL: https://serving.world
WP Version: 5.1.1
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: page
Page on Front: Home (#9)
Page for Posts: Unset
Table Prefix Length: wp_16_
Table Prefix Length: 6
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: WP Engine
TLS Connection: Connection uses TLS 1.3
TLS Connection: Probably Okay
Server Info: Apache
PHP Version: 7.2.17-1+ubuntu18.04.1+deb.sury.org+3
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 1000
PHP Max Upload Size: 5 MB
cURL Version: 7.58.0, OpenSSL/1.1.1b
SUHOSIN Installed: –
MySQL Version: 5.7.25
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Give Configuration ###

Give Version: 2.4.5
Give Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_16_give_donors -  1.0✔ wp_16_give_donormeta -  1.0✔ wp_16_give_comments -  1.0✔ wp_16_give_commentmeta -  1.0✔ wp_16_give_sessions -  1.0✔ wp_16_give_logs -  1.0✔ wp_16_give_logmeta -  1.0✔ wp_16_give_formmeta -  1.0✔ wp_16_give_sequential_ordering -  1.0✔ wp_16_give_donationmeta -  1.0
Give Cache: Enabled
Give Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donor Note✔Email access❌Renewal Receipt Email❌Renewal Receipt Email✔Subscription Cancelled Email✔Subscription Cancelled Email✔Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access
Upgraded From: 2.4.4
Test Mode: Disabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://serving.world/donation-confirmation/
Failure Page: https://serving.world/donation-failed/
Donation History Page: https://serving.world/donation-history/
Give Forms Slug: /donations/
Enabled Payment Gateways: Stripe - Credit Card, Offline Donation
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled

### Active Give Add-ons ###

Give - Annual Receipts: ✔ Licensed – by GiveWP – 1.0.1
Give - Fee Recovery: ✔ Licensed – by GiveWP – 1.7.4
Give - Form Field Manager: ✔ Licensed – by GiveWP – 1.4.1
Give - PayPal Pro Gateway: ✔ Licensed – by GiveWP – 1.2.1
Give - PDF Receipts: ✔ Licensed – by GiveWP – 2.3.3
Give - Recurring Donations: ✔ Licensed – by GiveWP – 1.8.10
Give - Stripe Gateway: ✔ Licensed – by GiveWP – 2.1.6
</details>

**Comment by DevinWalker** [comment]
We don't get many reports of a need for this... closing until it's validated and we will then have it in our [feedback system](https://feedback.canny.io].
