### ISSUE TITLE
feat: prevent shortcode button overlapping with other column

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#4090]
# Feature Request

## User Story
As an admin, I want to see all column on form listing page without any issue

## Possible Solution
Hide shortcode button text after a certain size:
![image](https://user-images.githubusercontent.com/1784821/57122085-08687c80-6d99-11e9-934f-a874b40633df.png)

## Acceptance Criteria
- [ ] Shortcode button is not overlapping with any other column

**Comment by DevinWalker** [comment]
Henry I'm assigning this one to you too - it should be a relatively simple fix. My thought is to wrap the button text in a span and hide that at a smaller resolution and update the style of the button a bit to match WP 5.3+ modified button styles. 

See this quick video I did for more explanation: https://www.loom.com/share/aad4bdf3538440fbbfd87a2d171db7bc

**Comment by henryholtgeerts** [comment]
Looks simple enough - I'll reach out if I run into anything! Thanks for the screencast, very helpful
