### ISSUE TITLE
feat: implement card management for better user experience

### ISSUE THREAD

**Issue by mehul0810** [impress-org/givewp#4108]
# Feature Request

## User Story
As a donor, I want to implement a card management feature for a donor so that the donor can use any existing card to quickly donate to any donation campaign.

### Add New Card - Non Logged-in Donor
Whenever a non-logged-in donor visits the donation form then the credit card fields will be displayed with no option to use an existing card.

![Non logged in donor - Donation Form](https://user-images.githubusercontent.com/1852711/57689714-ab54ac80-765d-11e9-8dc6-2895c9373f1f.png)

### Add New Card - Logged-in Donor
Whenever a logged-in donor visits the donation form and is a first-time donor then he can simply fill in the card details. Also, if the existing donor having multiple cards but want to use a new card can fill in the new card details to donate.

![Add new card - Donation Form](https://user-images.githubusercontent.com/1852711/57689715-ab54ac80-765d-11e9-8c17-6b35dfe829c8.png)

### Use an existing card with default card selected
![Use an existing card with default card selected- Donation Form copy](https://user-images.githubusercontent.com/1852711/57689718-abed4300-765d-11e9-8a64-5e34a4b1b1b3.png)

### Use an existing card with a card selected by the donor.
![Use an existing card with donor chosen card selected- Donation Form copy 2](https://user-images.githubusercontent.com/1852711/57689716-ab54ac80-765d-11e9-9bc3-15ee5d520aee.png)

### Payment Information Management on Donor Profile or separate shorcode
![Donor Profile](https://user-images.githubusercontent.com/1852711/57689713-aabc1600-765d-11e9-8ed4-3e607454803a.png)

For non-logged-in donors, I think that login via invitation _(replacing email access)_ link can be a useful feature to take full-featured benefits of card management.

@DevinWalker @ravinderk We can discuss more this issue on our weekly developer call. Also, would like to know initial thoughts if any to be added as a comment on the issue

**Comment by allienimmons** [comment]
https://secure.helpscout.net/conversation/947459176/0/?folderId=3046394

**Comment by Benunc** [comment]
I marked this urgent because currently donations are failing for Stripe customers who change their card info (only the CVC and expiry date) because Stripe is still using the old card info. see the ticket linked above.

**Comment by Benunc** [comment]
removing urgent here, and I am going to attempt to create a tangential issue with failed payment method errors.

**Comment by JasonTheAdams** [comment]
Closing this in favor of https://feedback.givewp.com/feature-requests/p/store-credit-card-details-for-future-donations
