### ISSUE TITLE
fix: do not allow admin to delete system generated donation notes

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#4109]
# Feature Request

## User Story
 I think we must not allow admin to delete system generated notes because they are really helpful to know about donation processing.

Discussion: https://givewp.slack.com/archives/C0FAGC83C/p1557836713029500

![image](https://user-images.githubusercontent.com/1784821/57750952-c37e0780-7701-11e9-893e-da5072b884a7.png)

## Possible Solution
Remove `delete` link for system generated donation notes
## Acceptance Criteria
- [ ] Admin is not able to delete system generate donation notes

**Comment by DevinWalker** [comment]
Brought into Canny as part of the larger improvement to this screen: https://givewp.canny.io/feature-requests/p/improve-donation-details-screen
