### ISSUE TITLE
fix: ensure that empty donation receipt emails are not triggered

### ISSUE THREAD

**Issue by mehul0810** [impress-org/givewp#4185]
# Bug Report

## User Story
As a user, I want to ensure that empty donation receipt emails are not triggered in any way so that will not fill up the mailing queue and will be a consistent UX.

Let me know if you can't reproduce the issue. I will explain the thorough steps.

## Current Behavior
Currently, I can trigger empty donation receipt email using "complete_donation" action of Give.

## Expected Behavior
I expect to not trigger any kind of empty emails.

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Acceptance Criteria
- [x] Ensure that we can't send empty email when no access available
- [x] Testing

**Comment by mikejhale** [comment]
@mehul0810 Is this still occurring? If so please provide some clarity and steps to reproduce the issue.

**Comment by mehul0810** [comment]
Yes @mikejhale It is still not solved. I've created issue as discussed on the dev call. But, due to other priorities, I've not got time to get involved into this issue.

**Comment by mikejhale** [comment]
@mehul0810 What is the related issue?
