### ISSUE TITLE
chore: Review Stripe setting descriptions and labels for improved clarity

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp#4206]
## User Story

As a user, I need to clearly understand how certain settings impact my site so I can make it work properly and as expected. 

Review the settings optimizations in #4202

**Comment by mehul0810** [comment]
Also, review the link to the documentation of Stripe on vertical tabs content and provide the list with text and its related documentation link so that I can update the same.

**Comment by DevinWalker** [comment]
I have reviewed this and it's good for now. We should circle back on the doc links once we get to improving the documentation overall.
