### ISSUE TITLE
chore: Document new Stripe Checkout 2.0 process

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp#4208]
## User Story

As a user I want clear documentation on how to configure Stripe Checkout 2.0 and the benefits of using it. 

## Possible Solution
Similar to https://docs.wpsimplepay.com/articles/new-stripe-checkout/ when it’s nearing release so our customers know how they can upgrade to the new checkout version

**Comment by mehul0810** [comment]
**Update:**
Here are a couple more detailed documentation explaining how their plugins are implementing SCA:
- https://easydigitaldownloads.com/blog/strong-customer-authentication-is-coming/
- https://woocommerce.com/posts/introducing-strong-customer-authentication-sca/

**Comment by mikejhale** [comment]
Issue moved to [impress-org/givewp-docs #236](https://github.com/impress-org/givewp-docs/issues/236) via [**ZenHub**](https://www.zenhub.com/)
