### ISSUE TITLE
refactor: meta capabilities shouldn't be assigned to roles

### ISSUE THREAD

**Issue by justintadlock** [impress-org/givewp#4212]
The plugin assigns its CPT **meta** caps to the roles that it creates.  While there's nothing _technically_ wrong with doing so, meta caps don't actually provide permission to do anything.

What happens with meta caps is they get "mapped" to the other primitive caps depending on the specific scenario.  For example, `edit_give_form` might get mapped to `edit_give_forms` and `edit_published_give_forms`, which are the real caps that get checked.

This is important in the context of role management plugins, such as my [Members plugin](https://wordpress.org/plugins/members).  I've seen it cause some confusion with users of other plugins in the past because they'll assign the meta cap to another role and wonder why it's not working.  Role/Cap management plugins auto-pick up any caps that are assigned to roles, so they kind of clog up the interface.

These are the meta caps that don't need to be assigned to roles:

```
delete_give_form
delete_give_payment
edit_give_form
edit_give_payment
read_give_form
read_give_payment
```

Simply removing these 3 lines of code should fix this for future users: https://github.com/impress-org/give/blob/release/2.5.4/includes/class-give-roles.php#L190-L192

Current plugin users will still have the meta caps assigned to their roles.  You could run an update routine and remove those if you wanted to go that route.

**Comment by DevinWalker** [comment]
Resolved via #4310
