### ISSUE TITLE
epic: Notification Center

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp#4225]
# Feature Request

## User Story

As a user, I want to see consistent notifications so that I am aware of system events without my screen or notice area being cluttered.

## Visuals

Idea for the design of the Notification center:
![image](https://user-images.githubusercontent.com/1054196/62638620-732ed400-b903-11e9-8140-4774ad0b7632.png)

## Possible Solution

GiveWP should use a notification API to add notices to the notification center in a way that can also be used by add-ons. 

This may be built as a React component that is housed in the WordPress admin area.

**Comment by JasonTheAdams** [comment]
It's worth keeping an eye on where this goes, too: https://make.wordpress.org/core/2019/08/05/feature-project-proposal-wp-notify/

**Comment by DevinWalker** [comment]
I've added feedback so I'm closing until we see more about what our users want and when/if WP is going to move forward with their notification center proposal and if that will for our use cases. Canny Feedback link: https://givewp.canny.io/feature-requests/p/notification-center
