### ISSUE TITLE
feat: deleting notification logs on a recurring basis

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp#4228]
# Feature Request

## User Story

As a site admin, I want the ability to delete notifications and logs at an interval so that my database does not fill up with unneeded logs. .

## Possible Solution
Create an admin settings page the allows the admin to set an interval to delete logs/notifications (ie: delete after 30 days, 90 days, custom timeframe, etc)

## Acceptance Criteria

- [ ] Admin can set a deletion interval for each type of log
- [ ] Log entries are deleted after the correct time frame

**Comment by DevinWalker** [comment]
Closing as part of Epic which has been moved to our Canny feedback center: https://givewp.canny.io/feature-requests/p/notification-center
