### ISSUE TITLE
epic: Reports UI

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp#4229]
## User Story

As a Give user, I want detailed and accurate reporting so that I can understand how my campaigns are performing. .

## Current Behavior

I currently am limited by the options available in current forms.

## Expected Behavior

Need additional and flexible reporting and data visualization shown in a clear and understandable way.

**Comment by DevinWalker** [comment]
Closing as we've already delivered MVP on this and now it's time to iterate and improve.
