### ISSUE TITLE
fix: improve Give description on WordPress plugin repository

### ISSUE THREAD

**Issue by mehul0810** [impress-org/givewp#4231]
# Bug Report

## User Story
As a user, I want to be more clear on that gateways are supported by Give core and fees levied by Give core so that it will be easy to understand for me and help me plan out budgets in a way, if any fees are applicable.

**Note:** Please check whole plugin description to ensure that we are having it up-to-date as per our latest marketing words.

## Current Behavior
Currently, there are 2 points which I noticed:
1. We should mention about PayPal Standard and Stripe Core as we are providing these gateways with Give core.
2. We should improve the section "Zero Commission Charges" as we are now started to take 2% application fees with Stripe.

## Expected Behavior
I expect to be more transparent to the first time customers which even can help increase our reach to new customers.

## Related
- https://wordpress.org/plugins/give

**Comment by mikejhale** [comment]
Related: https://secure.helpscout.net/conversation/929824936/45304?folderId=1836754

**Comment by mathetos** [comment]
We addressed these issues in August and didn't close out this issue. This is the commit:
https://github.com/impress-org/givewp/commit/5041f09f468357e5ea0c888fdf621cd228098f47#diff-eb6b6c90251ab33cee784713c451e6d8
