### ISSUE TITLE
feat: add options to sort donor wall

### ISSUE THREAD

**Issue by mathetos** [impress-org/givewp#4233]
# Feature Request

## User Story

As a Give admin I want to display my donor wall in the order that I want. This might be by donation amount, by form title, by date, or by first/last name. 

## Possible Solution

Add two shortcode attributes and block settings to control the sort order:

1. Sort By: Date, Donor First Name, Donor Last Name, Donation Amount, Form Title
2. Sort Order: ASC, DESC

## Related

* [WP.org request](https://wordpress.org/support/topic/donor-wall-sort-by-name/)

## Acceptance Criteria

- [ ] The shortcode attributes are available in the shortcode builder
- [ ] The block settings are available in the block editor
- [ ] Each attribute/setting works as expected, in combination with the Sort Order as well
- [ ] Implementing this feature does NOT impact the sort order of other shortcodes at all, like the Give Form Grid, or Core Posts/Pages or anything else at all.

**Comment by DevinWalker** [comment]
Closing as we have the ability to sort by donation amount and other orderby args: https://givewp.com/documentation/core/shortcodes/give_donor_wall/
