### ISSUE TITLE
feat: add server side validation checks for min and max donation amounts

### ISSUE THREAD

**Issue by bastienu** [impress-org/givewp#4236]
# Feature Request

## User Story
As a developper, I want Give to make some test before storing a payment so that the payment gateway is not making those tests.

I'm currently developping my own payment gateway. Everything is doing well : form, storing payment, going to my bank payment page, receiving IPN, etc. But I just saw that, when I use the `give_create_payment()` function, anything is checked and data is stored like this. For example, if I have price of 500€ and my form has a maximum of 200€, there is no error or warning on this...

You are maybe going to tell me that I have to make this tests and this is right.
But is it really the gateway payment job to make these tests ? I think Give should make all tests and checks before storing a new payment. 

Maybe I did not find the correct function and, if yes, I'm sorry for this issue !

## Possible Solution
Call a validate function in `give_create_payment()` or `give_insert_payment()` function and send a` false` return if data are incorrect.

## Acceptance Criteria

- [ ] if price is bigger than _give_custom_amount_range_maximum, don't store the issue.

**Comment by ravinderk** [comment]
@bastienu If you calling `give_create_payment ` directly then you have to take care of most of the validations. We are handling those here:  https://github.com/impress-org/givewp/blob/3cb3506109adea10d7ae8d3633a616fce1c8092f/includes/process-donation.php#L29

Give validates donation amount before trigger hook to handle validate donation entry (which handle by payment gateway)
https://github.com/impress-org/givewp/blob/3cb3506109adea10d7ae8d3633a616fce1c8092f/includes/process-donation.php#L1453

I found that the amount valid range validated by Give only on the frontend.
https://github.com/impress-org/givewp/blob/3cb3506109adea10d7ae8d3633a616fce1c8092f/assets/src/js/frontend/give-donations.js#L253
https://github.com/impress-org/givewp/blob/3cb3506109adea10d7ae8d3633a616fce1c8092f/assets/src/js/plugins/give-api/form.js#L632

We will add that validation to backend too. Thank you for pointing out.

**Comment by DevinWalker** [comment]
Closing as this issue has been dormant for awhile now and it's unclear what the issue at hand is.
