### ISSUE TITLE
fix: change license API endpoint URL to Lumen license server

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp#4243]
As part of the Licensing proxy server project a redirect was added on the hosting side to handle incoming license requests so that GiveWP would not need to be modified as part of moving to the new licensing proxy server. 

Once the licensing server has been launched and is successful, the API URL for the license check should be modified in code so that GiveWP does not rely on the hosting redirect. 

https://github.com/impress-org/givewp/blob/2e27651afa19e94b5bb3484273daca466e1e99b2/includes/class-give-license-handler.php#L137

The hosting redirect will not be removed, but as users update GiveWP they will no longer rely on the redirect.

**Comment by DevinWalker** [comment]
Since we upgraded our server on Pagely and fixed some internal bugs we're not spiking on our CPU usage:

![2020-07-22_17-26-27](https://user-images.githubusercontent.com/1571635/88241932-8041f180-cc40-11ea-9a40-8496c8104d40.png)

Closing.
