### ISSUE TITLE
Developing custom payment gateway

### ISSUE THREAD

**Issue by pstidsen** [impress-org/givewp#4249]
How can I develop a custom payment gateway? I want to make an integration with a Danish payment gateway (fx www.epay.dk) to support the Danish app, MobilePay. Do you have some kind of developer guide?

**Comment by souzadavi** [comment]
I need this too

**Comment by souzadavi** [comment]
Here has good links: https://wordpress.org/support/topic/create-a-new-gateway/

**Comment by bradp** [comment]
Closing this, as I believe it is solved.

**Comment by mathetos** [comment]
Just for everyone's benefit, here's the official link for our docs on this issue:
https://givewp.com/documentation/developers/how-to-build-a-gateway-add-on-for-givewp/
