### ISSUE TITLE
"Last name" field is not level with "First name" field

### ISSUE THREAD

**Issue by messybricks** [impress-org/givewp#4258]
When I create a new donation form, it looks like the form fields for first and last name do not line up with each other:

![image](https://user-images.githubusercontent.com/11467886/65343132-e893f280-db99-11e9-9835-2ede722c42ef.png)

**Comment by DevinWalker** [comment]
Hi @messybricks I believe this is a CSS conflict not an issue with our code. We'll be happy to help you here: https://wordpress.org/plugins/give/
