### ISSUE TITLE
fix: W3 Total Cache causing 503 error on donation

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp#4267]
# Bug Report

## User Story

As an admin, I want use W3 Total Cache to speed up my side without any errors so that I am able to continue accepting donations.

## Current Behavior

When W3 Total Cache is enabled, a donation causes a 503 error. 

## Expected Behavior

A donation can be made even when W3 Total Cache is installed

## Bug Type

- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Install and activate W3 Total Cache
2. Attempt to make a donation (Test donation is fine)

## Related

- https://give.productboard.com/feature-board/879919-givewp-feature-hierarchy/features/3017223/insights

## Acceptance Criteria

- [ ] A 503 error does not occur on a donation when W3 Total Cache is enabled

**Comment by mikejhale** [comment]
@mehul0810 Please look into this to see if you can find the cause and what it will take to fix if it's an issue with our code.

**Comment by mehul0810** [comment]
@mikejhale I've researched this issue and found that W3TC is causing the issue with their recent updates.

**W3TC file causing the issue:** https://github.com/W3EDGE/w3-total-cache/blob/58aad3c6caca480566ca10e5fe658f1d1d27e748/Generic_Plugin.php#L521

Also, I noticed that in the `master` branch they have updated the code so they might be planning for a hotfix release which will resolve the issue of fatal errors.

But, meanwhile, with the temporary fix, you can rollback WPTC plugin to `0.9.7.5` to start processing donations again without errors.

**Comment by mikejhale** [comment]
Closing this as it is being caused by their code, and will be fixed in a future release of W3TC.
