### ISSUE TITLE
fix: include receipt_link_url in plain text emails

### ISSUE THREAD

**Issue by mehul0810** [impress-org/givewp#4284]
@mikejhale commented on [Wed Oct 23 2019](https://github.com/impress-org/give-pdf-receipts/issues/208)

# Bug Report

## User Story

As a donor, I want have a link to my PDF receipt included in my donation email so that I have a record of my donation.

They are using text emails instead of HTML. The {receipt_link_url} isn't working. Clicking on it turns absolutely no result for me. For them, they get the error message: "The specified receipt ID appears to be invalid."

They excluded rules in caching plugin, disabled all plugins, installed Native PHP Session, added "define( 'GIVE_USE_PHP_SESSIONS' , false);" to wp-config.php, removed Donation Confirmation and History pages from caching, disabled Lightspeed Caching plugin, excluded the form from caching and still see the error.

## Current Behavior

receipt_link_url is blank in plain text emails

## Expected Behavior

receipt_link_url is in plain text emails is a valid link to the PDF

## Bug Type

- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Turn emails to Plain intead of HTML
2. Add pdf_receipt email tag to the email
3. Enable PDF receipts addon
4. Submit a donation
5. Click the PDF receipts link in the email

## Related

https://give.productboard.com/feature-board/879919-givewp-feature-hierarchy/features/2927326/detail

## Acceptance Criteria

- [ ] receipt_link_url is a valid link in plain text emails
- [ ] receipt_link_url is a valid link in HTML emails

---

@mehul0810 commented on [Wed Oct 23 2019](https://github.com/impress-org/give-pdf-receipts/issues/208#issuecomment-545267372)

@mikejhale @DevinWalker On doing research on this issue, I noticed that this issue is related to Give core. So, moving this issue to Give core and creating PR for core.

**Comment by mikejhale** [comment]
tested: 
-[x] `receipt_link_url` is a valid link in plain text emails
