### ISSUE TITLE
fix: redirect to Stripe 3D page when using Stripe Connect and 3D v2 credit card

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp#4286]
# Bug Report

## User Story

As a donor, I want to make a donation when using a 3D v2 credit card so that I can complete my donation.

## Current Behavior

When connecting to Stripe via Stripe connect, a 3D v2 Secure credit card donation shows as pending, but is not processed, and does not redirect to the Stripe 3D page.

The payment shows as pending in the Give Admin, and incomplete in Stripe dashboard:

![image](https://user-images.githubusercontent.com/1054196/67528827-09130900-f680-11e9-9a55-68d2b1d08007.png)

This does not occur when using Stripe API Keys. 

## Expected Behavior

Using a 3D Secure card redirects to the proper Stripe page for the additional info. 

## Bug Type

- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Connect with Stripe Connect
2. Use a 3D v2 test card
3. See the donor is not redirected to the Stripe confirmation screen.

## Related

Test 3D v2 Secure Credit Card: `4000000000003220`
https://give.productboard.com/inbox/features/3167306/detail

## Acceptance Criteria

- [x] 3D v2 Secure card redirects as expected 
- [x] Other stripe test cards work as expected

**Comment by mehul0810** [comment]
@mikejhale @DevinWalker 

**Update:** I've reproduced the issue and spent some time looking into Stripe documentation. This issue can be reproduced when a user connects Stripe via Connect API and this happens even with the 3D secure v1 cards as well. I've communicated with Stripe developers and they are also able to reproduce the issue and looking into it. Once I'll get some response from them, I'll keep it updated and get this issue resolved if there is something we need to take care of.

**Comment by mehul0810** [comment]
**Update:** On detailed discussion with Stripe developer via FreeNode, it seems that our code is correct but it seems that the Stripe developers on the chat are unable to figure out the issue. So, they asked me to send an email to support which I did. Now, will be waiting for a reply. Hence, this issue will take couple of days communicating with Stripe developers and finding out the issue.

**Comment by ravinderk** [comment]
@DevinWalker I am able to reproduce this issue and I created a video about my research. I sent an email to stripe email. I will keep us informed. 

video: https://www.loom.com/share/ceeee0a3020240e1afc42a6485da85cf

**Comment by ravinderk** [comment]
@DevinWalker Stripe team was able to reproduce the issue on the demo site and they accelerated my ticket.

Stripe Support says:
> Sorry for any confusion, I tested with "Stripe Card", and didn't realize you had a Checkout option on the page. I was able to reproduce what you're seeing and have reported to the appropriate internal team. Sorry for the inconvenience and thank you for reporting. We'll address as soon as possible.

**Comment by ravinderk** [comment]
Update from stripe support:

> We've done some investigation and it seems like the Checkout Session is being created with the connected account's secret key. Can you instead create the Checkout Session with the platform secret key and the connected account's ID in the header [1]?
> 
> It's unclear if this is the source of the problem, but we suspect this could be the cause.
> 
> ref: https://stripe.com/docs/connect/authentication#authentication-via-the-stripe-account-header

**Comment by ravinderk** [comment]
Update from Stripe Support

> I wanted to send a quick update. It turns out there was a bug that was causing Checkout to hang with the test card 4000002500003155. We have published a fix.
> 
> Please feel free to respond directly to this thread with any further questions.

I will test functionality again to confirm.

**Comment by ravinderk** [comment]
@DevinWalker I tested this and as Stripe support confirmed that issue fixed on there end, it working fine for me also: https://www.loom.com/share/e3796ed127e44804bb064910c53da39d
