### ISSUE TITLE
fix: don't charge 2% application fee for Stripe Checkout 2.0 payments

### ISSUE THREAD

**Issue by mehul0810** [impress-org/givewp#4287]
@mikejhale commented on [Fri Oct 25 2019](https://github.com/impress-org/givewp-stripe/issues/423)

# Bug Report

## User Story

As an admin, I want to not be charged 2% fee when I'm using Stripe Premium so that I do  not have to pay fees I shouldn't be paying.

## Current Behavior

If the form is set to "Stripe checkout" the 2% fee is charged

## Expected Behavior

The 2% fee is not charged for Stripe Checkout 2.0 donations with Stripe Premium

## Bug Type

- [x] This bug describes functionality that once worked as expected in version 2.5.4.

## Steps to Reproduce

1. Activate Stripe Premium
2. Enable Stripe Checkout 2.0
3. Process a donation
4. Check Stripe Admin `Payment Details` > `Fee` and see the charge.  

## Visuals

![image](https://user-images.githubusercontent.com/1054196/67527132-e7178780-f67b-11e9-9799-cc2a94190dc6.png)

## Related

https://give.productboard.com/inbox/features/3167269/detail

## Acceptance Criteria

- [ ] 2% is not charged with Stripe Checkout 2.0

---

@mehul0810 commented on [Sat Oct 26 2019](https://github.com/impress-org/givewp-stripe/issues/423#issuecomment-546565972)

Moving this issue to Give core

**Comment by mikejhale** [comment]
Tested:
- [x] 2% Fee not charges when Stripe premium is activated

![image](https://user-images.githubusercontent.com/1054196/67712103-513c6f00-f991-11e9-88a1-d95c488808dc.png)
