### ISSUE TITLE
feat implement Square functionality from add-on to core

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp#4293]
# Feature Request

## User Story

As a user, I want to process payments with Square in core so that I do not require the addon.

**Note:** An application fee of 2% will be charged for each payment if the Square gateway add-on is not active.

## Acceptance Criteria
- [x] Move frontend donation processing files to Give Core
- [x] Donor can successfully donate using Square
- [x] Ensure validations work properly for Square Card Payments.
- [x] Ensure that donations are processed successfully with all the supported card types.
- [x] Ensure that application fee is deducted properly and reflects the same in Square dashboard of connected account and Give account.

**Comment by mehul0810** [comment]
@mikejhale @DevinWalker 

I've worked on the donation processing with Square with the latest update in the Square API. It is now processing donations properly and changing the application fee. Please see the below screenshot.
![image](https://user-images.githubusercontent.com/1852711/68272019-75323b80-0088-11ea-9acf-3d7a2d085eee.png)

Hence, closing this issue
