### ISSUE TITLE
feat: add settings for Square in core

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp#4294]
# Feature Request

## User Story

As a user, I want to configure my Square settings so that it I can accept payments with Square

## Acceptance Criteria

- [x] Square settings in Stripe core
- [x]  Ensure backward compatibility is retained for the settings moved to Square in core

**Comment by mehul0810** [comment]
I've worked on this issue and ensured that the admin settings for Square are backward compatible and moved properly to Square core.

![image](https://user-images.githubusercontent.com/1852711/68019831-cf1ab600-fcc2-11e9-877c-0ecbb5cca039.png)

Hence, closing this issue.
