### ISSUE TITLE
feat: implement Square webhooks

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp#4295]
# Feature Request

## User Story

As a user, I want to configure Square webhooks so that I have accurate data on the status of payments. 

## Acceptance Criteria
- [x] Research on implementing Square webhooks
- [ ] Add Webhook status check settings field in admin
- [ ] Make sure webhook is set properly when Square add-on is activated
- [ ] Show Webhook status under Square Settings
- [ ] If somehow, webhook not set automatically. Provide a link on clicking it will set the webhook

**Comment by mehul0810** [comment]
@mikejhale @DevinWalker 
Webhooks are not required as of now for one-time donations and we are not using the functionality for which the webhooks are supported by Square.

**For Reference:** https://developer.squareup.com/docs/webhooks-api

Hence, closing this issue.
