### ISSUE TITLE
feat: add Square as a payment method in Give Core

### ISSUE THREAD

**Issue by mikejhale** [impress-org/givewp#4296]
# Feature Request

## User Story

As a user, I want to enable Square in Give core so that I can accept donations with Square without needing the addon.

## Acceptance Criteria

- [x] Square is added as a payment gateway in Core.

**Comment by mehul0810** [comment]
I've added Square gateway to the list of payment gateways in Give settings. Square gateway will now display as a part of Square core irrespective of Square add-on is active or not active.

![image](https://user-images.githubusercontent.com/1852711/68014485-c40d5900-fcb5-11e9-9870-c8644625065a.png)

Hence, closing this issue.
