### ISSUE TITLE
fix: improve the donation listing in Square to avoid confusion

### ISSUE THREAD

**Issue by mehul0810** [impress-org/givewp#4300]
# Bug Report

## User Story
As a user, I want to see the better titles for the transaction so that I can quickly determine what donation amount I received from whom just from the Square dashboard listing.

## Current Behavior
Currently, There is a common title for each transaction in Square for all the donations via Give.

## Expected Behavior
I expect to have varied transaction title like `Donation via GiveWP: <form-name> -  <donor-name>` for better clarity

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [x] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Visuals
![image](https://user-images.githubusercontent.com/1852711/68272817-c2171180-008a-11ea-8ed4-8d7e927ce14e.png)

## Acceptance Criteria
- [ ] Improve the transaction title by setting proper note in code while processing a donation
- [ ] Testing

**Comment by DevinWalker** [comment]
I don't see this as an issue because I can click on the transaction and see the details. I think this is how most Square users expect it to work.
