### ISSUE TITLE
fix: connect the donor who donated via square to related payment transaction

### ISSUE THREAD

**Issue by mehul0810** [impress-org/givewp#4302]
# Bug Report

## User Story
As a user, I want to ensure that the donor is connected to proper donation in Square so that user can easily identify who donated.

## Current Behavior
Currently, donor is not linked with donation in Square dashboard

## Expected Behavior
I expect to see donor linked with the donation in Square dashboard

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [x] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Visuals
![image](https://user-images.githubusercontent.com/1852711/68645634-a3a78f00-053e-11ea-9f3c-be88b582ac67.png)

## Acceptance Criteria
- [ ] Link Donor with Donation in Square dashboard
- [ ] Testing

**Comment by DevinWalker** [comment]
We're already linking the transaction ID which leads to the donor (customer) profile in Square. I don't see us getting to this in the near future. Closing it out. If many customers ask for it we'll create a Canny feedback but none have as of yet.
