### ISSUE TITLE
fix: personalized message from tributes ecard not showing in preview or email

### ISSUE THREAD

**Issue by allienimmons** [impress-org/givewp#4303]
# Bug Report

## User Story

As a person leaving a tribute, I want the personalized message I leave to be sent via email to the person I am honoring so that they can see it.
As an admin of a site with forms that use tributes, I was my donor's personalized message to be viewable in teh preview of the donor record so that I can see it. 

## Current Behavior
Right now, if a donor leaves a tribute ecard and includes a personalized message, it will show up on the donor record page. However if the admin clicks preview, the message will be missing from the email. All other other ecard information will show, but the message will be missing. Also, the person receiving the ecard via email will see the same thing - an ecard with all the content except the personalized message. On the customers site, this is what happened. I tried it on a local site, and the same thing happened. I spun up a completely fresh site and was able to see the preview, but not the email in full. The customer reported that they saw this intermittent behavior.

## Expected Behavior
I expect as an admin to be able to preview the personalized ecard in full with no details missing.
As a recipient, I expect to see the same thing via the email I get.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Create a message in the Tributes ecard global settings that includes the {donation_message} email tag. You will see if you preview it from global settings that it works as expected with the text in a gray box.
2. Make a test donation with ecard enabled and leave a personlized message. 
3. Preview the donation record. You will see the  personalized message having been added and visible on the left. 
4. Click the Preview button to the right and notice that the preview is missing the personalized message.
5. check your inbox as the recipient of the ecard and see the same thing. 

## Visuals
![Donation record view with personalized message to the left](https://user-images.githubusercontent.com/41754561/68981692-49bef780-07d2-11ea-997f-97ac2360a5b3.png)
![ecard content in global settings](https://user-images.githubusercontent.com/41754561/68981693-49bef780-07d2-11ea-80ee-54c3815af418.png)
![ecard in email](https://user-images.githubusercontent.com/41754561/68981694-4a578e00-07d2-11ea-997e-857b0c7697da.png)
![Global settings preview](https://user-images.githubusercontent.com/41754561/68981695-4a578e00-07d2-11ea-9cff-7769e1f2c30f.png)

## Related
https://secure.helpscout.net/conversation/999770116/50272/

## Acceptance Criteria

- [ ] e.g. The personalized message is always visible in the donation record preview.
- [ ] e.g. The personalized message is always visible in the email.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X </li>
        <li>Version: 10.14.6</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
        <li>Version: Version 78.0.3904.97</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: https://www.goodpeoplefund.org/staging
Site URL: https://www.goodpeoplefund.org/staging
WP Version: 5.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: page
Page on Front: Home (#5722)
Page for Posts: Unset
Table Prefix Length: 1573053453_gpf_
Table Prefix Length: 15
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: www.goodpeoplefund.org
TLS Connection: 
TLS Connection: 
Server Info: Apache
PHP Version: 7.2.24
PHP Post Max Size: 32 MB
PHP Time Limit: 90
PHP Max Input Vars: 1000
PHP Max Upload Size: 32 MB
cURL Version: 7.66.0, OpenSSL/1.0.2t
SUHOSIN Installed: –
MySQL Version: 5.6.45
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.5.10
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ 1573053453_gpf_give_donors -  1.0✔ 1573053453_gpf_give_donormeta -  1.0✔ 1573053453_gpf_give_comments -  1.0✔ 1573053453_gpf_give_commentmeta -  1.0✔ 1573053453_gpf_give_sessions -  1.0✔ 1573053453_gpf_give_logs -  1.0✔ 1573053453_gpf_give_logmeta -  1.0✔ 1573053453_gpf_give_formmeta -  1.0✔ 1573053453_gpf_give_sequential_ordering -  1.0✔ 1573053453_gpf_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access✔Renewal Receipt Email❌Renewal Receipt Email✔Subscription Cancelled Email❌Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access✔Subscription Payment Failed Email
Upgraded From: 2.5.9
Test Mode: Disabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://www.goodpeoplefund.org/staging/donation-confirmation/
Failure Page: https://www.goodpeoplefund.org/staging/donation-failed/
Donation History Page: https://www.goodpeoplefund.org/staging/donation-history/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Stripe - Credit Card
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: November 6, 2019 2:57 pm

### Active GiveWP Add-ons ###

Give - Fee Recovery: ✔ Licensed – by GiveWP – 1.7.7
Give - Form Field Manager: ✔ Licensed – by GiveWP – 1.4.4
Give - Google Analytics Donation Tracking: ✔ Licensed – by GiveWP – 1.2.4
Give - MailChimp: ✔ Licensed – by GiveWP – 1.4.4
Give - PDF Receipts: ✔ Licensed – by GiveWP – 2.3.5
Give - Recurring Donations: ✔ Licensed – by GiveWP – 1.9.5
Give - Stripe Gateway: ✔ Licensed – by GiveWP – 2.2.2
Give - Tributes: ✔ Licensed – by GiveWP – 1.5.4

### Inactive Plugins ###

Accordion Shortcodes: by Phil Buchanan – 2.4.2
Admin Columns Pro: by AdminColumns.com – 4.7.2
Advanced Recent Posts: by Eugene Holin – 0.6.14
Annual Archive: by Twinpictures – 1.5.3
AW WordPress Yearly Category Archives: by Andy Warren – 1.2.8
BE Subpages Widget: by Bill Erickson – 1.7
Classic Editor: by WordPress Contributors – 1.5
Cloudflare: by John Wineman, Furkan Yilmaz, Junade Ali (Cloudflare Team) – 3.4.1
Custom Content Shortcode: by Eliot Akira – 3.8.5
Donations Plugin for GoodPeopleFund.Org: by InConcert Web, Greg Whitehead – 1.1
Easy Google Fonts: by Titanium Themes – 1.4.4
Elfsight Yottie: by Elfsight – 2.7.0
Give - Email Reports: by GiveWP – 1.1.4
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 7.10.0
Gravity Forms: by rocketgenius – 2.4.14
Gravity Forms MailChimp Add-On: by rocketgenius – 4.6
InfiniteWP - Client: by Revmakx – 1.9.4.2
iThemes Security Pro: by iThemes – 3.3.0
LayerSlider WP: by Kreatura Media – 6.9.2
Mail List Plugin for GoodPeopleFund.Org: by Insight Dezign, Edward Booth – 1.1
MimeTypes Link Icons: by Toby Cox, Juliette Reinders Folmer – 3.2.8
Native PHP Sessions for WordPress: by Pantheon – 0.9.0
Popup Maker: by Popup Maker – 1.8.14
Quick Page/Post Redirect Plugin: by anadnet – 5.1.9
Recent Posts Widget Extended: by Satrya – 0.9.9.7
Remove Query Strings From Static Resources: by Speed Up My Website – 1.4
Shortcodes Ultimate: by Vladimir Anokhin – 5.6.0
ShortPixel Image Optimizer: by ShortPixel – 4.14.6
Simple Custom CSS: by John Regan, Danny Van Kooten – 4.0.3
Simple Social Icons: by StudioPress – 3.0.1
Toolset Types: by OnTheGoSystems – 3.3.6
Ultimate Posts Widget: by Boston Dell-Vandenberg – 2.0.7
User Role Editor: by Vladimir Garagulya – 4.52.1
Wordfence Security: by Wordfence – 7.4.1
WPBakery Page Builder: by Michael M - WPBakery.com – 6.0.5
WP Feedback: by WP Feedback – 1.1.8
WP Mail SMTP: by WPForms – 1.7.1
WP Time Capsule Staging: by Revmakx – 1.0.0
Yoast SEO: by Team Yoast – 12.5

### Active MU Plugins ###

ManageWP - Worker Loader: by ManageWP –

### Theme ###

Name: Twenty Nineteen
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by DevinWalker** [comment]
Issue moved to [impress-org/give-tributes #293](https://github.com/impress-org/give-tributes/issues/293) via [**ZenHub**](https://www.zenhub.com/)
