### ISSUE TITLE
fix: resolve updates not showing up without a refresh licenses.

### ISSUE THREAD

**Issue by Benunc** [impress-org/givewp#4318]
# Bug Report

## User Story

As a site admin, I want all GiveWP plugins to show updates reliably, without having to refresh the licenses.

## Current Behavior
In more than a few cases over the past few months, updates to add-ons don't show unless the user goes and manually clicks the "refresh all licenses" button. 

## Expected Behavior
I expect the updates to show up automatically.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in some previous version.

## Steps to Reproduce
Not easily replicable, but I have a digital ocean-hosted site with no caching and when an update comes out for certain add-ons (not sure which ones) it often doesn't display until the "refresh all licenses" button is clicked.

## Possible Solution
Could the readme problem fixed in the GiveWP website resolve this?

## Acceptance Criteria
- [x] add-on updates show in a timely manner (72 hours) without having to refresh licenses.
- [x]  look for add-ons updates when someone manually presses the "Check Again" button within WP's Dashboard > Updates

**Comment by Benunc** [comment]
This just happened on a customer site with the PDF receipts add-on.

**Comment by ravinderk** [comment]
@Benunc We setup monthly cron to refresh license information.
ref: https://github.com/impress-org/givewp/blob/3cb3506109adea10d7ae8d3633a616fce1c8092f/includes/actions.php#L17

So yes there is a possibility that admin will not see add-on update till one month. We did that because we do not want to overload `givewp` website with license check requests.

**Comment by ravinderk** [comment]
@Benunc To manually update license information they just have to visit license setting page, no need to click on refresh licenses button.
https://github.com/impress-org/givewp/blob/3cb3506109adea10d7ae8d3633a616fce1c8092f/includes/admin/settings/class-settings-license.php#L43
