### ISSUE TITLE
fix: Recurring Donations 1.9.7 does not provide an update and refreshed updates don't stick

### ISSUE THREAD

**Issue by allienimmons** [impress-org/givewp#4323]
# Bug Report

## User Story

As a GiveWP Recurring Donations user, I want to 

- see an automatic update alert on the plugins page from 1.9.6 to 1.9.7
- update the add-on to 1.9.7 and see it remain in that version when the page is refreshed 

so that I'm not confused and am able to use the most up to date version of the plugin.

## Current Behavior
The Recurring Donations plugin does not automatically offer an update to 1.9.7. If you refresh the license it will, but then updating it reverts back to 1.9.6 if you refresh the page or leave the page and come back to it. 

## Expected Behavior
For the update for Recurring to automatically show on the plugins page. 
And when it's updated, for it to remain that way.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Open a site with GiveWP and Recurring Donations (1.9.6)
2. Notice there is no update on the plugins page for 1.9.6
3. Go to Donations > Licenses and click Refresh All Licenses
4. Go to Dashboard > Check Again
5. Go to the Plugins page - notice there is now an alert for Recurring to be updated to 1.9.7. 
6. Click update, wait for the green checkmark.
7. Refresh the page
8. Notice the plugin goes back to 1.9.6

## Acceptance Criteria

- [x] e.g. Recurring 1.9.6 or any other version will show a yellow update alert on the plugins page, prompting the user to update to 1.9.7.
- [x] e.g. Once updated, the plugin does not revert to an older version.

## Environment### WordPress Environment ###

Home URL: https://give.allienimmons.com
Site URL: https://give.allienimmons.com
WP Version: 5.3
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: Siteground
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.29 (Unix) mod_hive/6.27 OpenSSL/1.0.1e-fips mod_fastcgi/2.4.6
PHP Version: 7.3.12
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
PHP Max Upload Size: 128 MB
cURL Version: 7.59.0, OpenSSL/1.0.2r
SUHOSIN Installed: –
MySQL Version: 5.6.36
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.5.10
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access❌Renewal Receipt Email❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Cancelled Email❌Subscription Completed Email✔Subscription Reminder Email✔Subscriptions Email Access✔Subscription Payment Failed Email
Upgraded From: 2.5.10
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://give.allienimmons.com/donation-confirmation/
Failure Page: https://give.allienimmons.com/donation-failed__trashed/
Donation History Page: https://give.allienimmons.com/donation-history__trashed/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Stripe - Credit Card
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: N/A

### Active GiveWP Add-ons ###

Give - Recurring Donations: ✔ Licensed – by GiveWP – 1.9.6
Give - Stripe Gateway: ✔ Licensed – by GiveWP – 2.2.2

### Other Active Plugins ###

Yoast SEO: by Team Yoast – 12.6.2

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.1.3
Give - Authorize.net Gateway: by GiveWP – 1.4.6
Give - Braintree Gateway: by GiveWP – 1.2.4
Give - Currency Switcher: by GiveWP – 1.3.5
Give - Donation Upsells for WooCommerce: by GiveWP – 1.1.4
Give - Email Reports: by GiveWP – 1.1.4
Give - Fee Recovery: by GiveWP – 1.7.7
Give - Form Field Manager: by GiveWP – 1.4.4
Give - GoCardless Gateway: by GiveWP – 1.3.4
Give - MailChimp: by GiveWP – 1.4.5
Give - Manual Donations: by GiveWP – 1.4.5
Give - PayFast Payment Gateway: by WordImpress – 1.0.2
Give - Paytm Gateway: by GiveWP – 1.1.0
Give - PDF Receipts: by GiveWP – 2.3.6
Give - Per Form Gateways: by GiveWP – 1.0.2
Give - Tributes: by GiveWP – 1.5.4
My Custom Functions: by Space X-Chimp – 4.40

### Theme ###

Name: Twenty Twenty
Version: 1.0
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

**Comment by DevinWalker** [comment]
This was a caching issue - I've cleared it and now the updates work as expected.
