### ISSUE TITLE
fix: Stripe Checkout redirect loop.

### ISSUE THREAD

**Issue by rickalday** [impress-org/givewp#4329]
# Bug Report

## User Story

As a user, I want to use Stripe Checkout's Redirect option without any issues.

## Current Behavior

The form redirect's to itself.
<img width="1276" alt="Screen Shot 2019-12-12 at 1 41 20 PM" src="https://user-images.githubusercontent.com/312000/70743336-25790c80-1ce5-11ea-8b14-f6f8e30fea10.png">

## Expected Behavior

It should redirect to Stripe's Checkout page.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Use default theme
2. Activate Give core and Stripe add-on
3. Set Stripe Checkout Type to Redirect
4. In Give Advanced Settings set "Script Loading Location" to "Footer"
5. Try to make a donation and you will see the form page just redirect to itself.

## Visuals

Reproduced and workaround:
http://somup.com/cqllqsfaps

## Possible Solution

The workaround is to set "Script Loading Location" to "Header" in Give Advanced Settings but this can lead to other issues if the user needs to load the scripts in the footer.

## Related

https://secure.helpscout.net/conversation/1014385246/51425/

## Acceptance Criteria

- [ ] e.g. Something happens when an action is taken.
- [ ] e.g. Something does not happen when an action is taken.
- [ ] e.g. Fixing behavior in Component A does not affect existing behavior in Component B.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X | Microsoft Windows | Linux | Android | iOS</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    
</details>

**Comment by Benunc** [comment]
Given that there is a workaround here, if this can't be fixed easily we'll need to add this to the docs for Stripe checkout.
