### ISSUE TITLE
Develop New Reports Screen UI

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#4330]
# Epic User Story

As an admin, I want to view reports that are more informative, filterable, and flexible so that my fundraising efforts can be better optimized and actionable. As well, when I log in to WordPress I want a better dashboard widget that shows me the most relevant data and is filterable based on dates but won't slow down my wp-admin main dashboard load times.

## Appetite

1 month

## Solution

A new screen is built in react to replace our current reports screen that displays data based on the data that can be easily queried from our current data structure.

## Rabbit Holes

- This is the MVP approach so spending too much time trying to optimize how data is pulled from the database or creating an API may not be necessary. As long as data can be pulled and queried and data is flowing into the reports within an acceptable load time, that'll suffice.
- Creating charts and graphs that can be reused by other add-ons or third-party developers or an entire API for creating them. Just create base line data graphs.
- Spending too much time on backwards compatibility. Ensure that "legacy" reports can be viewed in a simply and efficient fashion.

## No-gos
- Do not develop front-end embeds (but keep in mind that's what we'll want to do eventually.)
- Data doesn't have to be exportable right now, although you'll see an option in the concepts.
- Don't build all the tabs in the concepts right now, just focus on the dashboard widget and main reports screen (containing all the most valuable reports that are possible given our current db structure.)

## Designs

See figma here: https://www.figma.com/file/w38WexhmfOkcXRvFOTNgcO/GiveWP-Updated-Admin-Screens?node-id=0%3A10592

Note that all these screens are not in the MVP scope. Only the dashboard widget and basic reports screen.

The most valuable and easiest reports to query should be in the MVP. 

![2019-12-12_16-51-43](https://user-images.githubusercontent.com/1571635/70760802-b4931e00-1cff-11ea-8bc8-db280dbf9f1e.png)

![2019-12-12_16-51-33](https://user-images.githubusercontent.com/1571635/70760804-b78e0e80-1cff-11ea-8b4f-b5a2d9217d75.png)

**Comment by henryholtgeerts** [comment]
**Call Summary(s) - Dec 12th:**
**Discussing Reports: Pt 1**
- Henry demoed progress on reports so far
- Discussed need to refactor to avoid side effects and eliminate static facade

**Discussing Reports: Pt 2**
- Discussed pros/cons of report-builder API approach vs frontend heavy hard-coded approach
- Discussed how existing work could be rolled into a more frontend heavy solution
- Talked through challenges posed in registering reports API endpoints for different addons

**Comment by henryholtgeerts** [comment]
### Overview Page Metrics

The following metrics were decided upon after comparing original Figma designs with additional research into common non-profit KPIs and CEO dashboards. One valuable document regarding sample non-profit indicators can be found here: https://www.compasspoint.org/sites/default/files/documents/560_libraryofindicatorsjune09.pdf

**Income Over Time**
_Line chart depicting site-wide income for the selected period of time. Each datapoint shows $$$ earned and # of donations for that point in time._

**Total Income**
_MiniChart depicting total income earned for the selected period of time, as well as the current trend in income_

**Total Donors**
_MiniChart depicting total individual donors for the selected period of time, as well as the current trend in donor count_

**Average Donation**
_MiniChart depicting average donation amount for the selected period of time, as well as the current trend in average donation amount_

**Total Refunds**
_MiniChart depicting total number of refunds for the selected period of time, as well as the current trend in refund count_

**Top Form Performance**
_Pie chart depicting popularity of the top donation forms for a given period of time_

**Payment Statuses**
_Bar chart depicting current payment status counts (completed, abandoned, refunded, cancelled) for a give period of time_

**Payment Methods**
_Doughnut chart depicting popularity of different payment methods for a given period of time_

**Top Donors**
_List of top 25 donors for the selected period of time_

**Recent Donations**
_List of 25 most recent donations for the selected period of time_

**Bonus: Top Donation Locations**
_List of top 10 donation locations for the selected period of time (queried using city/country meta data)_
