### ISSUE TITLE
refactor: add yarn workspace for givewp components

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#4349]
# Feature Request

## User Story

As a developer, I want to import shared GiveWP components from Yarn workspaces so that I do not have to load components using relative paths.

## Visuals
n/a

## Possible Solution
Setup GiveWP Yarn workspace, have a shared components directory and index, modeled after GiveIO.

## Acceptance Criteria
- [ ] Shared presentational components can be easily imported without using relative paths
- [ ] Shared presentational components can be easily made available to other components from the workspace

**Comment by JasonTheAdams** [comment]
NPM supports workspaces now and we'll make a separate repo at the right time.
