### ISSUE TITLE
fix: activating Give impact the design of WP core editor

### ISSUE THREAD

**Issue by mehul0810** [impress-org/givewp#4354]
# Bug Report

## User Story
As a user, I want to ensure that the design of the core editor is not affected by using Give plugin so that I can use the core editor without any issues.

## Current Behavior
*Before activating Give*
![image](https://user-images.githubusercontent.com/1852711/71173399-a35e8a00-2288-11ea-9314-97a5fd3da80f.png)

*After activating Give*
![image](https://user-images.githubusercontent.com/1852711/71173316-61354880-2288-11ea-8ddd-5888413ffc94.png)

*After activating Give - Core Editor in Full Screen Mode*
![image](https://user-images.githubusercontent.com/1852711/71173688-5fb85000-2289-11ea-99d7-662f22a92863.png)

## Expected Behavior
I expect to see that the plugin designs should not conflict with core editor.

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Keep Gutenberg enabled with the latest version of WordPress
2. Check the design of the core editor especially the area marked in the screenshot. Also, track performance using Query Monitor
3. Install and Activate Give Core only.
4. Notice the difference in the core editor again. You will see the issue. Do check this design issue in a variety of screens like on 13inch MBP

## Acceptance Criteria
- [x] Core Editor UI should not be impacted by GiveWP plugin
- [x] Testing with various screen sizes

**Comment by DevinWalker** [comment]
@mehul0810 note that the color changing of Query Monitor is done by that plugin itself. The color changes from orange to red depending on the load time of the page. We're not modifying that at all. 

I'll take a look into the other issues you pointed out today!
