### ISSUE TITLE
fix: ensure donor wall shortcode attribute "form" applies to the returned donors

### ISSUE THREAD

**Issue by samsmith89** [impress-org/givewp#4359]
# Bug Report

## User Story

As a site admin, I want to only display donors from a certain form using the donor wall shortcode.

## Current Behavior
As per the documentation:
https://givewp.com/documentation/core/shortcodes/give_donor_wall/
This feature is already available with the attribute "form".
When this attribute is used the wall still displays all the donors on the site.

## Expected Behavior

I expect the attribute to limit the number of displayed donors to the specified form.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Create a shortcode similar to [give_donor_wall form="2079"]
2. Save the page and view it on the front-end
3. See that all the donors are displayed on the page

## Visuals

Here is a link to a form with the shortcode mentioned in the steps:
https://give.gsamsmith.com/donor-wall/

## Related

Helpscout ticket:
https://secure.helpscout.net/conversation/1037494372/53581

Doc where this feature is mentioned:
https://givewp.com/documentation/core/shortcodes/give_donor_wall/

Similar issue stating this as a feature request:
https://github.com/impress-org/givewp/issues/4233

## Acceptance Criteria

- [ ] When the donor wall shortcode has the "form" attribute it only shows that donation form.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    ### WordPress Environment ###

Home URL: https://give.gsamsmith.com
Site URL: https://give.gsamsmith.com
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: yXk_
Table Prefix Length: 4
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: give.gsamsmith.com
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.15.8
PHP Version: 7.3.8-1+ubuntu18.04.1+deb.sury.org+1
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
PHP Max Upload Size: 64 MB
cURL Version: 7.58.0, OpenSSL/1.1.1
SUHOSIN Installed: –
MySQL Version: 5.7.28
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.5.10
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ yXk_give_donors -  1.0✔ yXk_give_donormeta -  1.0✔ yXk_give_comments -  1.0✔ yXk_give_commentmeta -  1.0✔ yXk_give_sessions -  1.0✔ yXk_give_logs -  1.0✔ yXk_give_logmeta -  1.0✔ yXk_give_formmeta -  1.0✔ yXk_give_sequential_ordering -  1.0✔ yXk_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access✔Daily Email Report✔Weekly Email Report✔Monthly Email Report✔Renewal Receipt Email❌Renewal Receipt Email✔Subscription Cancelled Email❌Subscription Cancelled Email✔Subscription Completed Email✔Subscription Reminder Email✔Subscriptions Email Access✔Subscription Payment Failed Email
Upgraded From: 2.5.9
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://give.gsamsmith.com/donation-confirmation/
Failure Page: https://give.gsamsmith.com/donation-failed/
Donation History Page: https://give.gsamsmith.com/donation-history/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Authorize.net, Offline Donation
Default Payment Gateway: Authorize.net
PayPal IPN Verification: Enabled
PayPal IPN Notifications: IPN received for #798 ( 1X399962F5537932C ) on 12/08/2019 at 15:22. Status VERIFIED
Donor Email Access: Enabled
Stripe Webhook Notifications: December 13, 2019 3:33 pm

### Active GiveWP Add-ons ###

Give - Annual Receipts: ❌ Unlicensed – by GiveWP – 1.0.2
Give - Authorize.net Gateway: ✔ Licensed – by GiveWP – 1.4.6
Give - Braintree Gateway: ✔ Licensed – by GiveWP – 1.2.4
Give - Donation Upsells for WooCommerce: ✔ Licensed – by GiveWP – 1.1.4
Give - Email Reports: ✔ Licensed – by GiveWP – 1.1.4
Give - Form Countdown: ❌ Unlicensed – by WordImpress – 1.0.1
Give - Form Field Manager: ✔ Licensed – by GiveWP – 1.4.4
Give - Manual Donations: ✔ Licensed – by GiveWP – 1.4.5
Give - Moneris: ❌ Unlicensed – by GiveWP – 1.0.0
Give - PayPal Pro Gateway: ✔ Licensed – by GiveWP – 1.2.2
Give - PDF Receipts: ✔ Licensed – by GiveWP – 2.3.6
Give - Per Form Gateways: ✔ Licensed – by GiveWP – 1.0.2
Give - Recurring Donations: ✔ Licensed – by GiveWP – 1.9.7
Give - Sofort Payment Gateway: ❌ Unlicensed – by WordImpress, CoachBirgit – 1.0
Give - Stripe Gateway: ✔ Licensed – by GiveWP – 2.2.2
Give - Tributes: ✔ Licensed – by GiveWP – 1.5.4
Give - Zapier: ✔ Licensed – by GiveWP – 1.2.3

### Other Active Plugins ###

Email Cop: by Ashfame – 0.1.1
Give - Hook Helper: by Ravinder Kumar – 1.0
Give - Sofort Payment Gateway: by WordImpress, CoachBirgit – 1.0

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.1.3
All-in-One WP Migration File Extension: by ServMask, Inc. – 1.5
ARI Adminer: by ARI Soft – 1.2.3
Contact Form 7: by Takayuki Miyoshi – 5.1.6
Debug Bar: by wordpressdotorg – 1.0
Duplicator: by Snap Creek – 1.3.24
Give - 2Checkout Gateway: by WordImpress – 1.1.3
Give - AmeriCloud Payments: by AmeriCloud Solutions, Inc. – 1.3.4
Give - AWeber: by GiveWP – 1.0.4
Give - CCAvenue Gateway: by GiveWP – 1.0.4
Give - Constant Contact: by GiveWP – 1.2.4
Give - ConvertKit: by GiveWP – 1.0.3
Give - Currency Switcher: by GiveWP – 1.3.5
Give - Fee Recovery: by GiveWP – 1.7.7
Give - Gift Aid: by GiveWP – 1.2.3
Give - GoCardless Gateway: by GiveWP – 1.3.5
Give - Google Analytics Donation Tracking: by GiveWP – 1.2.4
Give - iATS Payment Solutions: by GiveWP – 1.0.5
Give - MailChimp: by GiveWP – 1.4.5
Give - Mollie Gateway: by GiveWP – 1.2.3
Give - PayFast Payment Gateway: by WordImpress – 1.0.2
Give - Paymill Gateway: by GiveWP – 1.1.0
Give - Paytm Gateway: by GiveWP – 1.1.0
Give - PayUmoney: by GiveWP – 1.0.5
Give - Razorpay: by GiveWP – 1.3.0
Helper Plugin: by  – 1.0
iThemes Sync: by iThemes – 2.1.0
Limit Login Attempts Reloaded: by WPChef – 2.10.0
My Custom Functions: by Space X-Chimp – 4.40
Query Monitor: by John Blackbourn – 3.5.2
SpinupWP: by Delicious Brains – 1.1.2
Transients Manager: by Pippin Williamson – 1.8
WooCommerce: by Automattic – 3.8.1
WooCommerce Blocks: by Automattic – 2.5.2
WordPress Importer: by wordpressdotorg – 0.6.4
WP Business Reviews: by Impress.org – 1.2.0
WP Config File Editor: by AHMeD SAiD – 1.6.7
WP Crontrol: by John Blackbourn & crontributors – 1.7.1
WP Rollback: by Impress.org – 1.7.0

### Active MU Plugins ###

SpinupWP Debug Log Path: by Delicious Brains – 1.0
SSO: by Garth Mortensen, Mike Hansen – 0.3

### Theme ###

Name: Twenty Seventeen
Version: 2.2
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by ravinderk** [comment]
@samsmith89 I found that `form` is not correct shortcode attribute. it is `from_id` which causes of filter donor list on the basis of the specific donation form. You can review that on the testing site.

I will create an issue to update donor wall shortcode document: https://givewp.com/documentation/core/shortcodes/give_donor_wall/

**Comment by DevinWalker** [comment]
Thanks for investigating @ravinderk - we'll make sure this doc gets updated.

**Comment by samsmith89** [comment]
@ravinderk I've tested this in a live site and it still is not working. I've created a page here that should have multiple donations listed, but it is only displaying one donation from the first form id:
https://give.gsamsmith.com/donor-wall/
Let me know if you need me to open another issue.

**Comment by ravinderk** [comment]
@samsmith89 We do not support filtering donor lists on the basis of multiple forms. You can do this on for specific form. Please create another issue for that.

**Comment by dev-myk** [comment]
@samsmith89 Hi, I am experiencing the same problem with giveWP. how did you go about it to solve it?

**Comment by JasonTheAdams** [comment]
Hi @dev-myk! I suggest reaching out to [our support team](https://givewp.com/support) so they can dig into the issue with you. This is a very old, closed Issue, and I'd hate for your questions not to get answered.

**Comment by dev-myk** [comment]
Hi, thank you for responding, let me get in touch with them.
