### ISSUE TITLE
Stripe account depending on Form ID

### ISSUE THREAD

**Issue by huzaifahj** [impress-org/givewp#4363]
Hey guys,

I'm new on github and was directed here via the wordpress.org support forum.

I'm wondering if you can guide me on making custom code to allow the stripe account (secret key, publishable key, user id) to vary depending on the form ID. I'm aware there is a paypal solution of this which is much simpler as it just deals with an email.

It seems the keys can be manually overriden at:
includes/gateways/stripe/includes/admin/admin-helpers.php
line 86

I guess you could globally modify the keys once a form is submitted? But then there will be an issue if multiple forms are submitted at once? I'm not sure of the best way to approach this.

Kind regards and thanks for your time.

**Comment by DevinWalker** [comment]
Closing as we now have support for Multiple Stripe Accounts.
