### ISSUE TITLE
fix: download addon when "download" button is selected on License page

### ISSUE THREAD

**Issue by samsmith89** [impress-org/givewp#4375]
# Bug Report

## User Story

As a site admin, I want to download the addon from the License page with the button that's provided so that I can easily get a copy of the zip file without having to log into my account at Give.

## Current Behavior

With an active subscription, I'm unable to download the zip file from the Licenses page. An error message "You must have an active subscription to Authorize.Net Gateway in order to download this file." displays on the page. 

## Expected Behavior

I expect to have a zip file of the addon download when I select the button.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Set up an active subscription for a license in the backend of Give.
2. Select the button to download the addon.
3. See you are presented with the error message

## Visuals

![Screen Shot 2019-12-30 at 10 08 13 AM](https://user-images.githubusercontent.com/20672471/71587584-51b9c900-2aec-11ea-8791-a87b87a0457d.png)

## Related

https://secure.helpscout.net/conversation/1041592951/53831/

## Acceptance Criteria

- [ ] The zip file is downloaded when the "download" button is selected on the Licenses page.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    
</details>

**Comment by DevinWalker** [comment]
I'm having a hard time reproducing this. @samsmith89 please see this video: https://www.loom.com/share/0068d167ba8f4587a31b1da197d1cec8

If you can let me know how I can replicate it outside the steps provided that would be useful. For now, I'll close this one out. If replicable please reopen.
