### ISSUE TITLE
fix: No email notifications are sent for new donations

### ISSUE THREAD

**Issue by rickalday** [impress-org/givewp#4379]
# Bug Report

## User Story

As an admin, I want to receive email notifications when a new donation is made.
As a donor, I also want to get a receipt of my donation.

## Current Behavior

No emails are sent to the donor or admin.

## Expected Behavior
Notification emails should be sent to the donor and admin.

## Bug Type

- [x] This bug describes functionality that once worked as expected in version 2.5.10.

## Steps to Reproduce

1.  Install Give and enable Stripe
2. Make a test donation
3. Check donation history, the donation is marked as complete and all data is in the backed but no emails are sent to the admin nor the donor.

## Related
https://secure.helpscout.net/conversation/1043850980/54004?folderId=672194
https://secure.helpscout.net/conversation/1042219285/53878?folderId=672194
https://secure.helpscout.net/conversation/1041754216/53840?folderId=3046394
https://secure.helpscout.net/conversation/1042803165/0/?folderId=672194
https://secure.helpscout.net/conversation/1042839378/0/?folderId=672194
https://secure.helpscout.net/conversation/1042888875/0/?folderId=672194
https://secure.helpscout.net/conversation/1042975821/53961?folderId=672194
https://secure.helpscout.net/conversation/1041432852/53819
https://secure.helpscout.net/conversation/1037663251/53592
https://secure.helpscout.net/conversation/1039186906/53705/
https://secure.helpscout.net/conversation/1043850980/54004
https://secure.helpscout.net/conversation/1043850980/54004?folderId=672194

## Acceptance Criteria

- [x] When donation notification emails are sent to donors and admins

**Comment by allienimmons** [comment]
There are more examples in HS - they all have the "noemails" tag.

**Comment by ravinderk** [comment]
@DevinWalker This issue arises because of a small patch of another issue https://github.com/impress-org/givewp/issues/4379
