### ISSUE TITLE
feat: show payment note list sorted by note id 

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#4388]
# Feature Request

## Developer Story
As a developer, I want to see the note list in the correct order so that I can debug it.

## Visuals
The current list of note sorted by time instead of note id https://github.com/impress-org/givewp/blob/9cad5af533162f0d314bd8a5b5b4680088dcad38/includes/admin/payments/view-payment-details.php#L859
![image](https://user-images.githubusercontent.com/1784821/71709447-2b15ce00-2e1d-11ea-9982-3b239c50e4e4.png)

## Acceptance Criteria
- [ ] Donation note list sorted by ID

**Comment by DevinWalker** [comment]
Closing as ambiguous / lacking detail. Related: https://givewp.canny.io/feature-requests/p/improve-donation-details-screen
