### ISSUE TITLE
Tests should run in the context of continuous integration

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#4391]
# Bug Report

## User Story
As a developer, I want TravisCI to successfully setup tests so that it can continue with the testing process.

## Current Behavior
On occasion, the below error appears while running checks on TravisCI. 
`The command "bash tests/bin/install.sh give_test root '' localhost $WP_VERSION" failed and exited with 56 during .`

ref: https://travis-ci.org/impress-org/givewp/jobs/633822482?utm_medium=notification&utm_source=github_status

## Visuals
![Screen Shot 2020-01-07 at 11.05.42 AM.png](https://images.zenhubusercontent.com/5de5476735cbb7ad97ed643a/e011c5e2-ddb4-4e85-aeb0-e9535ac61093)

## Expected Behavior
TravisCI should be able to setup/install tests, and continue on to run those tests.

## Bug Type
- [x] This bug describes functionality that once worked as expected.
- [ ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
Unsure of exact steps needed to reproduce. See [this failing PR as an example](https://github.com/impress-org/givewp/pull/4338)

## Acceptance Criteria
- [ ] TravisCI can setup tests without errors
- [ ] OR problem in checked code can be identified and a solution is found

**Comment by ravinderk** [comment]
In addition to that sometime we also face this issue:

![image](https://user-images.githubusercontent.com/1784821/71915837-9c011100-31a2-11ea-8c8c-0279fd145a79.png)


ref:https://travis-ci.org/impress-org/givewp/jobs/632448842?utm_medium=notification&utm_source=github_status

**Comment by DevinWalker** [comment]
I've created a Canny Feedback for improving unit testing: https://givewp.canny.io/feature-requests/p/improve-unit-testing

**Comment by kevinwhoffman** [comment]
This issue has no direct user-facing aspect to it, so we're going to keep this type of issue in GitHub. I've updated the title and label accordingly.

**Comment by JasonTheAdams** [comment]
We are now running tests in all CI scenarios.
