### ISSUE TITLE
Bug: wrong order being set for form grid sorting

### ISSUE THREAD

**Issue by allienimmons** [impress-org/givewp#4392]
# Bug Report

## User Story

As a website admin, I want to use the Form Grid Block settings to sort the forms by title alphabetically.

## Current Behavior
Currently, when you use the Form Grid Block and sort by Form Title, it will sort by the slug instead. If the Form title is the same as the slug, this is not a problem. But if the slug and form title are different, the slug is the element that is being alphabetized, not the title.

## Expected Behavior
When the user chooses "Order by: Form Name" the forms should be ordered by the title of the form, not the slug.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. I added GiveWP on a fresh WordPress install
2. I created 5 forms: Test A, Test B, Test C, Test D. 
3. I edited each slug so that Test B's slug was A, Test D's slug was B, Test A's slug was C and Test C's slug was D. 
4. I created a new page and added the Form Grid.
5. I chose "Form Title" under the Order By dropdown.
6. The forms sorted themselves by slug. Instead of Forms A, B, C and D, they sorted into B, D, A and C, proving that the slug was being alphabetized instead of the title.

## Visuals
![Screen Shot 2020-01-08 at 9 31 15 AM](https://user-images.githubusercontent.com/41754561/71986073-cf22bf00-31f9-11ea-98e6-a84364ba1127.png)

## Acceptance Criteria

- [ ] e.g. Forms in the Form Grid are sorted by title and not slug.
- [ ] e.g. If the slug of a form is changed, it does not affect it's sorting behavior.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X </li>
        <li>Version: 10.14.6</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
        <li>Version: 79.0.3945.88</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://amys-bug.local
Site URL: http://amys-bug.local
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: amys-bug.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.14.0
PHP Version: 7.2.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
PHP Max Upload Size: 300 MB
cURL Version: 7.52.1, OpenSSL/1.0.2l
SUHOSIN Installed: –
MySQL Version: 5.7.23
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.5.12
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://amys-bug.local/donation-confirmation/
Failure Page: http://amys-bug.local/donation-failed/
Donation History Page: http://amys-bug.local/donation-history/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: N/A

### Theme ###

Name: Twenty Twenty
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by henryholtgeerts** [comment]
@allienimmons Thanks for writing this up! I'll get started on it this afternoon. 👍

**Comment by henryholtgeerts** [comment]
Update! A fix has been proposed and is being reviewed here: https://github.com/impress-org/givewp/pull/4397

**Comment by henryholtgeerts** [comment]
Fix has been merged and will be available in Release 2.5.13 😺
