### ISSUE TITLE
Bug: Multiple Donate buttons appearing when a button mode form also appears on the page

### ISSUE THREAD

**Issue by allienimmons** [impress-org/givewp#4395]
# Bug Report

## User Story

As a site admin, I want to be able to have multiple forms of any kind on the same page without seeing errors.

## Current Behavior
When a full-view form and a button form shortcode are embedded onto the same page, the full-view form will show two donate buttons one after the other.

## Expected Behavior
No matter how many forms and what type, there should only ever be one donate button.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Install GiveWP on a fresh WP install.
2. Create two forms - one All Fields, one Button.
3. Embed both on a page using their shortcodes.
4. Observe the All Fields form has 2 buttons at the bottom.

## Visuals
http://somup.com/cYVjbrfdFX

## Related
https://secure.helpscout.net/conversation/1034777306/53231/

## Acceptance Criteria

- [x] e.g. One button appears when a form is embedded where a button form is also embedded
- [x] e.g. No matter how many forms are on what page and what type, each only has 1 donate button.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
        <li>Version: 10.14.6</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
        <li>Version:79.0.3945.88</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: https://give.allienimmons.com
Site URL: https://give.allienimmons.com
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: Siteground
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.29 (Unix) mod_hive/6.27 OpenSSL/1.0.1e-fips mod_fastcgi/2.4.6
PHP Version: 7.3.13
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
PHP Max Upload Size: 128 MB
cURL Version: 7.59.0, OpenSSL/1.0.2r
SUHOSIN Installed: –
MySQL Version: 5.6.36
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.5.12
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access
Upgraded From: 2.5.11
Test Mode: Disabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://give.allienimmons.com/donation-confirmation/
Failure Page: 
Donation History Page: https://give.allienimmons.com/history/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Stripe - Credit Card, PayPal Standard, Test Donation, Offline Donation
Default Payment Gateway: Offline Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: N/A

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.1.3
Give - Annual Receipts: by GiveWP – 1.0.2
Give - Authorize.net Gateway: by GiveWP – 1.4.6
Give - Braintree Gateway: by GiveWP – 1.2.4
Give - CCAvenue Gateway: by GiveWP – 1.0.4
Give - Currency Switcher: by GiveWP – 1.3.5
Give - Email Reports: by GiveWP – 1.1.4
Give - Fee Recovery: by GiveWP – 1.7.7
Give - Form Field Manager: by GiveWP – 1.4.4
Give - MailChimp: by GiveWP – 1.4.5
Give - Manual Donations: by GiveWP – 1.4.5
Give - PayFast Payment Gateway: by WordImpress – 1.0.2
Give - PayPal Pro Gateway: by GiveWP – 1.2.2
Give - Paytm Gateway: by GiveWP – 1.1.0
Give - PDF Receipts: by GiveWP – 2.3.6
Give - Per Form Gateways: by GiveWP – 1.0.2
Give - Recurring Donations: by GiveWP – 1.9.8
Give - Square: by GiveWP – 1.0.4
Give - Stripe Gateway: by GiveWP – 2.2.2
Give - Tributes: by GiveWP – 1.5.6
Give - Zapier: by GiveWP – 1.2.3
Loco Translate: by Tim Whitlock – 2.3.1
My Custom Functions: by Space X-Chimp – 4.40
WooCommerce: by Automattic – 3.8.1

### Theme ###

Name: Twenty Twenty
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by rickalday** [comment]
Another related ticket: https://secure.helpscout.net/conversation/1053604628/54886
