### ISSUE TITLE
feat: add additional up sells in the plugin for increased awareness of pro version

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#4400]
# Feature Request

In order to increase new customer counts we should add new up sells into the plugin that are not overly intrusive but still beneficial to bringing customers onto our site.

### 1. Update "Add-ons" link so it's more prominent

Ensure that the "Add-ons" link is more visible and opens in a new tab so that we can then send to a landing page on our site specifically for users coming from the plugin.

The current page that opens now can't be measured. We can use UTM links within the new one and a tiny URL to track the clicks.

**Current UI**

![2020-01-09_11-40-55](https://user-images.githubusercontent.com/1571635/72105140-cf968500-32e1-11ea-8b89-b9e797be817f.png)

**Proposed UI**

1. Displays Green when *no add-ons are activated*.
2. When an add-on is activated it goes back to the normal color as to not distract further from the UI.

![2020-01-09_13-38-20](https://user-images.githubusercontent.com/1571635/72106993-4f721e80-32e5-11ea-9f61-6617df608eb4.png)

### 2. Upsell Recurring Donations 

If we detect that the user is not using Recurring then we should upsell them with a nice subtle banner.

1. Within the Donation Form Edit Screen 

![Recurring Upsell](https://user-images.githubusercontent.com/1571635/72103138-6dd41c00-32dd-11ea-9abd-85a722030e2a.png)

2. ....

### 3. Dashboard Widget 

If no add-ons are activated the Dashboard widget can show an upsell to view our catalog. 

[Concept coming...]

---

Related issue: https://github.com/impress-org/givewp/issues/3660

**Comment by ravinderk** [comment]
Slack Chat Summary

Participants: 
Topic: Prioritize this issue and QA
Result: Ravinder will  take over this and take care of the first two-point.

**Comment by mathetos** [comment]
Working with @telizarose on getting your links with UTM parameters. Based on the info above and screenshots it looks like this is the list of links needed:

- [ ] Donation Form Options Screen: "Recurring Donations add-on" Inline text that links here: `https://givewp.com/addons/recurring-donations/` 
- [ ] Donation Form Options Screen: "View Add-on" Button that links here: `https://givewp.com/addons/recurring-donations/`

Are there others?

**Comment by DevinWalker** [comment]
@mathetos the main "Add-ons" link as well.

**Comment by mathetos** [comment]
@DevinWalker Updated the list above.

**Comment by telizarose** [comment]
Those three links are here. 

1. Add-on menu item: https://givewp.com/addons/?utm_source=GiveWPPlugin&utm_medium=admin&utm_campaign=Plugin_Links&utm_content=Addons

2. Recurring in-line link: https://givewp.com/addons/recurring-donations/?utm_source=GiveWPPlugin&utm_medium=admin&utm_campaign=Plugin_Links&utm_content=RecurringLink

3. Recurring Button: https://givewp.com/addons/recurring-donations/?utm_source=GiveWPPlugin&utm_medium=admin&utm_campaign=Plugin_Links&utm_content=RecurringButton

Master List: https://docs.google.com/spreadsheets/d/1y7pFtZoM6fHfwLv-Mxf3BNf-DuxXNeBpd6ceICrp2sw/edit#gid=1233934955
