### ISSUE TITLE
fix: validate email setting value before saving admin setting

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#4411]
# Bug Report

## Developer Story
As a developer, I do not want them to store invalid to prevent appropriate behavior.

## Current Behavior
Admin can save empty value for email settings.

## Expected Behavior
Do not save invalid email value.

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Save empty value for recipient setting field in any admin email setting
2. After saving try to add a new recipient ( click on `Add Recipient` ). 

## Visuals
![image](https://user-images.githubusercontent.com/1784821/72455797-7484f680-37e9-11ea-8601-303d1fa756af.png)

## Possible Solution
Identify multiple scenarios to store email value and save the only valid email.

## Acceptance Criteria
- [x] Admin edit email setting without any issue.
- [x] Email setting has validated properly before storing to the database.

**Comment by rickalday** [comment]
### Workaround ###

1. Non-code: Use per-form email settings.

2. Hack: change this line https://github.com/impress-org/givewp/blob/6f37a267de63aca07ac0eba281e3fc3606930aab/includes/admin/class-admin-settings.php#L537
from: if ( $value['repeat'] && is_string( $option_value ) ) {
to: if ( $value['repeat'] ) {
Add a new recipient email and reverse the change in the file.

**Comment by JasonTheAdams** [comment]
Closing in favor of Canny post. This can be re-opened when a developer is assigned.
