### ISSUE TITLE
feature: add api URL helper function

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#4417]
# Feature Request

## User Story
As a developer, I want to be able to use a helper function to return an API url so that I can avoid hardcoding URLs and am able to change the API version in the future without editing hardcoded URLs within multiple components.

## Possible Solution
Accept a specific data model, and return a string pointing to the appropriate API endpoint. An example model could be:

```
{
    version: 'v2' \\NOT required, defaults to 'v2',
    resource: 'reports' \\ Required
    endpoint: 'payment-statuses' \\ Required 
}
```
## Related
See RESTList, RESTChart and RESTMiniChart Components for how the API is called currently (hardcoded).

## Acceptance Criteria
- [ ] Eliminates need for hardcoded API urls
- [ ] Enables ability to change default API version in one place, without need to edit multiple files

**Comment by JasonTheAdams** [comment]
Hardcoded URLs is something we can introduce in the Router at a later point. Closing in the meantime.
