### ISSUE TITLE
fix: resolve subscriptions page no longer generating automatically on install

### ISSUE THREAD

**Issue by allienimmons** [impress-org/givewp#4448]
As a site admin, I want the Subscriptions page to generate automatically with the [give_subscriptions] shortcode present so that I don't have to create it myself.

## Current Behavior
Currently, when GiveWP and the Recurring Donations add-on are installed and activated, the Donation Confirmation, Donation Failed, Donation History pages are created automatically. The Subscriptions page is not created. 

## Expected Behavior
According to our documentation, the Subscriptions page should also be created automatically when Recurring Donations is installed and activated. 

According to this doc, this page should be created automatically: https://givewp.com/documentation/add-ons/recurring-donations/managing-subscriptions/

"... the Recurring Donations add-on creates a page called “Recurring Donations” upon install containing the [give_subscriptions] shortcode."

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Install GiveWP on a fresh WordPress Install
2. Install the most recent Recurring Donations add-on and activate it.
3. Go to Pages
4. Observe that the Subscriptions page is not present.

## Related
https://secure.helpscout.net/conversation/1065632848/55746?folderId=3046394

## Acceptance Criteria

- [ ] When GiveWP and Recurring Donations are active on a site, the Subscriptions page appears automatically on the Pages screen.
- [ ] The Subscriptions page has the [give_subscriptions] shortcode on it already.
- [ ] The Subscriptions page is set in the Subscriptions Page dropdown on Donations > Settings > General

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
        <li>Version: 10.14.6</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
        <li>Version: 79.0.3945.130 </li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://willpagesautocreate.local
Site URL: http://willpagesautocreate.local
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: willpagesautocreate.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.14.0
PHP Version: 7.2.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
PHP Max Upload Size: 300 MB
cURL Version: 7.52.1, OpenSSL/1.0.2l
SUHOSIN Installed: –
MySQL Version: 5.7.23
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.5.13
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access❌Renewal Receipt Email❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access✔Subscription Payment Failed Email
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://willpagesautocreate.local/donation-confirmation/
Failure Page: http://willpagesautocreate.local/donation-failed/
Donation History Page: http://willpagesautocreate.local/donation-history/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation, Stripe - Credit Card
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: N/A

### Active GiveWP Add-ons ###

Give - Recurring Donations: ✔ Licensed – by GiveWP – 1.9.10

### Theme ###

Name: Twenty Twenty
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by ravinderk** [comment]
I found that this was removed unintentionally in https://github.com/impress-org/give-recurring/pull/821

**Comment by ravinderk** [comment]
Issue moved to [impress-org/give-recurring #918](https://github.com/impress-org/give-recurring/issues/918) via [**ZenHub**](https://www.zenhub.com/)
