### ISSUE TITLE
feat: update Recount stats tools user flow

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#4450]
# Feature Request

## Developer Story
As a developer, I want to admin to recalculate stats fast and efficiently on large databases without sticking to the webpage.

## Visuals
![image](https://user-images.githubusercontent.com/1784821/73202735-b0ad4500-4161-11ea-820f-eb03423e91d9.png)

## Possible Solution
Detect stats generation time. Take a decision programmatically to either continue the recalculation process (small database) or (large database) transfer the workload to a background process and inform the user about time and assure him that he will get an email notification on process completion.

## Related
https://github.com/impress-org/givewp/issues/4447

## Acceptance Criteria
...... (need to work)

**Comment by DevinWalker** [comment]
Closing as we haven't received a lot of requests for this and this issue lacks proper explanation on the need.
