### ISSUE TITLE
feat: lazy load iframe to improve page loading performance

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#4459]
# Feature Request

## Developer Story
As a developer, I want to improve the donor experience.

## Current behavior
Iframe loads immediately on-page request which impact on page loading performance.

## Possible Solution
Lazy load iframe to improve page loading performance.

## Acceptance Criteria
- [ ] Iframe form is not adding extra weight to page performance.

**Comment by DevinWalker** [comment]
Closing as duplicate of: https://github.com/impress-org/givewp/issues/4575
