### ISSUE TITLE
Give WP with salesforce problem

### ISSUE THREAD

**Issue by crisisaid** [impress-org/givewp#4460]
Hello,
We developed a plugin to push donations data to Salesforce we have tried to use zapier.com but it did cost us lots of money, So we did develop our own plugin to push all the donations fields to salesforce. and it's working fine with us so far. We only have a small issue we use the SQL query below to pull out data from the SQL to salesforce but the first or last name goes missing or null sometimes am I using the right SQL query? 

SELECT * FROM (SELECT id, NAME, email, (SELECT meta_value FROM wp_give_donormeta WHERE meta_key = '_give_donor_first_name'
AND donor_id = wp_give_donors.id) AS first_name, (SELECT meta_value FROM wp_give_donormeta WHERE
meta_key = '_give_donor_last_name' AND donor_id = wp_give_donors.id) AS last_name FROM wp_give_donors) donors
WHERE donors.first_name = '' OR  donors.last_name = ''

**Comment by DevinWalker** [comment]
Apologies @crisisaid on the super late reply. If you're still in need of help please reach out to our [Priority Support](https://givewp.com/support) team so we can take a closer look.
