### ISSUE TITLE
fix: prefer template literals in ESLint

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#4462]
# Feature Request

## Developer Story
As a developer, I want to convert concatenated strings to template literals when possible.

ref: https://eslint.org/docs/rules/prefer-template

## Possible Solution
setup rule in eslint lint to auto convert concatenated strings to template literals.

## Acceptance Criteria
- [ ] Concatenated strings auto convert to template literals when commit.

**Comment by JasonTheAdams** [comment]
This isn't something we really need an issue for. We can just Boy Scout Code these as we see them.
