### ISSUE TITLE
Wrong parameter in apply filters?

### ISSUE THREAD

**Issue by flack** [impress-org/givewp#4464]
# Bug Report

## User Story

I'm trying to write customizations by using filters instead of modifying the Give code directly, and I stumbled across this line:

https://github.com/impress-org/givewp/blob/2e2749d5456fcc3fc4282cbb152611447c77ff70/includes/misc-functions.php#L975

## Current Behavior

As you can see, the parameter `$meta_value` is passed twice, which doesn't make a lot of sense

## Expected Behavior

could it be that the fifth parameter should rather be  `$meta_type`? Because that would actually be useful 

## Bug Type

- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. just see the code line that I linked above

## Acceptance Criteria

no idea what I should put here

## Environment

irrelevant

**Comment by ravinderk** [comment]
@flack Thank you to point out. You are correct.
