### ISSUE TITLE
fix: unable to update company name when change donation donor

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#4483]
# Bug Report

## User Story
As an admin, I want to update `Company Name` when changing the donation donor.

## Current Behavior
`Company Name` does not update when changing a donation donor.

## Expected Behavior
Update `Company Name` when changing a donation donor.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Enable `Company Name` from `Settings  -> Display Options ->  Display`
2. Change any donation donor (donor must have company name )

## Related
https://github.com/impress-org/givewp/pull/2926#issuecomment-584495765

## Acceptance Criteria
- [ ] `Company Name` updates when changing a donation donor.

**Comment by DevinWalker** [comment]
When changing donor the Company Name should likely change to empty and be editable. This is outside the scope of this issue and will be handles in our Admin Donor Details revamp: https://givewp.canny.io/feature-requests/p/improve-admin-donor-profile-view
