### ISSUE TITLE
feat: edit tributes after submission

### ISSUE THREAD

**Issue by allienimmons** [impress-org/givewp#4486]
# Feature Request

## User Story

As a site admin, I want to be able to edit a tribute's meta data, or offer the donor a way to edit the data, so that I can fix any errors that were made when the donation was made.
 

According to this customer, a number of donors contacted them after donating with name or spelling changes for tributes. In some cases, they send certificates or plaques with the tributes names on them so it's important that the change be made to reflect accurately information. Notes can be added, but they're not very visible or intuitive. 

## Related
https://secure.helpscout.net/conversation/1082838447/57234?folderId=3046394

## Acceptance Criteria

- [ ] e.g. The tributes fields in the donation record are editable by the donor or admin.

**Comment by DevinWalker** [comment]
Closing as I've added this to the upvotes of this feature request: https://givewp.canny.io/feature-requests/p/add-custom-data-to-donations-and-donors
