### ISSUE TITLE
feat: include hidden fields in default CSV generation options

### ISSUE THREAD

**Issue by allienimmons** [impress-org/givewp#4487]
# Feature Request

## User Story

As a site admin, I want to be able to download a bulk CSV of my donation history which includes global hidden fields so that I don't have to download one CSV per form if I want to include the payment purchase key, current URL, current page ID and anonymous donation.

Currently, you need to select a form in order to download a CSV with payment purchase key, current URL, current page ID or anonymous donation included. Given that these are technically not per-form items in teh way that add-on hidden field data is, they should be included in the general checklist of items to include in a CSV.

## Related
https://secure.helpscout.net/conversation/1081850479/57104?folderId=3046394

## Acceptance Criteria

- [ ]  _give_payment_purchase_key is included in the general list of data to include in a CSV and can be included for all forms
- [ ] _give_current_url is included in the general list of data to include in a CSV and can be included for all forms
- [ ] _give_current_page_id is included in the general list of data to include in a CSV and can be included for all forms
- [ ] _give_anonymous_donation  is included in the general list of data to include in a CSV and can be included for all forms

**Comment by DevinWalker** [comment]
There's not a real clean way to include all hidden fields for all forms in a mass CSV export. I don't see this as a popular request as there's a workaround (select a form) so I'm closing this out.
