### ISSUE TITLE
fix: Delete user Give user roles when the plugin is deleted.

### ISSUE THREAD

**Issue by rickalday** [impress-org/givewp#4491]
# Bug Report

## User Story

As an admin, I want to clear all GiveWP settings including user roles so that my DB stays lean.

## Current Behavior

The Give Subscriber and its capabilities remain in place after deleting the plugin.
Also, the __give_subscriptions and _give_subscriptionmeta tables stay in the DB

## Expected Behavior

- All GiveWP related user roles, as well as tables, should clear from the database when the plugin is deleted.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Activate the plugin again
2. Navigate to “Donations > Settings > Advanced”
3. There, enable the option about deleting all data on uninstall
4. Uninstall and delete GiveWP

Check DB tables and user roles.

## Possible Solution

- Delete unused tables using PHPMyAdmin or similar.
- Use the [User Role Editor plugin](https://wordpress.org/plugins/user-role-editor/) to remove unneeded user roles.

## Related

https://wordpress.org/support/topic/capabilities-list-includes-features-from-deleted-plugin/

## Acceptance Criteria

- [ ] GiveWP specific user roles and DB tables are removed when the plugin is deleted.

**Comment by DevinWalker** [comment]
@rickalday if you uninstall GiveWP Core before Recurring then these roles will be left in place. You need to uninstall Recurring so that they are removed. See: https://github.com/impress-org/give-recurring/blob/develop/uninstall.php#L34

This is already handled by the add-on, not Core.
