### ISSUE TITLE
feature: use React Portal to render Reports tooltips

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#4494]
# Feature Request

## User Story
As a developer, I want tooltips to be rendered with a React Portal so that tooltips can be rendered with a functional component, and mirror other elements of the codebase.

## Possible Solution
See ChartJS cusotm tooltip documentation: https://www.chartjs.org/docs/latest/configuration/tooltip.html
See React Portals documentaiton: https://reactjs.org/docs/portals.html

## Acceptance Criteria
- [ ] a 'Tooltip' component is introduced
- [ ] the Chart and MiniChart components use portals to render Tooltip components
- [ ] relevant  Tooltip information is passed as a props to the tooltip component

**Comment by DevinWalker** [comment]
The current tooltips seem to be working fine without a refactor. Closing as we'll likely stick with what we have now with ChartJS for the time being.
