### ISSUE TITLE
Develop the new Form Template and introduce new Multi-step donation form

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#4499]
# Feature Request

This is the epic which is a container for all subsequent issues being worked on to achieve the Form Template feature.

*Note:* If you don't have Zenhub installed you will not be able to see all attached issues to this epic.

## Developer Story

As a developer, I want to provide a form theme setting ( integrated frontend form ) to admin so that he can configure the appearance of the donation form.

## Visuals

![2020-06-19_13-56-11](https://user-images.githubusercontent.com/1571635/85178977-a5ec6d00-b234-11ea-8c2a-a8f666efdd55.png)

![2020-06-19_13-56-41](https://user-images.githubusercontent.com/1571635/85179062-cb797680-b234-11ea-9d1c-8a4346d23bc0.png)

![2020-06-19_13-56-49](https://user-images.githubusercontent.com/1571635/85179068-cddbd080-b234-11ea-8997-45ae9ff4feb9.png)

![2020-06-19_13-56-59](https://user-images.githubusercontent.com/1571635/85179069-cfa59400-b234-11ea-9120-b975bb6eae65.png)

![2020-06-19_13-57-14](https://user-images.githubusercontent.com/1571635/85179077-d16f5780-b234-11ea-9b78-c13416638ec0.png)

**Comment by henryholtgeerts** [comment]
Project progress is also tracked using airtable. See: https://airtable.com/shrVl0TadcLW3yxEU/tblFeDBm3joANMPRa/viwGWT9jIEz0QLdKR?blocks=bipWrL2mqPsBwgjwZ

**Comment by DevinWalker** [comment]
This has largely been completed. There's a few clean up issues attached to this epic but that's minor. Closing.
