### ISSUE TITLE
fix: improve Reports inline documentation

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#4502]
# Bug Report

## User Story
As a developer, I want the new Reports functionality to have improved inline documentation so that I can better understand what each endpoint does, how it works, and how the frontend accepts data from the server.

## Current Behavior
The reports endpoints lack clear inline documentation.

## Expected Behavior
Reports endpoints and frontend components are well documented and easy to pick up/expand on.

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [x] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Acceptance Criteria
- [ ] Reports endpoint classes are documented
- [ ] PHP methods are introduced with comments describing parameters and return values
- [ ] Reports components and associated utilities are documented

**Comment by JasonTheAdams** [comment]
This isn't something we really need an issue for. We can just Boy Scout Code these as we see them.
