### ISSUE TITLE
fix: Donation Upsell punctuation error

### ISSUE THREAD

**Issue by allienimmons** [impress-org/givewp#4511]
# Bug Report

## User Story

As an admin using Euros and reversed commas and decimals, I want the Donation Upsell options to be consistent with the way I've structured my currency settings so that donors are not confused or charged incorrectly.

## Current Behavior
Currently, some users need to use Euros for their currency. They also want to use commas for decimal separators and periods for thousands separators. When both of those things are in place, on a form that has multiple donation levels, used with the WooCommerce Upsells plugin, the punctuation marks do not stay as set. When purchasing a product with WooCommerce upsells, the amount will look correct until a new donation level is chosen.

## Expected Behavior
Upon selecting a donation level, the currency format should not change to be different than what has been built into the Multi Level Donation option.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [X] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Install WooCommerce Donation Upsells
2. In the settings for both GiveWP and WooCommerce, set the currency to Euros, set a comma for the decimal separator and a comma for a thousands separator
3. Create a form which uses Multi Level donation option. Set at least 2 option amounts
4. Create a product in WooCommerce
5. Add the product to your cart
6. Add a donation upsell - notice that before changing the multi level amount, the currency is correct
7. Choose a new option from the dropdown
8. Notice that the amount changes

## Visuals
Before a donation option is chosen:
![Screen Shot 2020-03-05 at 10 04 48 AM](https://user-images.githubusercontent.com/41754561/75994314-c6ccc480-5ec8-11ea-87f4-6c07ae1f910c.png)

After a new donation level is chosen:
![Screen Shot 2020-03-05 at 10 04 52 AM](https://user-images.githubusercontent.com/41754561/75994332-d0562c80-5ec8-11ea-8863-a937da15f635.png)

The correct format is €20,00. This is twenty Euros. 
€2.000,00 would be two thousand Euros.

## Related
https://secure.helpscout.net/conversation/1027570022/52604/

## Acceptance Criteria

- [ ] e.g. The currency settings as described stay the same no matter what
- [ ] e.g. The currency settings for an upsell donation do not change when selected
- [ ] e.g. Fixing behavior in Component A does not affect existing behavior in Component B.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X </li>
        <li>Version: 10.14.6</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://testing-woocommerce-upsell-translation.local
Site URL: http://testing-woocommerce-upsell-translation.local
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, in-progress, failed, wc-pending, wc-processing, wc-on-hold, wc-completed, wc-cancelled, wc-refunded, wc-failed, refunded, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: testing-woocommerce-upsell-translation.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.14.0
PHP Version: 7.2.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
PHP Max Upload Size: 300 MB
cURL Version: 7.52.1, OpenSSL/1.0.2l
SUHOSIN Installed: –
MySQL Version: 5.7.23
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.5.13
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: EUR
Currency Position: Before
Decimal Separator: ,
Thousands Separator: .
Success Page: http://testing-woocommerce-upsell-translation.local/donation-confirmation/
Failure Page: http://testing-woocommerce-upsell-translation.local/donation-failed/
Donation History Page: http://testing-woocommerce-upsell-translation.local/donation-history/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation, Stripe - Credit Card
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: N/A

### Active GiveWP Add-ons ###

Give - Donation Upsells for WooCommerce: ❌ Unlicensed – by GiveWP – 1.1.4

### Other Active Plugins ###

Jetpack by WordPress.com: by Automattic – 8.2.1
My Custom Functions: by Space X-Chimp – 4.41
WooCommerce: by Automattic – 3.9.2
WooCommerce Services: by Automattic – 1.22.3

### Theme ###

Name: Twenty Twenty
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by allienimmons** [comment]
A similar problem with Fee Recovery here: https://secure.helpscout.net/conversation/1104573806/0/?folderId=672194

**Comment by allienimmons** [comment]
Another instance of this: https://secure.helpscout.net/conversation/1120077810/60715?folderId=3046394

**Comment by ravinderk** [comment]
Issue moved to [impress-org/givewp-donation-upsells-woocommerce #67](https://github.com/impress-org/givewp-donation-upsells-woocommerce/issues/67) via [**ZenHub**](https://www.zenhub.com/)
