### ISSUE TITLE
Reset password link isn't working when username contains a + character

### ISSUE THREAD

**Issue by flack** [impress-org/givewp#4512]
# Bug Report

## User Story

As a user, I want register with a user name like e.g. "Mickey+Minnie"

## Current Behavior

The "reset password" link from the welcome mail looks like this:

`/wp-login.php?action=rp&key=RLai07DTBi6W7hFNcaMM&login=Mickey+Minnie`

When you click it, you get redirected to `/wp-login.php?action=lostpassword&error=invalidkey`

This is because the browser treats a literal `+` in the URL as a whitespace, so Wordpress sees `Mickey Minnie` as the username instead of `Mickey+Minnie`

## Expected Behavior

The link should work. 

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [+] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. complete the registration form with a username containing a `+`
2. click the reset password link in the mail
3. the error occurs

## Possible Solution

Any `+` sign in the username needs to be urlencoded to `%2b` 

## Acceptance Criteria

- [ ] The reset password link should work for usernames containing a `+`. 

## Environment

irrelevant

**Comment by flack** [comment]
I'm currently using this crude workaround to get around the issue:

```diff
--- a/wp-content/plugins/give/includes/emails/class-give-email-tags.php
+++ b/wp-content/plugins/give/includes/emails/class-give-email-tags.php
@@ -1507,7 +1507,7 @@ function give_get_reset_password_url( $user_id ) {
                                array(
                                        'action' => 'rp',
                                        'key'    => get_password_reset_key( $user ),
-                                       'login'  => $user->user_login,
+                                       'login'  => str_replace('+', '%2b', $user->user_login),
                                ), wp_login_url()
                        )
                );
```

**Comment by DevinWalker** [comment]
Hi @flack I'm not sure how you were able to register that username because it contains the `+` character which is an illegal character.

You should have received:

![2020-07-22_21-43-06](https://user-images.githubusercontent.com/1571635/88252878-a6798880-cc64-11ea-8c6c-d0a4e3299b77.png)

WordPress itself does not allow registering username like this as well:

![2020-07-22_21-44-19](https://user-images.githubusercontent.com/1571635/88252887-b1341d80-cc64-11ea-84cb-7944f8a7b6e8.png)

I'm not seeing this as a bug with our plugin but rather an issue with somehow the site in question allows illegal characters as described. Thus, I'm closing this issue. Please let me know if you have have any questions!

**Comment by flack** [comment]
@DevinWalker we're using email addresses as usernames in our site, and having me+test1@mysite.com is a conveient way to have multiple test accounts. Many people also recommend registering with email addresses like this to sites in order to better trace where spam comes from, see here for example:

https://danq.me/2017/09/26/gmail-plus/

Plus signs in usernames may not work out of the box in WP, but it's super easy to add support for this, there are a lot of howtos, e.g. this one:

https://www.parorrey.com/blog/wordpress/allow-plus-sign-for-wordpress-username-registration/

We've been using this for a while already and it works without issues, except for that tiny problem with the link mentioned above. If it was a really big refactor to support this in give, I wouldn't bother, but it's really just a one-line change
