### ISSUE TITLE
fix: resolve Reports php notices related to recurring donations

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#4515]
# Bug Report

## User Story
As a developer, I want Reports to properly handle whether the Recurring Donations plugin is activated so that Reports logs no PHP Notices during debugging.

## Current Behavior
Various PHP notices are logged when loading the reports page if Recurring Donations is not activated.

## Expected Behavior
No PHP notices are logged when load the reports page.

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [x] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Acceptance Criteria
- [ ] No php notices are logged when load the reports page

**Comment by rickalday** [comment]
@henryholtgeerts there are also some notices in the Dashboard and Reports pages on a brand-new GiveWP install that has no donations yet.

**Comment by mathetos** [comment]
@rickalday This issue that Henry created seems to be about having Recurring Donations activated. Are you saying that the notices appear on the Dashboard and Reports page even with NO add-ons activated at all? Please clarify. 

Also, I believe this is in relation to this free support ticket:
https://wordpress.org/support/topic/new-reports-php-notice-when-no-donations/

**Comment by rickalday** [comment]
@mathetos and @henryholtgeerts 
That is correct, the following notices show up on a brand new install of GiveWP with no add-ons installed.
In Reports page:
```
PHP Notice:  Undefined offset: 0 in /wp-content/plugins/give/src/Views/Admin/Pages/Reports.php on line 117
PHP Notice:  Undefined property: stdClass::$give_subscription in /wp-content/plugins/give/src/API/Endpoints/Reports/PaymentStatuses.php on line 48
PHP Notice:  Undefined property: stdClass::$give_subscription in /wp-content/plugins/give/src/API/Endpoints/Reports/PaymentStatuses.php on line 57
```

In WP main dashboard page:
`PHP Notice:  Undefined offset: 0 in /wp-content/plugins/give/src/Views/Admin/DashboardWidgets/Reports.php on line 98`
