### ISSUE TITLE
feature: form themes metabox UI enhancement

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#4517]
# Feature Request

## User Story
As a developer, I want the new form themes metabox/admin UI to match the Figma designs so that users have the best experience possible.

## Visuals
See Figma:
https://www.figma.com/file/jaVXDA4wjQD9OqTi0l9KQe/Form-Themes?node-id=1882%3A44&viewport=-259%2C1586%2C0.5

## Related
See #4500 

## Acceptance Criteria
- [ ] Form themes metabox UI styles match Figma
- [ ] Form themes metabox tabs match Figma
- [ ] Form Theme options match figma
- [ ] Necessary theme options for "Legacy" form theme have been copied over from Form Display tab

**Comment by henryholtgeerts** [comment]
For reference: current Form Display options, some of which will need to be moved to Form Theme options for "Legacy" theme

![screencapture-givewp-local-wp-admin-post-php-2020-03-09-16_50_25](https://user-images.githubusercontent.com/5186078/76256515-776af900-6226-11ea-8027-da8593c6ad89.png)

**Comment by ravinderk** [comment]
A note:

> need to discuss adding a prefix to font awesome icon classes.

cc: @henryholtgeerts @DevinWalker
