### ISSUE TITLE
fix: prevent side effects in Reports bootstrapping

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#4519]
# Bug Report

## User Story
As a developer, I want to prevent side-effects while bootstrapping Reports so that as few classes are loaded as necessary when Give is initiated, and overall bootstrapping is made more lean.

## Current Behavior
Certain classes are initiated when the API file is included (this is a side-effect).

## Expected Behavior
File inclusion should not include side-effects!

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [x] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Acceptance Criteria
- [ ] Reports related classes (API and Views) are bootstrapped alongside other Give classes
- [ ] Inclusion of Reports files does not produce side effects
- [ ] Construction of Reports classes does not produce side effects

**Comment by henryholtgeerts** [comment]
After discussing this issue on 4/21/20, the decision was reached to hold off on further implementation of improved bootstrapping for the Reports feature until a cohesive unified methodology for bootstrapping is established across GiveWP. This is to ensure that we are not constantly reinventing the wheel on bootstrapping, and because the Reports functionality currently works fine from a user perspective, this is purely an efficiency related issue and not critical to release soon.

**Comment by JasonTheAdams** [comment]
We now have a formal system for bootstrapping in GiveWP using the Service Provider flow. 🎉
