### ISSUE TITLE
fix: prevent "non-unique" google chrome notice on from edit page

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#4532]
# Bug Report

## Developer Story
As a developer, I want to prevent notices in the console tab on google chrome.

## Current Behavior
I can see a few "non-unique" related notice in google chrome.

## Expected Behavior
Every element must contain a unique id.

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Open form edit page in WP backend
2. Open inspect tool -> console in google chrome

## Visuals
<img width="1264" alt="Screen Shot 2020-03-11 at 10 13 58 AM" src="https://user-images.githubusercontent.com/1784821/76445465-7505cc00-63eb-11ea-93d6-09a5abffa0bc.png">

## Acceptance Criteria
- [ ] I am not getting ID related notice in google chrome.

**Comment by ravinderk** [comment]
`non-unique` id related issue for color picker field has been fixed: https://github.com/impress-org/givewp/compare/7f6496a38dd2...14c067594706


The second issue is related to the email setting field of the donor-related email notification:

![image](https://user-images.githubusercontent.com/1784821/76445976-548a4180-63ec-11ea-905d-122547105c1f.png)

**Comment by JasonTheAdams** [comment]
This is not breaking and is likely going to be fixed in a future fix or refactor. Closing in the meantime.
