### ISSUE TITLE
fix: Floating labels in Stripe CC fields

### ISSUE THREAD

**Issue by rickalday** [impress-org/givewp#4534]
# Bug Report

## User Story

As an, I want to use floating labels in my forms.

## Current Behavior

Floating labels do not work specifically for the Stripe CC fields: Credit card number, CVC, and expiration date. 

## Expected Behavior

Floating labels should work.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Enable floating labels
2. Use Stripe CC as a payment option
3. Check form

## Visuals

http://somup.com/cYel2Fhky7

## Related

https://secure.helpscout.net/conversation/1102822779/59036?folderId=3400524

## Acceptance Criteria

- [ ] Floating labels should work.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X | Microsoft Windows | Linux | Android | iOS</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    
</details>

**Comment by DevinWalker** [comment]
Due to the way Stripe elements works this will not be possible. Stripe places its own credit card fields on the page and we can't enable floating labels with that.
