### ISSUE TITLE
fix: Incorrect average donation amount in report

### ISSUE THREAD

**Issue by rickalday** [impress-org/givewp#4537]
# Bug Report

## User Story

As an admin, I want the correct average donation amount in my reports when I use a period as a thousands separator.

## Current Behavior

The average donation amount is not calculated properly and displays an astronomical amount.

## Expected Behavior

The average donation amount should be correct.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Use a period in the thousands separator and a comma as a decimal separator in the Currency settings
2. Check Avg. Donation amount in Reports page and Dashboard widget.

## Visuals

<img width="743" alt="Screen Shot 2020-03-12 at 12 28 32 PM" src="https://user-images.githubusercontent.com/312000/76555810-feee7d00-645d-11ea-89df-47aedb6944ff.png">

## Related

https://secure.helpscout.net/conversation/1104573806/59146?folderId=3400524

## Acceptance Criteria

- [ ] Avg. Donation amount displays the correct amount

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X | Microsoft Windows | Linux | Android | iOS</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    
</details>

**Comment by ravinderk** [comment]
@henryholtgeerts Maybe this is happening because somewhere in code we are sanitizing already sanitize number.
We can disable `sanitize` by set it to `false`. https://github.com/impress-org/givewp/blob/0e92e84d9444dee243cdf73cb65cb53fa45e1373/includes/formatting.php#L418
