### ISSUE TITLE
feat: add currency select and test mode toggle to reports

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#4542]
# Feature Overview

Currently in our Reports we lump together all donation payments into a single currency. This makes the reports inaccurate when I use a plugin like currency switcher to accept EUR, GBP, or any other currency. 

This has always been the case with our reports since Day 1 and we've received some complaints but most users stick to a single currency. However, if along the lines they switch from one currency to another the reports are still inaccurate.

As well, Test data is included in the reports and if you don't delete it all using our tool then the reports are also inaccurate.

## Enhancement Proposal.

To fix this issue I propose we include the following two elements in the header.

1. *A currency select dropdown:* This will have the default currency set by default. If donations donations are found from other currencies they will appear in the dropdown. When a currency is selected only stats from that currency will appear.

2. *A "View test data" toggle:* This will be useful for testing purposes. If GiveWP is in test mode, the default will be on. If GiveWP is in live mode the default will be off. When it is on only test data will be shown. Likewise, when it is off only live stats will display.

## Concept

![2020-03-13_11-40-44](https://user-images.githubusercontent.com/1571635/76650721-6a991e80-6520-11ea-94f1-8851e2caad58.png)

**Comment by henryholtgeerts** [comment]
@DevinWalker Thanks for pointing these issues out. I am going to suggest we tackle these each as separate issues, and estimate the first (currency handling) at **2 days,** the second (handling Test data) at **1 day of work.**

From a UI standpoint I think it may make more sense to add a settings button (maybe a gear icon?) which opens a modal for adjusting these options, since they serve fairly niche uses, and may be confusing to users who are not specifically looking for them.

**Comment by DevinWalker** [comment]
Good suggestion @henryholtgeerts 

Here's what I mocked up:

![2020-04-21_12-08-33](https://user-images.githubusercontent.com/1571635/79904066-f5dfbc80-83c8-11ea-8763-2b9ab89f5548.png)

**Comment by rickalday** [comment]
https://secure.helpscout.net/conversation/1145321163/63511/

**Comment by rickalday** [comment]
https://secure.helpscout.net/conversation/1161663678/65181/

**Comment by jurassicdanie** [comment]
Tticket: https://secure.helpscout.net/conversation/1188265345/67337/
