### ISSUE TITLE
WP Rocket compatibility

### ISSUE THREAD

**Issue by piotrbak** [impress-org/givewp#4546]
# Bug Report

## User Story
My name is Piotr, I work for WP Rocket. We had a mutual customer who realized that WP Rocket is disabled on all donation pages.

## Current Behavior
Right now you're adding DONOTCACHEPAGE to all donation pages. It disables all WP Rocket features including caching and optimizations.

We're already preventing WP Rocket from working on some of your pages, this compatibility is done on our end here:
https://github.com/wp-media/wp-rocket/blob/e40b824350a165cf52f2285a681d5b6796ed5555/inc/3rd-party/plugins/ecommerce/give.php#L26

## Expected Behavior
I'm not sure if there's any reason to disable caching on single donation pages if so, there are two possible ways out, you can let us know which pages should we exclude, or you can exclude it on your own. Here's the correct approach to disable generation of cached files:

https://github.com/wp-media/wp-rocket-helpers/blob/de4ad8f82a0981f7ecdfcedba17066f762128627/cache/wp-rocket-no-cache-for-page/wp-rocket-no-cache-for-page.php#L40

## Bug Type
Compatibility

## Steps to Reproduce
1. Install WP Rocket and Give
2. In incognito mode go to any donation page
3. Confirm in the source that WP Rocket's comment is not present in the footer.

## Acceptance Criteria
WP Rocket working on as many GiveWP pages as possible

## Environment
Not important

**Comment by Benunc** [comment]
Some hosts with caching that can't be configured might be helped by a fix here.

**Comment by DevinWalker** [comment]
@piotrbak would you mind contacting us regarding how we may be able to get a developers license or Github access to WP Rocket for testing and compatibility purposes? We have a PR for this issue set, just need to hear back from you or a team member regarding getting this fully tested and merged.

**Comment by piotrbak** [comment]
@DevinWalker Can I catch you via email? I'll send you 100% discount coupon code for WP Rocket.

**Comment by DevinWalker** [comment]
@piotrbak yes please send it to devin(at)givewp.com
