### ISSUE TITLE
fix: simplify form route controller

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#4551]
# Bug Report

## Description
As we can see in the code that we are loading from route controller on core load which differs route controller logic. A controller must not load by itself and handle loading logic instead of that route have to handle it. We have to do a minor refactor of code to fix this.

## Acceptance Criteria
- [ ] Form route is handling logic to load controller and the controller does not load on core load.

**Comment by DevinWalker** [comment]
Closing as unclear and a lack of description.
