### ISSUE TITLE
feat: make form templates extendable

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#4553]
# Feature Request

## Developer Story
As a developer, I want to developer form templates in a way that it will be easy to extend by other developers so that he/she can create a new form template easily.

## Possible Solution
Currently, WordPress hooks (provided in the core) is the only way to modify form dom structure to achieve specific form design. It needs a lot of hard work and knowledge of core to modify form dom structure (keeping add-ons compatibility). To make form template development easy we code core form template in a way that they will be easy to extend which prevents a lot of time from other developers.

To make form template extendible we have to hide hooks complexity under the hood and make them accessible by property and method.

## Acceptance Criteria
- [ ] Form template has a basic expendability feature.

**Comment by JasonTheAdams** [comment]
At this point we know considerable new architecture is required to best pull this off, which is why we're introducing exciting new systems like the Fields API! This is going to be great!
