### ISSUE TITLE
fix: subscription payment failed email needs editing

### ISSUE THREAD

**Issue by allienimmons** [impress-org/givewp#4555]
# Bug Report

## User Story

As an admin, I want the automatic/default message for a failed subscription payment to look normal and not have typos/markup so that my donors can receive a clean, clear, professional looking email without me having to edit the email. 

## Current Behavior
Currently, the default Subscription Payment Failed email has one typo and lots of markup in the visual email. It looks like this:

We want to inform you that your recurring payment to ____.org was unsucessful. Your ongoing support is important to us. To continue your recurring donation, please update your payment method by clicking on this link:\r\n\r\n{update_payment_method_link}\r\n\r\nIf no action is taken, your subscription will automatically cancel after a few more attempts. If possible, please renew your payment method before your next scheduled donation on {next_payment_attempt}.\r\n\r\nSincerely,\r\n\r\_______.org \r\n

## Expected Behavior
The word "unsuccessful" should be spelled properly. All the instances of /r and /n should not be present in the Visual view.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Install GiveWP and Recurring Donations
2. Go to Donations > Settings > Emails >Donor Emails. > Subscription Payment Failed > Edit
3. View the visual tab of the text editor

## Visuals
<img width="998" alt="Screen Shot 2020-03-18 at 10 00 58 AM" src="https://user-images.githubusercontent.com/41754561/76971790-0a312500-6904-11ea-8747-da71f66277cc.png">

## Related

https://secure.helpscout.net/conversation/1082348180/57171/

## Acceptance Criteria

- [ ] e.g. The default text has no typos.
- [ ] e.g. The default text has no markup in the visual editor.
- [ ] e.g. Fixing behavior in Component A does not affect existing behavior in Component B.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X </li>
        <li>Version: 10.15.3 </li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://save-the-whales.local
Site URL: http://save-the-whales.local
WP Version: 5.3.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: page
Page on Front: This is my Home Page (#23)
Page for Posts: Unset
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: save-the-whales.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.14.0
PHP Version: 7.2.9
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
PHP Max Upload Size: 300 MB
cURL Version: 7.52.1, OpenSSL/1.0.2l
SUHOSIN Installed: –
MySQL Version: 5.7.23
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.6.0
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note❌Email access❌Renewal Receipt Email❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email❌Subscriptions Email Access✔Subscription Payment Failed Email
Upgraded From: 2.5.13
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://save-the-whales.local/donation-confirmation/
Failure Page: http://save-the-whales.local/donation-failed/
Donation History Page: http://save-the-whales.local/donation-history/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Stripe - Credit Card
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Disabled
Stripe Webhook Notifications: N/A

### Active GiveWP Add-ons ###

Give - Annual Receipts: ✔ Licensed – by GiveWP – 1.0.2
Give - Form Field Manager: ❌ Unlicensed – by GiveWP – 1.4.4
Give - Manual Donations: ❌ Unlicensed – by GiveWP – 1.4.5
Give - PDF Receipts: ❌ Unlicensed – by GiveWP – 2.3.4
Give - Recurring Donations: ❌ Unlicensed – by GiveWP – 1.9.13

### Other Active Plugins ###

Akismet Anti-Spam: by Automattic – 4.1.3
My Custom Functions: by Space X-Chimp – 4.41

### Theme ###

Name: Twenty Twenty
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by ravinderk** [comment]
This issue has been fixed.

ref: https://github.com/impress-org/give-recurring/compare/a4d685d14184...a055e19176b2

![image](https://user-images.githubusercontent.com/1784821/77140809-c58ec080-6aa0-11ea-8fee-5e5491b8e8e4.png)

**Comment by ravinderk** [comment]
Issue moved to [impress-org/give-recurring #928](https://github.com/impress-org/give-recurring/issues/928) via [**ZenHub**](https://www.zenhub.com/)
