### ISSUE TITLE
fix: change opt-in form on Welcome Screen

### ISSUE THREAD

**Issue by mathetos** [impress-org/givewp#4560]
Our opt-in form on the Welcome screen currently goes to the wrong list within Active Campaign. It's going to the "GiveWP Newsletter" list which we are retiring; and it should instead go into the "GiveWP Master List"

You'll have to generate the code within the "Forms" area of Active Campaign to get the updated markup.

**Comment by DevinWalker** [comment]
I just tested this and it's working fine:

![2020-05-15_12-30-25](https://user-images.githubusercontent.com/1571635/82089137-e130d480-96a7-11ea-8a6c-416b6bbada2d.png)
