### ISSUE TITLE
feat: improve core bootstrapping

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#4562]
# Feature Request

## Developer Story

As a developer, I want to load a part of the plugin code only if required. This will improve plugin loading performance and also reduce memory usage.

https://github.com/impress-org/givewp/blob/0e92e84d9444dee243cdf73cb65cb53fa45e1373/give.php#L355
https://github.com/impress-org/givewp/blob/0e92e84d9444dee243cdf73cb65cb53fa45e1373/give.php#L479

As we can see in the above link that we are loading most of the core initial even if not required.

Slack discussion: https://givewp.slack.com/archives/C0FAGC83C/p1584561548026300

## Possible Solution

Improve the plugin bootstrapping process and load classes and functions dynamically by the autoloader.

## Acceptance Criteria

- [ ] Plugin is not loading extra code when bootstrap.

**Comment by JasonTheAdams** [comment]
We now have a slick new bootstrapping system using Service Providers. So this can be closed! 🙌
