### ISSUE TITLE
Donor ID not available in Export Donor Report

### ISSUE THREAD

**Issue by amandagorman** [impress-org/givewp#4564]
# Bug Report

## User Story

As a user, I want to export the Export Donor report so that I have a cumulative report of all donations for my donors, which includes their individual Donor ID.

## Current Behavior
Currently, the Donor ID is only available when pulling the Export Donation History report, not the Export Donor report. the User ID is available for both, but Donor ID is only an option for Export Donation History report.

## Expected Behavior
I would like for the Donor ID field to be pulled in both Export Donation History report & Export Donor report. 

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [X] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Navigate to Donations --> Tools --> Export
2. Export Donor report
3. View field columns, no Donor ID included

## Visuals
![image](https://user-images.githubusercontent.com/37075106/77082042-ed632300-69d1-11ea-872c-3e824a16687a.png)

## Acceptance Criteria

- [ ] View Export Donor report under Donations - Tools - Export, ensure that a checkbox for "Donor ID" is available to check.
- [ ] Export Donor report pulled, Donor ID is a column in the spreadsheet

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X | Microsoft Windows | Linux | Android | iOS</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    
</details>

**Comment by JasonTheAdams** [comment]
I've created a Canny post for this and am closing this Issue in favor of gathering feedback there.
