### ISSUE TITLE
fix: stop re-sanitization of number to prevent inconsistent amount formatting

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#4574]
# Bug Report

## Developer Story

As a developer, I want to fix root cause of the issue.

## Current Behavior

We fixed that issue https://github.com/impress-org/givewp/issues/4537 by limiting number of decimal to two but we can found that maybe somewhere in code we are re-sanitizing number: https://github.com/impress-org/givewp/issues/4537#issuecomment-601010477 

## Expected Behavior

Prevent inconsistent amount formatting

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

Check issue: https://github.com/impress-org/givewp/issues/4537

## Acceptance Criteria

- [x] Avg. Donation amount displays the correct amount and formatted with the number of decimals as per admin setting.

**Comment by matheuswd** [comment]
Related: https://secure.helpscout.net/conversation/1211596107/69021?folderId=3863238

**Comment by rickalday** [comment]
https://secure.helpscout.net/conversation/1194863068/67839/
