### ISSUE TITLE
fix: remove unnecessary check from give_first and give_email form field

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#4581]
# Bug Report

## Developer Story

As a developer, I want to remove the unnecessary function from code

## Current Behavior

As you can see in code that `give_first` and `give_email` are required but we are still using  `give_field_is_required` to check if these required or not.

https://github.com/impress-org/givewp/blob/37f2264e5434d0e24bf68f304b72aacb05cd2612/includes/forms/template.php#L818
https://github.com/impress-org/givewp/blob/37f2264e5434d0e24bf68f304b72aacb05cd2612/includes/forms/template.php#L889

## Expected Behavior

Remove unnecessary check.

## Acceptance Criteria

- [ ] Do not allow to filter`give_first` and `give_email` in `give_get_required_fields`.
- [ ] Unnecessary `give_field_is_required` check has been removed from `give_first` and `give_email`.

**Comment by jonwaldstein** [comment]
@ravinderk do you feel like we still need to fix this?

**Comment by ravinderk** [comment]
> @ravinderk do you feel like we still need to fix this?

@jonwaldstein yes, it is still relevant because we are using the same html.
