### ISSUE TITLE
refactor: move fontawesome assets from 'icons' directory to 'plugins'

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#4583]
# Feature Request

## User Story
As a developer, I want to access fontawesome assets from the 'plugins' directory so that they match other vender provided dependencies.

## Visuals
![image.png](https://images.zenhubusercontent.com/5de5476735cbb7ad97ed643a/53257321-883f-4941-a99a-5c4d37dc2af3)

## Possible Solution
Move 'fa' directory from icons into 'plugins'. Update code that references theses locations.

## Acceptance Criteria
- [ ] 'icons' directory is removed
- [ ] fontawesome assets are accessed from 'fa' directory in 'plugins'

**Comment by jonwaldstein** [comment]
We're mainly using the `@fortawesome` packages these days so closing this out until we feel it's still an issue.
