### ISSUE TITLE
feat: allow hooks for custom form settings should default to global settings if no form ID is provided

### ISSUE THREAD

**Issue by rickalday** [impress-org/givewp#4586]
# Feature Request

## User Story

As an admin, I want be able to program custom per-form settings using available GiveWP hooks.  Some of these hooks require a form id.  

Some settings don't make sense for each form: country, currency... They must be the same for all forms, and I must only use the global settings. So I use a null form_id for the cart. It generally works, the settings for the form are not found, and we use the general settings. But sometimes it's not possible. For example, 'give_get_offline_payment_instruction' returns without doing anything if the form_id is zero. I had to find a tip, and I used form_id= -1. It is possible that a null form_id means using global settings?

## Related

https://secure.helpscout.net/conversation/1118241765/0/?folderId=3400524

## Acceptance Criteria

- [ ] Global settings are used if no form ID is passed to hooks that require a form ID.

**Comment by DevinWalker** [comment]
Closing as a non-specific / ambiguous request.
