### ISSUE TITLE
feat: remove fee recovery for offline donations

### ISSUE THREAD

**Issue by allienimmons** [impress-org/givewp#4597]
# Feature Request

## User Story

As an admin, I want the fee recovery option to be conditional so that Offline Donations do not ask for a fee amount.

It does not make sense to ask for the donor to cover the fees when paying offline, such as with a check. The fee recovery option should be disabled automatically if the donor selects Offline Donations, or there should be an option in the plugin settings to disable it for Offline Donations.

## Related
https://secure.helpscout.net/conversation/1121888396/60931?folderId=3046394

## Acceptance Criteria

- [ ] e.g. Fee Recovery is not an option or is optional on the admin side for Offline Donations.

**Comment by DevinWalker** [comment]
You can already do this within the add-on itself: 

1. Set "Offline Donation" to disabled:

![2020-07-22_23-30-43](https://user-images.githubusercontent.com/1571635/88257794-6ec60d00-cc73-11ea-92c8-3419e30e75cc.png)

2. See that when you switch to that gateway it is disabled:

![2020-07-22_23-30-20](https://user-images.githubusercontent.com/1571635/88257812-7c7b9280-cc73-11ea-950f-54ed25076fd2.gif)

Note: this is not currently working properly with the new Multi-step form template. We should ensure it works like expected with the new template and ongoing templates. I've created a Canny Feedback request for this so I'm closing this issue. Please upvote this here if this is important to you: https://givewp.canny.io/bug-reports/p/disabled-fee-recovery-gateways-should-work-with-multi-step-form-templates
