### ISSUE TITLE
feature: do not render decimal places on 'choose amount' screen of Sequoia template

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#4599]
# Feature Request

## User Story
As a user, I want the 'choose amount' screen to hide decimal places by default so that I am not overwhelmed by a wall of zeros, and I can quickly locate the amount I'd like to donate.

This behavior is also more consistent with the Figma designs, which do not include decimal places in the choose amount section (see Figma boards: https://www.figma.com/file/jaVXDA4wjQD9OqTi0l9KQe/Form-Themes?node-id=2089%3A1149&viewport=-259%2C1586%2C0.5)

## Visuals
See Figma boards: https://www.figma.com/file/jaVXDA4wjQD9OqTi0l9KQe/Form-Themes?node-id=2089%3A1149&viewport=-259%2C1586%2C0.5

![Screen Shot 2020-03-30 at 12.58.09 PM.png](https://images.zenhubusercontent.com/5de5476735cbb7ad97ed643a/f3de4b66-53cb-4f51-a63a-7fc572b734cc)

## Possible Solution
The data-decimal-seperator and data-decimal-count attributes of the `form` element could be used to control the form input, and referenced cleanup up the amount button labels with a frontend solution.

## Acceptance Criteria
- [x] Decimal places do not render on the choose amount screen
- [x] Code has been tested with fee recovery addon and does not impact performance
- [x] A decision has been made and noted in this issue regarding how to handle amount with a decimal place set by user, and how to handle decimal places in custom amounts

**Comment by Benunc** [comment]
This will need testing alongside the fee recovery add-on, which has unique interaction with the number of decimals. Fee recovery forces decimals back to "on" so that the calculations are correct.
