### ISSUE TITLE
feature: load fontawesome assets on build step (do not track w version control)

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#4601]
# Feature Request

## User Story
As a developer, I want FontAwesome assets loaded during a build step so that the GiveWP repo is not tracking all FontAwesome assets in version control.

## Details
Additionally, only specific needed icons should be packaged within the plugin's assets directory.

While FontAwesome assets are primarily used in the GiveWP admin interface, they will increasingly find use in new Form Templates. We should discuss how these Form Templates (eg Sequoia) should best pull in FontAwesome assets where needed.

## Possible Solution
See _Using Package Managers_ doc on FontAwesome website: https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers

Also see `font-awesome` package on npm: https://www.npmjs.com/package/font-awesome

## Acceptance Criteria
- [ ] FontAwesome assets are loaded during build step
- [ ] FontAwesome assets are not tracked in GiveWP version control
- [ ] Specific icons are dynamically packaged in plugin's assets directory as needed
- [ ] Easy solution exists for Form Templates to incorporate FontAwesome assets as needed

**Comment by JasonTheAdams** [comment]
This looks great, @henryholtgeerts. Thanks for putting this together!

**Comment by jonwaldstein** [comment]
We're mainly using the `@fortawesome` packages these days so this may have already been resolved.
