### ISSUE TITLE
fix: donation forms using Stripe do not redirect to success page

### ISSUE THREAD

**Issue by allienimmons** [impress-org/givewp#4605]
# Bug Report

## User Story

As a donor, I want to donate to a form with Stripe using GiveWP 2.6.1 and then immediate see my donation confirmation receipt/success page.

## Details
This only happens with 2.6.1 (I rolled back the plugin and tested with 2.5 and it works as expected)
This also only seems to happen with Stripe (I tested with the test gateway and it worked as expected)
I also tried it with WordPress 5.3 and 5.4 and the problem persists with both
The donation does clear in GiveWP and Stripe, it doesn't fail or submit an error.
No errors are listed in the Logs, just that the Stripe webhook was received successfully. 

## Current Behavior
Currently, if the site is using Give 2.6.1 and the form is using Stripe, the page will refresh and show the form again instead of showing the donor the Donation Confirmation page with their receipt details.

## Expected Behavior
The form page should immediately redirect them to their set donation confirmation page.

## Bug Type

- [x] This bug describes functionality that once worked as expected in version 2.6
- [ ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Install GiveWP 2.6.1 and create a form that uses the stripe gateway
2. Make a donation 
3. Observe that if the donation is successful, the form will refresh instead of redirecting

## Visuals
http://somup.com/cYfVIT1uj2

## Related
https://secure.helpscout.net/conversation/1125073375/0/?folderId=672194
https://secure.helpscout.net/conversation/1125057932/0/?folderId=672194
https://secure.helpscout.net/conversation/1125352053/61327?folderId=672194

## Acceptance Criteria

- [x] The form must redirect to the success page after the donation.
- [x] The form must not refresh itself when the donation is complete.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X 
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
        <li>Version: 80.0.3987.149 </li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://getmichelleanewlaptop.com
Site URL: http://getmichelleanewlaptop.com
WP Version: 5.4
WP Multisite: –
WP Memory Limit: 768 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: page
Page on Front: Get Michelle a New Laptop (#13)
Page for Posts: Unset
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, wc-pending, wc-processing, wc-on-hold, wc-completed, wc-cancelled, wc-refunded, wc-failed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: Siteground
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.29 (Unix) mod_hive/6.27 OpenSSL/1.0.1e-fips mod_fastcgi/2.4.6
PHP Version: 7.3.16
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
PHP Max Upload Size: 128 MB
cURL Version: 7.59.0, OpenSSL/1.0.2r
SUHOSIN Installed: –
MySQL Version: 5.6.36
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.6.1
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access❌Renewal Receipt Email❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access✔Subscription Payment Failed Email
Upgraded From: 2.6.0
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://getmichelleanewlaptop.com/donation-confirmation/
Failure Page: http://getmichelleanewlaptop.com/donation-failed/
Donation History Page: http://getmichelleanewlaptop.com/donation-history/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Stripe - Credit Card
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: April 1, 2020 1:37 pm

### Active GiveWP Add-ons ###

Give - Annual Receipts: ❌ Unlicensed – by GiveWP – 1.0.2
Give - Donation Upsells for WooCommerce: ❌ Unlicensed – by GiveWP – 1.1.5
Give - Form Field Manager: ❌ Unlicensed – by GiveWP – 1.4.4
Give - Recurring Donations: ✔ Licensed – by GiveWP – 1.9.14
Give - Square: ❌ Unlicensed – by GiveWP – 1.1.1

### Other Active Plugins ###

Google Fonts Typography: by Fonts Plugin – 1.9.99
Jetpack by WordPress.com: by Automattic – 8.3
ManageWP - Worker: by GoDaddy – 4.9.6
My Custom Functions: by Space X-Chimp – 4.42
WooCommerce: by Automattic – 4.0.1
WooCommerce Services: by Automattic – 1.22.5
WP Rollback: by Impress.org – 1.7.0

### Active MU Plugins ###

ManageWP - Worker Loader: by GoDaddy –

### Theme ###

Name: Twenty Twenty
Version: 1.1
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by allienimmons** [comment]
Another one. https://secure.helpscout.net/conversation/1125541328/61346/

**Comment by allienimmons** [comment]
https://secure.helpscout.net/conversation/1125574886/61349/

**Comment by rickalday** [comment]
https://secure.helpscout.net/conversation/1124899415/61286/

**Comment by rickalday** [comment]
https://secure.helpscout.net/conversation/1124919690/61294/
