### ISSUE TITLE
fix: load data on Reports page and dashboard widget (with form templates active)

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#4617]
# Bug Report

## User Story
As a user, I want the Reports page and dashboard widget to load data, even with form templates active so that I can still access views of my reports data.

## Details
This issue is currently only present in the `form-theme` branch, and does not appear in any release or the `develop` branch.

## Current Behavior
When working in the `form-theme` branch, the Reports page and dashboard widget fail to load data. 

## Expected Behavior
The Reports page and Reports dashboard widget should load data as they normally do, even within the `form-theme` branch.

## Bug Type
- [x] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Checkout the `form-theme` branch
2. Run `composer dumpautoload` and `npm install && npm run watch`
3. Open your site's admin dashboard, see that the Reports dashboard widget only loads blank charts
4. Open your site's Reports page, see that the charts are blank there as well

## Visuals
![Screen Shot 2020-04-06 at 4.44.22 PM.png](https://images.zenhubusercontent.com/5de5476735cbb7ad97ed643a/158e2e4d-6c9f-478b-9f6a-90f41d90ee73)

![Screen Shot 2020-04-06 at 4.43.54 PM.png](https://images.zenhubusercontent.com/5de5476735cbb7ad97ed643a/dbab267f-d19b-4ea1-ac4c-743b1df70209)

## Acceptance Criteria
- [x] Reports data loads as expected in the Reports page
- [x] Reports data loads as expected in the Reports dashboard widget

**Comment by ravinderk** [comment]
fixed: https://github.com/impress-org/givewp/compare/9bcb848e8db4...9de92bf35d1b
