### ISSUE TITLE
Elementor Page Builder

### ISSUE THREAD

**Issue by haslo41** [impress-org/givewp#4621]
# Feature Request

## User Story

As a newbie to web development, 
1. i rely heavily on Elementor to build my sites, I want a feature so that i could design the giveform with elementor and add fields etc

2. i would like to have an option for custom fields based on the multi level donation that is selected. ie if there are three levels of donations, Bronze, Silver Gold, when selected Silver a particular field/s are brought up for the donor to enter, but these fields would not be availble if Broze or Gold is selected.

## Acceptance Criteria

- [ ] e.g. Something happens when an action is taken.
- [ ] e.g. Something does not happen when an action is taken.
- [ ] e.g. Implementing feature in Component A does not affect existing behavior in Component B.

**Comment by DevinWalker** [comment]
Thank you for your suggestion. We plan on integrating more closely with Elementor. However, we envision you building a donation form with our builder and then integrating that with Elementor. Not the the other way around, wherein you would create a donation form in Elementor entirely. Both plugins serve a purpose and can work together in tandem closely in a way that fits your need but don't rely on one another.
