### ISSUE TITLE
Multilevel donation

### ISSUE THREAD

**Issue by haslo41** [impress-org/givewp#4622]
# Bug Report

## User Story

As a freelance webdeveloper, I have an issue where when the donor selects a button on the multi level donation form the button doesn remain highlighted to show selection, i have tried to add custom css but the buton is only highlighted briefly. it doesnt stay highlighted when clicked._.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1.
2.
3.

## Acceptance Criteria

- [ ] e.g. Something happens when an action is taken.
- [ ] e.g. Something does not happen when an action is taken.
- [ ] e.g. Fixing behavior in Component A does not affect existing behavior in Component B.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X | Microsoft Windows | Linux | Android | iOS</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    
</details>

**Comment by DevinWalker** [comment]
Closing as this is a support question. Please reach out to our [Priority Support](https://givewp.com/support) for assistance should you still need it.
