### ISSUE TITLE
fix: prevent new reports redirect from legacy reports filtering

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#4644]
# Bug Report

## User Story
As a user, I want the legacy reports not to redirect to the new reports dashboard when filtering by a time period so that I am able to view data older than the past month in the legacy reports page.

## Details
This behavior largely renders the legacy reports screen useless, as you cannot see data older than the previous month without being redirected to the new reports dashboard.

## Current Behavior
When viewing the legacy reports page, if a user selects a filter other than previous month, and presses the filter button, they are redirected to the new reports dashboard.

## Expected Behavior
When filtering the legacy reports page, you should not be redirected to the new reports dashboard. The filtered legacy reports should load as expected.

## Bug Type
- [x] This bug describes functionality that once worked as expected in version 2.5.x.
- [ ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Navigate to the legacy reports page
2. Filter by previous year
3. Click "Filter", and you will be redirected to the new reports dashboard

## Possible Solution
Ensure that the "legacy=true" URL parameter is being passed when accessing the filtered legacy reports page.

## Acceptance Criteria
- [ ] Users are able to filter results on the legacy reports page without being redirected to the new reports dashbaord
- [ ] Legacy reports filter as expected

**Comment by Benunc** [comment]
According to both @rickalday and @matheuswd this issue is still happening on 2.6.3. Reopening for discussion.

**Comment by rickalday** [comment]
https://secure.helpscout.net/conversation/1181740159/66856?folderId=672194

**Comment by ravinderk** [comment]
@Benunc This issue fixed in Give `2.6.3` but we can also reproduce this when fee recovery active. We already resolved this: https://github.com/impress-org/give-fee-recovery/pull/268
Fee recovery with this patch is not released yet and we are planning to release this `Fee Recovery 1.7.9`
