### ISSUE TITLE
Tooltip for "Subscription completed email" doesn't make sense

### ISSUE THREAD

**Issue by Outdoorsman** [impress-org/givewp#4649]
# Bug Report

## User Story
Right now the "Subscription completed email" tool tip looks like this. It seems the wording is incorrect since this email isn't sent when a subscription is cancel but created.

![2020-04-15_18-52-26](https://user-images.githubusercontent.com/3075533/79406755-be968900-7f4c-11ea-90a6-baf142f44f83.jpg)

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Go in the backend to `Donations` > `Settings`
2. Select the `Emails` tab
3. Make sure `Donor Emails` sub tab is selected
4. Hover over the `?` icon next to `Subscription Completed Email` to see the incorrect tooltip wording.

## Acceptance Criteria

- [ ] e.g. Something happens when an action is taken.
- [ ] e.g. Something does not happen when an action is taken.
- [x] e.g. Fixing behavior in Component A does not affect existing behavior in Component B.

**Comment by DevinWalker** [comment]
That definitely does not read right. Thanks for pointing that out. We'll review that tooltip and others for clarity and have it out in the next release.

**Comment by ravinderk** [comment]
This belongs to the recurring addon, so moving it.

**Comment by ravinderk** [comment]
Issue moved to [impress-org/give-recurring #938](https://github.com/impress-org/give-recurring/issues/938) via [**ZenHub**](https://www.zenhub.com/)
