### ISSUE TITLE
feature: PDF receipts button should be styled correctly in the Sequoia template

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#4657]
# Feature Request

## User Story
As a user, I want the Sequoia template to be compatible with the PDF receipts addon so that a download receipt button appears if the addon is enabled.

## Details
The receipt download button is already in place and styled, it only needs to be setup to link to the appropriate PDF, and conditionally rendered (depending on wether the PDF receipts addon is enabled).

## Visuals
![Screen Shot 2020-04-21 at 4.17.17 PM.png](https://images.zenhubusercontent.com/5de5476735cbb7ad97ed643a/777027f1-e8d1-4132-8d9c-dc350f928b0c)

## Possible Solution
Check that the PDF receipts addon is enabled. If yes, show the receipt download button.

## Acceptance Criteria
- [ ] Receipt download button is conditionally shown, depended on activation of PDF receipts addon
- [ ] Button links to the PDF receipt as expected

**Comment by ravinderk** [comment]
@henryholtgeerts I create these prs to resolve the compatibility issues. You can start work on styling.

https://github.com/impress-org/givewp/tree/feature/make-pdf-receipt-download-button-compatible-with-pdf-receipt-addon
https://github.com/impress-org/give-pdf-receipts/pull/221

**Comment by henryholtgeerts** [comment]
Appropriate changes have been made in these branches:
https://github.com/impress-org/givewp/tree/feature/make-pdf-receipt-download-button-compatible-with-pdf-receipt-addon
impress-org/give-pdf-receipts#221

Resulting in this styling: 
<img width="594" alt="Screen Shot 2020-05-13 at 11 54 29 AM" src="https://user-images.githubusercontent.com/5186078/81835824-b102fd80-9510-11ea-82b4-9561e72e355e.png">
