### ISSUE TITLE
prevent unexpected behaviour which generated by orphaned license keys

### ISSUE THREAD

**Issue by Benunc** [impress-org/givewp#4669]
# Bug Report

## User Story

As a user, I only want accurate license key errors so that the WP dashboard/admin interface is not crowded with incorrect messages.

## Details
Any user with old license keys saved in the database (a number that will grow over time as more people purchase plans to replace single add-ons and legacy bundles) gets a phantom warning related to expired/inactive license keys when in reality their plan license keys are active. 

## Current Behavior
Currently, users with old license expired license keys have no way of removing them (and thus the warnings on every admin screen) unless they know the workaround in my video below.

This creates extra work for the user, as well as a burden on the Support and Customer Success teams as they have to have access to the site to resolve the problem for the customer. 

## Expected Behavior
All licenses saved in the database should display on the licenses screen and be able to be deactivated or deleted completely.

## Bug Type
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
The steps involve adding a live license key and then expiring it, which needs someone with EDD access to the site to facilitate. Here's a video: https://screencast-o-matic.com/watch/cYf0oAA0JT

Here's what I did before that video:
1. Add license for a single add-on to the site.
2. Log in as EDD-level admin on the givewp.com site, and manually switch that license to expired.
3. Refresh the licenses on the licenses tab of the test site.

## Related
We regularly have calls about this.

## Acceptance Criteria
- [ ] All licenses in the DB show on the back end.
- [ ] The error messages related to licenses only show if there are no active plan licenses.

**Comment by ravinderk** [comment]
Discussion: https://givewp.slack.com/archives/C0E290T6Z/p1588178782102500

We discussed this issue and shortlisted the following issues with license functionality.
1. "Unauthorized access" notice when update addon.
2. Single addon expired licenses notices confuse admin who upgraded to bundle plan.
3. A rare admin behavior also detected on the license setting page where the admin is able to see a single license key separately even it is part of the bundle plan.
