### ISSUE TITLE
feat: add text and graphic to gateways that do not have fields or are offsite in form template

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#4670]
# Feature Request

## User Story

As a donor, I want a clear understanding of the donation experience so that I'm not confused when a gateway takes me off site or there is a general lack of text.

As an admin, I want to know how the functionality of the Test Gateway works and don't want my donors to be confused when a gateway doesn't have any text that displays when clicking on it.

## Details

Currently right now with Sequoia some gateways have fields that display (Credit Card gateways) or text (Offline Donations) while others do not have any (PayPal Standard). This leads to a poor donor experience when selecting the different options. What we need to do is ensure each gateway has the appropriate text that informs the donor and is clear and concise.  

## Visuals

**PayPal Standard**

![2020-04-23_14-07-56](https://user-images.githubusercontent.com/1571635/80151998-c323f880-856f-11ea-855a-774d009fcab7.png)

**Test Gateway**

![2020-04-23_14-32-48](https://user-images.githubusercontent.com/1571635/80152038-d3d46e80-856f-11ea-93cb-51676122b959.png)

**Offline Donations**

![2020-04-23_14-45-18](https://user-images.githubusercontent.com/1571635/80152789-282c1e00-8571-11ea-9ce3-daace8a5b254.png)

## Possible Solution

Each gateway that's offsite needs to have text that makes it clear to the user what to expect. We need to ensure that the text that displays is styled appropriately, has the light gray background, and has a nice graphic whenever possible.

## Acceptance Criteria

- [x] PayPal Standard has text and image that displays appropriately
- [ ] Razorpay has text and an image that displays appropriately
- [x] Test Gateway has text and an image that displays appropriately
- [x] Offline Donations has text and an image that displays appropriately 
- [x] The actual UI matches the concept for all gateways

**Comment by henryholtgeerts** [comment]
Adding an offsite redirection note to Razorpay requires modification of the Razorpay addon. An issue has been opened for this reason: https://github.com/impress-org/give-razorpay/issues/55
