### ISSUE TITLE
This string is not properly i18n-ed

### ISSUE THREAD

**Issue by mathetos** [impress-org/givewp#4677]
This string needs to be properly internationalized:
https://github.com/impress-org/givewp/blob/develop/includes/gateways/stripe/includes/actions.php#L109 

Customer report:
https://secure.helpscout.net/conversation/1146450480/63620?folderId=672194#modal

**Comment by kevinwhoffman** [comment]
@mathetos That string exists multiple times in the plugin, however there is only one place that I found where it is not wrapped in the proper i18n function.

The string that needs attention is located here, which is confirmed by the presence of `SEPA` in the customer's screenshot:
https://github.com/impress-org/givewp/blob/9bad167f17989ee95b31b9bcbfa1037711677ab3/includes/gateways/stripe/includes/payment-methods/class-give-stripe-sepa.php#L129

**Comment by DevinWalker** [comment]
Fixed here https://github.com/impress-org/givewp/commit/cf551005092690d707aa52dde06739da5a871be3
