### ISSUE TITLE
feat: add form template compatibility to form grid shortcode

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#4681]
# Feature Request

## Developer Story

As a developer, I want to make a form template compatible with form grid shortcode with so that admin can use with.

## Details

Form grid shortcode works with existing legacy form but we have to add extra logic to render embed form if form template for the selected form is other then Legacy.

## Possible Solution

Use `give_form_shortcode` function to get form HTML of form which has form template other then legacy and then on `a.js-give-grid-modal-launcher` click open embed form in modal.

## Acceptance Criteria

- [x] Form grid shortcode styling looks good in admin and frontend.
- [x] When clicking on modal launcher modal opens with style depends upon selected form template.

**Comment by DevinWalker** [comment]
Closing as the PR above has been merged.
