### ISSUE TITLE
feat: add option to show form title on donor wall

### ISSUE THREAD

**Issue by rickalday** [impress-org/givewp#4683]
# Feature Request

## User Story

As a site admin, I want to be able to display the form title in the donor wall.

## Possible Solution

Add a shortcode attribute and block setting to toggle the form title display on/of (true/false)

## Related

https://secure.helpscout.net/conversation/1148208221/63773/

## Acceptance Criteria

- [ ] The shortcode attribute is available in the shortcode builder
- [ ] The block setting is available in the block editor

**Comment by DevinWalker** [comment]
Closing as this has been added to Canny: https://givewp.canny.io/feature-requests/p/short-form-title-on-donor-wall
