### ISSUE TITLE
make Sequoia form template compatible with form field manager

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#4688]
# Feature Request

## Developer Story

As a developer, I want to make a sequoia form template compatible with form field manager addon so that admin can add custom fields to the donation form.

## Details

![image](https://user-images.githubusercontent.com/1784821/80483436-b5a5ae80-8973-11ea-819b-22c7f164a4ac.png)

As you can see above screenshot, admin can use one location to add/show custom form field which stores as donation metadata. Custom fields appear on donation form without any issue because we are using the legacy form renderer. The custom field value is not showing in receipt because the form field manager uses receipt hooks to render custom field which is missing from the custom receipt view.

## Possible Solution

Review existing setup in form field manager addon and add custom field render logic on receipt view to core.

## Acceptance Criteria

- [ ] Form field locations work fine and produce results as expected.
- [ ] I can see custom field values on the donation receipt.

**Comment by henryholtgeerts** [comment]
@ravinderk I'm planning to open an issue for styling FFM this afternoon, separate from this FFM compatibility issue. What's the current status of work on your end? I think it'd be smart to rethink the form field locations available, before I spend too much time building out styles for all the locations that are supported in legacy forms. Eg: adding a separate step location, and limiting available options to below donation fields/below personal fields.  Open to ideas, these are just initial thoughts!

**Comment by ravinderk** [comment]
@henryholtgeerts I did not start yet. I will update you once I will start it. I also agree to rethink about FFM location because of starting work on compatibility.

**Comment by ravinderk** [comment]
I created a Pr for form field manager repo to resolve this issue: https://github.com/impress-org/give-form-field-manager/pull/312

@henryholtgeerts Let resolve styling issue in a separate issue.
