### ISSUE TITLE
Constant Contact should not affect PayPal Pro Payments

### ISSUE THREAD

**Issue by jurassicdanie** [impress-org/givewp#4694]
# Bug Report

## User Story

As a user, I want Constant Contact to work properly with PayPal Payflow.

## Details
Donation transactions are processing successfully in PayPal Pro, but not being marked Complete in GiveWP; they are staying marked as "Pending". This is happening about 90% of the time. After doing some digging, we have found that this only happens under certain conditions, with Constant Contact being turned on.

## Current Behavior
I was able to reproduce the error consistently only when:
1. I'm logged out.
2. I have Guest Donations disabled on the form so that "Create an Account" is required on the 3.checkout form.
And only if I have the Constant Contact add-on enabled and the checkbox on the form to join the email list is left checked.
Those conditions reproduce the error every time.

## Expected Behavior
To be able to use the Add-On "Give - Constant Contact" to integrate with the email marketing platform and add donors to our email list, with all donations processing correctly.

## Bug Type
It is producing an error

## Steps to Reproduce
Have Constant Contact and PayPal Pro set up on donation form
1. Be logged out of your account
2. Have Guest Donations disabled on the form so that "Create an Account" is required on the checkout form.
3. And only if I have the Constant Contact add-on enabled and the checkbox on the form to join the email list is left checked.
Those conditions reproduce the error every time.

## Related
https://secure.helpscout.net/conversation/1149799290/63973/

## Acceptance Criteria

- [ ] e.g. Something happens when an action is taken.
- [ ] e.g. Something does not happen when an action is taken.
- [ ] e.g. Fixing behavior in Component A does not affect existing behavior in Component B.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X | Microsoft Windows | Linux | Android | iOS</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    
</details>

**Comment by DevinWalker** [comment]
Closing as edge case and made in the incorrect repo - if we see more reports we'll add it as a bug to our feedback board.
