### ISSUE TITLE
fix: make donor wall dates localizable

### ISSUE THREAD

**Issue by Benunc** [impress-org/givewp#4704]
# Bug Report

## User Story

As a user, I want dates on the donor wall to be translatable/localizable so that they display in the same language as the dates elsewhere on the site.

## Current Behavior
Currently, the dates are in English, even if the site is localized to a different language. 

## Expected Behavior
I expect the dates to be in the correct language.

## Bug Type
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Create a page with a donor wall shortcode/block on it.
2. Change the site to Spanish and download all translation files from the WP Admin.
3. View the page created in step 1. 

The dates are not translated.

## Possible Solution
https://github.com/impress-org/givewp/blob/075c491391e7dae9f0c26c43ac9e7b8b663a92b1/includes/misc-functions.php#L2138 

That function seems to be self-aware of its own limitation, here.

## Related
https://secure.helpscout.net/conversation/1141503806/63081?folderId=672194

## Acceptance Criteria
- [ ] The donor wall dates are translatable
- [ ] If it's not possible without significant overhaul of the above function, a workaround snippet using the filter in that function is provided to the support team.

## Environment

<details>
    <summary>WordPress System Info</summary>
    ### WordPress Environment ###

Home URL: https://livegive.wpsteward.com
Site URL: https://livegive.wpsteward.com
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: fr_FR
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_8138bfdc07_
Table Prefix Length: 14
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: livegive.wpsteward.com
TLS Connection: Connexion utilisé TLS 1.2
TLS Connection: Probably Okay
Server Info: Apache/2.4.43 (Unix) OpenSSL/1.0.1f
PHP Version: 7.1.33
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
PHP Max Upload Size: 512 MB
cURL Version: ❌ 7.35.0, OpenSSL/1.0.1f - Nous recommandons au minimum cURL 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.62 - Nous recommandons MySQL 5.6 ou supérieur. Voir : Pré-requis WordPress
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.6.2
GiveWP Cache: Activé
Database Updates: Toutes les mises à jours de la base de données sont terminéees.
Database Tables: ✔ wp_8138bfdc07_give_donors -  1.0✔ wp_8138bfdc07_give_donormeta -  1.0✔ wp_8138bfdc07_give_comments -  1.0✔ wp_8138bfdc07_give_commentmeta -  1.0✔ wp_8138bfdc07_give_sessions -  1.0✔ wp_8138bfdc07_give_logs -  1.0✔ wp_8138bfdc07_give_logmeta -  1.0✔ wp_8138bfdc07_give_formmeta -  1.0✔ wp_8138bfdc07_give_sequential_ordering -  1.0✔ wp_8138bfdc07_give_donationmeta -  1.0
GiveWP Cache: Activé
GiveWP Cache: ✔Nouveau don✔Reçu de dons✔Nouveau don hors-ligne✔Instructions pour le dons hors ligne✔Enregistrement d’un nouvel utilisateur✔Information d'enregistrement de l'utilisateur✔Commentaire sur le don❌Accès aux mails❌Renewal Receipt Email✔Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email❌Subscriptions Email Access✔Subscription Payment Failed Email
Upgraded From: 2.6.1
Test Mode: Activé
Currency Code: USD
Currency Position: Avant
Decimal Separator: .
Thousands Separator: ,
Success Page: https://livegive.wpsteward.com/donation-confirmation/
Failure Page: https://livegive.wpsteward.com/donation-failed/
Donation History Page: https://livegive.wpsteward.com/donation-history/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Don hors ligne, PayPal Standard, PayPal Payments Pro, Authorize.net, Authorize.net eCheck (ACH), Braintree, Stripe - Apple Pay, Stripe - Carte de crédit, Stripe - Checkout, Stripe + Plaid, Stripe - Google Pay, Stripe iDEAL
Default Payment Gateway: Stripe + Plaid
PayPal IPN Verification: Activé
PayPal IPN Notifications: IPN reçu pour #211 ( 9EH155265E921591R ) le 09/20/2019 à 14:04. Statut VERIFIED
Donor Email Access: Désactivé
Stripe Webhook Notifications: mai 4, 2020 3:20
Square Token Renewal Date: 2020-04-15 13:30:46

### Active GiveWP Add-ons ###

Give - 2Checkout Gateway: ✔ Autorisé – par GiveWP – 1.1.4
Give - Annual Receipts: ✔ Autorisé – par GiveWP – 1.0.2
Give - Authorize.net Gateway: ✔ Autorisé – par GiveWP – 1.4.6
Give - Braintree Gateway: ✔ Autorisé – par GiveWP – 1.2.4
Give - CCAvenue Gateway: ✔ Autorisé – par GiveWP – 1.0.4
Give - Currency Switcher: ✔ Autorisé – par GiveWP – 1.3.7
Give - Fee Recovery: ✔ Autorisé – par GiveWP – 1.7.8
Give - Form Field Manager: ✔ Autorisé – par GiveWP – 1.4.4
Give - Google Analytics Donation Tracking: ✔ Autorisé – par GiveWP – 1.2.4
Give - MailChimp: ✔ Autorisé – par GiveWP – 1.4.6
Give - Manual Donations: ✔ Autorisé – par GiveWP – 1.4.6
Give - PayPal Pro Gateway: ✔ Autorisé – par GiveWP – 1.2.2
Give - PDF Receipts: ✔ Autorisé – par GiveWP – 2.3.6
Give - Per Form Gateways: ✔ Autorisé – par GiveWP – 1.0.2
Give - Recurring Donations: ✔ Autorisé – par GiveWP – 1.10.1
Give - Square: ✔ Autorisé – par GiveWP – 1.1.1
Give - Stripe Gateway: ✔ Autorisé – par GiveWP – 2.2.5
Give - Tributes: ✔ Autorisé – par GiveWP – 1.5.6
Give - Zapier: ✔ Autorisé – par GiveWP – 1.3.0

### Other Active Plugins ###

Advanced CF7 DB: par Vsourz Digital – 1.7.2
Disable Gutenberg: par Jeff Starr – 2.1
Email Cop: par Ashfame – 0.1.1
Google Analytics for WordPress by MonsterInsights: par MonsterInsights – 7.10.4
User Role Editor: par Vladimir Garagulya – 4.53.1
User Switching: par John Blackbourn & contributors – 1.5.4
WP Rollback: par Impress.org – 1.7.0

### Inactive Plugins ###

Ben's Helper Functions: par BenUNC –
Elementor: par Elementor.com – 2.9.8
Give - AmeriCloud Payments: par AmeriCloud Solutions, Inc. – 1.3.4
Give - Constant Contact: par GiveWP – 1.2.4
Give - Database HealthCheck: par WordImpress – 0.0.2
Give - Email Reports: par GiveWP – 1.1.4
Give - Form Countdown: par GiveWP – 1.0.1
Give - Mollie Gateway: par GiveWP – 1.2.4
Give - PayFast Payment Gateway: par WordImpress – 1.0.2
Give - Paytm Gateway: par GiveWP – 1.1.0
Hello Dolly: par Matt Mullenweg – 1.7.2
Loco Translate: par Tim Whitlock – 2.3.3
Page Builder by SiteOrigin: par SiteOrigin – 2.10.15
Plugin Detective - Troubleshooting: par N Squared – 1.1.6
Query Monitor: par John Blackbourn – 3.5.2
Shortcode in Menus: par Gagan Deep Singh – 3.5
Simple Social Shout for GiveWP: par Matt Cromwell – 1.0
SiteOrigin Widgets Bundle: par SiteOrigin – 1.16.1
Stop Donor Spam: par Matt Cromwell – 1.2.0
Tickera: par Tickera.com – 3.4.6.9
Wordfence Security: par Wordfence – 7.4.6
WP Crontrol: par John Blackbourn & crontributors – 1.8.1

### Active MU Plugins ###

api-hacks.php: par  –
helpr-mu.php: par  –
per-form-currency.php: par  –

### Theme ###

Name: Twenty Seventeen
Version: 2.3
Author URL: https://wordpress.org/
Child Theme: Non – Si vous modifiez Give sur un thème parent que vous n’avez pas personnellement créé, nous vous recommandons d’utiliser un thème enfant. Voir Comment créer un thème enfant

</details>

**Comment by ravinderk** [comment]
This has been fixed in `Give 2.6.3`: https://github.com/impress-org/givewp/issues/4721
