### ISSUE TITLE
Suggestion: Allow user to install addons directly from the admin.

### ISSUE THREAD

**Issue by bradp** [impress-org/givewp#4706]
# Feature Request

## User Story

As a user, I want to be able to install plugins easily and without hassle.

## Details
Rather than having this be a 'Download', we make it an 'install' and automatically install the plugin to the site. And either add a 'download' link near the changelog link, or a 'download addons' near the manage licenses. Right now, to install an addon, a user needs to download it, and the re-upload it to the same page we're on to activate it. Let's save them a step.

## Visuals
![Screenshot 2020-05-04 10 42 53](https://user-images.githubusercontent.com/66798/80997363-d0aa6f80-8e06-11ea-89c6-6f0710aaef17.png)

**Comment by DevinWalker** [comment]
Unfortunately, this is not allowed by WP.org plugin policy.
