### ISSUE TITLE
Reorder addons in admin

### ISSUE THREAD

**Issue by bradp** [impress-org/givewp#4707]
# Feature Request

## User Story
As a user, I’m probably more likely to want stripe vs moneris for example. Maybe break it into sections? Payment Gateways / Reporting / emails. With the ones we know are more common at the top

## Visuals
![Screenshot 2020-05-04 10 42 53](https://user-images.githubusercontent.com/66798/80997427-e881f380-8e06-11ea-87fe-8ab69625d162.png)

**Comment by DevinWalker** [comment]
Not a common request, closing.
