### ISSUE TITLE
fix: prevent JavaScript error on install if Stripe is not connected but enabled

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#4709]
# Bug Report

## User Story

As a admin, I want installing GiveWP to not have any JS issues on the frontend of my website.

## Details

Currently when you install GiveWP without configuring anything you receive a JS error on the frontend pointing to Stripe.

## Steps to Reproduce

1. Install GiveWP from WP.org
2. Don't configure anything
3. View the frontend of your website and Developer Tools

## Visuals

![2020-05-04_21-15-12](https://user-images.githubusercontent.com/1571635/81034645-b2fff900-8e4c-11ea-9b7f-2a419db47c7c.png)

## Possible Solution

Check if Stripe is connect or using API keys before calling `Stripe()`.

## Acceptance Criteria

- [x] Installing GiveWP causes no JS issues 
- [x] Connecting via API keys still continues to work
- [x] Connecting to Stripe via Stripe Connect continues to work
- [x] No JS errors are seen when one form is on a page
- [x] No JS error occur when multiple forms are on the same page
- [x] No JS errors occur when the same form is on a page multiple times

**Comment by ravinderk** [comment]
@DevinWalker agree to move this issue to `2.7.0`: https://givewp.slack.com/archives/C0FAGC83C/p1588791755114600
