### ISSUE TITLE
feat: add date filter for Forms, Donation Methods, and Renewal payments

### ISSUE THREAD

**Issue by rickalday** [impress-org/givewp#4716]
# Feature Request

## User Story

As a site admin, I want to be able to sort reports based on date and date range so that I can have a better idea of how my forms, payment methods, and renewals are performing.

## Visuals

<img width="1095" alt="Screen-Shot-2020-05-05-at-4 07 48-PM" src="https://user-images.githubusercontent.com/312000/81204323-b3081200-8f8e-11ea-9fe3-5ed4044e221d.png">

## Related

https://secure.helpscout.net/conversation/1156248256/64648?folderId=3400524
https://secure.helpscout.net/conversation/1156333515/64660/

## Acceptance Criteria

- [ ] There's a simple UI to sort all reports based on date or date range.

**Comment by DevinWalker** [comment]
This has to do with our legacy report which we are no longer developing on.
