### ISSUE TITLE
feat:  Improve UX for donation processing time

### ISSUE THREAD

**Issue by rickalday** [impress-org/givewp#4717]
# Feature Request

## User Story

As a donor, I would like some indication that my donation is processing after I click the Donate button.

## Details

Currently, there's only the spinning icon that shows that something is going on.  However, this icon can be easy to miss or even hidden by some CSS.

## Possible Solution

I proposed that the text on the donation button text changes dynamically to something like "Processing..."
This text should also be translatable and the admin should be able to edit it either with a filter or admin option.

## Related

https://secure.helpscout.net/conversation/1157126781/64740/

## Acceptance Criteria

- [ ] There's a more prominent way to let the user know the donation is being processed.

**Comment by DevinWalker** [comment]
Thanks @rickalday - we are handling this within the new form template which has a better UX for when the donation is processing. Therefore, I'm closing this issue as it's being addressed elsewhere.
