### ISSUE TITLE
fix: improve error handling in stripe

### ISSUE THREAD

**Issue by mehul0810** [impress-org/givewp#4725]
# Bug Report

## User Story
As a developer, I want to provide better error handling for Stripe so that users can see proper messages and it will be better to debug issues at our end.

## Details
- https://stripe.com/docs/api/errors

## Current Behavior
Currently, it is hard to let the customer know about the issue and as a developer, it is hard to trace the issue with Stripe

## Expected Behavior
Improve Error Handling with Stripe

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Related
- https://github.com/impress-org/give-recurring/issues/924

## Acceptance Criteria
- [ ] Add support for proper Error Handling as Stripe suggests.
- [ ] Testing

**Comment by mehul0810** [comment]
Additional Tasks to be achieved along with the error handling for Stripe:
1. With any API call to Stripe, if API Key is expired due to disconnection of the same Stripe account from another site. Then, update the status of Stripe connection to "Disconnected" in Give admin. This will help the user to know that Stripe is disconnected and they need to reconnect it.

I will add more scenarios as I come across while working on other PR's

**Comment by ravinderk** [comment]
@DevinWalker I am pushing this issue to next release instead of `Give 2.7.0`.

**Comment by jonwaldstein** [comment]
@ravinderk i'm closing this out in favor of our gateway api now handling & logging errors
