### ISSUE TITLE
Form submitted with empty required fields is reloaded and no validation errors are shown

### ISSUE THREAD

**Issue by ergosarapu** [impress-org/givewp#4736]
# Bug Report

## User Story
As a user, I want that custom gateway form submission required fields are properly validated so that I can get proper feedback about what I have missed to fill in.

## Details
Custom-built gateway's required fields are not properly validated if the default gateway is set as default, browser validation has been triggered and form is submitted again.

## Current Behavior
Form submitted with empty required fields is reloaded and no validation errors are shown

## Expected Behavior
Form submitted with empty required fields is not reloaded and validation errors are shown

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Install Test Gateway (code included below)
2. Enable Test Gateway and set it as default
3. Create donation form and include it in page
4. Navigate to page
5. Submit the form (don't fill in anything yet)
6. Browser validation asks to fill in First name, fill it in
7. Submit the form

## Acceptance Criteria
- [ ] Required fields validation happens and errors are displayed whenever form is submitted

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
        <li>Version: 10.13.6</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome</li>
        <li>Version: 81.0.4044.129</li>
    </ul>
</details>

<details>
    <summary>Plugin</summary>
    <ul>
        <li>Name: GiveWP</li>
        <li>Version: 2.6.2</li>
    </ul>
</details>

## Test Gateway code
```
<?php
/**
 * Plugin Name:     Test Gateway for GiveWP
 * Description:     Test Gateway for GiveWP donations plugin
 * Text Domain:     givewp-test-gateway
 * Domain Path:     /languages
 * Version:         0.1.0
 *
 * @package Givewp_TestGateway
 */

if (! defined('ABSPATH')) {
    exit;
}

/**
 * Register payment method.
 */
add_filter('give_payment_gateways', function ($gateways) {
    // Duplicate this section to add support for multiple payment method from a custom payment gateway.
    $gateways['test_gateway'] = array(
        // This label will be displayed under Give settings in admin.
        'admin_label'    => __('Test Gateway', 'test-gateway-for-give'),
        // This label will be displayed on donation form in frontend.
        'checkout_label' => __('Test Gateway', 'test-gateway-for-give'),
    );
    return $gateways;
});

/**
 * Show test form
 */
add_action('give_test_gateway_cc_form', function ($form_id, $args) {
    ?>
    <legend><?php _e('Test section', 'test-gateway-for-give'); ?></legend>
    <div id="give-message-wrap" class="form-row form-row-wide">
        <label class="give-label">
            <?php _e('Test label', 'test-gateway-for-give'); ?>
            <?php if (give_field_is_required('test_input', $form_id)) : ?>
                <span class="give-required-indicator">*</span>
            <?php endif ?>
            <span class="give-tooltip give-icon give-icon-question"
                  data-tooltip="<?php _e('Enter something into test input.', 'test-gateway-for-give') ?>">
            </span>
        </label>
        <input type="text" id="test_input" name="test_input" value="">
      </div>
    </div>
    <?php
}, 10, 2);

/**
 * Validate custom fields
 */
add_filter('give_donation_form_required_fields', function ($required_fields, $form_id) {
    $payment_mode = give_get_chosen_gateway($form_id);
    if ('test_gateway' === $payment_mode) {
        $required_fields['test_input'] = array(
            'error_id'      => 'test_input_empty',
            'error_message' => __('Please enter something into test input.', 'test-gateway-for-give'),
        );
    }
    return $required_fields;
}, 10, 2);

/**
 * Process checkout submission. Should not be important.
 */
// add_action('give_gateway_test_gateway', function ($posted_data) {
//
// });
```

**Comment by DevinWalker** [comment]
Closing as this is a development support related question. In short, you need to provide validation requirements for the fields you're adding yourself. We have examples should you need them. Please contact our [Priority Support](https://givewp.com/support) if you need further assistance.
