### ISSUE TITLE
fix: Sequoia form template should not produce console warnings relating to Stripe elements

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#4741]
# Bug Report

## User Story
As a developer, I want the Sequoia form template to be fully compatible with Stripe elements so that it does not produce console warnings or bugs when Stripe credit card is the selected payment gateway.

## Details
The give-stripe.js file causes Stripe elements to load secure inputs into the form when a user selects Stripe credit card as their payment gateway. This action causes a handful of console warnings to be fired and occasionally results in bugs.

## Current Behavior
Stripe elements produces console warnings regarding multiple dom elements with shared IDs and a cross-site cookie issue when the Stripe credit card gateway is selected.

The multiple dom element warnings also point to a solution for a bug whereby Stripe elements would not properly load into credit card fields as expected.

## Expected Behavior
No console warnings should be fired and Stripe elements should consistently load secure fields.

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Enable Stripe credit card payment gateway
2. Activate Sequoia form template
3. Select Stripe payment gateway in checkout
4. Open browser console to view warnings/errors

## Visuals
![Screen Shot 2020-05-15 at 10.53.29 AM.png](https://images.zenhubusercontent.com/5de5476735cbb7ad97ed643a/7afa34ce-13c8-4771-b693-38d687238cc5)

## Acceptance Criteria
- [ ] No console warnings are generated regarding multiple DOM elements with matching IDs
- [ ] No console warnings are generated regarding cross-site cookies
- [ ] Stripe elements consistently loads secure fields

**Comment by ravinderk** [comment]
I notice one more warning related to iframeResize when the iframe form template set to `modal` mode.

![image](https://user-images.githubusercontent.com/1784821/82067693-b0c05900-96ee-11ea-83d7-c15259b04fdc.png)

**Comment by henryholtgeerts** [comment]
There was some difficulty replicating this issue during a slack call. After further testing it seems like we have different scripts that are racing each other, and under certain conditions the inputs are loaded as expected, and under other conditions they are not. 

It'd be great to have a few other devs test this out locally and see if they can reproduce the error in the latest form-templates branch.

**Comment by henryholtgeerts** [comment]
This behavior has not been replicated, and was likely resolved by changes made in the moveFieldsUnderPaymentGateway function as a result of the embedded CC fields styling PR. I'm going to consider the bug resolved and move forward with closing this issue.
