### ISSUE TITLE
Reports page should not crash due to large datasets

### ISSUE THREAD

**Issue by rickalday** [impress-org/givewp#4749]
# Bug Report

## User Story

As a site admin, I want view donation reports without crashing my site.

## Current Behavior

I have a test site with over 15k donation.  When I try to view donations in a selected range, for example, 1st May 2019 - 6th June 2019, the page takes a long time to reload an eventually crashes.

## Expected Behavior

I expect reports to load fast and without crashing the site

## Bug Type

I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. (Must have thousands of donations to test) Go to Donations -> Reports
2. Select a date range, for example 1st May 2019 - 6th June 2019.
3. Site crashes

## Related

https://secure.helpscout.net/conversation/1105966175/59279?folderId=3400524

## Acceptance Criteria

- [ ] Site does not crash when querying donation reports from a selected date range

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X | Microsoft Windows | Linux | Android | iOS</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    
</details>

**Comment by rickalday** [comment]
https://secure.helpscout.net/conversation/1204943152/68615?folderId=672194

**Comment by rickalday** [comment]
The customer posted an update in this ticket: https://secure.helpscout.net/conversation/1204943152/68615/
He switched from Siteground to Kinsta and his issue is gone now.  

He provided new System Info and the plans look similar.   He had more PHP memory in Siteground.

Siteground:
Server Info: Apache
PHP Version: 7.3.18
PHP Post Max Size: 128 MB
PHP Time Limit: 120
PHP Max Input Vars: 3000
PHP Max Upload Size: 128 MB

Kinsta:
Server Info: nginx/1.19.0
PHP Version: 7.3.19-1+ubuntu20.04.1+deb.sury.org+1
PHP Post Max Size: 128 MB
PHP Time Limit: 300
PHP Max Input Vars: 10000
PHP Max Upload Size: 128 MB

**Comment by kevinwhoffman** [comment]
@ravinderk Please look into this urgent issue. The related [Help Scout conversation](https://secure.helpscout.net/conversation/1105966175/59279?folderId=3400524) provides additional context.

**Comment by jonwaldstein** [comment]
@DevinWalker @rickalday sounds like this was specific to the customer's server? Has this ever come up again?

**Comment by DevinWalker** [comment]
That more of a question for @Benunc - I haven't heard any reports of it.

**Comment by jonwaldstein** [comment]
Closing this until another report comes up.
