### ISSUE TITLE
fix: the paypal gateway help text should not affect the legacy template

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#4753]
## Issue Description

The new "How it works" text displaying below PayPal Standard should not be on the legacy template:

![2020-05-18_20-01-07](https://user-images.githubusercontent.com/1571635/82279950-954d8c00-9942-11ea-85e8-d4c8c4ef289c.png)

### Acceptance Criteria

- [x] The PayPal help text only displays within the new form template
- [x] The legacy form template continues to work as expected

**Comment by henryholtgeerts** [comment]
This PR has been tested with Square and Authorize.net gateways, and works as expected.
