### ISSUE TITLE
GiveWP Payment Gateway label strings should all translate with PolyLang.

### ISSUE THREAD

**Issue by Benunc** [impress-org/givewp#4758]
# Bug Report

## User Story

As a user of Give + Polylang, I want all of the payment Gateway labels to translate so that forms can be multilingual.

## Current Behavior
When I install And activate Polylang, it walks me through installing all of the languages, and even though the PO and MO files should be correctly translating the strings for `Offline Donations` and `Credit Card` and `Test Donation`, currently only `Credit Card` is being translated.

## Expected Behavior
I expect all three to be translated.

## Bug Type
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. On a fresh install, install GiveWP and activate it.
1. Add a form, and enable Stripe Credit Card, Test Donations, and Offline Donations. 
2. Do NOT modify the label in the settings.
2. Install Polylang from https://wordpress.org/plugins/polylang/
3. In the wizard for Polylang, select Spanish (es_ES) as the first language, and also select German (de_DE).
4. Finish activation of Polylang.
5. Navigate to the Updates page (`wp-admin/update-core.php`) and ensure that all translation files have been downloaded. 
5. Visit a form on the front end.
6. Only the `Credit Card` string will be translated.

## Possible Solution
I think that the labels are set for Offline, PayPal, and Test donations in https://github.com/impress-org/givewp/blob/075c491391e7dae9f0c26c43ac9e7b8b663a92b1/includes/class-give-cache-setting.php#L232 which does NOT include Credit cards, so that could be the problem here.

## Related
https://secure.helpscout.net/conversation/1170628833/66021?folderId=848135

## Acceptance Criteria
- [ ] All payment gateway labels in the default state are translatable by Polylang.

## Environment
<details>
    <summary>WordPress System Info</summary>
### WordPress Environment ###

Home URL: http://localgive.local
Site URL: http://localgive.local
WP Version: 5.4.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: localgive.local
TLS Connection: ( ! ) Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /Users/steward/Local Sites/localgive/app/public/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php on line 199
Call Stack
#TimeMemoryFunctionLocation
10.0001412840{main}(  ).../edit.php:0
20.0001414088require_once( '/Users/steward/Local Sites/localgive/app/public/wp-admin/admin.php' ).../edit.php:10
30.21706264056do_action(  ).../admin.php:254
40.21706264432WP_Hook->do_action(  ).../plugin.php:478
50.21706264432WP_Hook->apply_filters(  ).../class-wp-hook.php:311
60.21706265560Give_Admin_Settings->output(  ).../class-wp-hook.php:287
70.21796328040include( '/Users/steward/Local Sites/localgive/app/public/wp-content/plugins/give/includes/admin/views/html-admin-settings.php' ).../class-admin-settings.php:264
80.21836331328do_action(  ).../html-admin-settings.php:128
90.21836331704WP_Hook->do_action(  ).../plugin.php:478
100.21836331704WP_Hook->apply_filters(  ).../class-wp-hook.php:311
110.21836332832Give_Settings_System_Info->output(  ).../class-wp-hook.php:287
120.22056342432include_once( '/Users/steward/Local Sites/localgive/app/public/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php' ).../class-settings-system-info.php:56
130.48246426120file_get_contents
(  ).../html-admin-page-system-info.php:199

( ! ) Warning: file_get_contents(): Failed to enable crypto in /Users/steward/Local Sites/localgive/app/public/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php on line 199
Call Stack
#TimeMemoryFunctionLocation
10.0001412840{main}(  ).../edit.php:0
20.0001414088require_once( '/Users/steward/Local Sites/localgive/app/public/wp-admin/admin.php' ).../edit.php:10
30.21706264056do_action(  ).../admin.php:254
40.21706264432WP_Hook->do_action(  ).../plugin.php:478
50.21706264432WP_Hook->apply_filters(  ).../class-wp-hook.php:311
60.21706265560Give_Admin_Settings->output(  ).../class-wp-hook.php:287
70.21796328040include( '/Users/steward/Local Sites/localgive/app/public/wp-content/plugins/give/includes/admin/views/html-admin-settings.php' ).../class-admin-settings.php:264
80.21836331328do_action(  ).../html-admin-settings.php:128
90.21836331704WP_Hook->do_action(  ).../plugin.php:478
100.21836331704WP_Hook->apply_filters(  ).../class-wp-hook.php:311
110.21836332832Give_Settings_System_Info->output(  ).../class-wp-hook.php:287
120.22056342432include_once( '/Users/steward/Local Sites/localgive/app/public/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php' ).../class-settings-system-info.php:56
130.48246426120file_get_contents
(  ).../html-admin-page-system-info.php:199

( ! ) Warning: file_get_contents(https://www.howsmyssl.com/a/check): failed to open stream: operation failed in /Users/steward/Local Sites/localgive/app/public/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php on line 199
Call Stack
#TimeMemoryFunctionLocation
10.0001412840{main}(  ).../edit.php:0
20.0001414088require_once( '/Users/steward/Local Sites/localgive/app/public/wp-admin/admin.php' ).../edit.php:10
30.21706264056do_action(  ).../admin.php:254
40.21706264432WP_Hook->do_action(  ).../plugin.php:478
50.21706264432WP_Hook->apply_filters(  ).../class-wp-hook.php:311
60.21706265560Give_Admin_Settings->output(  ).../class-wp-hook.php:287
70.21796328040include( '/Users/steward/Local Sites/localgive/app/public/wp-content/plugins/give/includes/admin/views/html-admin-settings.php' ).../class-admin-settings.php:264
80.21836331328do_action(  ).../html-admin-settings.php:128
90.21836331704WP_Hook->do_action(  ).../plugin.php:478
100.21836331704WP_Hook->apply_filters(  ).../class-wp-hook.php:311
110.21836332832Give_Settings_System_Info->output(  ).../class-wp-hook.php:287
120.22056342432include_once( '/Users/steward/Local Sites/localgive/app/public/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php' ).../class-settings-system-info.php:56
130.48246426120file_get_contents
(  ).../html-admin-page-system-info.php:199
: 
: 
: 
1: 412840
2: 414088
3: 6264056
4: 6264432
5: 6264432
6: 6265560
7: 6328040
8: 6331328
9: 6331704
10: 6331704
11: 6332832
12: 6342432
13: 6426120
: 
: 
: 
1: 412840
2: 414088
3: 6264056
4: 6264432
5: 6264432
6: 6265560
7: 6328040
8: 6331328
9: 6331704
10: 6331704
11: 6332832
12: 6342432
13: 6426120
: 
: 
: 
1: 412840
2: 414088
3: 6264056
4: 6264432
5: 6264432
6: 6265560
7: 6328040
8: 6331328
9: 6331704
10: 6331704
11: 6332832
12: 6342432
13: 6426120
TLS Connection: 
Server Info: nginx/1.16.0
PHP Version: 7.3.5
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
PHP Max Upload Size: 300 MB
cURL Version: 7.54.0, LibreSSL/2.6.5
SUHOSIN Installed: –
MySQL Version: 5.7.28
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
: 
: 
: 
1: 412840
2: 414088
3: 6264056
4: 6264432
5: 6264432
6: 6265560
7: 6328040
8: 6331328
9: 6331704
10: 6331704
11: 6332832
12: 6342432
13: 6426120
: 
: 
: 
1: 412840
2: 414088
3: 6264056
4: 6264432
5: 6264432
6: 6265560
7: 6328040
8: 6331328
9: 6331704
10: 6331704
11: 6332832
12: 6342432
13: 6426120
: 
: 
: 
1: 412840
2: 414088
3: 6264056
4: 6264432
5: 6264432
6: 6265560
7: 6328040
8: 6331328
9: 6331704
10: 6331704
11: 6332832
12: 6342432
13: 6426120

### GiveWP Configuration ###

GiveWP Version: 2.6.3
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access
Upgraded From: 2.6.2
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://localgive.local/donation-confirmation/
Failure Page: http://localgive.local/donation-failed/
Donation History Page: http://localgive.local/donation-history/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation, Stripe - Credit Card, Stripe + Plaid, Stripe - Checkout, PayPal Standard
Default Payment Gateway: Stripe + Plaid
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: N/A

### Active GiveWP Add-ons ###

Give - Stripe Gateway: ✔ Licensed – by GiveWP – 2.2.5

### Other Active Plugins ###

Disable Gutenberg: by Jeff Starr – 2.1
Polylang: by WP SYNTEX – 2.7.2

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.1.5
Give - Currency Switcher: by GiveWP – 1.3.7
Hello Dolly: by Matt Mullenweg – 1.7.2

### Active MU Plugins ###

helpers.php: by  –

### Theme ###

Name: Twenty Twenty
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
</details>

**Comment by ravinderk** [comment]
@Benunc is it duplicate of this: https://github.com/impress-org/givewp/issues/4319

**Comment by Benunc** [comment]
per discussion re: 1-star review context, we're going to take a closer look at this for a patch.
