### ISSUE TITLE
Free add-ons should not trigger GiveWP add-on license errors.

### ISSUE THREAD

**Issue by Benunc** [impress-org/givewp#4760]
# Bug Report

## User Story

As a free add-on user, I want those free "official" add-ons to not trigger license warnings so that I'm not confused about license keys that don't exist.

## Current Behavior
The license handler uses the plugin author name of "GiveWP" to determine that a license key is needed. That means that all of these plugins will create an error: https://profiles.wordpress.org/givewp/#content-plugins

It only happens if you DON'T have a plan license, as of 2.6.3, but if you have individual add-on licenses, there will be an error that indicates you need to input the license key, but that license key does not exist.

## Expected Behavior
I expect only add-ons that have a license key to ask for one.

## Bug Type
- [x] This bug describes functionality that never worked as expected.

## Steps to Reproduce
1. Fresh install, no plan license activated.
2. Install and activate GiveWP and https://wordpress.org/plugins/give-receipt-attachments/
3. Navigate to a different page. (It may require a few hours or days before that nag hits you)
4. Navigate to the licenses tab of the settings page.
5. It will be asking for a license. 

## Visuals
![Screen Shot 2020-05-20 at 3 19 24 PM](https://user-images.githubusercontent.com/9629102/82488067-4f610700-9aad-11ea-82c7-8bda9eedece3.png)

## Possible Solution
Either change the author name of the add-ons, or change how our license handler looks for add-ons that need license keys.

## Related
https://secure.helpscout.net/conversation/1171220937/66065?folderId=672199

## Acceptance Criteria
- [x] Add-ons that are free never trigger license warnings/errors.
- [x] Add-ons that are Premium always do trigger warnings/errors when they need attention, after the fix is applied here.

**Comment by ravinderk** [comment]
As per the temporary solution point `Plugin URI` to other then `givewp.com` for free addons will fix the issue.

Discussion: https://givewp.slack.com/archives/C0FAGC83C/p1590002550022800

**Comment by mathetos** [comment]
I think it would be worth looking into how WooCommerce does this. Essentially, it looks like they have unique IDs for each download they offer, and they add those into the header of the plugin like this:

`Woo: 12345:342928dfsfhsf8429842374wdf4234sfd`

See their docs on this here:
https://docs.woocommerce.com/document/create-a-plugin/#section-12

For now, I'm using the shortlinks and I believe it is resolving the issue even though the shortlink is `go.givewp.com/free-addon`

**Comment by ravinderk** [comment]
I am reopening this issue. after discussion with the team, we decided to use to easy digital download to get a list of premium addons: https://givewp.slack.com/archives/C0FAGC83C/p1604084281178900
