### ISSUE TITLE
The CSV Export should report all custom amounts as what they are

### ISSUE THREAD

**Issue by jurassicdanie** [impress-org/givewp#4765]
# Bug Report

## User Story

As a user, I want to export a CSV and have custom donation amounts show as what the amount donated was.

## Details
Currently, when you export a CSV, it will only put the word "custom" for all custom amounts, and it won't show what that amount actually was.

## Current Behavior
The CSV export currently puts the word "custom" for all custom donation amounts but doesn't show what the amount actually was. For all fixed amounts, it actually shows what they are.

## Expected Behavior
The CSV export should show all custom amounts the same way it shows the fixed amounts - as the actual number.

## Bug Type
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Go into Tools -> Export -> Generate CSV 
2. Select all checkboxes and start the export
3. Download CSV and view the amount field where you will see the word custom for any custom amounts

## Visuals
https://givewp.com/index.php?gf-download=2020%2F05%2FScreen-Shot-2020-05-19-at-1.51.00-PM.png&form-id=2&field-id=21&hash=ad9163ba67be44831b9370111f4b4982b9cdd1b63778c9ff8edbdcee0b9abb46

## Related
Support ticket link: https://secure.helpscout.net/conversation/1170413352/65999?folderId=3805719

## Acceptance Criteria
- [ ] e.g. Something happens when an action is taken.

## Environment
This happens in multiple browsers, computer OS's, and accounts, and websites with different setups.

**Comment by Benunc** [comment]
The customer and Danielle did not understand that "Donation Total" is the column they are looking for. Closing this.
