### ISSUE TITLE
Bundled TCPDF does not work well with PHP 7.4

### ISSUE THREAD

**Issue by flack** [impress-org/givewp#4772]
# Bug Report

## User Story

As a user, I want to generate PDF receipts (with the PDF plugin)

## Current Behavior

When I try to create a PDF, I get the following errors: 

![Screenshot_20200526_114622](https://user-images.githubusercontent.com/425166/83003196-453f8b00-a00e-11ea-95e8-0aff06a29655.png)

## Expected Behavior

It should work without warnings/notices etc.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [x] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Install PDF plugin (on a server running PHP 7.4)
2. try to download a PDF

## Possible Solution

The current TCPDF release (6.3.5) works fine with PHP 7.4. The current Give release seems to include TCPDF 6.2.26, so a simple dependency update should resolve this

## Acceptance Criteria

- [ ] e.g. Something happens when an action is taken.
- [x] e.g. Something does not happen when an action is taken.
- [ ] e.g. Fixing behavior in Component A does not affect existing behavior in Component B.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Linux</li>
        <li>Version: Ubuntu 20.04</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: irrelevant</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
irrelevant
    
</details>

**Comment by DevinWalker** [comment]
Hey @flack we've updated the version in the upcoming release `2.7.0`. You can see here in the branch that composer is now using the latest `6.3`+ version: https://github.com/impress-org/givewp/blob/release/2.7.0/composer.json#L9

We'll hopefully get this out within the next few weeks! Thanks for stopping by. :)
