### ISSUE TITLE
fix: Sequoia form template amount input should match Figma designs

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#4782]
# Bug Report

## User Story
As a user, I want the Sequoia form template amount input box to match existing Figma designs so that I have a cohesive, clean donation experience.

## Current Behavior
The donation amount input is largely styled correctly, and already matches the Figma boards pretty closely. However, certain elements should be polished to be as close as possible. 

## Expected Behavior
The amount input should include the small divider line between currency and amount (as seen in the Figma boards), and and match padding/spacing exactly. These changes will make the input feel more polished, balanced and interesting to users. 

## Bug Type
- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [x] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Visuals
See Figma: https://www.figma.com/file/jaVXDA4wjQD9OqTi0l9KQe/Form-Templates?node-id=1882%3A44&viewport=-259%2C1586%2C0.5

![Screen Shot 2020-06-01 at 1.07.38 PM.png](https://images.zenhubusercontent.com/5de5476735cbb7ad97ed643a/fe1dab03-07fb-48f8-8289-be02bae8036e)

## Possible Solution
Add a styled border to the existing currency div. This should be responsive to different classes regarding currency placement (eg if the symbol appears after the amount, the border should appear on the symbol's left).

## Acceptance Criteria
- [ ] Dividing line exists between currency symbol and amount
- [ ] Input font sizes/styles match Figma design
- [ ] Spacing matches Figma design
- [ ] Input is responsive to changes in currency symbol placement

**Comment by DevinWalker** [comment]
This was resolved in: https://github.com/impress-org/givewp/pull/4790
