### ISSUE TITLE
donor can not access old donation receipt when authenticate by email on pantheon server

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#4797]
# Bug Report

## User Story

As a donor, I want to access the donation receipt after authenticating by email address.

## Details

I was able to reproduce this issue on the pantheon server. we fixed a similar issue in the past by loading receipt on ajax because few hosts like WPEngine allow accessing cookies on ajax request. Pantheon does not allow us to access a cookie on Ajax request that why we can not access the donation receipt from the donation history page after authenticating by email address.

ref: https://github.com/impress-org/givewp/issues/3819

## Current Behavior

Donor is not able to access the donation receipt.

## Expected Behavior

The allow donor to access the donation receipt after authenticating by email address.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Create a dev site on  Pantheon server
2. Pay a few donations as guest donors.
3. Request access token from the history donation page.
4. After the email login tries to access receipt from the history page.

## Possible Solution

Rename `give_nl` cookie name to `wp-give_nl` because pantheon allow to access cookies which prefixed with `wp-`.

## Acceptance Criteria

- [ ] Donor can access receipt on Pantheon server after authenticating by email address.

**Comment by jonwaldstein** [comment]
I can't find any recent reports of issues with pantheon specifically.  Closing this until another report comes up.
