### ISSUE TITLE
feat: Allow donors to edit their address via the [give_profile_editor] shortcode

### ISSUE THREAD

**Issue by rickalday** [impress-org/givewp#4798]
# Feature Request

## User Story

As a donor, I want to be able to update all my personal info.

## Details

Currently, it's not possible for donors to update their address info without login into the backend.

## Related

https://secure.helpscout.net/conversation/1192676903/67719/

## Acceptance Criteria

- [ ] Donors to edit their address via the [give_profile_editor] shortcode

**Comment by jonwaldstein** [comment]
@rickalday @Benunc would you say this is not relevant anymore since we have a full featured Donor Dashboard block?

If that's the case we should encourage people to use the donor dashboard in our docs instead of this shortcode.

**Comment by jonwaldstein** [comment]
Closing this in favor of the Donor Dashboard which has the ability to edit addresses.
