### ISSUE TITLE
GiveWP plugin should work with Sensei with WooCommerce Paid Courses

### ISSUE THREAD

**Issue by matheuswd** [impress-org/givewp#4802]
# Bug Report

## User Story

As a site owner, I want to use Sensei Paid Courses by Woocommerce and GiveWP in the same WordPress install.

## Current Behavior

When I activate the Sensei Paid Courses by Woocommerce plugin, all my donations are marked as $0 and the form titles are marked as _undefined_.

## Expected Behavior

When I activate Sensei Paid Courses by Woocommerce I must be able to check the donation value and form titles under Donations > Donations, Donations > Reports, Donations > All Forms.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Add Sensei Paid Courses by Woocommerce to a WordPress install with GiveWP set up and with donations
2. Activate Sensei Paid Courses by Woocommerce
3. Check Donations > Donations, Donations > Reports, Donations > All Forms

## Visuals

Screencast
http://somup.com/cY1bDJQZVD

![Screen Shot 2020-06-16 at 21 37 06](https://user-images.githubusercontent.com/11727852/84825579-888f8700-b019-11ea-9b86-4c4996f639d1.png)
![Screen Shot 2020-06-16 at 21 37 30](https://user-images.githubusercontent.com/11727852/84825638-a0670b00-b019-11ea-9f18-712c542583c7.png)
![Screen Shot 2020-06-16 at 21 38 11](https://user-images.githubusercontent.com/11727852/84825713-c42a5100-b019-11ea-97c0-17768e4baa13.png)

## Related

https://secure.helpscout.net/conversation/1194723923/67832?folderId=3863238
https://github.com/impress-org/givewp/issues/2710

**You can find the Sensei Paid Courses by Woocommerce zip file in the Slack message for this issue**

## Acceptance Criteria

- [ ] Reports should return the values when Sensei Paid Courses by Woocommerce is active
- [ ] Donations should return the values when Sensei Paid Courses by Woocommerce is active
- [ ] All Form should display the correct amount, Goal, Donations and Income

### WordPress Environment ###

Home URL: http://wc-sensei-and-give.test
Site URL: http://wc-sensei-and-give.test
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, wc-pending, wc-processing, wc-on-hold, wc-completed, wc-cancelled, wc-refunded, wc-failed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: wc-sensei-and-give.test
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.16.0
PHP Version: 7.3.5
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
PHP Max Upload Size: 300 MB
cURL Version: 7.54.0, LibreSSL/2.6.5
SUHOSIN Installed: –
MySQL Version: 8.0.16
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.6.3
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://wc-sensei-and-give.test/donation-confirmation/
Failure Page: http://wc-sensei-and-give.test/donation-failed/
Donation History Page: http://wc-sensei-and-give.test/donation-history/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: N/A

### Other Active Plugins ###

Debug Bar: by wordpressdotorg – 1.0.1
Query Monitor: by John Blackbourn – 3.6.0
Sensei with WooCommerce Paid Courses: by Automattic – 3.0.1.2.0.1
WooCommerce: by Automattic – 4.2.0
WP Debugging: by Andy Fragen – 2.7.2

### Theme ###

Name: Twenty Twenty
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

**Comment by Benunc** [comment]
Potentially related (here's the issue I was looking for on my call with you, @matheuswd ) https://github.com/impress-org/givewp/issues/2710

**Comment by DevinWalker** [comment]
In order to reproduce this we'll need a copy of: https://woocommerce.com/products/woocommerce-paid-courses/ 
​
​I don't see a zip of that provided in Github, Help Scout, or in Slack anywhere. Please provide so we can take a look at it.

**Comment by DevinWalker** [comment]
I've moved this into Canny for prioritization: https://givewp.canny.io/bug-reports/p/fix-compatibility-with-sensei-paid-courses
