### ISSUE TITLE
Currency Switcher does not work in the new form template.

### ISSUE THREAD

**Issue by rickalday** [impress-org/givewp#4829]
# Bug Report

## User Story
The currency selector does not show any other options:
<img width="579" alt="Screen Shot 2020-06-18 at 12 26 25 PM" src="https://user-images.githubusercontent.com/312000/85052715-0d37ed80-b15f-11ea-8588-924bd70cf6d8.png">

There are no errors in the console.  If I switch to the legacy template then it works.

**Comment by jonwaldstein** [comment]
This seems to have been resolved here https://github.com/impress-org/give-currency-switcher/pull/278
