### ISSUE TITLE
FFM upload field throws js error in new template.

### ISSUE THREAD

**Issue by rickalday** [impress-org/givewp#4830]
# Bug Report

## User Story
If a form has an FFM upload field and is using the new form template, this JS error pops up in the console:
<img width="896" alt="Screen Shot 2020-06-18 at 12 40 34 PM" src="https://user-images.githubusercontent.com/312000/85054169-48d3b700-b161-11ea-9f20-2219c05714bd.png">

## Steps to reproduce
1. Install GiveWP 2.7.0
2. Create a new form or edit an existing form using the new form template.
3. Add an Upload FFM field to the form.
4. Visit form on the frontend and check browser console.

**Comment by ravinderk** [comment]
Merge pr reverted: https://github.com/impress-org/givewp/compare/918687a09f37...fa98c614b615

I find out that this issue only occurs when we output `give-ffm-frontend.min.js` file of form field manage addon. As you can see we are not adding `plupload-handlers` as a dependency file which causes an issue. I moved this issue to FFM to fix it in the right way.

![image](https://user-images.githubusercontent.com/1784821/85069787-507f7400-b1d2-11ea-856c-df20720d3d0c.png)

**Comment by ravinderk** [comment]
Issue moved to [impress-org/give-form-field-manager #318](https://github.com/impress-org/give-form-field-manager/issues/318) via [**ZenHub**](https://www.zenhub.com/)
