### ISSUE TITLE
2.7.0 Inline docs should be improved

### ISSUE THREAD

**Issue by Benunc** [impress-org/givewp#4832]
This issue is a placeholder to begin the work of making changes across much of the 2.7.0 interface. 

I will submit a PR to this with the changes.

### Acceptance Criteria
- [ ] There is no first person language in inline docs
- [ ] There are no typos in inline docs
- [ ] The inline documentation uses as few words as necessary to convey the point
- [ ] The inline docs are in our brand voice

**Comment by DevinWalker** [comment]
2.7.0 is getting released, hence closing this issue. @Benunc I'd love for you to continue your inline docs auditing in a new issue.
