### ISSUE TITLE
Form with custom content loads all page content when embedded in an Elementor Page

### ISSUE THREAD

**Issue by rickalday** [impress-org/givewp#4835]
# Bug Report

## User Story
Using a Give form with custom content within an Elementor page causes the whole page content to be loaded within the Give plugin content output.

I was able to reproduce this in a copy of our demo site.

## Visuals
Video provided by the user: https://www.dropbox.com/s/nx0uikpn6goe2m3/give%20bug.mov?dl=0

## Related:
https://wordpress.org/support/topic/elementor-bug-with-the-custom-content-2/

**Comment by DevinWalker** [comment]
This is a classic case of `the_content` filter setting being enabled. To fix this disable the setting:

![2020-06-18_18-29-34](https://user-images.githubusercontent.com/1571635/85087218-bd264e80-b191-11ea-9974-d5655129e207.png)

**Comment by qantumthemes** [comment]
After so many years of recommending this plugin, I am truly astonished not only by the quality but also from the speed of the developers. Will for sure include it as recommended for our next big theme!
