### ISSUE TITLE
New installs should load the 2.7.0 new theme in the widgets properly

### ISSUE THREAD

**Issue by jurassicdanie** [impress-org/givewp#4841]
# Bug Report

## User Story

As a user, I want to spin up a new site with GiveWP 2.7.0 and add a form to my widgets with the new template set up.

## Details
Currently, when you attempt to add the widget as described above, the widget form settings just loads and loads.

## Current Behavior
If you add the widget with the new form template, it doesn't ever load, it just gets stuck on loading settings. 

Console Errors:

JQMIGRATE: Migrate is installed, version 1.4.1
wp-polyfill.min.js:1 @babel/polyfill is loaded more than once on this page. This is probably not desirable/intended and may have consequences if different versions of the polyfills are applied sequentially. If you do need to load the polyfill more than once, use @babel/polyfill/noConflict instead to bypass the warning.
1.15 @ wp-polyfill.min.js:1
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
jquery-migrate.min.js?ver=1.4.1:2 JQMIGRATE: Migrate is installed, version 1.4.1
wp-polyfill.min.js?ver=7.4.4:1 @babel/polyfill is loaded more than once on this page. This is probably not desirable/intended and may have consequences if different versions of the polyfills are applied sequentially. If you do need to load the polyfill more than once, use @babel/polyfill/noConflict instead to bypass the warning.
1.15 @ wp-polyfill.min.js?ver=7.4.4:1
jquery-migrate.min.js?ver=1.4.1:2 JQMIGRATE: Migrate is installed, version 1.4.1
admin-widgets.min.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)

## Expected Behavior
I should be able to spin up a new website and install GiveWP 2.7.0 version on it, while using the new form template, and add a widget to my site succesfully

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [x ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Spin up a fresh WP local WP site
2. Install 2.7 + the sample-data CSV
3. Create a new form
4. Go to customize (2020 theme)
5. Go to Widgets
6. Select Footer #1
7. Click "add a widget"
8. Select the GiveWP-Donation Form.
The settings seem to never load.

## Visuals
![image](https://user-images.githubusercontent.com/63911898/85150521-a24eeb00-b220-11ea-82c2-e6e0ad656ed0.png)

## Acceptance Criteria
Have the widget settings load successfully, so the set up of the donation form on the widget area loads correctly.

### WordPress Environment ###

Home URL: http://givetest.local
Site URL: http://givetest.local
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: givetest.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.16.0
PHP Version: 7.3.5
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
PHP Max Upload Size: 300 MB
cURL Version: 7.64.0, OpenSSL/1.1.1b
SUHOSIN Installed: –
MySQL Version: 8.0.16
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.7.0
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access
Upgraded From: 2.7.0
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://givetest.local/donation-confirmation/
Failure Page: http://givetest.local/donation-failed/
Donation History Page: http://givetest.local/donation-history/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation, Stripe - Credit Card
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: N/A

### Inactive Plugins ###

Give - Donation Plugin: by GiveWP – 2.7.0

### Theme ###

Name: Twenty Twenty
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

**Comment by henryholtgeerts** [comment]
Was able to to replicate this issue, it also appears on the Widgets page (outside of the Customizer). 

JS errors on widgets page:
<img width="614" alt="Screen Shot 2020-06-19 at 8 39 58 AM" src="https://user-images.githubusercontent.com/5186078/85151544-c1418300-b208-11ea-9950-968d72fc84d2.png">

JS errors in customizer:
<img width="616" alt="Screen Shot 2020-06-19 at 8 40 48 AM" src="https://user-images.githubusercontent.com/5186078/85151569-ca325480-b208-11ea-8845-9da0b8786db9.png">

Likely some issue with the script not being enqueued correctly. I'm assigning this issue to myself, and I'll take a look at it this morning!

**Comment by henryholtgeerts** [comment]
After investigating, it looks like the suffix logic in this function is causing the issue:
<img width="1125" alt="Screen Shot 2020-06-19 at 8 56 43 AM" src="https://user-images.githubusercontent.com/5186078/85153383-01a20080-b20b-11ea-8dc3-d5baf8f021ef.png">

The script is being enqueued as "admin-widgets.min.js" and "admin-widget.min.css", despite the fact that webpack is not producing any minified assets (causing the 404 errors). If you look at the assets directory, you can see that even when in production mode, no minified assets are produced. 

We can either configure webpack to support minification (see: https://webpack.js.org/plugins/uglifyjs-webpack-plugin/) or remove the suffix logic while enqueue the script. 

@ravinderk @JasonTheAdams Care to share your thoughts on this?

**Comment by henryholtgeerts** [comment]
Looking into Webpack documentation, it looks like webpack should be performing some basic optimizations (including minifaction) by default - as long as mode is set to 'production'. See: https://webpack.js.org/guides/production/#minification

The problem we are facing may be a result of not properly defining module in the module exports of our config object. Docs on production mode: https://webpack.js.org/configuration/mode/#mode-production

**Comment by ravinderk** [comment]
@henryholtgeerts By researching over code base I discover that we stop using `.min.js` terminology to prevent plugin weight and we do not want to ship duplicate code in two different files. That means `[name].js` will be compressed/minified in production mode .

I will update the widget script and style file name to resolve the issue.
