### ISSUE TITLE
The add-ons tab of the welcome screen should link to something correctly

### ISSUE THREAD

**Issue by matheuswd** [impress-org/givewp#4843]
# Bug Report

Reference: https://github.com/impress-org/givewp/issues/4746

## User Story

As a brand new GiveWP user, I want to click on the add-ons page of the welcome screen and be taken somewhere useful, preferably to somewhere where I can buy add-ons.

## Current Behavior

The add-ons tab of the welcome screen at .../wp-admin/?page=give-getting-started sends to .../wp-admin/edit.php?post_type=give_forms&page=give-addons which is not a correct link.

## Expected Behavior

I expect to be taken to a page where I can research and buy add-ons or plans.

## Bug Type

- [ ] This bug describes functionality that once worked as expected in version X.X.X.
- [ ] This bug describes functionality that never worked as expected.
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Navigate to .../wp-admin/?page=give-getting-started
2. Click the add-ons link (see screenshot below)
3. Errors.

## Visuals

![image](https://user-images.githubusercontent.com/11727852/85159282-3470e680-b255-11ea-9774-a54e705e3264.png)
<img width="643" alt="Screen Shot 2020-06-19 at 17 49 35" src="https://user-images.githubusercontent.com/11727852/85159319-3f2b7b80-b255-11ea-82ed-fa3d3966c465.png">

## Possible Solution

Make the link to to https://go.givewp.com/addons-menu-link or similar.
## Acceptance Criteria

- [ ]  the link goes somewhere actionable.

## Environment

```
### WordPress Environment ###

Home URL: http://demo.matheuswd.com.br
Site URL: http://demo.matheuswd.com.br
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: demo.matheuswd.com.br
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.3
PHP Version: 5.6.35-1+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
PHP Max Upload Size: 100 MB
cURL Version: 7.47.0, OpenSSL/1.0.2g
SUHOSIN Installed: –
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.7.0
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://demo.matheuswd.com.br/donation-confirmation/
Failure Page: http://demo.matheuswd.com.br/donation-failed/
Donation History Page: http://demo.matheuswd.com.br/donation-history/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation, Stripe - Credit Card
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: N/A

### Active GiveWP Add-ons ###


### Other Active Plugins ###


### Inactive Plugins ###


### Theme ###

Name: Twenty Twenty
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme
```

**Comment by ravinderk** [comment]
@DevinWalker @mathetos This has been already fixed but I do not know how this reappear: https://github.com/impress-org/givewp/issues/4746

**Comment by ravinderk** [comment]
Fixed: https://github.com/impress-org/givewp/compare/0b54cd168783...7979547d4d0e
