### ISSUE TITLE
In 2.7 the test gateway displays "Test GiveWP with the Test Gateway" text incorrectly

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#4860]
# Bug Report

This text should only appear on the new donation form template. Currently it's displaying by default if the gateway is set as the default on page load. When you switch to another gateway and back again it's removed.

![2020-06-24_08-50-09](https://user-images.githubusercontent.com/1571635/85588827-e57dd500-b5f7-11ea-9870-d493c8b8fd90.png)

## Steps to Reproduce

1. Make the Test Gateway the default in Settings
2. Add a legacy donation form to a page
3. View in the block or on the frontend and you'll see what's in the screenshot above

**Comment by henryholtgeerts** [comment]
Was able to resolve quickly with this hotfix commit: https://github.com/impress-org/givewp/commit/b7f649029cfe91884c4778aa8122b38871b977b9

Essentially, the function was not being passed the form ID, which it needed to determine if the form was a legacy form.

This fix resolves this issue both in the test donation gateway and the Stripe standard gateway.
