### ISSUE TITLE
Template selector in 2.7 should be more responsive

### ISSUE THREAD

**Issue by Benunc** [impress-org/givewp#4861]
# Bug Report

## User Story

As a user, I want words to wrap when on a smaller screen, not overlap.

## Current Behavior
On smaller screen widths, the words get all jumbled together. 

![Screen Shot 2020-06-24 at 1 30 33 PM](https://user-images.githubusercontent.com/9629102/85604224-18878f00-b61f-11ea-9d17-aff60118df88.png)

## Expected Behavior
I expect the words to split to multiple lines.

## Bug Type

- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. On a site with 2.7.0 active, create a new form.
2. resize the browser window until you see the words overlap.

## Acceptance Criteria
- [ ] all words displayed on the screen are legible.
- [ ] On smaller screens, the words wrap to a new line.

**Comment by henryholtgeerts** [comment]
This issue has been resolved in a hotfix commit: https://github.com/impress-org/givewp/commit/d040b6b4c88fab6506a8370f5a14f334f3425982

The issue was resolved by improve the .template-name style rules to use line-height 1.4, enabling the text to stack on smaller screens.
