### ISSUE TITLE
Sites without Donation Confirmation page configured should not prevent Stripe donations.

### ISSUE THREAD

**Issue by Benunc** [impress-org/givewp#4862]
# Bug Report

## User Story

As a user, I want a few things: I want Stripe donations to still go through if I have not configured a donation confirmation page, but I also want to be alerted if no confirmation page is set in the settings. Finally, If the cause of an issue is that a page is not set as donation confirmation page, I want the error message to say the more explicitly.

## Current Behavior
If a Donation Confirmation page is not set in the settings at Donations > Settings > General, Stripe donations fail with this error on the front end: 

![Screen Shot 2020-06-24 at 1 45 04 PM](https://user-images.githubusercontent.com/9629102/85606272-fe4eb080-b620-11ea-9b0b-5cb62e771f15.png)

And this in the logs: 
```
Unable to create a payment intent. Details: Invalid URL: An explicit scheme (such as https) must be provided.
```
I'm not sure the effect on the new multistep form template, but I'm still not seeing a successful donation there either, just no error in the logs.

## Expected Behavior
I expect to be alerted when donation confirmation page is not set up, and for error messages to be less cryptic.

## Bug Type
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Delete the Donation Confirmation page completely. (moving it to trash does not produce the error)
2. On a legacy form, attempt to submit a Stripe - Credit Card donation.

## Related
https://secure.helpscout.net/conversation/1197094611/68044?folderId=672197

## Acceptance Criteria
- [ ] Donations go through to Stripe even without a donation confirmation page set up.
- [ ] If the page is not set up, there's a persistent admin alert.
- [ ] The fix here does not affect the new Form Template.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X | Microsoft Windows | Linux | Android | iOS</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    ### WordPress Environment ###

Home URL: http://twoseven.local
Site URL: http://twoseven.local
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: twoseven.local
TLS Connection: ( ! ) Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /Users/steward/Local Sites/twoseven/app/public/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php on line 199
Call Stack
#TimeMemoryFunctionLocation
10.0001413656{main}(  ).../edit.php:0
20.0001414904require_once( '/Users/steward/Local Sites/twoseven/app/public/wp-admin/admin.php' ).../edit.php:10
30.16255254056do_action(  ).../admin.php:254
40.16255254432WP_Hook->do_action(  ).../plugin.php:478
50.16255254432WP_Hook->apply_filters(  ).../class-wp-hook.php:311
60.16255255560Give_Admin_Settings->output(  ).../class-wp-hook.php:287
70.16325312392include( '/Users/steward/Local Sites/twoseven/app/public/wp-content/plugins/give/includes/admin/views/html-admin-settings.php' ).../class-admin-settings.php:264
80.16355315680do_action(  ).../html-admin-settings.php:128
90.16355316056WP_Hook->do_action(  ).../plugin.php:478
100.16355316056WP_Hook->apply_filters(  ).../class-wp-hook.php:311
110.16355317184Give_Settings_System_Info->output(  ).../class-wp-hook.php:287
120.16665328064include_once( '/Users/steward/Local Sites/twoseven/app/public/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php' ).../class-settings-system-info.php:56
130.23845410280file_get_contents
(  ).../html-admin-page-system-info.php:199

( ! ) Warning: file_get_contents(): Failed to enable crypto in /Users/steward/Local Sites/twoseven/app/public/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php on line 199
Call Stack
#TimeMemoryFunctionLocation
10.0001413656{main}(  ).../edit.php:0
20.0001414904require_once( '/Users/steward/Local Sites/twoseven/app/public/wp-admin/admin.php' ).../edit.php:10
30.16255254056do_action(  ).../admin.php:254
40.16255254432WP_Hook->do_action(  ).../plugin.php:478
50.16255254432WP_Hook->apply_filters(  ).../class-wp-hook.php:311
60.16255255560Give_Admin_Settings->output(  ).../class-wp-hook.php:287
70.16325312392include( '/Users/steward/Local Sites/twoseven/app/public/wp-content/plugins/give/includes/admin/views/html-admin-settings.php' ).../class-admin-settings.php:264
80.16355315680do_action(  ).../html-admin-settings.php:128
90.16355316056WP_Hook->do_action(  ).../plugin.php:478
100.16355316056WP_Hook->apply_filters(  ).../class-wp-hook.php:311
110.16355317184Give_Settings_System_Info->output(  ).../class-wp-hook.php:287
120.16665328064include_once( '/Users/steward/Local Sites/twoseven/app/public/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php' ).../class-settings-system-info.php:56
130.23845410280file_get_contents
(  ).../html-admin-page-system-info.php:199

( ! ) Warning: file_get_contents(https://www.howsmyssl.com/a/check): failed to open stream: operation failed in /Users/steward/Local Sites/twoseven/app/public/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php on line 199
Call Stack
#TimeMemoryFunctionLocation
10.0001413656{main}(  ).../edit.php:0
20.0001414904require_once( '/Users/steward/Local Sites/twoseven/app/public/wp-admin/admin.php' ).../edit.php:10
30.16255254056do_action(  ).../admin.php:254
40.16255254432WP_Hook->do_action(  ).../plugin.php:478
50.16255254432WP_Hook->apply_filters(  ).../class-wp-hook.php:311
60.16255255560Give_Admin_Settings->output(  ).../class-wp-hook.php:287
70.16325312392include( '/Users/steward/Local Sites/twoseven/app/public/wp-content/plugins/give/includes/admin/views/html-admin-settings.php' ).../class-admin-settings.php:264
80.16355315680do_action(  ).../html-admin-settings.php:128
90.16355316056WP_Hook->do_action(  ).../plugin.php:478
100.16355316056WP_Hook->apply_filters(  ).../class-wp-hook.php:311
110.16355317184Give_Settings_System_Info->output(  ).../class-wp-hook.php:287
120.16665328064include_once( '/Users/steward/Local Sites/twoseven/app/public/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php' ).../class-settings-system-info.php:56
130.23845410280file_get_contents
(  ).../html-admin-page-system-info.php:199
: 
: 
: 
1: 413656
2: 414904
3: 5254056
4: 5254432
5: 5254432
6: 5255560
7: 5312392
8: 5315680
9: 5316056
10: 5316056
11: 5317184
12: 5328064
13: 5410280
: 
: 
: 
1: 413656
2: 414904
3: 5254056
4: 5254432
5: 5254432
6: 5255560
7: 5312392
8: 5315680
9: 5316056
10: 5316056
11: 5317184
12: 5328064
13: 5410280
: 
: 
: 
1: 413656
2: 414904
3: 5254056
4: 5254432
5: 5254432
6: 5255560
7: 5312392
8: 5315680
9: 5316056
10: 5316056
11: 5317184
12: 5328064
13: 5410280
TLS Connection: 
Server Info: Apache/2.4.43 (Unix)
PHP Version: 7.3.5
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
PHP Max Upload Size: 300 MB
cURL Version: 7.54.0, LibreSSL/2.6.5
SUHOSIN Installed: –
MySQL Version: 5.7.28
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
: 
: 
: 
1: 413656
2: 414904
3: 5254056
4: 5254432
5: 5254432
6: 5255560
7: 5312392
8: 5315680
9: 5316056
10: 5316056
11: 5317184
12: 5328064
13: 5410280
: 
: 
: 
1: 413656
2: 414904
3: 5254056
4: 5254432
5: 5254432
6: 5255560
7: 5312392
8: 5315680
9: 5316056
10: 5316056
11: 5317184
12: 5328064
13: 5410280
: 
: 
: 
1: 413656
2: 414904
3: 5254056
4: 5254432
5: 5254432
6: 5255560
7: 5312392
8: 5315680
9: 5316056
10: 5316056
11: 5317184
12: 5328064
13: 5410280

### GiveWP Configuration ###

GiveWP Version: 2.7.0
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://twoseven.local/donation-confirmation/
Failure Page: http://twoseven.local/donation-failed/
Donation History Page: http://twoseven.local/donation-history/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: N/A

### Inactive Plugins ###

Give - Stripe Gateway: by GiveWP – 2.2.5

### Theme ###

Name: Twenty Twenty
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by jonwaldstein** [comment]
@Benunc I am confirming this is still an issue (at least on legacy forms).  We should really fix this with your suggestions.
