### ISSUE TITLE
(2.7.0) Fatal error on Update Payment Method page for recurring donations

### ISSUE THREAD

**Issue by rickalday** [impress-org/givewp#4863]
# Bug Report

## User Story

As a donor, I want to be able to update my subscription payment details without errors.

## Current Behavior

Update Payment Method page shows a couple of fatal errors related to a now missing give_stripe_credit_card_form function.

## Expected Behavior

There should be no fatal errors and donors should be able to update their cc and amount info.

## Bug Type

- [x] This bug describes functionality that once worked as expected in version 2.6.13.
- [ ] This bug describes functionality that never worked as expected.
- [ ] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1.  Use GiveWP 2.7.0
2. View the subscriptions page and try to update the payment details for one of your subscriptions

## Visuals

<img width="783" alt="Screen Shot 2020-06-24 at 4 06 32 PM" src="https://user-images.githubusercontent.com/312000/85627884-d9fccf00-b634-11ea-8b35-329f8722c938.png">

## Acceptance Criteria

- [ ] There are no fatal errors in Update Payment Method page

**Comment by henryholtgeerts** [comment]
@rickalday Looking into this now, can you tell me what version of Give Recurring you are running? When I search for `give_stripe_credit_card_form` on the development branch of Give Recurring I'm not able to find any calls to it. I'm curious if changes have been made in the plugin which need to be released. 

You can see this this particular issue was addressed and resolved in this PR (merged): https://github.com/impress-org/give-recurring/pull/954.

@DevinWalker Do you have any insight on these changes that (as far as I can tell) haven't been released yet?

**Comment by rickalday** [comment]
@henryholtgeerts I'm using version 1.10.2.  I downloaded a copy from my givewp.com.
It's in the master branch copy https://github.com/impress-org/give-recurring/blob/master/includes/gateways/give-recurring-stripe.php#L764

**Comment by henryholtgeerts** [comment]
Good to know, it looks like the issue has been resolved on the `develop` branch of Give Recurring, and the `release/2.7.0` branch of GiveWP. It looks like this issue has been resolved in the Give Recurring repo, and the accompanying changes (present on the `develop` branch just need to be released.

**Comment by DevinWalker** [comment]
Closing as it's been resolved in the releases I'm pushing out right now. Please re-open if more reports come in post release.
