### ISSUE TITLE
Connecting a Stripe account should not break when WP_DEBUG is enabled in PHP7.4+

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#4868]
# Bug Report

## User Story

As a **site administrator,** I want **to avoid page breaking notices** so that **I can connect to Stripe (when WP_DEBUG) is enabled**.

## Details

Connecting to Stripe via the "welcome" screen with WP_DEBUG enabled displays a Deprecated notice before headers are sent, which breaks the page.

> Deprecated: array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead in givewp/vendor/stripe/stripe-php/lib/ApiRequestor.php on line 402

Using array_key_exists() on objects is deprecated as of PHP7.4.

See https://www.php.net/manual/en/migration74.deprecated.php

## Current Behavior

A deprecated notice is output before headers are sent.

## Expected Behavior

Notices should display after headers are sent.

## Bug Type

I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce

1. Enable WP_DEBUG
2. Connect to Stripe via the Welcome Screen
3. See PHP Deprecated notice

## Visuals

![image](https://user-images.githubusercontent.com/10858303/85747128-023c0a80-b6d5-11ea-863b-201c4c74cdb8.png)

## Possible Solution

I'm not sure if the Stripe SDK just needs to be updated, or if an output buffer needs to be used to mitigate the issue.

## Acceptance Criteria

- [x] Connect to Stripe with PHP7.4+

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Linux</li>
        <li>POP!_OS</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Firefox for Ubuntu</li>
        <li>Version: 77.0.1 (64-bit)</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    ### WordPress Environment ###

Home URL: http://127.0.0.1/wordpress
Site URL: http://127.0.0.1/wordpress
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: 127.0.0.1
TLS Connection: Connection uses TLS 1.3
TLS Connection: Probably Okay
Server Info: Apache/2.4.41 (Ubuntu)
PHP Version: 7.4.3
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
PHP Max Upload Size: 2 MB
cURL Version: 7.68.0, OpenSSL/1.1.1f
SUHOSIN Installed: –
MySQL Version: 8.0.20
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.7.0
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://127.0.0.1/wordpress/donation-confirmation/
Failure Page: http://127.0.0.1/wordpress/donation-failed/
Donation History Page: http://127.0.0.1/wordpress/donation-history/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation, Stripe - Credit Card
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: ( ! ) Notice: Trying to access array offset on value of type bool in /home/kylebjohnson/Code/impress-org/givewp/includes/admin/tools/views/html-admin-page-system-info.php on line 667
Call Stack
#TimeMemoryFunctionLocation
10.0001365104{main}(  ).../edit.php:0
20.0002366352require_once( '/var/www/html/wordpress/wp-admin/admin.php' ).../edit.php:10
30.13194396336do_action(  ).../admin.php:254
40.13194396712WP_Hook->do_action(  ).../plugin.php:478
50.13194396712WP_Hook->apply_filters(  ).../class-wp-hook.php:311
60.13204397840Give_Admin_Settings::output(  ).../class-wp-hook.php:287
70.13244456064include( '/home/kylebjohnson/Code/impress-org/givewp/includes/admin/views/html-admin-settings.php' ).../class-admin-settings.php:264
80.13284459352do_action(  ).../html-admin-settings.php:128
90.13284459728WP_Hook->do_action(  ).../plugin.php:478
100.13284459728WP_Hook->apply_filters(  ).../class-wp-hook.php:311
110.13284460856Give_Settings_System_Info->output(  ).../class-wp-hook.php:287
120.13754471704include_once( '/home/kylebjohnson/Code/impress-org/givewp/includes/admin/tools/views/html-admin-page-system-info.php' ).../class-settings-system-info.php:56

N/A
: 
: 
: 
1: 365104
2: 366352
3: 4396336
4: 4396712
5: 4396712
6: 4397840
7: 4456064
8: 4459352
9: 4459728
10: 4459728
11: 4460856
12: 4471704
Donor Email Access: Enabled
Stripe Webhook Notifications: N/A
: 
: 
: 
1: 365104
2: 366352
3: 4396336
4: 4396712
5: 4396712
6: 4397840
7: 4456064
8: 4459352
9: 4459728
10: 4459728
11: 4460856
12: 4471704

### Inactive Plugins ###

Airplane Mode: by Andrew Norcross – 0.2.5
Classic Editor: by WordPress Contributors – 1.5
Give - Fee Recovery: by GiveWP – 1.7.10
Give - Form Field Manager: by GiveWP – 1.4.6
LifterLMS: by LifterLMS – 3.41.1
Video Library: by  –
WooCommerce: by Automattic – 4.2.2
WooCommerce Order Shipping Export: by Forge Media – 2020.06.23-12.53
WooCommerce Order Taxes Export: by Forge Media – 2020.06.17-12.55
WooCommerce Subscription Retention Summary: by Forge Media – 2020.06.23-12.53
WooCommerce Subscriptions: by WooCommerce – 3.0.1
Yarnell Authorize.NET ARB (Automatice Recurring Billing): by  –

### Theme ###

Name: Twenty Twenty
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by kjohnson** [comment]
It looks like the connection to the Stripe account is made successfully, but that isn't obvious due to the broken page.

**Comment by kjohnson** [comment]
The call to `give_stripe_get_account_details()` results in a Deprecated Noticed thrown by `vendor/stripe/stripe-php/lib/ApiRequestor.php`

```php
if (array_key_exists('request-id', $rheaders)) {
    // ...
}
```

This can be suppressed with `@give_stripe_get_account_details()`.

**Comment by JasonTheAdams** [comment]
Honestly, I don't think this is worth pouring much time and effort into. I believe that the vast majority of sites will not be running with `WP_DEBUG` enabled, and those that are understand what they're doing. Since this is a deprecation, it's particularly hard to squelch without changing the PHP configuration, which we shouldn't be doing.

Stripe has a new version of their SDK, which we'll want to switch to in the not-too-distant future, which I'm sure has resolved this issue. It's certainly not worth using something like a composer patching library, as now we're adding complexity in order to hide a legitimate warning in development mode.
