### ISSUE TITLE
Fix currency preview field not accurately displaying preview on page load

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#4869]
## Issue Description

When I view the currency settings in GiveWP I want to see an accurate preview of my settings when the page loads so that I'm not confused.

Currently when you load the page the preview displays an incorrect decimal setting:

![2020-06-25_13-48-00](https://user-images.githubusercontent.com/1571635/85797800-2d345780-b6f1-11ea-9eb2-e727dbb581eb.png)

**Comment by jonwaldstein** [comment]
Confirming this has not been resolved yet.
