### ISSUE TITLE
The Apple Pay button should display below the Terms and conditions checkbox.

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#4871]
@Benunc commented on [Fri Jun 26 2020](https://github.com/impress-org/give-stripe/issues/454)

# Bug Report

## User Story

As a user, I want to prompt my donors to accept terms and conditions before they click the "Pay with Apple Pay" button so that the process has less friction.

## Current Behavior
The terms and conditions checkbox shows below the "Donate with Apple Pay" button.

## Expected Behavior
The checkbox is required, so it should display before the button.

## Bug Type
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce
1. Enable Terms and conditions in the global settings or on an individual form.
2. Configure Apple Pay
3. Load the Legacy form template.

## Visuals
![Screen Shot 2020-06-26 at 9 53 54 AM](https://user-images.githubusercontent.com/9629102/85864802-fadb3680-b792-11ea-8f3b-378b116093a1.png)

## Related
https://secure.helpscout.net/conversation/1192074232/67638?folderId=848135

## Acceptance Criteria

- [ ] The terms checkbox displays above the Apple Pay button.
- [ ] The terms checkbox still functions correctly, including displaying/hiding terms and preventing a donation from proceeding until the box is checked.
- [ ] A donation still goes through on the Apple Pay gateway.

## Environment
<details>
    <summary>WordPress System Info</summary>
    ### WordPress Environment ###

Home URL: http://live2.wpsteward.com
Site URL: http://live2.wpsteward.com
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: live2.wpsteward.com
TLS Connection: Warning:  file_get_contents(https://www.howsmyssl.com/a/check): failed to open stream: Connection timed out in /srv/users/serverpilot/apps/live2/public/wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php on line 199
TLS Connection: 
Server Info: Apache/2.4.43 (Unix) OpenSSL/1.0.1f
PHP Version: 7.2.31
PHP Post Max Size: 1 GB
PHP Time Limit: 30
PHP Max Input Vars: 5000
PHP Max Upload Size: 512 MB
cURL Version: ❌ 7.35.0, OpenSSL/1.0.1f - We recommend a minimum cURL version of 7.40.
SUHOSIN Installed: –
MySQL Version: ❌ 5.5.62 - We recommend a minimum MySQL version of 5.6. See: WordPress Requirements
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.6.3
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access❌Renewal Receipt Email❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access✔Subscription Payment Failed Email
Upgraded From: 2.6.1
Test Mode: Enabled
Currency Code: EUR
Currency Position: Before
Decimal Separator: ,
Thousands Separator: .
Success Page: http://live2.wpsteward.com/donation-confirmation/
Failure Page: http://live2.wpsteward.com/donation-failed/
Donation History Page: http://live2.wpsteward.com/donation-history/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Stripe - Checkout, Mollie Gateway, Stripe - Credit Card, Razorpay, PayPal Standard, Square Gateway, Authorize.net, Stripe - Apple Pay, Stripe - Google Pay
Default Payment Gateway: Stripe - Apple Pay
PayPal IPN Verification: Disabled
PayPal IPN Notifications: IPN received for #424 ( 64Y66231N07101740 ) on 06/25/2020 at 20:57. Status N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: 26th June 2020 1:28 pm
Square Token Renewal Date: N/A

### Active GiveWP Add-ons ###

Give - Authorize.net Gateway: ✔ Licensed – by GiveWP – 1.4.6
Give - Currency Switcher: ✔ Licensed – by GiveWP – 1.3.9
Give - Form Field Manager: ✔ Licensed – by GiveWP – 1.4.6
Give - GoCardless Gateway: ✔ Licensed – by GiveWP – 1.3.5
Give - MailChimp: ✔ Licensed – by GiveWP – 1.4.6
Give - Mollie Gateway: ✔ Licensed – by GiveWP – 1.2.4
Give - Razorpay: ✔ Licensed – by GiveWP – 1.4.4
Give - Recurring Donations: ✔ Licensed – by GiveWP – 1.10.2
Give - Square: ✔ Licensed – by GiveWP – 1.1.1
Give - Stripe Gateway: ✔ Licensed – by GiveWP – 2.2.5

### Other Active Plugins ###

Elementor: by Elementor.com – 2.9.13

### Inactive Plugins ###

Akismet Anti-Spam: by Automattic – 4.1.6
Duplicator: by Snap Creek – 1.3.36
Give - Annual Receipts: by GiveWP – 1.0.2
Give - Email Reports: by GiveWP – 1.1.4
Give - Fee Recovery: by GiveWP – 1.7.11
Give - Gift Aid: by GiveWP – 1.2.4
Give - iATS Payment Solutions: by GiveWP – 1.0.5
Give - Manual Donations: by GiveWP – 1.4.6
Give - PDF Receipts: by GiveWP – 2.3.9
Give - Per Form Gateways: by GiveWP – 1.0.2
Give - Tributes: by GiveWP – 1.5.7
Give - Zapier: by GiveWP – 1.3.0
Hello Dolly: by Matt Mullenweg – 1.7.2
Yoast SEO: by Team Yoast – 14.4.1

### Theme ###

Name: Hello Elementor Child
Version: 1.0.1
Author URL: https://elementor.com/
Child Theme: Yes
Parent Theme Name: Hello Elementor
Parent Theme Version: 2.3.0
Parent Theme Author URL: https://elementor.com/?utm_source=wp-themes&utm_campaign=author-uri&utm_medium=wp-dash

</details>

---

@henryholtgeerts commented on [Fri Jun 26 2020](https://github.com/impress-org/give-stripe/issues/454#issuecomment-650365690)

After some investigating, I'm moving this issue to GiveWP core, as it relates more specifically to the order that the index the terms and agreements function uses to hook into the `give_after_cc_fields` action. Moving this issue to GiveWP core means we can avoid additional releases of the Give Stripe plugin simply to addres this issue.

**Comment by ravinderk** [comment]
Issue moved to [impress-org/give-stripe #455](https://github.com/impress-org/give-stripe/issues/455) via [**ZenHub**](https://www.zenhub.com/)
