### ISSUE TITLE
Epic: PayPal Commerce

### ISSUE THREAD

**Issue by JasonTheAdams** [impress-org/givewp#4886]
# Pitch

This pitch has been defined in a [Google Doc](https://docs.google.com/document/d/1wD-Cyy4X6fDRe-tW4Ey3wSglcbYRAZQyDvjIEqVarRE/edit#heading=h.9g67mdj3rh9m).

The scope of this Epic is the integration of the new PayPal Commerce Platform payment gateway within GiveWP core.

## Note

This is the integration of the PayPal Commerce Platform API, but it will be called the **PayPal Checkout** gateway in GiveWP.

## Appetite

6 weeks, though we should finish as close to July 31 as possible

**Comment by JasonTheAdams** [comment]
## Call Summary

Attendees: Swati (from PayPal) and Jason Adams

Result:
Turns out that there was some mix up with the application on PayPal. We weren't using the app they'd intended us to be using, but at some point Swati had given us the right merchant id. So we were using the right merchant ID but the wrong client id and secret on the Gateway server.

I now have the right account details, which I will share with @ravinderk, and will update the Gateway. We'll see what issues this fixes and go from there.

**Comment by JasonTheAdams** [comment]
## Check In

So far the progress of PayPal Commerce integration has been steady, like trudging through a swamp with ankle weights. We're moving forward bit by bit, but every step has been strangely difficult. I wish this wasn't the norm with PayPal, but here we are. 😅 

We're about 90% of the way complete with the onboarding process. As mentioned in the previous call summary, we apparently were working with partially correct credentials. I was optimistic that this would help... but my first test with the new credentials just didn't work as they need to enable the PPCP product on our account. That kind of sums up the experience.

Anyway, I'll stop complaining. Once we have the credentials worked out, hopefully the status we get back from the API will be correct. It was almost working before, but specific product details were missing. We've been coordinating with Swati to figure this out. Unfortunately, this is blocking us from getting advanced fields working. @ravinderk, however, was able to process a donation with Smart Buttons!

All in all, due to the slow progress of the project, I'm thinking it will likely take more than another week to get this out. In terms of our code, we're really not that far from finishing, it's really the constant back and forth with PayPal to troubleshoot this. To Swati's credit, she's been as available as she has time to be. It seems like since this is new for them, too, they don't quite have this down to a smooth process.

**Comment by JasonTheAdams** [comment]
@kevinwhoffman @DevinWalker Here is a screencast of where we're currently at, walking through onboarding and a donation: https://share.getcloudapp.com/kpuboyZr

**Comment by kevinwhoffman** [comment]
@JasonTheAdams Excellent overview! The user experience has come a long way. The payment step of the donation form seems like the area that would benefit the most from some UX polish. I need a little more understanding of the smart buttons before that happens. I will reach out via Slack.

**Comment by JasonTheAdams** [comment]
## Status Update

If this epic was a TV show, it would be a soap opera.
![Drama!](https://media.giphy.com/media/3oxRmaXcYbuEGQG4dq/giphy.gif)

That said, we're getting through it! By this point donations are processing great with both the Advanced fields and Smart Buttons. All the styles are looking good — with the exception on the Smart buttons on really wide screens... because PayPal put a `max-width` of a specific pixel on them. The onboarding is working and notifying users of any account readiness issues, as well as providing a way of re-checking their account. Most issues are close to finish or in review. There are a few issues left open, the most significant of which probably being refunding — which should be done by tomorrow.

All in all, we're on track to have this pretty wrapped up by the end of day tomorrow. There are not a lot of options so far, the only being to get onboarded. The reason for this is that the emphasis has been on just getting the fundamentals working. If there's are any specific options that folks feel ought to be in the first release, it's imperative that these are communicated as soon as possible.

Note: Onboarding with live mode doesn't work. This is because PayPal has to finish setting us up on their end.
