### ISSUE TITLE
New form template should indicate required fields

### ISSUE THREAD

**Issue by rickalday** [impress-org/givewp#4889]
# Feature Request

## User Story

As a donor, I want to know which form fields are required before getting hit with an error message when I try to donate without filling all required fields.

The new form template hides form labels but that also includes the asterisk that marks a field as required.
Not all donors will know that a name and email are required to make a donation.

## Related

https://secure.helpscout.net/conversation/1212472973/69101/

## Acceptance Criteria

- [ ] Indicate to the user which fields are required
- [ ] Make sure the same solution is applied to Form Field Manager fields.

**Comment by jonwaldstein** [comment]
I can't find any recent reports of request for this.  Seems like the template design decisions were intentional.  Closing for now until a request comes up again.
