### ISSUE TITLE
Organizers should be able to connect to the PayPal Checkout gateway

### ISSUE THREAD

**Issue by JasonTheAdams** [impress-org/givewp#4892]
## User Story

As an organizer, I want to connect my PayPal account to the PayPal Checkout gateway so that I can start receiving donations via that gateway.

## Details
This piece of the PayPal Commerce integration should allow users to connect their PayPal account to the PayPal Checkout gateway.

## Visuals
![PayPal Checkout _ Not Connected](https://user-images.githubusercontent.com/2024145/86292313-65caaa00-bba5-11ea-9405-14e1e6621aed.jpg)
![PayPal Checkout _ Connected](https://user-images.githubusercontent.com/2024145/86292509-bc37e880-bba5-11ea-9801-487a1a4b65c2.jpg)

## Acceptance Criteria

- [x] PayPal Checkout connect settings are available
- [x] User is able to connect a new account to PayPal Checkout
- [x] User is able to connect an existing account to PayPal Checkout
- [x] User is able to disconnect their account

**Comment by ravinderk** [comment]
I found that the sandbox is not working correctly. We are waiting for the PayPal team to resolve the issue. You can review dev chat in [slack](https://givewp.slack.com/archives/C015XD31J5S/p1594159422004700) for more information.

**Comment by ravinderk** [comment]
PayPal team fixed the issue. I verified by completing the onboarding process myself on the test server.

Slack discussion: https://givewp.slack.com/archives/C015XD31J5S/p1594318862000500?thread_ts=1594159422.004700&cid=C015XD31J5S
