### ISSUE TITLE
PayPal Checkout gateway should process one-time donations via Smart Buttons

### ISSUE THREAD

**Issue by JasonTheAdams** [impress-org/givewp#4893]
## User Story

As a non-profit organizer, I want to receive one-time donations through the new PayPal Checkout gateway so that I can get donations from my website for free!

## Details
This is part of the PayPal Commerce integration epic. This should extend the PayPal Checkout gateway to process donations through the 1st party integration of the PayPal Commerce API. It should use the [Smart Buttons](https://developer.paypal.com/docs/checkout/) system.

### Notes
- Shipping address can be hidden by setting the shipping_preference to NO_SHIPPING in the POST /v2/checkout/orders API.

## Visuals
<img width="342" alt="Smart Buttons visual" src="https://user-images.githubusercontent.com/2024145/86293399-62382280-bba7-11ea-8485-e7e45a655e94.png">

## Acceptance Criteria

- [ ] Org admins can select (not as the default) whether to use Smart Buttons or Advanced Payment within gateway settings
- [ ] A donor is able to fully process a donation using the Smart Buttons

**Comment by JasonTheAdams** [comment]
@ravinderk This is going to be moved to the PayPal Pro add-on later on, so I'm removing this from the epic.

**Comment by ravinderk** [comment]
This feature already added to core giveWP `2.9.0`.
cc: @JasonTheAdams
