### ISSUE TITLE
fix: thank you page string

### ISSUE THREAD

**Issue by michaelbeil** [impress-org/givewp#4909]
# Bug Report  

## User Story

As a donor, I want to see the correct pronoun used in the thank you page. 

## Bug Type
- [x] I am not sure whether this functionality ever worked as expected.

## Steps to Reproduce 
1. Submit a form
2. The thank you page will contain the string: {name}, **you** contribution means a lot and will be put to good use making a difference. We’ve sent your donation receipt to {donor_email}.  

## Visuals 
![Screen Shot 2020-07-07 at 16 34 57](https://user-images.githubusercontent.com/4752949/86798179-cb6cd980-c070-11ea-82b2-dafd74a8b8da.png) 

## Possible Solution
Change https://github.com/impress-org/givewp/blob/02defb02673aa8b8305eb66473a869d2d3bd8c1c/src/Views/Form/Templates/Sequoia/optionConfig.php#L172 and  https://github.com/impress-org/givewp/blob/02defb02673aa8b8305eb66473a869d2d3bd8c1c/src/Views/Form/Templates/Sequoia/optionConfig.php#L174 

to:
{name}, **your** contribution means a lot and will be put to good use making a difference. We’ve sent your donation receipt to {donor_email}.

## Acceptance Criteria 
- [x] Change the string 

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X</li>
        <li>Version: 10.15.5</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Firefox</li>
        <li>Version: 78.0.1</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
  ### WordPress Environment ###

Home URL: http://localtest.local/give
Site URL: http://localtest.local/give
WP Version: 5.4.2
WP Multisite: ✔
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: posts
Table Prefix Length: wp_13_
Table Prefix Length: 6
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: localtest.local
TLS Connection: 
TLS Connection: 
Server Info: nginx/1.16.0
PHP Version: 7.3.5
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
PHP Max Upload Size: 1 MB
cURL Version: 7.54.0, LibreSSL/2.6.5
SUHOSIN Installed: –
MySQL Version: 8.0.16
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.7.2
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_13_give_donors -  1.0✔ wp_13_give_donormeta -  1.0✔ wp_13_give_comments -  1.0✔ wp_13_give_commentmeta -  1.0✔ wp_13_give_sessions -  1.0✔ wp_13_give_logs -  1.0✔ wp_13_give_logmeta -  1.0✔ wp_13_give_formmeta -  1.0✔ wp_13_give_sequential_ordering -  1.0✔ wp_13_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access
Upgraded From: 2.7.1
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://localtest.local/give/donation-confirmation/
Failure Page: http://localtest.local/give/donation-failed/
Donation History Page: http://localtest.local/give/donation-history/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation, Stripe - Credit Card, Stripe - Checkout
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: N/A

### Other Active Plugins ###

User Switching: by John Blackbourn & contributors – 1.5.5

### Inactive Plugins ###

Adminer: by Frank Bültge – 1.4.5 
Airplane Mode: by Andrew Norcross – 0.2.5
Akismet Anti-Spam: by Automattic – 4.1.6
AMP: by AMP Project Contributors – 1.5.4
Asset CleanUp: Page Speed Booster: by Gabriel Livan – 1.3.6.5
BackupBuddy: by iThemes – 6.4.0.16
bbPress: by The bbPress Contributors – 2.6.5
Breadcrumb NavXT: by John Havlik – 6.5.0
Browser-sync Filter: by Andrew Taylor – 2.2
BuddyPress Docs: by Boone B Gorges, David Cavins – 2.1.3
Caldera Easy Queries: by David  for CalderaWP LLC – 1.0.0-rc4
Caldera Forms: by Caldera Forms – 1.9.1
CalderaWP License Manager: by David Cramer for CalderaWP LLC – 1.1.0
Checkout Field Editor for WooCommerce: by ThemeHigh – 1.4.3
CMB2: by CMB2 team – 2.7.0
Code Snippets: by Code Snippets Pro – 2.14.0
Contact Form 7: by Takayuki Miyoshi – 5.2
Cooked Recipe Plugin: by Boxy Studio – 2.2.1
Cornerstone: by Themeco – 3.5.5
Debug Bar: by wordpressdotorg – 1.0.1
Debug Bar Console: by koopersmith – 0.3
Debug Bar Cron: by Zack Tollman, Helen Hou-Sandi – 0.1.2
Debug Bar Extender: by Thorsten Ott, Automattic – 0.5
Developer: by Automattic – 1.2.6
Download Monitor: by Never5 – 4.4.3 
Easy Social Share Buttons: by Idiom Interactive – 1.4.5 
Elementor: by Elementor.com – 2.9.13
Enhanced Media Library: by wpUXsolutions – 2.7.2 
Formidable Forms: by Strategy11 – 4.06 
GeoDirectory Payment Manager: by GeoDirectory – 1.1.9
Gitium: by Presslabs – 1.0.3
GiveWP Donation Widgets for Elementor: by GiveWP – 1.1.1
GoUrl Bitcoin Payment Gateway & Paid Downloads & Membership: by GoUrl.io – 1.6.2
GoUrl WooCommerce - Bitcoin Altcoin Payment Gateway Addon. White Label Solution: by GoUrl.io – 1.3.6
Gravity Forms: by rocketgenius – 2.4.17
Gravity Forms Coupons Add-On: by rocketgenius – 2.3
Gravity Forms PayPal Standard Add-On: by rocketgenius – 3.2
Gravity Forms Quiz Add-On: by Rocketgenius – 2.4.1
Gravity Forms Stripe Add-On: by rocketgenius – 2.0
Gravity Forms User Registration Add-On: by Gravity Forms – 4.4.7
Homepage Control: by WooThemes – 2.0.3
iThemes Exchange: by iThemes – 1.36.4
Jetpack by WordPress.com: by Automattic – 8.6.1
LifterLMS: by LifterLMS – 4.1.0
Loco Translate: by Tim Whitlock – 2.4.0
Log Deprecated Notices: by Andrew Nacin – 0.4.1 
Nextend Social Login: by Nextendweb – 3.0.24
Ninja Forms: by Saturday Drive – 3.4.24.3 
Paid Memberships Pro: by Stranger Studios – 2.3.4
Per-Form Confirmation Pages for GiveWP: by GiveWP – 1.1
Plugin Organizer: by Jeff Sterup – 10.1.3
Query Monitor: by John Blackbourn – 3.6.0 
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.3 
Revisr: by Expanded Fronts, LLC – 2.0.2
Rewrite Rules Inspector: by Daniel Bachhuber, Automattic – 1.2.1
RTL Tester: by Yoav Farhi, Automattic – 1.2
Say What?: by Lee Willis – 1.9.4
Scripts-To-Footer: by Joshua David Nelson – 0.6.4.1
Simple Custom CSS: by John Regan, Danny Van Kooten – 4.0.4
Simple Social Shout for GiveWP: by GiveWP – 1.1.1
Simply Show IDs: by Matt Martz – 1.3.3
Stackable - Gutenberg Blocks: by Gambit Technologies, Inc – 2.6.1
Subtitles: by Philip Arthur Moore, We Cobble – 3.0.0 
Theme Check: by Theme Review Team – 20200612.1
Tickera: by Tickera.com – 3.4.7.1 
Ultimate Member: by Ultimate Member – 2.1.6
Unplug Jetpack: by Tanner Moushey – 0.1.1
Unsplash WP: by Darren Cooney – 1.1.3
UserPro: by Deluxe Themes – 2.48
User Switching in Admin Bar: by Dražen Bebić – 1.2
Video User Manuals: by Video User Manuals Pty Ltd – 2.4.1
WC Autoship: by Patterns in the Cloud – 3.1.11
WishList Member™: by WishList Products – 2.90.2940
WooCommerce: by Automattic – 4.2.2
WooCommerce Admin: by WooCommerce – 1.2.4
WooCommerce Beta Tester: by WooCommerce – 2.0.1
WooCommerce Klarna Gateway: by WooThemes – 2.1.2
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.0.3
WooCommerce PayPal Powered by Braintree Gateway: by WooCommerce – 2.3.11
WooCommerce Product Vendors: by WooThemes – 1.1.8
WooCommerce Save & Share Cart: by cxThemes – 2.09
WooCommerce Services: by Automattic – 1.23.2
WooCommerce Shop as Customer: by cxThemes – 1.14
WooCommerce Smart Coupons: by WooThemes – 3.0.12
WooCommerce Stripe Gateway: by WooCommerce – 4.5.0
WooCommerce Subscriptions: by WooCommerce – 3.0.2
WooThemes Helper: by WooThemes – 1.6.2
WordPress Access Control: by Brandon Wamboldt – 4.0.13
WordPress Beta Tester: by Peter Westwood, Andy Fragen – 2.2.10
WordPress Importer: by wordpressdotorg – 0.7
WordPress phpinfo(): by Chris Flannagan – 16.3 
WP Approve User: by Konstantin Obenland – 7
WP Crontrol: by John Blackbourn & crontributors – 1.8.5
WP eCommerce: by WP eCommerce – 3.14.0
WP Job Manager: by Automattic – 1.34.2
WP Live Search: by  – 0.9
WP Mail SMTP: by WPForms – 2.1.1
WP REST API: by WP REST API Team – 1.2.5
WP Retina 2x: by Jordy Meow – 5.6.1
WP Rocket: by WP Rocket – 2.7.1
WP Side Comments: by Pierre SYLVESTRE – 1.0.5 
Yoast SEO: by Team Yoast – 14.4.1
Zippy Courses: by Zippy Courses  – 1.3.2

### Active MU Plugins ###

Plugin Organizer MU: by Jeff Sterup – 10.1.3

### Theme ###

Name: Twenty Twenty
Version: 1.4
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

**Comment by ravinderk** [comment]
@michaelbeil Thank you for reporting this 👍 🥇
