### ISSUE TITLE
Default Set Template PDFs on fresh installs should not be Blank

### ISSUE THREAD

**Issue by zjimpress** [impress-org/givewp#4911]
# Bug Report

## User Story

As a Donor, I want to see my PDF receipt so that I can review/keep for my records_.

## Details

The PDF receipt is viewed/and downloaded as blank. **This is happening in local & live environments on fresh GiveWP installs.**

**The workaround, is to set a different template and/or set a custom PDF template and save. After saving, resetting the default template will now generate the PDF receipt. This also does not reproduce the orginial error. That is to say the error only seems to be happening initially and once set and saved, will not reoccur.**

## Current Behavior

PDF receipt file showing all white when viewed or downloaded with a fresh Give install, however will be fixed once a new template is chosen or a new custom pdf is made, saved and then the default template is chosen once more.
## Expected Behavior

The PDF receipt is expected to be populated with the donation data when viewed in or browser or downloaded.

## Bug Type

- [x] This bug describes functionality that once worked as expected in version 2.6.3 (hypothesis)

## Steps to Reproduce

-Fresh install + make a few test donations
-Install and activate PDF receipts
-Go to Donations > Donations and hover over a donation and click to Download receipt.
-Blank PDF.
-GO to Donations > Settings > PDF Receipts and choose a new PDF template and/or create a custom PDF.
-Save the settings.
-Repeat step 3.
-Not a blank PDF
-Switch back to the default template.
-Repeat step 3.
-Not a blank PDF.

## Visuals

**.gif file:**
![blank-pdf](https://user-images.githubusercontent.com/65558352/86831998-9c9d3600-c065-11ea-9527-d27dd0781099.gif)

## Acceptance Criteria

- [ ] Clicking "Download Receipt" should properly render and display the PDF receipt on a fresh install.

## Environment

<details>
    <summary>Operating System</summary>
    <ul>
        <li>Platform: Mac OS X | Microsoft Windows | Linux | Android | iOS</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>Browser</summary>
    <ul>
        <li>Name: Chrome | Firefox | Safari | IE | Edge</li>
        <li>Version: X.X.X</li>
    </ul>
</details>

<details>
    <summary>WordPress System Info</summary>
    
```### WordPress Environment ###

Home URL: http://ztestsite.local
Site URL: http://ztestsite.local
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: ztestsite.local
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.16.0
PHP Version: 7.3.5
PHP Post Max Size: 1,000 MB
PHP Time Limit: 1200
PHP Max Input Vars: 4000
PHP Max Upload Size: 300 MB
cURL Version: 7.58.0, GnuTLS/3.5.18
SUHOSIN Installed: –
MySQL Version: 5.7.28
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.7.2
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access❌Renewal Receipt Email❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access✔Subscription Payment Failed Email
Upgraded From: 2.7.0
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: http://ztestsite.local/donation-confirmation/
Failure Page: http://ztestsite.local/donation-failed/
Donation History Page: http://ztestsite.local/donation-history/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Stripe - Credit Card
Default Payment Gateway: Stripe - Credit Card
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: N/A
Square Token Renewal Date: N/A

### Active GiveWP Add-ons ###

Give - Currency Switcher: ✔ Licensed – by GiveWP – 1.3.11
Give - Fee Recovery: ✔ Licensed – by GiveWP – 1.7.11
Give - Form Field Manager: ✔ Licensed – by GiveWP – 1.4.7
Give - MailChimp: ✔ Licensed – by GiveWP – 1.4.6
Give - Manual Donations: ✔ Licensed – by GiveWP – 1.4.6
Give - PayPal Pro Gateway: ✔ Licensed – by GiveWP – 1.2.2
Give - PDF Receipts: ✔ Licensed – by GiveWP – 2.3.10
Give - Recurring Donations: ✔ Licensed – by GiveWP – 1.10.4
Give - Square: ✔ Licensed – by GiveWP – 1.1.1
Give - Stripe Gateway: ✔ Licensed – by GiveWP – 2.2.8
Give - Tributes: ✔ Licensed – by GiveWP – 1.5.7

### Other Active Plugins ###

Akismet Anti-Spam: by Automattic – 4.1.6
My Custom Functions: by Space X-Chimp – 4.42

### Inactive Plugins ###

Classic Editor: by WordPress Contributors – 1.5

### Active MU Plugins ###

Local by Flywheel Live Link Helper: by Flywheel – 1.1

### Theme ###

Name: Twenty Twenty
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

```
</details>

**Comment by DevinWalker** [comment]
Issue moved to [impress-org/give-pdf-receipts #231](https://github.com/impress-org/give-pdf-receipts/issues/231) via [**ZenHub**](https://www.zenhub.com/)
