### ISSUE TITLE
"Thank you" description fields should allow basic HTML

### ISSUE THREAD

**Issue by rickalday** [impress-org/givewp#4918]
## User Story

As a site admin, I want the new form template "Thank you"  description field should allow basic HTML so that I can have some control of the formatting of the text.

## Details

Currently, line breaks do not work so I have a large block of text there's no way to break it into multiple paragraphs.  Unlike the other description fields in the form, this field strips out all HTML tags.

## Acceptance Criteria

-   [x] "Thank you" description field allows basic HTML

**Comment by jonwaldstein** [comment]
This has been resolved for what i'm assuming is the "new from template" being referred here as our multi-step form in https://github.com/impress-org/givewp/pull/5985
