### ISSUE TITLE
Onboarding wizard design should be implemented

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#4921]
# Feature Request

## User Story
As a developer, I want the Onboarding Wizard to implement a high fidelity design so that users can have an aesthetic and cohesive experience setting up their site, and so that future work on the Onboarding Wizard happens with an end design in mind.

## Details
Currently, the Onboarding Wizard is barely developed, and lacks any real design direction beyond the notion of the rough components presented in the fat marker sketches created during the project's shaping process. With this issue, a high fidelity design should be provided for developers to implement. This issue is primarily focused on getting this design implementation correct, not getting the logic actually necessary to correctly render the setup page steps in place. For this reason, this issue will likely not be resolved until _after_ a separate issue regarding the development of individual components is finished. This issue is however, a dependency for a more development focused component creation issue, because the high fidelity designs will inform exactly what components are needed, and how their markup might be structured.

### [Designs](https://www.figma.com/file/4kIK1E96lxEuMKad2msa0a/Epic-Plugin-Onboarding?node-id=230%3A435)

This issue should result in polished mockups based on the sketches provided in Figma. As designs are completed, the `Latest` page in Figma will be updated to reflect the most recent design.

## Acceptance Criteria
- [x] High fidelity designs have been created for the Onboarding Wizard (Figma linked in comments)
- [x] Designs are implemented in Onboarding Wizard app components
- [x] Design implementation is accessible (for keyboard navigation and screenreader)
- [x] Design implementation is responsive, between 13" displays and 27" displays
- [x] Design implementation is component based, so that app logic can be introduced in future issues

**Comment by kevinwhoffman** [comment]
@henryholtgeerts Thanks for creating this issue. Heads up, I removed the images from the issue so that they're not confused with the updated sketches in Figma. Let's try to reference Figma links whenever possible so that we're only dealing with one source of truth for design.

**Comment by DevinWalker** [comment]
Here's the link to the Figma file: https://www.figma.com/file/4kIK1E96lxEuMKad2msa0a/Epic-Plugin-Onboarding?node-id=230%3A562

I'll have all screens done by EOD Monday.
