### ISSUE TITLE
Custom amount option should not be overridden  by the donation levels available when the value is the same

### ISSUE THREAD

**Issue by matheuswd** [impress-org/givewp#4927]
## User Story

As a donor, I want to donate a custom amount montlhy for a project so that I'm charged on the correct date.

## Details
When I select the custom amount, if there is any donation level with the same value on it, the selection moves out from the Custom Amount button to the level button, but they may have different settings, such as donation frequency.

## Expected Behavior
When I click to donate a custom amount, it should not be overridden by any level available, but it should be a custom amount donation with the settings defined by the donor.

## Steps to Reproduce

1. Make sure you have the recurring donations add-on active on your site
2. Create a new form using the Multi-Step Donation Form
3. On Donation Options, set:
3.1. Donation Option: Multi-level Donation
3.2. Recurring Donations: Yes - Admin Defined
3.3. Custom Amount: Enabled
3.4. Recurring Options: every month for ongoing (example only)
4. Create two more donation levels
4.1. Set one level to be recurring every day for ongoing
4.2. Disable recurring option for the second level 
5. Try to make a donation using the custom amount with the same value as one of the levels you created
6. See that, if the custom amount equals to one of the amounts of the levels, the select button changes too

## Visuals
I've recorded a screencast that shows the error and the steps to reproduce it
https://screencast-o-matic.com/u/FnF3/

## System Information

<details><summary>Details</summary>

### WordPress Environment ###

Home URL: https://givewptest.matheuswd.com.br
Site URL: https://givewptest.matheuswd.com.br
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, give_subscription

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: givewptest.matheuswd.com.br
TLS Connection: Connection uses TLS 1.2
TLS Connection: Probably Okay
Server Info: nginx/1.10.3
PHP Version: 7.0.33-26+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 100 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
PHP Max Upload Size: 100 MB
cURL Version: 7.47.0, OpenSSL/1.0.2g
SUHOSIN Installed: –
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.7.2
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access❌Daily Email Report✔Weekly Email Report✔Monthly Email Report❌Renewal Receipt Email❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email✔Subscriptions Email Access✔Subscription Payment Failed Email
Upgraded From: 2.6.3
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://givewptest.matheuswd.com.br/donation-confirmation/
Failure Page: https://givewptest.matheuswd.com.br/donation-failed/
Donation History Page: https://givewptest.matheuswd.com.br/donation-history/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, PayPal Standard, Stripe - Credit Card, PayPal Payments Pro, PayPal Website Payments Pro (REST API), Stripe + Plaid, Moneris - Credit Card, GoCardless, Stripe - Apple Pay, Stripe - Google Pay
Default Payment Gateway: PayPal Website Payments Pro (REST API)
PayPal IPN Verification: Enabled
PayPal IPN Notifications: IPN received for #599 ( 8FN3633804802152D ) on 07/10/2020 at 19:12. Status VERIFIED
Donor Email Access: Enabled
Stripe Webhook Notifications: 2020-07-15 3:56 pm

### Active GiveWP Add-ons ###

Give - Authorize.net Gateway: ✔ Licensed – by GiveWP – 1.4.6
Give - Currency Switcher: ✔ Licensed – by GiveWP – 1.3.11
Give - Email Reports: ✔ Licensed – by GiveWP – 1.1.4
Give - Fee Recovery: ✔ Licensed – by GiveWP – 1.7.11
Give - Form Field Manager: ✔ Licensed – by GiveWP – 1.4.7
Give - GoCardless Gateway: ✔ Licensed – by GiveWP – 1.3.6
Give - MailChimp: ✔ Licensed – by GiveWP – 1.4.6
Give - Moneris: ✔ Licensed – by GiveWP – 1.0.1
Give - PayPal Pro Gateway: ✔ Licensed – by GiveWP – 1.2.2
Give - PDF Receipts: ✔ Licensed – by GiveWP – 2.3.10
Give - Per Form Gateways: ✔ Licensed – by GiveWP – 1.0.2
Give - Razorpay: ✔ Licensed – by GiveWP – 1.4.3
Give - Recurring Donations: ✔ Licensed – by GiveWP – 1.10.4
Give - Stripe Gateway: ✔ Licensed – by GiveWP – 2.2.8
Give - Tributes: ✔ Licensed – by GiveWP – 1.5.7
Give - Zapier: ✔ Licensed – by GiveWP – 1.3.0

### Other Active Plugins ###

Akismet Anti-Spam: by Automattic – 4.1.6
Code Snippets: by Code Snippets Pro – 2.14.0
Duplicator: by Snap Creek – 1.3.36
Loco Translate: by Tim Whitlock – 2.4.0
Nginx Helper: by rtCamp – 2.2.2
User Switching: by John Blackbourn & contributors – 1.5.5
WP Debugging: by Andy Fragen – 2.7.2
WP Rollback: by Impress.org – 1.7.0

### Inactive Plugins ###

Give - Gift Aid: by GiveWP – 1.2.4
PagSeguro for Give: by Matheus Martins – 1.0.0
Simple Social Shout for GiveWP: by GiveWP – 1.1.1

### Theme ###

Name: Twenty Seventeen
Version: 2.3
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

## Acceptance Criteria

-   [ ] Donor should be able to donate a monthly custom amount without the form changing the settings of the custom amounts

**Comment by jonwaldstein** [comment]
I can confirm this is still happening and a recent canny post has been linked. Although, it's really just how the amount field works by design.  That amount field would have to be adjusted to support this request which I think warrants a discussion first.
