### ISSUE TITLE
Twitter link anchor in heading of Welcome screen now show "Follow %s"

### ISSUE THREAD

**Issue by knutsp** [impress-org/givewp#4928]
As a new user, I want see what link is for, so I know who to follow, and where.

Twitter link anchor on the right side of main heading of Welcome screen should be meaningful, not a %s placeholder/tag.

Text should probably be Follow GiveWP in Twitter

Navigate to `wp-admin/index.php?page=give-getting-started` on a site running GiveWP.

**Comment by jonwaldstein** [comment]
This seems to be have resolved since the addition of our new onboarding wizard.

Refs:
https://github.com/impress-org/givewp/pull/4917
https://github.com/impress-org/givewp/pull/5050
