### ISSUE TITLE
Confusing option for Welcome Screen in Settings Advanced

### ISSUE THREAD

**Issue by knutsp** [impress-org/givewp#4929]
The option label is "Welcome screen" and the description is "Enable this option if you want to disable the Welcome screen"

## Expected Behavior

1. Either the label must say "Disable Welcome Screen", or better
2. reverse the currently double negative and confusing logic, so "Enable this option to show the Welcome Screen" and have the default set to true (Welcome enabled).

**Comment by DevinWalker** [comment]
Hey thanks for posting this and sorry to took so long to get to. We actually removed the welcome screen for an onboarding wizard so this option under Settings > Advanced no longer exists.
