### ISSUE TITLE
Donation comment should integrate with the REST API

### ISSUE THREAD

**Issue by matheuswd** [impress-org/givewp#4934]
## User Story

As a site owner, I want to see an integration between the donation comment and the REST API so that I can use it within Zapier and transfer a third-party service.

## Details

Nowadays, the donation comment data is not passed to the REST API, preventing the site owner from using it on Zapier, for example.
The site owner should be able to see the donation comment on the REST API.

## Acceptance Criteria

-   [ ] Donation comment should be available on the REST API
-   [ ] Donation comment should be available on Zapier

**Comment by kjohnson** [comment]
Closing in favor of feedback feature request, see https://feedback.givewp.com/feature-requests/p/send-donor-comment-to-zapier.
