### ISSUE TITLE
Required fields should be reflected as such in the new multi-step form template

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#4944]
## User Story

As a donor, I want to be aware of required fields in the new Multi-step form template so that I'm not confused when I submit my donation.

## Details

Right now when you require a field, such as the "Title Prefix Field" or by default the "First Name" and "Email" fields there is no indicator that these fields are required in the multi-step form template. 

## Expected Behavior

Required fields should have an indicator such as an asterisk `*` that then is removed when the field is completed. 

## Steps to Reproduce

1. Create a new multi-step form template
2. Go to the payment step and see that required fields have no indicator

## Acceptance Criteria

- [x] A required `*` displays on required fields
- [x] The required indicator is compatible with all field types (including FFM fields)

**Comment by alaca** [comment]
@DevinWalker how we want to do this? 
| Current | Solution 1|  Solution 2 | 
|--|--|--|
| ![current](https://user-images.githubusercontent.com/4222590/103908899-53f13300-5103-11eb-83fa-5bea9b7b70f1.jpg) |  ![solution1](https://user-images.githubusercontent.com/4222590/103908944-61a6b880-5103-11eb-8c4d-e7ec8041b1d0.jpg) | ![solution2](https://user-images.githubusercontent.com/4222590/103908973-6ff4d480-5103-11eb-92e0-9e7a0255a56e.png) |

**Solution 3** would be to change the FFM fields to look like default form fields ( without labels ) but then we lose helper icon functionality.

**Comment by ravinderk** [comment]
[Recently in the core, we implemented a change](https://github.com/impress-org/givewp/issues/5160) to mark non-required fields as optional. 

![image](https://user-images.githubusercontent.com/1784821/103912242-07bae880-512d-11eb-82d2-3b5d85a707b2.png)


@DevinWalker @alaca  Are we planning to redesign? or will we already consider a past change when updating UI?

**Comment by DevinWalker** [comment]
@ravinderk I would rather keep it how it is with NON-required fields having the (optional) text. Otherwise we're going to have asterisks all over the donation form fields and it won't look good.

**Comment by henryholtgeerts** [comment]
This issue can be resolved by ensuring that the `setupOptionalInputLables` function (which should be renamed to fix typo), is called in `refreshPaymentInformationSection` (immedieately after `setupInputIcons` should do the trick). Currently `setupOptionalInputLables` is only called on form initialization, and only adds the "optional" text to fields within #give_checkout_user_info.

**Comment by alaca** [comment]
@henryholtgeerts thanks for pointing that out. This is also the FFM add-on issue as we have to change its fields to match the default form fields for consistency.

**Comment by ravinderk** [comment]
Slack discussion: @DevinWalker agrees to show asterisks as design decision instead of reflecting optional fields: https://lw.slack.com/archives/C02QJ8F07B3/p1656076203215979

![image](https://user-images.githubusercontent.com/1784821/175876458-21046fd9-df67-4ecd-853c-083a40e23893.png)
