### ISSUE TITLE
Admin should not see amount setting field with broken styling

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#4948]
## Details
As an admin, I can see that the amount of field styling broke on the latest WordPress.

## Additional Context
We use amount setting field in form metabox settings.
![image](https://user-images.githubusercontent.com/1784821/88316365-5c140c80-cd35-11ea-91d6-09489b61a0ed.png)
![image](https://user-images.githubusercontent.com/1784821/88316385-6504de00-cd35-11ea-846e-d9770cb7881e.png)
![image](https://user-images.githubusercontent.com/1784821/88316406-6df5af80-cd35-11ea-8b6e-c406624c207f.png)

## Acceptance Criteria
-   [ ] Amount setting field display correctly on the latest WordPress.
-   [ ] Style fix does not affect other form meta box setting fields.

**Comment by kjohnson** [comment]
Closing as stale.
