### ISSUE TITLE
Form templates should not require pretty permalinks

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#4952]
## User Story

As a site administrator, I want to publish a donation form with my existing permalinks structure.

## Details

The default permalink structure causes a 404 in the form template iframe, which results in a persistent loading animation.

## Expected Behavior

The form template iframe should load regardless of the site's permalinks configuration.

## Steps to Reproduce

1. Set permalinks to "Plain" (?p=123)
1. Create a new donation form
1. Set the form template to "Multi-Step Donation Form"
1. Click "View Form"
1. The form does not display

## Visuals

| Permalinks | Form Template |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/10858303/88419545-670d8200-cdb3-11ea-971f-3d33a0a34b34.png)  | ![image](https://user-images.githubusercontent.com/10858303/88419593-71c81700-cdb3-11ea-8c7e-1be59cacbc1c.png) |
|![image](https://user-images.githubusercontent.com/10858303/88419618-80163300-cdb3-11ea-97dc-6f65688fedf5.png) | ![image](https://user-images.githubusercontent.com/10858303/88419642-8a383180-cdb3-11ea-8815-2bcfa53fd078.png) |

## System Information

<details><summary>Details</summary>

### WordPress Environment ###

Home URL: https://wordpress.test
Site URL: https://wordpress.test
WP Version: 5.4.2
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: 
Show on Front: posts
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: wordpress.test
TLS Connection: Connection uses TLS 1.3
TLS Connection: Probably Okay
Server Info: Apache/2.4.41 (Ubuntu)
PHP Version: 7.4.3
PHP Post Max Size: 8 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
PHP Max Upload Size: 2 MB
cURL Version: 7.68.0, OpenSSL/1.1.1f
SUHOSIN Installed: –
MySQL Version: 8.0.20
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌ Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.7.2
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Tables: ✔ wp_give_donors -  1.0✔ wp_give_donormeta -  1.0✔ wp_give_comments -  1.0✔ wp_give_commentmeta -  1.0✔ wp_give_sessions -  1.0✔ wp_give_logs -  1.0✔ wp_give_logmeta -  1.0✔ wp_give_formmeta -  1.0✔ wp_give_sequential_ordering -  1.0✔ wp_give_donationmeta -  1.0
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt✔New Offline Donation✔Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note✔Email access
Upgraded From: –
Test Mode: Enabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://wordpress.test/?page_id=5
Failure Page: https://wordpress.test/?page_id=6
Donation History Page: https://wordpress.test/?page_id=7
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Test Donation, Offline Donation, Stripe - Credit Card
Default Payment Gateway: Test Donation
PayPal IPN Verification: Enabled
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: N/A

### Inactive Plugins ###

Classic Editor: by WordPress Contributors – 1.5
Give - Fee Recovery: by GiveWP – 1.7.11
Give - Form Field Manager: by GiveWP – 1.4.7
LifterLMS: by LifterLMS – 4.2.0
Ninja Shop: by Ninja Shop LLC – 1.1.11
Ninja Shop - Membership: by Ninja Shop LLC – 1.0.2
Ninja Shop - Recurring Payments: by Ninja Shop LLC – 2.0.2
Organized Search Results: by  –
Query Monitor: by John Blackbourn – 3.6.0
Video Library: by  –
WooCommerce: by Automattic – 4.3.1
WooCommerce Order Shipping Export: by Forge Media – 2020.06.23-12.53
WooCommerce Order Taxes Export: by Forge Media – 2020.06.17-12.55
WooCommerce Subscription Retention Summary: by Forge Media – 2020.06.23-12.53
WooCommerce Subscriptions: by WooCommerce – 3.0.1
WordPress Importer: by wordpressdotorg – 0.7
Yarnell Authorize.NET ARB (Automatice Recurring Billing): by  –

### Active MU Plugins ###

git-branch-names.php: by  –
load.php: by  –

### Theme ###

Name: Twenty Twenty
Version: 1.2
Author URL: https://wordpress.org/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

## Acceptance Criteria

- [x] Form Template Loads with "Plain" permalinks
- [x] Form Template Loads with"Post Name" permalinks
- [x] Form Template Loads with "Custom Structure" permalinks

**Comment by JasonTheAdams** [comment]
WordPress basically provides three options for API's:
1. WordPress REST API
2. Use `index.php` with a query string
3. As `admin-ajax.php`

It we're intending to provide a public resource, we should use #1. 

If it's in the admin-side, we should use #3. 

If it's front-end but intended for internal GiveWP use (i.e. not a public resource), then #2 is a solid option. Also, this is the only scenario wherein rewrites (i.e. permalinks) actually matter. Rewrites just take a regex and bind it to some `index.php?query_var=something` endpoint. To avoid issues with permalinks, the simplest scenario is to just forego the rewrite altogether and just use `index.php` directly.

**Comment by ravinderk** [comment]
I agree with @JasonTheAdams. Embed from iframe URL is for internal use and instead of setting a custom rewrite URL, we can take leverage of `index.php` with custom query parameter which will work on most cases.

**Comment by kjohnson** [comment]
I'll second foregoing the URL rewrite. In this case, the form is embeded in an iframe, so the pretty permalinks aren't required.

Additionally, it is important for features to work regardless of the permalink structure, which as Jason points out rewrites to query strings anyway.
