### ISSUE TITLE
Onboarding Wizard should use smart defaults for the currency based on the selected country

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#4974]
## Details

Onboarding Wizard should use smart defaults for the currency based on the selected country

## Additional Context

This assumes that we can source an accurate lookup for currency by country.

This should still allow the user to override any automatic change.

## Acceptance Criteria

- [x] When the country is changed the selected currency should update to a smart default.
- [x] The currency can be set manually after being updated to a smart default.

**Comment by henryholtgeerts** [comment]
This issue is blocked by work on #4970, where logic to add localized currency data is being introduced.

**Comment by kjohnson** [comment]
Looks like WooCommerce does use some sort of Country/Currency lookup. Setting the Country/State in the Setup Wizard configures the currency.

**Comment by kjohnson** [comment]
Found it: https://github.com/woocommerce/woocommerce/blob/master/i18n/locale-info.php

**Comment by kjohnson** [comment]
I accidentally  pushed the changes to `epic/plugin-onboarding` - I forgot to add the `-b` flag when creating a new branch and didn't notice that it failed.

Resolved by 99c96581f68c996a7b342e821b2ab4796e6f0b8f

**Comment by kjohnson** [comment]
US - USD
![Screenshot_2020-08-11 GiveWP › Onboarding Wizard(1)](https://user-images.githubusercontent.com/10858303/89947979-505c8d00-dbf3-11ea-84ae-28b15da80b4c.png)

UK - Sterling
![Screenshot_2020-08-11 GiveWP › Onboarding Wizard(2)](https://user-images.githubusercontent.com/10858303/89947985-53f01400-dbf3-11ea-98eb-19c747504a6f.png)

Turkey - Lira
![Screenshot_2020-08-11 GiveWP › Onboarding Wizard(3)](https://user-images.githubusercontent.com/10858303/89947991-55b9d780-dbf3-11ea-808e-975543273264.png)

Ukraine - No Default
![Screenshot_2020-08-11 GiveWP › Onboarding Wizard(4)](https://user-images.githubusercontent.com/10858303/89947995-57839b00-dbf3-11ea-92be-4190c5cbc197.png)
