### ISSUE TITLE
PayPal Commerce should show a notice in the donation form when it's enabled but not connected

### ISSUE THREAD

**Issue by JasonTheAdams** [impress-org/givewp#4991]
## User Story

As an admin, I want a notice to display in my form when PayPal Commerce is enabled but I haven't connected my account so that it's clear to me why it's not working and what I can do to fix it.

## Details

Presently, when the PayPal Commerce gateway is enabled for a form it tries to work every time by showing the PayPal Smart Buttons and the Advanced fields. The Smart Buttons request times out and the Advanced fields just won't work. Things fail and it's not at all clear as to why.

We need to prevent the Smart Buttons from attempting to load and instead display a message where the buttons and inputs would go that explains why the gateway isn't working and what the admin can do to fix it.

## Additional Context

![image](https://user-images.githubusercontent.com/2024145/89235655-75258480-d5a3-11ea-8098-dcf980eeb7b0.png)

## Acceptance Criteria

-   [ ] PayPal Commerce scripts do not run, so not errors show up in the console
-   [ ] A message displays where the fields would that guide the user through the problem
-   [ ] The form works as expected once the account is connected

**Comment by mathetos** [comment]
We do this for Stripe already. We should implement this in the same way. And I prefer that notices like this would be in the admin and not donor-facing. 

![image](https://user-images.githubusercontent.com/930724/89237090-21b53580-d5a7-11ea-8f8d-8895ee1e7374.png)

**Comment by JasonTheAdams** [comment]
Thanks, @mathetos! I was considering this _in addition_ to an admin notice. Right now if Stripe is used in a form and it's not connected, it just displays nothing. Is this the UX we want to stick with?

![image](https://user-images.githubusercontent.com/2024145/89237762-ea478880-d5a8-11ea-8f12-5afc904141be.png)

**Comment by mathetos** [comment]
Personally, I think if we're putting a notice on the frontend form it should be with the donor's best interest in mind. So, a form notice should say something to the effect of:

> The Stripe payment gateway has not yet been configured to accept donations. Please notify {admin email address} to enable credit card payments in this form.

**Comment by JasonTheAdams** [comment]
I'm fine with that. What do you think, @DevinWalker @kevinwhoffman?

I'm also tempted to broaden this issue to Stripe as well.

**Comment by kevinwhoffman** [comment]
The underlying issue is that it is currently possible to "enable" a gateway even if it's not actually connected and capable of accepting donations. It seems to me we should put up some guardrails to prevent that from happening in the first place.

 I do agree that the solution here should apply to all gateways if it's possible to build that logic into core.

**Comment by JasonTheAdams** [comment]
@kevinwhoffman I agree that this is a [guardrails](https://app.gitbook.com/@give/s/development-manual/principles/bugs-vs-guardrails) issue. As such, it should probably only be "fixed" if users actually report the issue. Even if we prevented folks from enabling unconnected gateways, they could still disconnect a gateway once enabled. Determining which guardrails to put up could become a moving target.

I'm considering just closing this issue, making a feature (bug?) in Canny, and referencing this issue. What do you think?

**Comment by JasonTheAdams** [comment]
@DevinWalker This issue is older and my last inclination was to close it. I recall that you were the one the originally bring up the idea, so what do you think?
