### ISSUE TITLE
Container docblocks should be marked @since 2.7.3

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#5002]
## Details

The new container was released in 2.7.3, but the codebase is marked as 2.8.0 (which has not yet been released).

## Additional Context

```php
	/**
	 * Give constructor.
	 *
	 * Sets up the Container to be used for managing all other instances and data
	 *
	 * @since 2.8.0
	 */
	public function __construct() {
		$this->container = new Container();
	}
```

## Acceptance Criteria

-   [ ] Dockblocks for container related methods and properties are marked `@since 2.7.3`

**Comment by DevinWalker** [comment]
Not a priority
