### ISSUE TITLE
PayPal commerce user facing options should match Figma design

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#5003]
## User Story

As a developer, I want to match Figma design so that user facing options look nice.

## Details
After reviewing Figma design, I find out that few things we can improve:
- The payment options separator is missing.
![image](https://user-images.githubusercontent.com/1784821/89378822-44b02880-d712-11ea-83db-149003b95cbd.png)

- The credit card icon is missing.
![image](https://user-images.githubusercontent.com/1784821/89378935-7e812f00-d712-11ea-95d3-bb7ccf347e12.png)

- Smart buttons are stacked vertically instead of horizontal.
![image](https://user-images.githubusercontent.com/1784821/89379112-d15ae680-d712-11ea-8b7d-f34b03e6196e.png)

- Button tooltip is missing inadmin setting.
![image](https://user-images.githubusercontent.com/1784821/89380693-91493300-d715-11ea-971a-24d54517fb6a.png)

## Acceptance Criteria
-   [x] Payment method options style match Figma design

**Comment by kevinwhoffman** [comment]
@ravinderk It looks like you may be implementing a side-by-side design of the smart buttons, however @JasonTheAdams mentioned that the `PayPal Credit` button will not be visible in the plugin since it doesn't make sense in a donation context.

We do need to account for the fact that Google Pay or Apple Pay buttons may be visible in addition to the main PayPal button, so I think a stacked layout is preferred.

**Comment by ravinderk** [comment]
@kevinwhoffman Horizontal button looks good. Other than `PayPal Credit` there are other options that will appear with the smart buttons payment method for example `Venmo`.

cc: @JasonTheAdams 

![image](https://user-images.githubusercontent.com/1784821/89439484-e57d0300-d767-11ea-942e-535a12ce258a.png)

**Comment by kevinwhoffman** [comment]
If we end up having to use the `Debit or Credit Card` smart button, then that user experience involves the smart buttons collapsing and revealing the credit card fields. You can see that behavior in the [demo](https://developer.paypal.com/docs/checkout/#try-the-buttons) when clicking the black button. In this case, the side-by-side design would be problematic.

![image](https://user-images.githubusercontent.com/1938671/89440181-44fff200-d719-11ea-9935-bf3f08fce2ce.png)

This all depends on whether we need to use the `Debit or Credit Card` smart button, which should be clarified in the next day or so when the meeting with PayPal happens.

**Comment by ravinderk** [comment]
@kevinwhoffman If we end up using `Debit and Credit Card` payment button then I confirmed that this payment option will not appear in `vertical` layout: https://developer.paypal.com/demo/checkout/#/pattern/horizontal, so for that payment option we have to use `horizontal` layout for Smart Buttons.
