### ISSUE TITLE
Setup Page should provide better instructions for configuring Stripe webhooks.

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#5015]
## User Story

As a site owner, I want understand how to configure my Strip webhooks so that I can accept donations.

## Details

Instructions for configuring Stripe webhooks do not include steps for selecting what events to send, which is required to configure the webhooks.

## Additional Context

> I also noticed that when you actually go to add the endpoint in Stripe, you have to manually select which events to listen for (or optionally, add all of them). This was sorta confusing to me as a user, since I didn't get any heads up about it in the paragraph on the Setup Page. Maybe clarifying this in the copy would be helpful, especially since our check to see if the Webhook is configured is based on listening for a specific event. @henryholtgeerts 

> I've also noticed that we tell the user to enable all events, and Stripe explicitly suggests not doing this. @JasonTheAdams 

## Acceptance Criteria

-   [ ] The user understands how to configure Stripe webhooks.

**Comment by kevinwhoffman** [comment]
If we do decide to provide instruction for specific events, let's make sure we've reviewed our [current webhooks documentation](https://givewp.com/documentation/add-ons/stripe-gateway/#webhooks) and keep the docs team informed so that the web doc matches the contextual doc .

> Note: It is recommended to send all events over the webhook so that if Give is updated in the future to use any events that it currently does not, those will send as well. Unless your site is processing thousands of donations per day or more, you should have no issue with sending all events, and you can ignore the warnings from Stripe.

**Comment by kevinwhoffman** [comment]
@kjohnson Can you share a screenshot of what the new Setup Page currently looks like after connecting to Stripe but before the webhook is configured? It's important to see what we are starting with so we can improve it.

**Comment by kjohnson** [comment]
@kevinwhoffman 

Setup Page
![image](https://user-images.githubusercontent.com/10858303/89934741-0ec1e700-dbdf-11ea-8bce-9d0805106f9f.png)

Stripe Settings
![image](https://user-images.githubusercontent.com/10858303/89934851-36b14a80-dbdf-11ea-9424-43e50b35f975.png)

**Comment by kjohnson** [comment]
I'm thinking of hiding the PayPal row if Stripe is configured (and vica versa) to focus on the configured gateway. This would simplify the step and afford Stripe more space to communicate the webhooks requirements.

![image](https://user-images.githubusercontent.com/10858303/89935567-5b59f200-dbe0-11ea-87d3-e537dd56a08d.png)

**Comment by kevinwhoffman** [comment]
> I'm thinking of hiding the PayPal row if Stripe is configured (and vica versa) to focus on the configured gateway.

That makes sense to me since this is focused on new users who are likely choosing one or the other.

**Comment by kjohnson** [comment]
Testing hiding PayPal when Stripe is configured, I think this will also help bring attention to Stripe needing webhooks configured.

**Comment by kevinwhoffman** [comment]
Following up here to say after discussing with @DevinWalker and @JasonTheAdams, we decided to continue recommending all events since it is our current recommendation, less prone to user error, and the most future-proof.

We can work out the exact copy while this is in alpha. Just noting that decision for now.

**Comment by kevinwhoffman** [comment]
I will prioritize establishing a clear direction of the Stripe messaging and follow up here today.

**Comment by kevinwhoffman** [comment]
Closing after we learned that attempting to test and confirm a Stripe webhook from the Setup Page might actually introduce more confusion than it is worth.

See this [call summary](https://github.com/impress-org/givewp/issues/5170#issuecomment-677907686) and PR https://github.com/impress-org/givewp/pull/5171 for a resolution to the Stripe Connect workflow.
