### ISSUE TITLE
Onboarding Wizard should load with selected Features and Add-ons.

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#5040]
## Details

The Features and Add-ons selected in the Onboarding Wizard are persisted to the Draft Form and `give_onboarding` settings, respectively. These values should be pre-loaded in the Wizard when it is re-launched.

## Acceptance Criteria

-   [ ] A selected feature is pre-selected when the Wizard is re-launched.
-   [ ] A de-selected feature is not pre-selected when the Wizard is re-launched.
-   [ ] A selected add-on is pre-selected when the Wizard is re-launched.
-   [ ] A de-selected add-on is not pre-selected when the Wizard is re-launched.

**Comment by kevinwhoffman** [comment]
@kjohnson It looks like a PR was merged to resolve this issue, but the issue is still open and the accept criteria are not checked. Can you confirm and close if necessary?

**Comment by kjohnson** [comment]
@kevinwhoffman yeah, just an oversight.
