### ISSUE TITLE
Onboarding should be configured for new and existing installs

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5046]
## User Story
As a user, I want the Onboarding experience to logically insert itself into the install/update process so that I am not shown Onboarding screens when I don't want to see them, and I do see them if I need them.

## Details
The Onboarding experience consists of a Wizard and a Setup page. Whether or not/when a user sees each of these screens should logically fit into the install/update process. Currently, the Setup page is primarily controlled via a setting in the Advanced settings tab, and the Onboarding Wizard fails to consistently appear on fresh installs. 

## Acceptance Criteria
**Fresh Installs**
- [x] For fresh installs, the Onboarding Wizard should appear following plugin activations (i.e. WooCommerce)
- [x] For fresh installs, the Setup Page should be `Enabled` by default in Advanced settings.

**Existing installs**
- [x] For updates of existing installs, the Onboarding Wizard should **NOT** appear
- [x] ~For updates of existing installs, the Setup Page should be `Disabled` in the Advanced settings~

Edit: Removed "For updates of existing installs, the Setup Page should be `Disabled` in the Advanced settings" because the setting is disabled by dismissing the Setup Page, otherwise an update would unintentionally remove the Setup Page when in use.

**Comment by kjohnson** [comment]
Blocked by the `hotfix` for the missing database tables in a fresh install.

**Comment by kjohnson** [comment]
Note to self, I'm getting the following errors on activation. I need to follow-up after the hotfix.

- Undefined index: thousands_separator in .../includes/admin/upgrades/upgrade-functions.php on line 1388
- Undefined index: decimal_separator in .../includes/admin/upgrades/upgrade-functions.php on line 1388
- Undefined index: currency in .../includes/admin/upgrades/upgrade-functions.php on line 1652
