### ISSUE TITLE
Copy in Onboarding Wizard and Setup Page should be reviewed

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5047]
## User Story
As a user, I want the Onboarding experience to include appropriate/relevant copy and options so that I am not confused, misdirected or let down by the product early on in installation.

## Details
The Onboarding experience consists of a Wizard and a Setup page. Both pages employ copy to instruct the user on steps, make the user aware of give features, or provide options for the user as they discover what GiveWP can do for them. Throughout the Onboarding experience there are small areas of copy which need to fleshed out or revisited.

## Acceptance Criteria
- [x] Select your cause input includes relevant/popular Cause types
- [x] Typo is resolved in subtitle of step 3
- [x] Form Preview step copy is reviewed and improved
- [x] Step 5 subtitle is reviewd to address the fact that all listed addons are premium (not free)
    - > What else do you need to support your cause?
      > Take your fundraising to the next level with these premium add-ons.
- [x] All feature cards on Setup Page are reviewed
- [x] Typo is PayPal card on Setup Page is resolved
- [x] Copy at the top of Setup Page should be removed (approved by Devin in Slack)
- [x] Apostrophe in PayPal description should be correctly escaped
    - > It\’s been the go-to payment merchant...

**Comment by kevinwhoffman** [comment]
@henryholtgeerts I reviewed and updated the acceptance criteria of this issue to reflect the remaining copy updates that need to be made. Can you take care of them in a single PR?
