### ISSUE TITLE
Unused code and assets from the old Getting Started screen should be removed

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#5049]
- [x] Getting Started tab and assets should be removed
- [x] What's New tab and assets should be removed

**Comment by kjohnson** [comment]
@kevinwhoffman @DevinWalker Looks like the Readme Parser is used by a filter that checks minimum version.

```php
	$parser           = new Give_Readme_Parser( $url );
	$give_min_version = $parser->requires_at_least();

	if ( version_compare( GIVE_VERSION, $give_min_version, '<' ) ) {
		return new WP_Error(
			'Give_Addon_Update_Error',
			sprintf(
				__( 'GiveWP version %s is required to update this add-on.', 'give' ),
				$give_min_version
			)
		);
	}
```

**Comment by kevinwhoffman** [comment]
@kjohnson Good catch. Update the acceptance criteria accordingly so we're not removing anything that will still be needed after 2.8.0.
