### ISSUE TITLE
Onboarding Wizard should not scroll horizontally.

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#5069]
## Details

There is a slight horizontal scroll on the Preview step.

![Horizontal scroll bar in Preview Step](https://user-images.githubusercontent.com/10858303/90068503-bf52e800-dcbe-11ea-8563-6b322c52bb21.png)

## Acceptance Criteria

-   [ ] Preview donation form is horizontally fixed.

**Comment by henryholtgeerts** [comment]
This issue is resolved by this commit: https://github.com/impress-org/givewp/pull/5077/commits/aef5f6bc6272cfb7e8377bfecba08260c19c14b2 in the Onboarding Wizard design loose ends PR. With this in mind, I'm closing this issue.
