### ISSUE TITLE
Onboarding default focus state should not be confused with default selected state

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#5072]
## Details

When first opening the Onboarding Wizard the user does not have context of whether the green outline is the focus state of the selected state.

| Default Focus State | Selected State |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/10858303/90070907-a8ae9000-dcc2-11ea-815f-3653d08e7637.png) | ![image](https://user-images.githubusercontent.com/10858303/90070930-b2d08e80-dcc2-11ea-9938-c202cec4be12.png) |

## Acceptance Criteria

-   [ ] Card Inputs are not focused by default.
-   [ ] Tabbing starts at the first input/element of the form.

**Comment by henryholtgeerts** [comment]
I’ve felt this is a problem as well. I think the approach of not automatically focussing inputs makes sense. Other option might be to add some kinda of greyed-out check to each card, but that might look clunky. 

Unsure how significantly exactly the decision not to focus inputs on step load would impact accessibility.

**Comment by kjohnson** [comment]
In my testing, after removing the default focus, tabbing focuses the element that would otherwise have been auto-focused.
