### ISSUE TITLE
Onboarding Wizard should require confirmation before navigating away from a dirty form

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#5074]
Imported from a project card created by @kevinwhoffman

**Comment by kjohnson** [comment]
@kevinwhoffman can you elaborate on this?

**Comment by kevinwhoffman** [comment]
I was on Step 5 of the wizard and swiped backwards on my touch pad which took me to the Wizard welcome screen. None of my progress was saved so I had to start over. I don't expect that we persist the data after every step, but a simple modal to confirm I am navigating away from the wizard would have saved me from starting over.

We have a reusable modal solution in GiveWP that I think you should be able to use.
