### ISSUE TITLE
"One Time Donations" feature should be replaced with a feature that is toggleable

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#5075]
In the Weekly Development call, we discussed replacing the "One Time Donations" feature with one that could be toggled.

**Comment by kjohnson** [comment]
I remember discussing "Social Sharing" and "Custom Donations" as possible replacements.

If I remember correctly, toggling of "Custom Donations" would break the clean 2x3 grid of payment amounts, so we were leaning in favor of "Social Sharing".

**Comment by kevinwhoffman** [comment]
> I remember discussing "Social Sharing" and "Custom Donations" as possible replacements.

Yeah neither of those feel like clear winners, so let's wait for alpha feedback to address this.
