### ISSUE TITLE
New Gutenberg related functionality making blocks selectable should not break Form Preview

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5080]
## User Story

As a user, I want Form Preview to load correctly, even with new code aimed at making blocks selectable within the Gutenberg editor, so that I have the expected Onboarding experience.

## Details
Previously, the Form Preview loaded as expected. Since merging new code from `develop` into the Onboarding `epic` branch, a JS error prevents the Form Preview from loading correctly. Specifically, the Multi-Step form displays all steps at once, in a long column.

## Expected Behavior
The Form Preview should not run into any breaking JS errors on load, and display the Multi-Step form inside the Onboarding Wizard as it does anywhere else on the site.

## Steps to Reproduce
1. Go to the Onboarding Wizard (`wp-admin/?page=give-onboarding-wizard`)
2. Navigate to the Form Preview step
3. See how Form Preview loads incorrectly (all steps at once)
4. Open JS console, view associated error

## Visuals

How the page currently displays:
![screencapture-givewp-local-wp-admin-2020-08-13-06_47_48](https://user-images.githubusercontent.com/5186078/90142462-3f199a80-dd31-11ea-8f66-99591854f109.png)

Associated error, leading to the issue:
<img width="368" alt="Screen Shot 2020-08-13 at 6 48 28 AM" src="https://user-images.githubusercontent.com/5186078/90142478-4476e500-dd31-11ea-8fbb-670a297e587f.png">

## Acceptance Criteria
-   [ ] Form Preview loads as expected
-   [ ] No blocking errors appearing the JS console related to the Form Preview

**Comment by kevinwhoffman** [comment]
@henryholtgeerts Can you clarify whether you believe this error is limited to the form preview in the wizard, or whether you think it may be affecting other forms on live sites that are upgrading to 2.7.5?

**Comment by henryholtgeerts** [comment]
@kevinwhoffman Confusingly, as best I can tell it is only affecting forms in the Form Preview step of the Onboarding Wizard.
