### ISSUE TITLE
Setup Page should communicate completed steps

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#5082]
When I land on the Setup Page after the Onboarding Wizard, my first instinct is to click "First-Time Configuration" because it is labeled Step 1. However this takes me right back to the Wizard.

**Comment by kjohnson** [comment]
I'm looking at bringing the check mark into the Setup Page design to complete each step. This could also apply to the payment gateway and potentially the add-ons (when installed).

<img width="1204" alt="Donation Form(2)" src="https://user-images.githubusercontent.com/10858303/90149161-2ff71480-dd52-11ea-8288-8d9768c829f2.png">

**Comment by henryholtgeerts** [comment]
@kjohnson I like this direction! I think this PR should also ensure that the "completed" badge functionality is actually in place, and aesthetically matches the completed badge design suggested in the Figma boards

**Comment by kjohnson** [comment]
I'm thinking of dropping the completed badge, in favor of the check mark, but keeping the 5 - 10 minutes badge to communicate quick process (may re-word to 5 minutes).

**Comment by kevinwhoffman** [comment]
> I'm thinking of dropping the completed badge, in favor of the check mark

I agree with dropping the completed badge in favor of the more visible green check mark. While we want to respect the designs in Figma, we should also be flexible enough to adapt them if needed. After user testing, this is a valid time to adapt the designs to better meet user expectations.

In addition to the green check, striking out the completed step title would further indicate that the user has already "crossed the item off the list."

```css
text-decoration: line-through;
```

See this HubSpot example:
![image](https://user-images.githubusercontent.com/1938671/90150491-b829e980-dd53-11ea-8cf8-43d8239a02fa.png)

**Comment by kjohnson** [comment]
Yeah - I'm good with that.

**Comment by kjohnson** [comment]
![image](https://user-images.githubusercontent.com/10858303/90151335-9c731300-dd54-11ea-8522-1c61a9c959c2.png)

**Comment by kevinwhoffman** [comment]
@kjohnson I think that works well. It's definitely more clear that the step has been completed with the checkmark and `line-through` style, and the text itself still remains legible and accessible to screen readers. Let's move forward with this and see what feedback we get in alpha.

**Comment by kjohnson** [comment]
![image](https://user-images.githubusercontent.com/10858303/90152608-fd4f1b00-dd55-11ea-82ec-1a2bcedf638b.png)
