### ISSUE TITLE
Configure Webhooks button should send user to Stripe dashboard in whichever mode their site is currently in

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5095]
## User Story

As an admin, I want to be able to quickly configure Stripe webhooks so that I have an easy onboarding experience.

## Details

Currently, the Configure Webhooks button sends users to the Stripe dashboard in Live mode. Naturally, users then setup their GiveWP endpoint in live mode. However, their actual GiveWP site is most likely in Test mode, which means it won't hit the Live mode endpoint in Stripe.

To correct this, send users to the Stripe dashboard in whichever mode their Site is currently in.

## Steps to Reproduce
On a Fresh install:
1. The Setup page (`wp-admin/?page=give-setup-page`)
2. Copy endpoint URL from Stripe setup section
2. Click Configure Webhooks
3. Paste endpoint/setup new webhook
4. Return to the Setup Page, and see if Stripe Webhook spinner has updated
5. Check Stripe dashboard, and see if any Webhook attempts have been made

## Acceptance Criteria
-   [x] Configure Webhooks button directs users to the Stripe dashboard in the correct mode, so that configuration can happen without needing to know about Test/Live mode settings

**Comment by kevinwhoffman** [comment]
Definitely need to address it before release, but it doesn't need to be in alpha. For now, provide clear Testing Instructions regarding what mode Stripe should be in when setting up the webhook.

We'll make this process "smarter" in the coming days.
