### ISSUE TITLE
PHP 5.6 should not cause a fatal error on activation

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/givewp#5099]
## User Story

As an admin with a host on PHP 5.6.39, I want GiveWP to activate without a fatal error so that I can continue on to the onboarding wizard.

## Details

Fatal error prevents activation.

## Expected Behavior

Plugin activates and I view the onboarding wizard.

## Steps to Reproduce

1. Attempt to install GiveWP on a server matching the system info provided below.

## Visuals

![image](https://user-images.githubusercontent.com/1938671/90190165-8123fa00-dd8c-11ea-9c13-d51718e22a65.png)

## System Information

<details><summary>Details</summary>

Apache
PHP 5.6.39
MySQL 5.7.28
WP 5.5.0

</details>

## Acceptance Criteria

-   [ ] GiveWP can be activated on PHP 5.6.x without error

**Comment by kevinwhoffman** [comment]
@JasonTheAdams @DevinWalker I'm getting this activation error on the `epic/plugin-onboarding` branch. It does not appear to be a problem with the latest public release of GiveWP 2.7.5.

**Comment by kjohnson** [comment]
Looks like the error is thrown by PHPUnit, which wouldn't be deployed. PHPUnit hasn't supported 5.6 in a long time.

**Comment by kjohnson** [comment]
Come to think of it, I think I did update the version in the epic branch, so seeing this error now makes sense.

**Comment by JasonTheAdams** [comment]
The hotfix changes have been pulled into `develop`, did that get pulled into the onboarding epic branch?



> Looks like the error is thrown by PHPUnit, which wouldn't be in the release. PHPUnit hasn't supported 5.6 in a long time.

It should be using an older version of PHPUnit that does still supports 5.6.

**Comment by kjohnson** [comment]
Looks like phpunit wasn't originally in composer.json, so I had installed it to run tests.

![image](https://user-images.githubusercontent.com/10858303/90191714-61da9c00-dd8f-11ea-985d-e5ebfd0c723d.png)

https://github.com/impress-org/givewp/commit/2c4e8f29e2182531537cbfa0be2f495af9bd4c26

**Comment by kjohnson** [comment]
I can remove phpunit from the project and use a global install.

**Comment by JasonTheAdams** [comment]
I'm fine with having phpunit in the project — in fact it would be nice — but we need to make sure it's a version that supports PHP 5.6 — PhpUnit 5.x.
