### ISSUE TITLE
Typo in Options for Terms and Conditions 

### ISSUE THREAD

**Issue by bradleysa** [impress-org/givewp#5109]
## Details

Version 2.7.5 - There's a typo in the admin options for "Settings > Default Options > Terms and Conditions"

Current: Would you like donors to require that donors agree to your terms when donating?

It could be updated to:
Would you like to require that donors agree to your terms when donating?

## Acceptance Criteria

-   [x] The typo has been fixed.

**Comment by DevinWalker** [comment]
Thanks for finding that!
