### ISSUE TITLE
Multi-Step form should clarify required vs. optional fields

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5112]
## User Story

As a user, I want the Multi-Step for to indicate required feilds so that I know which fields I must fill out, rather than simply relying on validation notices.

## Details
Currently, the Multi-Step form does not indicate what fields are required vs those that are optional.

## Acceptance Criteria
-   [x] Required fields are differentiated from optional fields.

**Comment by henryholtgeerts** [comment]
Some discussion has happened regarding different design directions to go in indicating a required field. Some options include:
- Asterisk following the inline label (inspired by floating labels in material design)
- Red outline or underline on field input

**Comment by kjohnson** [comment]
My suggestion is to mark optional fields instead of required fields - highlight the exception and not the rule.

This communicates required fields with less overhead, especially in this case where almost all of the fields are required.

![image](https://user-images.githubusercontent.com/10858303/90441813-96a86500-e0a7-11ea-8177-a76f882c37a4.png)

**Comment by kevinwhoffman** [comment]
> My suggestion is to mark optional fields instead of required fields - highlight the exception and not the rule.

Agreed. I've updated the issue title to reflect the desired outcome is to understand the difference between required vs. optional.

@henryholtgeerts Before giving this the green light, can you confirm for me how FFM fields currently render in the multi-step form and how they are marked required?

**Comment by kjohnson** [comment]
@kevinwhoffman FFM renders below the donation amount and marks _required_ fields with a red asterisk after the label.

![image](https://user-images.githubusercontent.com/10858303/90638451-56f29200-e1fb-11ea-9c8d-6bf254391dbc.png)

**Comment by henryholtgeerts** [comment]
@kevinwhoffman Seconding the screenshots from @kjohnson, with one caveat: the placement of the FFM fields depends on what the admin sets for Form Field Location. Ideally, the default for this option, when using Multi-Step should be 'Below personal info fields'. 

<img width="581" alt="Screen Shot 2020-08-19 at 6 59 06 AM" src="https://user-images.githubusercontent.com/5186078/90644781-ff97f600-e1e9-11ea-9a04-fa9c3ccd3704.png">

**Comment by kjohnson** [comment]
Ah, I didn't see that. Makes sense. Yeah, these should be updated to match the context of the containing form template.

**Comment by kevinwhoffman** [comment]
@kjohnson I understand the presentational inconsistencies across core fields and FFM fields, but that feels like a rabbit hole given the number of FFM field types that would have to be updated.

Let's keep the scope of this issue limited to clarifying the difference between required and optional fields in a multi-step template using GiveWP core. With that said, let's move forward with Kyle's recommendation of the `(optional)` text in the placeholders.

![image](https://user-images.githubusercontent.com/10858303/90441813-96a86500-e0a7-11ea-8177-a76f882c37a4.png)

**Comment by kjohnson** [comment]
@kevinwhoffman @henryholtgeerts I created a separate issue for FFM, see impress-org/give-form-field-manager#322.
