### ISSUE TITLE
Donation goal should display the total amount without fees

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5113]
## User Story

As a user, I want the Donation Goal total to be displayed without fees so that I have a better understanding of how close the goal actually is to completion.

## Steps to Reproduce

1. Go to...
2. Select...
3. Scroll down to...
4. View error

## System Information

<details><summary>Details</summary>

</details>

## Acceptance Criteria

-   [ ] Something happens when an action is taken.
-   [ ] Something does not happen when an action is taken.
-   [ ] Fixing behavior in Component A does not affect existing behavior in Component B.

**Comment by kjohnson** [comment]
Relevant information provided by @kevinwhoffman via [Bug Report](https://givewp.canny.io/admin/board/bug-reports/p/donation-goal-should-display-the-total-amount-without-fees):

> ## Base Revenue
> Base revenue represents the intended donation amount before fee coverage comes into play. The base amount is the amount that the donor chose to give during the first step of the donation process. The donor's choice of whether or not to cover the fee does not affect base revenue.
>
> If the donor does not cover fees, then the base is equal to the gross.
> `Base Revenue = Gross - Covered Fees`
>
> ### Examples
> - If a donor gives $100 and covers $6 in fees, then the base amount is $100.
> - If a donor gives $100 and covers no fees, then the base amount is still $100.
>
> https://app.gitbook.com/@give/s/give-io/key-concepts/revenue#base-revenue

**Comment by kevinwhoffman** [comment]
We decided not to change the behavior of goal progress, so this feedback was closed in Canny with an explanation here:
https://feedback.givewp.com/bug-reports/p/goal-should-display-net-revenue-total-amount-minus-fees
