### ISSUE TITLE
A consistent changelog standard should be implemented

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/givewp#5116]
## Details

The goal is to offload the responsibility of a single person having to keep track of changes and instead delegate that responsibility to the development team. This should result in a more thorough and accurate changelog for contributors to reference and friendlier release notes for our users.

### Current

- `readme.txt` - changes made after GiveWP 2.0.0
- `changelog.txt` - changes made prior to GiveWP 2.0.0

### Proposed
- `CHANGELOG.md` - complete developer changelog updated with each pull request (follows [Keep a Changelog](https://keepachangelog.com/) standard)
- `readme.txt` - user-friendly release notes that are updated prior to a major/minor/patch release (does not need updated for alpha/beta releases)
- `changelog.txt` - remove (?) as it hasn't been updated since 2017 and could create confusion with `CHANGELOG.md`

## Acceptance Criteria

-   [x] `CHANGELOG.MD` has been added according to the [Keep a Changelog](https://keepachangelog.com/).
-   [x] Changes added after GiveWP v2.7.5 have been noted in the `Unreleased` section.

**Comment by kevinwhoffman** [comment]
@DevinWalker @JasonTheAdams Can you review the proposed implementation and specifically let me know your thoughts on deleting `changelog.txt` which hasn't been updated since 2017?

**Comment by JasonTheAdams** [comment]
Looks good to me! Since the `changelog.txt` hasn't been updated in so long, I'm perfectly fine with removing it. It's not really relevant anymore, and anything we want to know that far back will likely be done via blame and such — in which case we can always get this file in version history, too.
