### ISSUE TITLE
Minimum donation amount should be $5 rather than $1 to prevent card testing

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#5119]
## Details

When user's don't increase the default minimum donation amount and have custom amounts enabled they are susceptible to card testing. While not widespread, it has occurred a few times with Stripe and it's a pain to get it resolved. This should help further protect implementations from card testing.

## Additional Context

It's as quick as updating the default setting.

## Acceptance Criteria

-   [x] The min. amount default is $5 not $1

**Comment by dschaper** [comment]
I'm getting nailed by this right now.

Amount doesn't change anything. Carders don't care if they push though $1 or $5 or $10. All they are looking for is a success message. 

What needs to be fixed is not processing 400 cards on a single donor in less than 3 minutes. 

![Screenshot_2020-09-11 Search – pi-hole net – Stripe(2)](https://user-images.githubusercontent.com/2782850/92950438-7d2ddb00-f411-11ea-9b49-34b6e2f35811.png)

**Comment by dschaper** [comment]
Maybe something to prevent a donor from having 4 dozen payment methods to an account?

![Screenshot_2020-09-11 Customers – pi-hole net – Stripe](https://user-images.githubusercontent.com/2782850/92950714-fc231380-f411-11ea-84a9-172a942b51ee.png)
