### ISSUE TITLE
Onboarding Wizard Cause Type should be de-selectable or offer an "other" option.

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#5133]
> The "what is your cause" dropdown on step one should have an "other" option, or ability to unselect the cause once you click on one.
>
> Currently I click one, and if I don't want that one, I'm stuck with it. if I'm not a school or religious cause, I can't unselect without a page refresh.
>
> @Benunc

**Comment by telizarose** [comment]
This section should have additional fields including "other"
This [Slack thread](https://givewp.slack.com/archives/G017A89LKSN/p1597338862058700?thread_ts=1597272786.053600&cid=G017A89LKSN) outlines: 

- Educational
- Religious
- Political
- Environmental
- Advocacy
- Health

![image](https://user-images.githubusercontent.com/38927530/90553618-8b0d7a80-e149-11ea-96a7-63a314f9b75a.png)

**Comment by kevinwhoffman** [comment]
@telizarose Thanks for adding that list here.

@kjohnson Let's implement the list Taylor provided with `Other` as the final option in the list.
