### ISSUE TITLE
Onboarding with country should be simple and intuitive

### ISSUE THREAD

**Issue by JasonTheAdams** [impress-org/givewp#5140]
## User Story

As an admin, I want to connect my PayPal account with the right country so that it works properly.

## Details

Presently, there are two fields in the PayPal Commerce settings: the button to connect, and the country of the account. When the button is clicked it immediately starts the onboarding, using the country. In order to change the country, however, the user needs to change it in the dropdown and then click "Save changes". It's very easy to imagine a setting (in fact I've made this mistake myself while testing) where the user selects the country the in the dropdown and then clicks "Connect" button. It _feels_ like the country is selected, but it hasn't been applied.

An important note here, is that we only need the country when the user is connecting. They really shouldn't be able to change the country after being connected. In fact it does nothing. Perhaps we can come up with a way of asking for the country when the user goes to connect?

Video: https://share.getcloudapp.com/6queQZ2K

## Acceptance Criteria

-   [x] User is able to reliably connect with the correct country

**Comment by JasonTheAdams** [comment]
@DevinWalker Could I please get your UX/UI input on this?

**Comment by DevinWalker** [comment]
@JasonTheAdams I just reviewed your video and have my response here: https://www.loom.com/share/16132441153a467684162705706c9f9f 

Please review and let me know if it's possible what I'm aiming for here. If you have question, let's jump on a call!

**Comment by JasonTheAdams** [comment]
Thanks for the video response, @DevinWalker! Just to clear something up with regards to my mentioning a potential modal approach: What I was really trying to point out is that the country field only applies _when the user is onboarding_. So if an account is already connected, we either need to hide or disable that setting.

Let's contrast that to say, a setting where folks can set the color of the PayPal Button. That button is always relevant and can be changed at any point, reflecting the change on the front-end. The country, on the other hand, only needs to be provided when the user goes to connect their account — it doesn't really even need to be stored. We use the country to know whether to set them up as an Express or PPCP account when onboarding. That's it.

That's why I was wondering if it would be helpful to visually or otherwise tie the country selection to the onboarding flow. Perhaps put a box around the Country and Connect button settings, or display a modal to get their country when they click on the "Connect" button, or something like that. Once they're connected, the country is no longer a setting they should worry about.

Does that make sense?

**Comment by JasonTheAdams** [comment]
@DevinWalker This is still waiting on your response when you have a chance. 😄

**Comment by JasonTheAdams** [comment]
Had a call with @DevinWalker and we're going with the following:

### When the account is not connected
- Display the country field
- Hide all other fields
- When the "Connect with PayPal" button is clicked, pass the country so it's not necessary to "save settings"

### When the account is connected
- Hide the country field
- Show other settings (when there are any)
- Show the connected account details
