### ISSUE TITLE
Default select field behavior should be clarified

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#5162]
- [x] Optional select fields such as `State` should use a `Select...` placeholder
    - 📸 [Screenshot](https://cln.sh/jCpJvg)
- [x] `Country` select field should not begin with an empty option
    - 📸 [Screenshot](https://cln.sh/DTJnuE)
- [x] `Base Country` field in Donations > Settings should not display `Choose a form`
    - 📸 [Screenshot](https://cln.sh/G9lIKY)

**Comment by henryholtgeerts** [comment]
I agree that State should be not have a default selected, however I'm not so sure on country/currency. I'm wondering if it is better that the Onboarding Wizard reflect the default install settings (US and US Dollar). As I understand it, a sizable majority of our users are US based, and so these defaults were selected as a way to save setup time for new users. But, I'm open to other ideas!

**Comment by kjohnson** [comment]
It is my understanding that we are loading the plugin defaults for country and currency. This change should support that by removing the empty first option for country.

**Comment by kevinwhoffman** [comment]
@henryholtgeerts To clarify, my intent with this change is to keep `United States` as the default option when you first open the wizard. However when you open the select menu, there was this empty option just above it that resulted in an empty field when selected, which I don't think should be possible.

![image](https://user-images.githubusercontent.com/1938671/90806365-e4f97600-e2ea-11ea-9d37-e8fea2836bc1.png)

**Comment by kevinwhoffman** [comment]
@kjohnson I'm adding a third criterion to this issue to address this `Choose a form` text:

![image](https://user-images.githubusercontent.com/1938671/90807325-5128a980-e2ec-11ea-88b2-49cc171b2935.png)

**Comment by kjohnson** [comment]
@kevinwhoffman I'm seeing something different in Settings -> General (fresh install)

![image](https://user-images.githubusercontent.com/10858303/90808799-92ba5400-e2ee-11ea-9f57-863d65524053.png)

**Comment by kjohnson** [comment]
@kevinwhoffman I what happened was the empty option in the Wizard unset the country, which is why you are seeing the placeholder text in the settings - the change to the country select in the Wizard makes this moot.

**Comment by kjohnson** [comment]
Anyway, I was able to reproduce it and went ahead and set a specific placeholder.
