### ISSUE TITLE
Localization should support translations in JavaScript

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#5185]
WordPress v5.4 dropped the localized global variable `commonL10n` in favor of transaltions in JavaScript.

See [Changeset 48267](https://core.trac.wordpress.org/changeset/48267), [Ticket #51123](https://core.trac.wordpress.org/ticket/51123)

Reported via [Canny Feeddback]((https://feedback.givewp.com/bug-reports/p/adding-license-should-work-on-wp-55)

> When navigating to Donations > Settings > Licenses, I should be able to add the license without problems.
For now, when I add the license, nothing happens and the page freezes. The console shows a JS error.
>
> ![image](https://user-images.githubusercontent.com/10858303/91063188-a5d56880-e5fb-11ea-843a-82390e42b9d9.png)

**Comment by kevinwhoffman** [comment]
@Benunc and I agree this is urgent as it currently breaks license activation in WP 5.5.

**Comment by kjohnson** [comment]
@kevinwhoffman @Benunc I'll add that license activation does work, but the UI is broken which makes it look like license activation is broken. Refreshing the page does show that the license was activate. That said, perception is reality.

**Comment by kevinwhoffman** [comment]
Closing as this was resolved in #5186.
