### ISSUE TITLE
Onboarding wizard should not create empty menu item under wp-admin Dashboard

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#5187]
## User Story

As an admin I don't want an empty link in my wp-admin that points to a 404.

## Details

When I review the Dashboard submenu I see this empty space that links to a 404 "form preview".

![2020-08-24_09-57-14](https://user-images.githubusercontent.com/1571635/91073768-5d647d80-e5f0-11ea-8725-b4a33c17e597.png)

## Steps to Reproduce

1. Check out the latest development branch
2. Log into wp-admin and view the dashboard sub-menu

## Visuals

![2020-08-24_09-57-14](https://user-images.githubusercontent.com/1571635/91073822-7a994c00-e5f0-11ea-99e0-f1f07fdc0423.png)

## Acceptance Criteria

-   [ ] No link is displayed under the Dashboard menu when 
-   [ ] All onboarding scripts / styles only load when the onboarding flow is present

**Comment by kjohnson** [comment]
Looks like the Form Preview is attached to the Dashboard as a submenu, which should probably be hidden from the sidebar.
