### ISSUE TITLE
Disconnecting a single site from Stripe should not require disconnecting all sites on the same account

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5198]
## User Story

As an admin of several sites, I want the ability to disconnect a single site from Stripe without having to disconnect all of my previously connected sites that are connected to my same Stripe account.

## Details

Currently, disconnecting a connected Stripe account from the GiveWP plugin revokes permissions for GiveWP as an "Authorized applications" on that Stripe account. This is destructive behaviour that breaks other connections to GiveWP on that account.

## Expected Behavior

Disconnecting a connect Stripe account from the GiveWP plugin should not revoke permissions for GiveWP as an "Authorized applications" on that Stripe account so that other connected sites continue to operate as expected.

## Steps to Reproduce

1. Go to Settings -> Payment Gateways -> Stripe -> Manage Accounts.
1. Click "Connect with Stripe" and complete the connect process.
1. Go to Settings -> [Authorized Applications](https://dashboard.stripe.com/account/applications) in the Stripe dashboard of the connected account.
1. View GiveWP as an Authorized Application.
1. Go to Settings -> Payment Gateways -> Stripe -> Manage Accounts.
1. Click "Disconnect" to remove a connected account.
1. Go to Settings -> [Authorized Applications](https://dashboard.stripe.com/account/applications) in the Stripe dashboard of the connected account.
1. View GiveWP is no longer an Authorized Application.

## Visuals

GiveWP connected Stripe accounts
![image](https://user-images.githubusercontent.com/10858303/96024082-4a686f80-0e21-11eb-9367-2b5798a5fb4f.png)

Stripe authorized applications
![image](https://user-images.githubusercontent.com/10858303/96024140-594f2200-0e21-11eb-8731-c696d8aa83ee.png)

## Additional Context

The Stripe add-on includes the option to connect a site via key.

## Acceptance Criteria

-   [x] A Stripe account can be disconnected form the site.
-   [x] Disconnecting an account does not revoke GiveWP as an Authorized Application.
-   [ ] Manually connected Stripe accounts (Stripe add-on) can still be disconnected.

**Comment by kevinwhoffman** [comment]
@henryholtgeerts @kjohnson There was a [pull request](https://github.com/impress-org/givewp/pull/5201) created, however it didn't seem to fully address the issue. I think this is in part due to an issue that lacked detail.

When work continues, on this issue, please take the time to complete the issue template and acceptance criteria. Have @Benunc review the acceptance criteria to ensure we are developing a solution that fully addresses the problem.
