### ISSUE TITLE
FFM controls should work in multi-step form with single gateway

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5212]
## User Story

As a user, I want FFM inputs to work, even when only one payment gateway is enabled, so that I can complete my donation as expected.

## Details
From @rickalday on Canny
> If there's only one payment gateway enabled in the Payment Gateway settings, any FFM checkbox and radio options on the form cannot be checked. There's no visual clue that the options have been checked at all.
> This happens on the new form template.

## Expected Behavior
The FFM inputs should behave consistently in the Multi-Step form, regardless of how many payment gateways are enabled.

## Steps to Reproduce
1. Create a Donation Form with FFM checkboxes and radio options
2. Disable all but 1 payment gateway
3. View form on the front end
4. Notice how FFM inputs are not reactive to choices you make

## Additional Context
Link to associated Canny post:
[FFM controls should work in multi-step form with single gateway](https://feedback.givewp.com/bug-reports/p/ffm-controls-should-work-in-multi-step-form-with-single-gateway)

## Visuals
Screencast: http://somup.com/cYjOFI6WlW

## Acceptance Criteria
-   [x] FFM Inputs work as expected in the Multi-Step form when only one payment gateway is enabled
-   [x] FFM Inputs behave the same no matter how many or how few payment gateways are enabled

**Comment by kevinwhoffman** [comment]
@henryholtgeerts Given the JavaScript changes in WP 5.5, please test each FFM field type with one and multiple gateways. Keep your console open and look for errors.
