### ISSUE TITLE
License status should accurately reflect the saved keys

### ISSUE THREAD

**Issue by kevinwhoffman** [impress-org/givewp#5233]
## Job Story

When copying and pasting an active license key from the GiveWP website into the GiveWP plugin, I want the plugin to accurately reflect the active status of my license so that I'm not bothered by admin notices claiming that I have an inactive license.

## Details

According to our [feedback](https://feedback.givewp.com/bug-reports/p/all-add-ons-should-show-as-active-when-the-license-keys-are-added), the following add-ons are mentioned alongside reports of this licensing issue:

- ActiveCampaign
- WooCommerce Upsells

However it is not clear whether the problem is with these add-ons in particular, or the licensing system as a whole.

## Expected Behavior

If a customer has active license keys on the GiveWP website, then those keys should not trigger inactive notices within the plugin.

## Steps to Reproduce

**Note: These steps may not consistently replicate the problem, however**

1. Activate a plus bundle
2. Note the admin notice claiming that `Your GiveWP add-on is not receiving critical updates because you have 1 inactive license key`.
3. Click `activate your license`.
4. Identify the add-on with the inactive license.
5. Copy the active license key from the GiveWP website and paste it the license field of the inactive add-on.
6. The license appears to activate in plugin

### Before Pasting the Key

![image](https://user-images.githubusercontent.com/1938671/92034371-22262500-ed3b-11ea-8ad2-74b8f6eb941b.png)

### After Pasting the Key

![image](https://user-images.githubusercontent.com/1938671/92034252-f86cfe00-ed3a-11ea-8b71-6e904a05b55a.png)

## Acceptance Criteria

-   [ ] When pasting an active license key into the plugin, the license is activated properly on the GiveWP website.
-   [ ] When pasting an active license key into the plugin, the license is activated properly within the GiveWP plugin

**Comment by kevinwhoffman** [comment]
Reassigning to @DevinWalker after discussion in Slack.

@DevinWalker Be sure to review the Canny feedback for helpful insights and screencasts.

**Comment by DevinWalker** [comment]
The issue with the missing name for both of those add-ons and subsequent missing change log details was due to those two missing the "Download readme.txt configuration" info in EDD. I have entered it for both add-ons and now they now appear properly in the list:

![2020-09-02_15-58-17](https://user-images.githubusercontent.com/1571635/92045410-50086b00-ed35-11ea-9eb5-3fc3812ac187.png)

Clicking the "Refresh License" button will make them appear or customers can wait until the CRON job runs for the license check.

I'm going to review what other issues are happening in Canny and see if I can pinpoint anything else.

**Comment by JasonTheAdams** [comment]
@DevinWalker To be clear, you're saying the bug had to do with misconfiguration on GiveWP.com, not something within the codebase?

**Comment by DevinWalker** [comment]
Yes in the scenario mentioned in the initial issue creation. I'm investigating if this resolves other issues folks mentioned as well.

**Comment by DevinWalker** [comment]
This was due to the "Readme.txt" config in EDD for ActiveCampaign and the Woo add-on being erased due to a bug with EDD Software Licensing. I have spoken with Matt about it and we have not a game plan to ensure only admins can edit our download CPT posts.
