### ISSUE TITLE
Remove custom definition of array_column from includes/misc-functions.php

### ISSUE THREAD

**Issue by tw2113** [impress-org/givewp#5253]
In short, array_column arrived in PHP 5.5. GiveWP currently requires PHP5.6. It should be safe to remove this custom definition at the moment for all future releases, and reduces the codebase volume safely

**Comment by JasonTheAdams** [comment]
Thanks for the suggestion, @tw2113! Just to be clear, is there any downside to leaving the shim apart from it likely being unnecessary? Just want to make sure you're not aware of it causing problems for someone in any way.

**Comment by tw2113** [comment]
Nope, no technical issue with just leaving it, as it wouldn't be getting defined by the plugin, due to existing in PHP core already. More a housekeeping GH issue than anything :)

**Comment by JasonTheAdams** [comment]
Roger that! Thank you! 😄

**Comment by kjohnson** [comment]
Closing this issue since `/includes` is now considered legacy code and is slated for deprecation and removal in the future.
