### ISSUE TITLE
Give Totals block should have feature parity with `give_totals` shortcode

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5260]
## User Story

As an admin, I want the Give Totals block to have feature parity with the Give Totals shortcode so that I do not reach for the block to do more than the shortcode.

## Details
Currently, the Milestone block emulates the Give Total shortcode, but adds a handful of minor feature improvements over the existing Give Totals implementation. As the Milestone block is transformed simply into a Give Totals block, some of these feature improvements should be retained, while others should be removed. 

## Acceptance Criteria
-   [x] Milestone block is renamed Give Totals
-   [x] Change references to Milestone to Give Totals
-   [x] Featured image controls/attribute is removed
-   [x] Deadline functionality should be reviewed and removed if necessary
-   [x] Title/description should be reviewed and rolled into a single "Message" field if necessary

**Comment by henryholtgeerts** [comment]
@kevinwhoffman @kjohnson I started work on this issue, but am not at the place of reviewing some functionality that was introduced for Milestones, but is not originally supported by Give Totals - but could be useful. Specifically, I'm curious about your thoughts on the following:

- Removing deadline functionality (because it further blurs the line between Give Totals and Campaigns)
- Rolling title/description into a single field called "message", more closely following the Give Totals shortcode parameters

Obviously, its just as easy to leave any of these features in. I'm not too concerned one way or another, because I think the other argument to be made for keeping these features is that they help introduce this block as an "improved" Give Totals shortcode - in ways more meaningful than simply presentation or the addition of different metrics to display.

**Comment by kjohnson** [comment]
@henryholtgeerts I would rather introduce those features intentionally, instead of releasing it (and supporting it) by default.
