### ISSUE TITLE
Give Totals block presentation should be polished

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5261]
## User Story

As a admin, I want the Give Totals block frontend and admin appearance polished so that it fits nicely alongside other GiveWP elements.

## Details
The Give Totals block contains the entire feature set necessary to ship. Now there are only a few areas of polish necessary to finish out development.

## Additional Context
The Give Totals block started as the Milestone block, which had a set of design needs that was larger in scope than an a simple Give Totals block would require. 

## Acceptance Criteria
-   [x] Default message is updated to be more generic
-   [x] Admin controls all work/look cohesive in the block editor interface
-   [x] Users can control block colors

**Comment by henryholtgeerts** [comment]
Here's a look at my initial pass restyling the Totals block's frontend appearance so that it is inline with other design elements (especially influenced by the multi-step form):

<img width="640" alt="Screen Shot 2020-09-15 at 3 31 45 PM" src="https://user-images.githubusercontent.com/5186078/93256098-d460e200-f768-11ea-9c20-13f2068e8d35.png">

<img width="649" alt="Screen Shot 2020-09-15 at 3 32 14 PM" src="https://user-images.githubusercontent.com/5186078/93256109-d75bd280-f768-11ea-85d3-e2ca8f625a9b.png">

I'm left wondering about two things:
- Should users be able to set a primary color (like they can with form templates)
- Should the user be able to toggle-off these givewp styles, if they'd prefer to style it themselves?

@kevinwhoffman @kjohnson I'd love your thoughts both on the designs seen here, and what direction you lean regarding my two questions.

**Comment by henryholtgeerts** [comment]
For comparison, here is an implementation of the existing give_totals shortcode on the same theme:
<img width="601" alt="Screen Shot 2020-09-15 at 3 47 54 PM" src="https://user-images.githubusercontent.com/5186078/93257561-096e3400-f76b-11ea-8d06-2148171fd2eb.png">

For complete editing context, here's the block as seen from the block editor with the inspector open:
<img width="1060" alt="Screen Shot 2020-09-15 at 3 48 44 PM" src="https://user-images.githubusercontent.com/5186078/93257631-24d93f00-f76b-11ea-9d8e-132596d89369.png">

**Comment by henryholtgeerts** [comment]
Call Summary: 9/15/20
On call: @kevinwhoffman, @henryholtgeerts 
Discussed tweaks to the block's frontend appearance, so that it is more closely in line with the original Give Totals shortcode.
- Styling the link as an inline a tag (not as a button)
- Inherit the font styles from theme
- Remove card styling
- Ability to remove message entirely (and see no additional spacing left over where it was)

**Comment by henryholtgeerts** [comment]
Here's an image of the Totals block, now styled more closely to the original give_totals block:
<img width="628" alt="Screen Shot 2020-09-15 at 4 37 45 PM" src="https://user-images.githubusercontent.com/5186078/93262248-e72be480-f771-11ea-9912-eab828108cd8.png">

**Comment by kevinwhoffman** [comment]
Thanks @henryholtgeerts! I think this is a good balance between maintaining the give_totals functionality while adding a bit of polish to the presentation.

**Comment by kjohnson** [comment]
@henryholtgeerts re: primary color setting: I definitely see the importance to theme-ability with a WordPress product, like the Primary Color on the Form Template - that is probably just as important here.

That said, I think we should consider how to best organize the available options, without bloating the overhead of available options.

**Comment by kevinwhoffman** [comment]
@henryholtgeerts Regarding the `Metric` option, I realized that this is essentially what we refer to as `Goal Format` in the donation form editor. Do you think it makes sense to use the same terminology here for consistency?

![image](https://user-images.githubusercontent.com/1938671/93265033-0167c180-f776-11ea-844f-509f6d2031c6.png)

**Comment by henryholtgeerts** [comment]
@kevinwhoffman Hmm...I suppose it does makes sense, although honestly I'm not sure that Goal Format is actually an kinda of improvement (regarding clarity). That said - I'm happy to make the change 👍

**Comment by kevinwhoffman** [comment]
@henryholtgeerts Let's call it `Goal Format` so that we're using consistent terminology wherever we are displaying goals and progress bars. I don't have a strong preference between `Metric` and `Goal Format`, but I'd rather err on the side of consistency and familiarity for our existing users.
