### ISSUE TITLE
Gateway menu items should reflect gateway priority

### ISSUE THREAD

**Issue by JasonTheAdams** [impress-org/givewp#5278]
## Details

Presently, the order of the Payment Gateways listed out in the submenu order is:
Gateways > Offline > Stripe > ...

Really, Gateways > Offline is a fixed order, and then everything comes after that. Offline is not a common, high priority gateway, so it shouldn't be at the front of the line. Stripe and PayPal should be, followed by the others.

## Acceptance Criteria
- [x] New order is Gateway > Stripe > PayPal > ... Others > Offline

**Comment by ravinderk** [comment]
This issue resolved in https://github.com/impress-org/givewp/pull/5279 pr
