### ISSUE TITLE
Campaigns UI should differentiates title from preview heading

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#5282]
## Details

The Campaign title should not be coupled to the campaign preview heading.

## Acceptance Criteria

-   [ ] Can set a title
-   [ ] Can set a heading different than the title

**Comment by henryholtgeerts** [comment]
I think this issue might actually need slightly different implementation than is described here. Ideally, the title of a campaign is not necessarily the same as the heading shown in the campaign summary card. For instance, a campaign could be titled "Back to School Fundraiser 2020" but the heading could say "Help our students have a great year!"

This would be in keeping with the convention used in Multi-Step forms, where the form title simply informs a default for the form heading, but the heading itself can be overriden/different from the form title.

**Comment by kjohnson** [comment]
Certainly worth discussing.

My intent here was to emulate the Post Title UI, as a heading block in the Campaign Preview, which would be the default heading when a block is added to a page/post. Once added to a page, the block is simply a heading that can be updated.

![image](https://user-images.githubusercontent.com/10858303/93922372-cfa7ab00-fcdf-11ea-8dd3-9cd361fe2604.png)

**Comment by henryholtgeerts** [comment]
Got it - I'm personally leaning toward the first option (separate title UI).

**Comment by kjohnson** [comment]
Sure. I can work with that. I think I'll have the Post Title has the default value, to avoid double input, but can be changed.
