### ISSUE TITLE
Campaign featured image should be flexible enough to handle various aspect ratios

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#5294]
## Additional Context

- https://developer.wordpress.org/themes/functionality/featured-images-post-thumbnails/
- https://developer.wordpress.org/reference/functions/set_post_thumbnail_size/
- https://wordpress.stackexchange.com/questions/32811/set-featured-image-size-for-a-custom-post-type

## Acceptance Criteria

-   ...

**Comment by kevinwhoffman** [comment]
@kjohnson @henryholtgeerts I did some prototyping in Figma to test how the component might handle different aspect ratios. Please review [my notes in Figma](https://www.figma.com/file/QrLU21GCFGVncBBU5EIq8Y/Epic-Campaigns?node-id=256%3A67). We can jump on a call if needed to clarify.

**Comment by kevinwhoffman** [comment]
This flexibility for the featured image has been achieved in the Multi-form Goal block. Closing.
