### ISSUE TITLE
Data validation should occur after applying the filter. 

### ISSUE THREAD

**Issue by alaca** [impress-org/givewp#5303]
## User Story

As a developer, I want that data validation is performed after applying the filter when inserting revenue into the database. 
Right now the data can be easily omitted. 

## Expected Behavior

Data validation should validate the data after applying the filter.

## Acceptance Criteria

-   [x] Data is validated after applying the filter

**Comment by ravinderk** [comment]
fixed in https://github.com/impress-org/givewp/compare/50d9220f3e7d...384104b65740
