### ISSUE TITLE
Multi-Forms Goal block should be scaffolded

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5306]
## User Story

As an admin, I want to be able to add a Multi-Form Goal block to pages so that I can show progress across forms towards a shared goal.

## Details
The Multi-Forms Goal block is being developed on the tail work work done to build Campaigns and the Totals block. The new block logic should live within a MultiFormGoals directory, and incorporate progress already made previously during this sprint.

## Additional Context
This PR aims simply to scaffold the directory, and get a block in place that is workable. It is not meant to polish editor UI, and should leave the door open for improvements to image display and other features.

## Acceptance Criteria
-   [x] MultiFormGoals directory is scaffolded
-   [x] Multi-Form Goal block is available in block editor

**Comment by kjohnson** [comment]
Let's remember to follow the Domain architecture for this feature.
