### ISSUE TITLE
Multi-Form Goal should maintain a minimum width

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#5323]
The design for the Multi-Form Goal relies on a minimum width for the two column content layout.

The minimum width should be enforced, even when greater than the content width.

## Visuals

As is, with Elementor and the Twenty Twenty theme.
![Screenshot from 2020-10-01 16-08-10](https://user-images.githubusercontent.com/10858303/94857979-52c3b200-0400-11eb-817a-36701e717bc8.png)

Adjusted for a minimum width and centered with css "trick".
![Screenshot from 2020-10-01 16-05-09](https://user-images.githubusercontent.com/10858303/94857939-43446900-0400-11eb-80d5-08d2e201b4da.png)

## Acceptance Criteria

- [ ] Multi-Form Goal maintains a minimum width, regardless of container.
- [ ] Multi-Form Goal isn't larger than the viewport.

**Comment by henryholtgeerts** [comment]
@kjohnson I'm curious if instead we should use flex and minmax settings to responsively stack the image and text, when used in smaller screens? I also notice that in the screenshots the image is taking up more than half of the card, which to me suggests a styling bug what might be more apparent inside of an editor like elementor than other places. Ideally, when using the shortcode, the image should max out at half of the card width, and maybe stack on mobile/when the card gets too narrow.

**Comment by kjohnson** [comment]
Flexbox might work better for layout here than grid, which I think is currently used.

Good point about the image. Perhaps the Media & Text block defaults to 50/50, which wouldn't be set in another context, like Elementor.

**Comment by henryholtgeerts** [comment]
Revisiting this issue, I've opted to open a new issue to address this based on our conversation: https://github.com/impress-org/givewp/issues/5527
