### ISSUE TITLE
Donation processing should have a better user experience

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#5368]
## Details
Presently, when the donation begins to process and the donor redirects to the Paypal checkout page before that a bright white overlay goes over the screen which is not better user experience. We can display the same shade of dark overlay as PayPal (when a PayPal window is displaying) for consistency, and because it's easier on the eyes.

## Additional Context
The bright white overlay can be toggle by `Give.form.fn.showProcessingState()` as per business logic. In the design decisions, we can consider that Do we want to make this change only for PayPal Donations payment gateway or for all.

## Visuals
**PayPal Payment Processing Model Background**
![image](https://user-images.githubusercontent.com/1784821/95822899-5fbe9a80-0d4a-11eb-9619-e17fca9ccc68.png)

**Default donation processing overlay**
![image](https://user-images.githubusercontent.com/1784821/95824606-381d0180-0d4d-11eb-9401-51dcfa14bb0a.png)

## Acceptance Criteria
- [x] Show overlay for a one-time donation for PayPal Donations for form with "Legacy" for the template.
- [x] Show overlay for one-time donation for PayPal Donations for form with "Multi Step Form" for the template
- [x] Show overlay for recurring donation for PayPal Donations for form with "Multi Step Form" for the template.
- [x] Show overlay for recurring donation for PayPal Donations for form with "Multi Step Form" for the template.

**Comment by DevinWalker** [comment]
## New "Please Wait" Screen Design Direction

This is the screen that appears when the donor is returned to GiveWP after making a successful donation via the Smart Buttons.

1. Use the same opacity as the PayPal modal so it’s a smooth transition.
2. Use the  loading icon that spins that’s the same in the multi-step form style but in white.

![Frontend Please Wait](https://user-images.githubusercontent.com/1571635/95900263-7cf16a00-0d46-11eb-941b-7071e9b8c1aa.png)
