### ISSUE TITLE
Readme.txt should be updated to reflect new features and optimized for search

### ISSUE THREAD

**Issue by mathetos** [impress-org/givewp#5386]
## User Story

As a prospective GiveWP user, I want to understand the current benefits of GiveWP and its features by reading the [plugin page on WordPress.org](https://wordpress.org/plugins/give).

## Details

When adding new features we need to ensure they get mentioned in the readme. We also want to occassionally update the text for optimization of wordpress.org search purposes. 

In this case we need to do the following:

* Audit the existing readme for any general updates that it might need for clarity
* Audit the current screenshots and ensure they are the best reflection of the current free plugin
* Consider how best to add info on PayPal Donations
* Consider how best to add info on the multi-form goal block (if helpful/necessary)

## Acceptance Criteria

This will be updated once the general audits are run and we know exactly what result we want from this update.

- [x] Include updated Getting Started links
- [x] Add PayPal Donations documentation

**Comment by kjohnson** [comment]
Closed by https://github.com/impress-org/givewp/pull/5413
