### ISSUE TITLE
Testing donation data should be seeded

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#5412]
Reporting requires a (potentially) large data set for benchmarking performance and measuring the improvement of each change.

## Acceptance Criteria

- [x] Donations belong to a donation form.
- [x] Donations belong to a donor.
- [x] Donations are generated with a single base currency on which may be "switched" with an exchange rate.

**Comment by kevinwhoffman** [comment]
@kjohnson It seems like the test data that you're looking for would overlap with the [Test Data pitch](https://docs.google.com/document/d/1xqZEgyJkLYLdAAZfjIObjy6OxPKzh6DreoPHtyaAMu0/edit) that @alaca is working on this release.

If possible, can you two make sure that the work done here serves the Test Data pitch as well?

**Comment by kjohnson** [comment]
Of course. I plan to spike something to get going then followup with @alaca .

**Comment by mathetos** [comment]
Please note that if we're adding Give CLI commands, we'll need to update our online docs as well:
https://givewp.com/documentation/developers/give-cli/

**Comment by mathetos** [comment]
Feedback issue created for this:
https://feedback.givewp.com/documentation/p/update-give-cli-to-include-new-fake-donordonation-commands

**Comment by kjohnson** [comment]
Closing in favor of feedback.
