### ISSUE TITLE
Addon update notice should look good on plugin list page

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#5427]
## Details
![image](https://user-images.githubusercontent.com/1784821/97981176-e28dbf00-1df7-11eb-82af-7c78d7d2d61e.png)

As you can see in the above screenshot, the GIveWP addon update notice is not wide as the table row on the plugin list page.

## Acceptance Criteria

-   [ ] GiveWP addon update notice look good on plugin list page.
-   [ ] GiveWP addon update notice look good on the multisite plugin list page.

**Comment by kjohnson** [comment]
Closing as unable to reproduce.

![image](https://user-images.githubusercontent.com/10858303/198677869-1487d7fc-0b57-4cdd-bdc1-af10b9b9ba69.png)
