### ISSUE TITLE
Avatar Size shortcode attribute should affect actual avatar size and other Donor Wall avatar improvements

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#5442]
## User Story

As a admin, I want to control the avatar size on the donor wall so that it can fit my design goals.

Additionally, in the Donor Wall block there is no option to change the avatar size. 

Finally, when the Gravatar appears it's not the correct resolution and appears grainy / pixelated because it's coming from the API at 80x80px and we're smushing it to 60x60px. We should ensure that it's always pulled at 2x the size (if displaying at 60px the image should be 120px) for the highest possible resolution. So if I'm an admin and set the `avatar_size` to 120 then we would pull from Gravatar a 240px resolution image. 

## Details

Currently the `avatar_size` parameter is not working. This stems from the work that was done to validate the Gravatar by @ravinderk - in doing that PR we left out testing the resize functionality, which is now broken. 

## Expected Behavior

The `avatar_size` parameter should work as expected alongside the new gravatar validation functionality.

### Shortcode

1. Insert a donor_wall shortcode with the `avatar_size` parameter set to `120`. Example: `[donor_wall avatar_size="120"]`.
2. View on the frontend and notice the 

### Block

1. Insert the "Donor Wall" block
2. Notice there's no option to change the avatar size

### Resolution

1. View the donor wall on any device and notice the image looks grainy / pixelated. 

## Acceptance Criteria

-   [x] `avatar_size` works in the shortcode
-   [x] The Donor Wall block supports changing the size of the avatar
-	[x] The donor's gravatar appears high resolution and quality
- 	[x] The donor wall is properly responsive with a larger or smaller sized avatar

**Comment by ravinderk** [comment]
@DevinWalker To fix border issue , i am removing it from donor images. Border will be visible only for name initials

![image](https://user-images.githubusercontent.com/1784821/101668730-e952c600-3a76-11eb-8f78-81e83bcc7e32.png)
