### ISSUE TITLE
A fresh WP install should not throw warnings when GiveWP is activated

### ISSUE THREAD

**Issue by JasonTheAdams** [impress-org/givewp#5454]
## Details

A non-prohibiting — but annoying — bug was introduced in 2.9.2 by yours truly. If upgrading from an older version of GiveWP or using GiveWP on a fresh install, then GiveWP will throw warnings admin-side. It does not actually break anything, and the errors only show up if debug mode is enabled.

## Expected Behavior

GiveWP should not throw warnings just by running.

## Steps to Reproduce

1. Create a fresh WP install
2. Make sure `WP_DEBUG` is enabled and `WP_DEBUG_DISPLAY` is true
3. Install and activate GiveWP 2.9.2
3. Check out them warnings

## Acceptance Criteria

-   [x] A fresh WP instance does not throw warnings when GiveWP is installed
-   [x] Upgrading from 2.8.0 does not throw warnings

**Comment by kjohnson** [comment]
https://gist.github.com/kjohnson/2b1aca8fefdbb4338ab3b4a536aa068d

**Comment by JasonTheAdams** [comment]
Yup, already got a hotfix in process. Thanks. 😄

**Comment by kjohnson** [comment]
@JasonTheAdams I deleted my comment - you responded too quick!

I specifically want to share with the team a test-driven approach to fixing this issue, which was the purpose of my patch.

See https://gist.github.com/kjohnson/2b1aca8fefdbb4338ab3b4a536aa068d
