### ISSUE TITLE
Typo in src/Views/Form/Templates/Sequoia/Actions.php should be fixed

### ISSUE THREAD

**Issue by jr70** [impress-org/givewp#5477]
## User Story

As a User I want to read meaningful text. 

## Details

I have been translating your superb plugin into UK English and I noticed a typo in src/Views/Form/Templates/Sequoia/Actions.php @ line 258 where the word 'donation' is missing.

Currently it is:

`$content = isset( $this->templateOptions['payment_amount']['content'] ) && ! empty( $this->templateOptions['payment_amount']['content'] ) ? $this->templateOptions['payment_amount']['content'] : sprintf( __( 'How much would you like to donate? As a contributor to %s we make sure your goes directly to supporting our cause. Thank you for your generosity!', 'give' ), get_bloginfo( 'sitename' ) );`

## Expected Behavior

I believe line 258 should be:

`$content = isset( $this->templateOptions['payment_amount']['content'] ) && ! empty( $this->templateOptions['payment_amount']['content'] ) ? $this->templateOptions['payment_amount']['content'] : sprintf( __( 'How much would you like to donate? As a contributor to %s we make sure your donation goes directly to supporting our cause. Thank you for your generosity!', 'give' ), get_bloginfo( 'sitename' ) );`

**Comment by JasonTheAdams** [comment]
Good catch! Thanks, @jr70! This has been resolved in 4e6ae728 and will be included in the next release.
