### ISSUE TITLE
Add a hook in  'column_default' function (class-subscriptions-list-table.php file)

### ISSUE THREAD

**Issue by Genevieve-K** [impress-org/givewp#5482]
## User Story

As a developer, I added a cart to GiveWP so that the donor can make multiple donations. When the donor submits the donation form, the gift is added to the cart. And when the cart is validated, the popup window with the payments info opens.
A donation within the meaning of GiveWP is intended for several beneficiaries, with a different amount for each.
Each beneficiary has a page, and the same form is used for several pages. The form title is not relevant information for us.
Ex: https://give.agape.org.uk/

Main treatments:
- management of a cart in the session
- addition of specific emails for the beneficiary
- for donors and administrators, addition of the different beneficiary names in reports, emails, administration interface...

I recently activated Give Recurring. There is only one beneficiary here, but we also work with the shopping cart. I added the beneficiary in the table subscription meta. I was able to display the beneficiary name in different info. But I had a problem to display it in the admin, in the subscription list  (.../edit.php?post_type=give_forms&page=give-subscriptions).

## Details

This table is displayed in the file class-subscriptions-list-table.php.

I can add a hook to 'give_report_subscription_columns' to add my custom column. And I must define a associated function to display it.

    add_filter( 'give_report_subscription_columns', 'give_cart_admin_add_beneficiary_column');

    function give_cart_admin_add_beneficiary_column( $columns )
    {
    	$columns['beneficiary_id'] = __( 'Beneficiary', 'give-cart' );
   	return $columns;
    }
If I write a function column_beneficiary_id( $item ), it will be outside the classe, and the 'column_default' function is called.

My suggestion is to add a filter in  the 'column_default' function:

	function column_default( $item, $column_name ) {
		return apply_filters( 'give_subscription_column_default', $item->$column_name, $item, $column_name );
	}
I have tried and can thus add the beneficiary.

## Acceptance Criteria

-   [x] Subscription table can have custom columns via hooks

**Comment by JasonTheAdams** [comment]
Hi @Genevieve-K!

Thanks for the detailed explanation of your application and need! That's very helpful! Your suggestion seems perfectly acceptable and makes sense.

If you're willing to put together a PR for this, then I would be happy to review it and help get it through. Otherwise, we'll do our best to get to this as soon as we're able.

Have a wonderful weekend!

**Comment by Genevieve-K** [comment]
Hi Jason,
I agree to do a PR. I don't see how to create a branch to add the updated file. Could you help me?
Have a good weekend too!

**Comment by JasonTheAdams** [comment]
Great! To make a Pull Request you would first need to [fork](https://docs.github.com/en/free-pro-team@latest/github/getting-started-with-github/fork-a-repo) the repository, and then [create a pull request from the fork](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by Genevieve-K** [comment]
My update is for Give Recurring, this repo is GiveWP. I don't have access to give-recurring.

**Comment by JasonTheAdams** [comment]
Oh. my. goodness.

![Oops](https://media.giphy.com/media/14aUO0Mf7dWDXW/giphy.gif)

Hahah! You are completely right. That's a premium add-on and so the repository isn't public. As such, you have no way of making a Pull Request. 😅 

As recompense for my sending you on an impossible task, I'm going to handle this myself right now. I'll come back and close this Issue once I've merged the Pull Request.

Thank you for so kindly and patiently pointing out my error. 😆

**Comment by JasonTheAdams** [comment]
Ok! I just got a Pull Request finished. Once one of my team member has a chance to review the PR it will be merged. At that time I'll provide you with a diff patch so you can apply it to the plugin on your server — allowing you to use the filter before it's released.

**Comment by JasonTheAdams** [comment]
The PR has been merged! Here's the patch so you can apply the changes to your project. The changes will be included in the next version of GiveWP Recurring.
```diff
diff --git a/includes/admin/class-subscriptions-list-table.php b/includes/admin/class-subscriptions-list-table.php
index 1b2f89cf..2841aff0 100644
--- a/includes/admin/class-subscriptions-list-table.php
+++ b/includes/admin/class-subscriptions-list-table.php
@@ -275,13 +275,15 @@ class Give_Subscription_Reports_Table extends WP_List_Table {
 	/**
 	 * Render most columns.
 	 *
+	 * @since 1.11.3 add a filter for setting custom column values
+	 *
 	 * @param object $item
 	 * @param string $column_name
 	 *
 	 * @return mixed
 	 */
-	function column_default( $item, $column_name ) {
-		return $item->$column_name;
+	public function column_default( $item, $column_name ) {
+		return apply_filters( 'give_subscriptions_table_column_default', null, $item, $column_name );
 	}
 
 	/**
```

**Comment by Genevieve-K** [comment]
Thank you very much Jason.

Le lun. 7 déc. 2020 à 20:29, Jason Adams <notifications@github.com> a
écrit :
