### ISSUE TITLE
discuss tracking data architecture

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#5488]
## Details

We decided that we will record only [non-sensitive data](https://github.com/impress-org/givewp/pull/5462):
The below image shows the proposed database structure to store data on the state server.

DB diagram updates:
1. Updated: https://github.com/impress-org/givewp/issues/5488#issuecomment-740041951
2. Added: add a table to show the relationship between recurring, fee recovery , FFM, and donation forms.

![Stats-Server](https://user-images.githubusercontent.com/1784821/101479943-00ab8980-3979-11eb-9c23-dd79755af8e1.png)

| Table Name  | Description |
| ------------- | ------------- |
| sites  | This table contains website and server information  |
| themes_information |  This table contains non-changing theme information like slug, url, title, author |
| sites_themes_relationship | This table contain information about the website and their theme data, dynamic data like version  |
| plugins_information  | This table contains non-changing plugin information like slug, url, name, author |
| sites_plugins_relationship  | This table contain information about the website and their plugin data, dynamic data like version  |
| sites_donation_forms | This table contains stat by website donation form  |
| sites_gateways  | This table contains information about active payment gateways  |
| sites_givewp_settings  | This table contains information about the website Give configuration  |
|donation_metrics  | This table contains information about the website donation related stats like donor count, form count, revenue, etc.  |
|forms_addons_relationshilp  | This table contains relation information about the website donation form and active premium GiveWP addons.  |

## Acceptance Criteria
- [ ] Decide database architecture

**Comment by JasonTheAdams** [comment]
This looks great! Excellent start and very well structured.

Couples Notes:
- Perhaps make a `donation_metrics` table that's 1:1 with the `sites` table to pull out columns such as `donor_count` to make the sites table truly about the site.
- We will need some kind of authentication that will likely affect the DB structure a bit. I assume that's just not the focus here?

Couple typos:
- checkout-lable -> checkout_label
- form_Template -> form_template
- parent_theme_vesion -> parent_theme_version

**Comment by ravinderk** [comment]
@JasonTheAdams DB diagram updated as per your suggestion.

**Comment by ravinderk** [comment]
@JasonTheAdams @kjohnson I added `forms_addons_relationshilp` as we discussed.

**Comment by JasonTheAdams** [comment]
@ravinderk I don't think you quite grasped what I was suggesting. Here's a simple version:
![Form addon usage example](https://user-images.githubusercontent.com/2024145/101514129-c9fe5080-3931-11eb-95f5-a1946a546404.png)

Simply by being present in the `form_addon_usage` table, that indicates that the form is using the add-on. That also makes the table dynamic, so we don't have to worry about any add-on specific columns such as `is_recurring_active`.

Make sense?

**Comment by ravinderk** [comment]
@JasonTheAdams I understand it. I update db diagram

**Comment by ravinderk** [comment]
closing this issue in favor of https://github.com/impress-org/give-telemetry-server/issues/1
