### ISSUE TITLE
Donor gravatar should load in donor wall Gutenberg block in WP admin

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#5496]
## Details

Donor gravatar script does not compatible with donor wall Gutenberg block. That why valid gravatar does not load in WP admin

## Expected Behavior

Donor gravatar should load on the frontend and backend.

## Steps to Reproduce

1. Create a new page
2. Insert donor wall block
3. Check if donor gravatar loads if exist.

## Acceptance Criteria

-   [ ] Donor gravatar loads in donor wall shortcode.
-   [ ] Donor gravatar loads on donor listing page
-   [ ] Donor gravatar load on frontend for donor wall shortcode.

**Comment by kjohnson** [comment]
Closing as no longer valid - unable to reproduce using GiveWP version 2.23.0.

![image](https://user-images.githubusercontent.com/10858303/198673516-a9cf62cd-8aa0-4687-8301-748cfe285af9.png)
