### ISSUE TITLE
multi select

### ISSUE THREAD

**Issue by lifecolorline** [impress-org/givewp#5507]
This is a donation site where users can choose only 1 option.

[https://video.kozossegireklamozas.hu/wp-content/uploads/2020/12/charity.jpg](url)

I need that users can choose one or more options what they want.

Can anybody help me ?

**Comment by alaca** [comment]
Hi @lifecolorline,
I'd suggest you reach out to our support at https://givewp.com/support/

**Comment by JasonTheAdams** [comment]
Hi @lifecolorline, as @alaca said your best means of getting help is to contact support. This repository is for questions and requests specifically related to the GiveWP code. All other questions will be best handled by support.
