### ISSUE TITLE
Donation forms should prevent card testing

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#5521]
There are reports of donation forms being used to test credit cards, which creates a problem with our customer's relationship with payment processors, ie Stripe.

**Comment by kjohnson** [comment]
_Originally posted at https://givewp.canny.io/admin/feedback/bug-reports/p/additional-spam-donation-protection?boards=bug-reports_

I think the solution here is to require that a user be registered (or otherwise verified) in order to make a donation, as an increased level of security.

Otherwise, the donation requests are unauthenticated, which renders WordPress nonces and CSFR tokens moot - both of which rely on an authenticated user's session.

Without authentication, an attacker can harvest nonces or CSFR tokens, as they can be created by the unauthenticated user - security theatre. This method will slow down the rate of attack, but is easily automated.

Further, it seems that any strategy to rate limit an individual's requests would require authentication (or verification), as any other unique identifier can be spoofed - randomly generated email addresses or rolling IP addresses. Not to mention referer spoofing.

An alternative method may be lightweight email verification, in which a donation is held in a pending state until the email address associated with the donation is verified by actually sending an email to that account. This is basically a lightweight, password-less authentication.

Ultimately, we need to implement a solution that disproportionately increases the barrier of entry for an attacker - Verifying an email address is a low cost feature with a disproportionately higher cost to the attacker.

---

That said, an attacker could setup a catch-all email account, randomly generate email addresses on that domain, and programatically crawl incoming links in the inbox. At which point you would need to implement some sort of learning system which detects patterns of attacks. Thus the downward spiral continues. This, I believe, is outside of the scope of a donation plugin.

**Comment by kjohnson** [comment]
Perhaps we could rate limit donations at the site level?

**Comment by kjohnson** [comment]
Related: https://givewp.canny.io/admin/feedback/feature-requests/p/givewps-akismet-integration-should-have-a-method-to-send-false-positives

**Comment by kjohnson** [comment]
@JasonTheAdams thoughts on a global rate limiter? The request was to rate limit per user, but that doesn't work for un-authenticated donations.

**Comment by JasonTheAdams** [comment]
Can you please unpack what you mean by a global rate limiter? I'm open to rate limiting and would think to do it by IP and/or session. But I'd like to hear more about what you're thinking.

Looking back, too, I don't think we can really go down the road of requiring users to authenticate. It's the most effective way of preventing this stuff, but I'm afraid it's just a bit of a non-starter. I doubt Customers will be willing to risk less legitimate donations in favor of higher security.

**Comment by kjohnson** [comment]
Being that unauthenticated users are not easily identifiable, I'm considering adding a high level rate limiter to prevent card testing. There are multiple levels of restriction that we could use: global, IP, session.

The concern with rate limiting by the IP or Session is that these has a simple workarounds. Multiple machines can be used to spam from multiple IPs and new Sessions can easily be created.

By contrast, rate limiting across the entire site creates a bottleneck without a work around, since the restriction is at the site level.

**Comment by JasonTheAdams** [comment]
Ah, I see. So instead of trying to rate limit per user or session, you're saying there would be a rate limit for the site as a whole? Hmm... we'd have to be really careful about something like that, and it would need to be opt-in and controllable. We'd hate to have a high traffic customer update GiveWP and suddenly have donations drop because they naturally hit the limit.

I do recognize the limiting by IP or session can be fairly easily circumvented. I'm afraid the reality is we're simply not going to come up with a bulletproof solution (outside of authentication). The most promising methods that I can tell are as follows:
1. Improving Akisment integration
2. reCAPTCHA integration
3. Rate limiting (options for both global and session)

**Comment by kjohnson** [comment]
I agree with making a rate limiting change opt-in. I'm thinking of this as a tool in the toolbox, along with Akismet and/or reCAPTCHA.
