### ISSUE TITLE
Error while validating Korean zipcode

### ISSUE THREAD

**Issue by jgreys** [impress-org/givewp#5534]
## Details

An error occurs when filling a valid zipcode for Korean addresses.

## Expected Behavior

In 2015, the Korean Government changed their postcodes from 6 digits to 5 digits. This new format must be recognized as valid in order to be able to make a donation.

## Steps to Reproduce

1. Go to a donation form
2. Select "South Korea" as country
3. Fill "06316" in zipcode field.
4. Submit

## Acceptance Criteria

-   [x] Something happens when an action is taken.
-   [ ] Something does not happen when an action is taken.
-   [ ] Fixing behavior in Component A does not affect existing behavior in Component B.

**Comment by ravinderk** [comment]
If anyone looking for detailed information on this change, then you read this [blog post](https://thesoulofseoul.net/2015/07/06/the-addresses-are-changing-again/).

**Comment by jgreys** [comment]
@ravinderk Thanks a lot :)
