### ISSUE TITLE
[Broken functionality] PayUmoney Gateway Addon not working with Latest Version

### ISSUE THREAD

**Issue by knit-pay** [impress-org/givewp#5538]
## User Story

As a donor, I should be able to donate using PayUmoney payment gateway.

## Details

I am using Give 2.9.5 with WordPress 5.6. On the old Give version, PayUmoney and many other gateways were working fine, but on the new version of Give (with the new frontend interface), PayUmoney and many other third-party gateways stopped working. I think there is some compatibility issue in the new version of Give with the old Payment Gateway plugins. If you have changed something bigger in the new interface of Give, kindly add the backward compatibility so that all the previous payment gateways start working as they were working in the old interface.

## Expected Behavior

User should be able to make the payment using official and third-party payment gateway plugins of Give

## Steps to Reproduce

1. Go to Donation form page (frontend) (in new interface)
2. Fill all the details and select PayUmoney Payment Gateway.
3. Click on Donate Now
4. Loading icon appears and never goes away.
5. the Same issue is there for various other third-party Gateways.

## Visuals

https://user-images.githubusercontent.com/65900807/103684169-25fbd980-4fb1-11eb-81f0-ee2d5c436f72.mp4

https://user-images.githubusercontent.com/65900807/103682467-efbd5a80-4fae-11eb-8661-c83970355ebb.mp4

## Additional Context

In the first video you can see that Give is not working with the official PayUmoney addon and third-party gateway (Knit Pay) and in the second video you can see and same settings are working fine with the official Paytm gateway addon.

## Acceptance Criteria

-   [ ] Official PayUmoney Payment Gateway Addon should work with the latest version of Give. 
-   [ ] Third-party payment gateway like Knit Pay should work with the latest version of Give (It was working fine with old interface).

**Comment by rvdsteege** [comment]
Issue has been resolved for [Pronamic Pay](https://github.com/pronamic/wp-pronamic-ideal) (which Knit Pay is based upon) in https://github.com/wp-pay-extensions/give/issues/2#issuecomment-760200004.
