### ISSUE TITLE
Personal information section fields icon should not remove when switch payment gateway

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#5541]
## Details

I noticed that the Personal information section fields icon remove when switching the payment gateway. Form field icon should not depend upon any donor activity and should remain on the donation form.

![Screen+Recording+2021-01-06+at+05 53 44+PM](https://user-images.githubusercontent.com/1784821/103768388-6d817480-5048-11eb-8206-990be5d15ac1.gif)

## Expected Behavior

Donation form style should not affect by donor activity.

## Steps to Reproduce

1. Open donation form with Multi-step form template
2. Notice form field icons in the personal information section.
3. Switch payment gateway.
4. Review form field icons in the personal information section.

## Acceptance Criteria

-   [x] Donor activity does not affect form field icons in personal information seciton.

**Comment by henryholtgeerts** [comment]
Hmm...I am having trouble reproducing this issue locally. Any insight into what addons you have active or configuration that might be causing it?

https://user-images.githubusercontent.com/5186078/103785740-933b5900-5009-11eb-855a-8e67da873fad.mp4
