### ISSUE TITLE
Onboarding domain should be e2e tested

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5546]
## User Story

As a developer, I want the Onboarding domain to be e2e tested so that I can confidently make changes to the codebase without fear of unknowingly breaking onboarding features.

## Details

A handful of Cypress tests should be implemented to support e2e testing for the onboarding domain. 

## Additional Context

This issue builds on work done in this PR: https://github.com/impress-org/givewp/pull/5543

## Acceptance Criteria

Setup Page tests:
-   [x] Setup Page can manually launch onboarding wizard
-   [x] Setup Page can be dismissed

Onboarding Wizard tests:
-   [x] Dismiss setup wizard link works
-   [x] Intro step continue button leads to Cause step
-   [x] Only one fundraising type card can be selected
-   [x] Cause type can be selected
-   [x] Cause step continue button leads to Location step
-   [x] Changes to country should update state/province and currency options (test US, CAN, UK)
-   [x] Location step continue button leads to Features step
-   [x] Multiple feature cards can be selected and unselected
-   [x] Features step continue button leads to Preview step
-   [x] Preview form loads in iframe
-   [x] Preview continue button leads to Addons step
-   [x] Multiple addon cards can be selected and unselected
-   [x] Top navigation works as expected
-   [x] Addons step continue button leads to Setup Page

Bonus tests:
-   [ ] Addons selected in Onboarding Wizard are reflected in Step 3 of Setup Page
-   [ ] Features selected in Onboarding Wizard are reflected in Preview Form

**Comment by kjohnson** [comment]
@henryholtgeerts I'm dropping the following acceptance criteria:

> Setup Page links redirect to active webpages

My reasoning being that this isn't something that would be broken by any change in logic, but rather is a hard-coded href.
