### ISSUE TITLE
GiveWP CLI commands should not produce a fatal error

### ISSUE THREAD

**Issue by alaca** [impress-org/givewp#5558]
## User Story

As a developer, I want that GIveWP CLI commands are working correctly without producing errors. 

## Details

Currently, when trying to use the GiveWP CLI commands will produce a fatal error.

`[15-Jan-2021 09:48:15 UTC] PHP Fatal error:  Uncaught ReflectionException: Class Faker\Generator does not exist in /var/www/html/wordpress/wp-content/plugins/give/src/Container/Container.php:744
Stack trace:
#0 /var/www/html/wordpress/wp-content/plugins/give/src/Container/Container.php(744): ReflectionParameter->getClass()
#1 /var/www/html/wordpress/wp-content/plugins/give/src/Container/Container.php(707): Give\Container\Container->resolveDependencies()
#2 /var/www/html/wordpress/wp-content/plugins/give/src/Container/Container.php(595): Give\Container\Container->build()
#3 /var/www/html/wordpress/wp-content/plugins/give/src/Container/Container.php(538): Give\Container\Container->resolve()
#4 /var/www/html/wordpress/wp-content/plugins/give/src/Container/Container.php(821): Give\Container\Container->make()
#5 /var/www/html/wordpress/wp-content/plugins/give/src/Container/Container.php(746): Give\Container\Container->resolveClass()
#6 /var/www/html/wordpress/wp-content/plugins/give/src/Container/Container.php(707): Give\Container\Container->resolveDependenc in /var/www/html/wordpress/wp-content/plugins/give/src/Container/Container.php on line 744`

## Expected Behavior

Using the GiveWP CLI command should not produce fatal errors. 

## Steps to Reproduce

1. Download and install GiveWP from the WordPress.org site
2. Open the terminal and run the `wp give` command

## Acceptance Criteria

-   [ ] Using GiveWP CLI commands should work correctly and without producing errors

**Comment by ravinderk** [comment]
@alaca Can you confirm that you will get PHP fatal error only for `give` command? does it affect any other command?

**Comment by adriantoll** [comment]
@ravinderk I get this when doing any wp-cli command, such as:

`wp theme get themename`

Error output:

```
PHP Fatal error:  Uncaught ReflectionException: Class Faker\Generator does not exist in /wp-content/plugins/give/src/Container/Container.php:744
Stack trace:
#0 /wp-content/plugins/give/src/Container/Container.php(744): ReflectionParameter->getClass()
#1 /wp-content/plugins/give/src/Container/Container.php(707): Give\Container\Container->resolveDependencies(Array)
#2 /wp-content/plugins/give/src/Container/Container.php(595): Give\Container\Container->build('Give\\TestData\\F...')
#3 /wp-content/plugins/give/src/Container/Container.php(538): Give\Container\Container->resolve('Give\\TestData\\F...', Array)
#4 /wp-content/plugins/give/src/Container/Container.php(821): Give\Container\Container->make('Give\\TestData\\F...')
#5 /wp-content/plugins/give/src/Container/Container.php(746): Give\Container\Container->resolveC in /wp-content/plugins/give/src/Container/Container.php on line 744
```

**Comment by ravinderk** [comment]
@JasonTheAdams Few hosts use wp-cli to update plugin automatically. it will affect the plugin updates process on these hosts and website struck on recent plugin version only.  this will affect on few websites but can we prioritize this?

@kjohnson Can you give your suggestion?

**Comment by kjohnson** [comment]
My guess is that Faker was originally packaged as a dev requirement, but if we are shipping the TestData domain, then Faker needs to be a production requirement. That should resolve this issue on the next release.
