### ISSUE TITLE
Onboarding buttons should match concept

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#5575]
## Details

Somehow the styles for the connect to PayPal and Stripe buttons lost their styles. I just confirmed this on a fresh install:

![2021-01-28_22-40-35](https://user-images.githubusercontent.com/1571635/106240900-f14afe80-61b9-11eb-92b0-63a40b03f625.png)

## Acceptance Criteria

-   [ ] Buttons correctly match concept:

![2021-01-28_22-42-10](https://user-images.githubusercontent.com/1571635/106240970-10499080-61ba-11eb-958a-3ce05e196a87.png)

**Comment by kjohnson** [comment]
Weird...

**Comment by kjohnson** [comment]
Looks like the `row-item` lost the paypal/stripe class name on the `article` element.

**Comment by kjohnson** [comment]
Looks like when the Cypress test IDs were added to the HTML, the setup page configuration did not set a `testId`, which was breaking the output HTML.

**Comment by kjohnson** [comment]
Found the underlying problem.

Adding the `testId` tag created a situation where two unmerged were being scrubbed as one large unmerged tag.

Example:
```
id="{{ id }}" class="setup-item" testId="{{ testId }}" 
```

was being interpreted as a a single tag:

id="`{{ id }}" class="setup-item" testId="{{ testId }}`"

which, when scrubbed, results in:
```
id=""
```
