### ISSUE TITLE
Prevent PHP notice on system info page

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#5606]
## Details

I see the following PHP error on fresh install when visiting the system info page.
```
[13-Jan-2021 21:42:12 UTC] PHP Notice: Trying to access array offset on the value of type bool in /wp-content/plugins/give/includes/admin/tools/views/html-admin-page-system-info.php on line 696
```

## Acceptance Criteria

-   [x] Plugin does not cause PHP notice on the system info page on a fresh install.

**Comment by coder-karen** [comment]
I was also able to reproduce this with a fresh install, when using PHP 8.0 specifically (and using Apache and MySQL 8.0.16).

I'm creating a PR, my first with GiveWP - as this is your issue hopefully that is ok and I will add you as a reviewer.
