### ISSUE TITLE
Multi-step form template should include donation summary on last page

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#5608]
## User Story

As a donor I want to be clear the amount I'm giving, the frequency I'm giving, and if I'm covering Fees before I complete my donation so that I'm not confused.

## Details

Currently there is no donation summary on the final step of the multi-step donation form. We need to include a summary so that it does not confuse the donor.

*Note:* If you have the Fee Recovery add-on active and enabled you _will see a summary_ with the fee breakdown. 

The solution to this issue should not conflict with that breakdown, but rather work _with_ it. As well, we don't currently have support for _Recurring Donations_. This solution needs to work with Recurring Donations as well.

*New "Donation Summary" Form Options:* Two new settings will need to be added to the "Step 3: Payment Information" multi-form settings.

1. Donation Summary Label
2. Summary Description 

### One-time donation

![2021-02-16_11-28-55](https://user-images.githubusercontent.com/1571635/108111885-32f8f780-704a-11eb-9e35-13ba343e53d7.png)

### One-time donation plus Fee Recovery

![2021-02-16_11-33-25](https://user-images.githubusercontent.com/1571635/108112326-caf6e100-704a-11eb-9755-ff6281350b7c.png)

### Recurring Donation

![2021-02-16_11-34-07](https://user-images.githubusercontent.com/1571635/108112413-e4982880-704a-11eb-8a88-c5830b49960b.png)

### Recurring Donation plus Fee Recovery

![2021-02-16_11-39-28](https://user-images.githubusercontent.com/1571635/108112924-a51e0c00-704b-11eb-8be6-d8d0806e7e77.png)

## Acceptance Criteria

-   [ ] Donation Summary displays properly and matches concept
-   [ ] Donation Summary is compatible with Fee Recovery
- [ ] Donation Summary is compatible with Recurring Donations
- [ ] Donation Summary works with Fee Recovery + Recurring Donations together
- [ ] Donation Summary is tested with all Recurring Donations frequencies and periods

**Comment by kjohnson** [comment]
Closed by https://github.com/impress-org/givewp/pull/6061.
