### ISSUE TITLE
Fields API should support persisting field values as donation or donor meta

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#5625]
Related #5624

See https://givewp.slack.com/archives/C0FAGC83C/p1613775880047100?thread_ts=1613775545.045100&cid=C0FAGC83C

## User Story

As a developer, I want specify that a field be saved as either donation meta or donor meta so that the collected information is stored in the correct context..

## Details

Currently, custom fields are persisted as donation meta. We should also support persisting values as donor meta.

## Acceptance Criteria

-   [x] Custom field values can be stored as donation meta.
-   [x] Custom field values can be store as donor meta.

**Comment by JasonTheAdams** [comment]
Per the discussion, I'm thinking the following:
1. A `dataType` property is added to the base Field class which defaults to `donation_meta`.
2. Two fluent methods are added, `Field::storeAsDonationMeta()` and `Field::storeAsDonorMeta()`
3. We handle `donation_meta` and `donor_meta` ourselves, and provide a hook so folks can provide their own data type and handle it if they wish to store elsewhere or do something else entirely.
