### ISSUE TITLE
VisaCheckout on new givewp layout is broken

### ISSUE THREAD

**Issue by souzadavi** [impress-org/givewp#5629]
We developed a donation gateway to VisaChekout. It works fine on old form Givewp design, on new one is happening a very strange thing.

When click on visa checkout button the page just disappear.
The problem is on page: https://doar.criarsite.online/donations/doacao-internacional-online/

We are trying to figure out whats going on, look like the deal is on file: /wp-content/plugins/give/assets/dist/js/give.js

But we don't have a clue how to fix it. Any direction to fix it will be very appreciated.

thanks a lot.

**Comment by JasonTheAdams** [comment]
Hi @souzadavi!

Let's see if we can figure this out. To be clear, the Multi-Step from is in many ways still the Legacy Form, but loaded inside an iframe with a lot of CSS and JS to finagle it. It's entirely possible there's an issue with the fact that it's inside of an iframe; you'll need to make sure your scripts are loading within the iframe.

@henryholtgeerts Can you provide any insight into this?

**Comment by souzadavi** [comment]
> Hi @souzadavi!
> 
> Let's see if we can figure this out. To be clear, the Multi-Step from is in many ways still the Legacy Form, but loaded inside an iframe with a lot of CSS and JS to finagle it — something we would very much like to improve in the future. It's entirely possible there's an issue with the fact that it's inside of an iframe; you'll need to make sure your scripts are loading within the iframe.
> 
> @henryholtgeerts Can you provide any insight into this?

The iframe is the deal. I hope get any information from @henryholtgeerts to fix it.

**Comment by souzadavi** [comment]
We found the problem, for some how Visa Checkout change the style atribute height of givewp iframe.

![Screenshot from 2021-02-24 15-40-34](https://user-images.githubusercontent.com/636225/109049444-134f7800-76b7-11eb-9944-1b0a30b35311.png)



![Screenshot from 2021-02-24 15-40-19](https://user-images.githubusercontent.com/636225/109049452-13e80e80-76b7-11eb-81fd-36ed018557b4.png)

**Comment by souzadavi** [comment]
We solved the problem creating a event listener at visabtn[0] and change the height. So its fixed. Thanks.
