### ISSUE TITLE
Addons should be able to register Donor Profile badges

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5636]
## User Story

As a donor, I want badges to be dynamically registered on my Donor Profile to game-ify my donation experience so that I am encouraged to donate again.

## Details

In the new Donor Profile experience, donors should be shown "Bages" in the upper right (aside their donor info), to indicate any special donor status they have. Some examples are "Recurring Giver" and "Top Donor".

## Additional Context

Initial designs for the Badge system can be found here: https://www.figma.com/file/BKr2K0XdDyRRoccJbJKRD7/Epic%3A-Donor-Profile?node-id=397%3A1743

## Acceptance Criteria

-   [ ] Badges are dynamically registered by Addons and core when appropriate
-   [ ] Donors are shown badges based on their status/qualifications
-   [ ] Badge design and color reflect Figma boards

**Comment by kjohnson** [comment]
Closing as a stale.
