### ISSUE TITLE
Updating to GiveWP 2.10.0 should prompt users to update their legacy donation management pages

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5638]
## User Story

As an admin, after adding a Donor Profile block to a page, I want to be prompted to easily update my legacy donation management page settings so that donors can be sent to the Donor Profile from their donation receipt.

## Details

Currently, even when the Donor Profile block is added, admin must remember to manually update their legacy donation management page settings, so that their new Donor Profile page is respected (in place of Donation History, Subscription Management, etc). Ideally, admin will be easily prompted to update these settings when they update to GiveWP 2.10.0.
## Additional Context

This solution addresses an issue raised in this comment: https://github.com/impress-org/givewp/issues/5628#issuecomment-783974582

## Acceptance Criteria

-   [x] Updating to GiveWP 2.10.0 displays a prompt for Admin to create a Donor Profile page and udpate their legacy donation management pages
-   [x] Admin can create a Donor Profile page and update their legacy donation management pages from the setting page, if they dismissed the prompt previously

**Comment by JasonTheAdams** [comment]
Great thoughts, Henry, thank you for putting this together.

I wonder if it would be simpler and more straightforward to just prompt the user when they update to 2.10.0. The prompt would say something like:
> New in GiveWP 2.10.0 we're excited to share with you the new Donor Profile block! This place is intended to replace the existing Donation History, Subscription Management, Edit Profile, and Annual Receipt pages — now in one, awesome new place. Would you like us to automatically create a Donor Profile page for you and switch over the existing pages to use this one?
[Yes, Please] / [No, Thank You]

For this prompt we would check if they have those existing pages in place. In this way folks wouldn't have to discover the Donor Profile via the block editor. What do you think?

**Comment by henryholtgeerts** [comment]
@JasonTheAdams Ooooh good thinking! Maybe your suggestion, along with an area in settings to do the same thing, in case a user dismisses the notice on update?

**Comment by JasonTheAdams** [comment]
Yeah! Exactly. I mean, a some point if the user doesn't want us to do it they can always fall back on documentation to guide them along. But you get the idea. 😄

**Comment by henryholtgeerts** [comment]
Sounds good, I'll update this issue to reflect our conversation here, and get started.

**Comment by JasonTheAdams** [comment]
@DevinWalker Do you concur in the shift of direction? I know it's important to you that we get this right, so I'd like your sign off before we start putting too much effort into it.
