### ISSUE TITLE
The new Migrations UI should be e2e tested

### ISSUE THREAD

**Issue by alaca** [impress-org/givewp#5664]
## User Story

As a developer, I want the new Migrations UI to be e2e tested so that we could ship new features with confidence.

## Details
Cypress tests should be implemented to support e2e testing for the new Migrations UI.

## Acceptance Criteria

**Migrations list table tests**
- [ ] Sort migrations by status
- [ ] Sort migrations by title
- [ ] Sort migrations by last run
- [ ] Sort migrations by source
- [ ] Sort migrations by run order
- [ ] Paginate migrations
- [ ] View migration error
- [ ] Re-run migration

**Comment by kjohnson** [comment]
Closing in favor of the new QA process (automated and manual).
