### ISSUE TITLE
Admin should not get javascript error on database updates page 

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#5697]
## Details

I am seeing following error on `Tools  Data  Database updates` page
![image](https://user-images.githubusercontent.com/1784821/110632511-b6cb7d00-81cd-11eb-9dde-637aac4c65a1.png)

**Comment by alaca** [comment]
@ravinderk I can't reproduce this issue. I have tried in FF and Chrome.

On what branch you are and did you run `npm run production` or `npm run watch`?

**Comment by ravinderk** [comment]
I saw that `Table` component accepts `columnFilters` prop as an array but we are passing an object in `Log`. Doe sit make sense?


![image](https://user-images.githubusercontent.com/1784821/110668359-3c145900-81f1-11eb-90c8-e931baec367a.png)
![image](https://user-images.githubusercontent.com/1784821/110667998-d58f3b00-81f0-11eb-9b38-ae8616b8e4f1.png)
![image](https://user-images.githubusercontent.com/1784821/110668098-f2c40980-81f0-11eb-974e-4845c57844e5.png)
