### ISSUE TITLE
wp rewrite flush --hard error

### ISSUE THREAD

**Issue by lukecav** [impress-org/givewp#5710]
Running a WP-CLI command to flush rewrites.

`wp rewrite flush --hard`: Process exited with status 255

This resulted in the following error.

`PHP Fatal error:  Uncaught ReflectionException: Class Faker\Generator does not exist in /chroot/home/a7c6a6b8/df0872f3d2.nxcli.net/html/wp-content/plugins/give/src/Container/Container.php:744`

**Comment by kjohnson** [comment]
Hey @lukecav - thanks for the report. I think we have this resolved from a [previous report](https://github.com/impress-org/givewp/issues/5558), which I believe has been released.

Can you confirm your version of GiveWP?

**Comment by lukecav** [comment]
@kjohnson Let me check which version of the GiveWP plugin is being used on the site.

**Comment by lukecav** [comment]
@kjohnson The plugin version was 2.9.6.

**Comment by kjohnson** [comment]
@lukecav looks like the fix was released in 2.9.7 on 2021-02-09. Could you update your version if GiveWP and confirm that the issue is resolved?
