### ISSUE TITLE
The Donor Dashboard interface when you are logged into a profile without donations should be less confusing

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5732]
## User Story

As a [type of user], I want [some goal] so that [some reason].

## Details

From Canny:
As a user who is already logged in, I am confused by seeing a log in option. My thought as a user is "what does that do? log me out and then back in?" 

Also, some clarity about why there are two options (when there are two, which is by default) for seeing donations on the dashboard.

An additional note for that instance above the "Already have an account" section that explains that logging in there will log you out of the existing account and into another one.

## Acceptance Criteria

-   [ ] Contextual docs (login notice) language is clarified

**Comment by JasonTheAdams** [comment]
Canny post for this has closed, so closing this, too.
