### ISSUE TITLE
Donors without WP accounts should be able to upload avatar images

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5743]
## User Story

As a Donor, I want to be able to upload an avatar image even if I'm not logged in with a WP account so that I can change my appearance within the Donor Dashboard.

## Details

Currently, when attempting to upload an image via the Donor Dashboard while using a Donor account that does not have an associated WP account, you are shown a forever spinning loader on the "Update" button.

## Expected Behavior

The Update process should work as expected, regardless of whether the donor has an associated WP account.

## Steps to Reproduce

1. Go to the Donor Dashboard
2. Log In with a Donor account (without an associated WP account)
3. Upload a new avatar
4. Click update, see that the spinner never resolves

## Visuals

http://somup.com/cre0jabOtr

## Acceptance Criteria

-   [x] Donors without WP accounts can succesfully update their avatar images

**Comment by kjohnson** [comment]
@henryholtgeerts is there a related Canny post for this bug report?

Specifically, I'd like to confirm that this is something that we want to work on. Do we support avatars for non-WP users anywhere else? Would it be better to hide avatars for non-WP users, since there is not a user account for which to check permissions?

**Comment by matheuswd** [comment]
Hey @kjohnson, I've created feedback here https://feedback.givewp.com/bug-reports/p/donors-without-wp-accounts-should-be-able-to-upload-avatar-images, so I can let the user know that we are taking a look at it.

**Comment by henryholtgeerts** [comment]
@kjohnson Prior to Donor Dashboards, we did not support custom avatars in any form, so adding the functionality to support custom avatars for non-WP users is (in my mind) more of a bug correction than a new feature. As far as file-upload permissions checks go -- GiveWP already allows for non-WP users to upload files in the context of FFM, so adding an endpoint to support image uploads provided that it is within an active donor session (via WP user check, or session check), feels ok to me.

**Comment by kjohnson** [comment]
@henryholtgeerts that works for me - just wanted to make sure that this was properly considered.
