### ISSUE TITLE
Links in field descriptions are stripped of the attributes and don't link

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#5746]
## User Story

As a user I want to be able to click on links in the field descriptions so that I can read more about the field option itself.

## Details

Currently links display, but do not have an `href` or `target` attribute. It's just an empty anchor tag. I'm guessing this has to do with security stripping the tags out:

![2021-03-24_12-15-14](https://user-images.githubusercontent.com/1571635/112370733-f8aef580-8c9a-11eb-882b-4ded6880a85d.png)

![2021-03-24_12-15-59](https://user-images.githubusercontent.com/1571635/112370737-fb114f80-8c9a-11eb-93e5-1cb2adc3704c.png)

## Steps to Reproduce

1. View the latest Form Template
2. Scroll down to the field shown in the screenshot above
## Acceptance Criteria

-   [ ] Links in fields work as expected
- [ ] Security is not compromised.

**Comment by ravinderk** [comment]
@DevinWalker I can see that the link is not enclosed with a double quote in `href` attribute. I create a quick pull request for this.
