### ISSUE TITLE
Adding donations to the revenue table should stop the update process in case of an error

### ISSUE THREAD

**Issue by alaca** [impress-org/givewp#5748]
## User Story

As a site admin, I want the revenue table update to work correctly. Currently, the process of adding donations into the revenue table does not stop the update process in case of an error.  

## Details

The handler ( `AddPastDonationsToRevenueTable::class` ) responsible for adding donations to the revenue table requires that all donations have values set for the `donation_id`, `form_id`, and `amount` fields. The problem in case something is missing, e.g. donation doesn't have associated `form_id`, is that situations like that are not handled properly. The update process continues to run and it gets stuck in an infinite loop. This also fills the logs table on each iteration.

## Expected Behavior

Adding donations to the revenue table should stop the update process in case of an error and inform the site admin that something went wrong during the update process. 

## Steps to Reproduce

1. Install [Give 2.8.1](https://github.com/impress-org/givewp/releases/tag/2.8.1)
2. Add a donation form
3. Make a few donations
4. Delete the previously created donation form so that the donations are no longer associated with that donation form. 
5. Update Give to the latest version
6. Run the update process

## Acceptance Criteria

-   [x] Adding donations to the revenue table should stop the update process in case of an error
-   [x] Site admin should be notified that something went wrong during the DB update

**Comment by ravinderk** [comment]
I review steps to reproduce it but I do not think it is a real world scenario.  If the admin deleting the donation form without removing the donation then they are making mistakes and it's on them to maintain data consistency.

I fixed a similar issue https://github.com/impress-org/givewp/pull/5472.
I will suggest to use `DB::insert` and handle exception to prevent infinite migration.

https://github.com/impress-org/givewp/blob/775c659589fe106d06b20b9a5fa12a2b19ca9770/src/Revenue/Repositories/Revenue.php#L40

**Comment by ravinderk** [comment]
@alaca Maybe you have an old revenue table in form_id column that was a foreign key. Can you review your table because we removed it: https://github.com/impress-org/givewp/pull/5447.

I see an opportunity to improve code, so I created a pull request https://github.com/impress-org/givewp/pull/5749.
Can you test this pull request against your database and update it if anything missing. We will merge it if it works fine on your database.

**Comment by alaca** [comment]
> @alaca Maybe you have an old revenue table in form_id column that was a foreign key. Can you review your table because we removed it: #5447.

No, the `form_id` is not FK

![image](https://user-images.githubusercontent.com/4222590/112496968-75b69980-8d85-11eb-8e08-e5a4cce85ccc.png)


Regarding #5749, good work! I was about to suggest something like that. 
That will fix the issue we are having now.
