### ISSUE TITLE
Notice on donors page

### ISSUE THREAD

**Issue by flack** [impress-org/givewp#5750]
## User Story

As an admin I want to see the list of donors on this URL:

/wp-admin/edit.php?post_type=give_forms&page=give-donors

## Details

Since the update to 2.10, I get three notices like this:

 Notice: Undefined index: s in /home/flack/git/rfp/wp-content/plugins/give/includes/admin/donors/class-donor-table.php on line 367

## Expected Behavior

There shouldn't be any notices

## Steps to Reproduce

1. Go to /wp-admin/edit.php?post_type=give_forms&page=give-donors
2. View error

## Acceptance Criteria

- [x] The value of the `s` parameter is used to search donors.
- [x] The value of the `s` parameter not being set does not result in an errors or notices.
- [x] The value of the `s` parameter is escaped to prevent XSS.

**Comment by kjohnson** [comment]
@flack thanks for the report. I updated the issue with Acceptance Criteria to use for a PR.
