### ISSUE TITLE
Chinese/Japanese/Korean characters broken when generating/exporting CSV

### ISSUE THREAD

**Issue by jgreys** [impress-org/givewp#5761]
## Details

When I export the data in CSV format ( Donations > Tools > Export ), if the data contains Chinese, Japanese, or Korean characters, they are broken.

## Expected Behavior

When exporting data, the data must be readable.

## Steps to Reproduce

1. Go to Donations > Tools > Export
2. Click on Generate CSV
3. Open the csv file generated
4. Characters broken

**Comment by JoshuaHungDinh** [comment]
The related PR has been closed. Please reference: Cross-posting from https://github.com/impress-org/givewp/pull/5762:
