### ISSUE TITLE
Stripe Admin UI should be improved

### ISSUE THREAD

**Issue by henryholtgeerts** [impress-org/givewp#5789]
## User Story

As an admin, I want the Stripe Admin UI to be clearer and more aesthetically contistent so that I can easily understand what I am changing, and have a cohesive admin experience across supported gateways.

## Details

There are a handful of admin interface improvements to be made to the Stripe admin experience, largely meant to clarify admin have already setup, clarify what they need to setup and to make the Stripe admin experience more consistent with GiveWP styling.

## Additional Context

See Figma boards: https://www.figma.com/file/vtf3p6Vt9wh1e5EkrbiZKu/Stripe-Admin-UI-2021?node-id=0%3A1

## Acceptance Criteria

-   [x] Global account management view is improved
-   [x] Stripe API setup modal design is improved
-   [x] Credit Card field formatting input is improved
-   [x] Per-form account management view is improved

**Comment by kjohnson** [comment]
Closed by https://github.com/impress-org/give-stripe/pull/485.
