### ISSUE TITLE
Donor wall should be scoped to a specific donation form

### ISSUE THREAD

**Issue by slewisma** [impress-org/givewp#5813]
## User Story

As a content manager or site developer, I want an option to show a donor wall on each form that shows that form's donors only so that I can easily add donor walls for forms in a peer to peer fundraising scenario.

## Details

I tried to add a donor wall to each donor form by adding the donor wall shortcode as a GeneratePress Hook Element but there isn't an easy way to specify the current form's ID such that each form show its own donors on the wall. Nested shortcodes don't work in the donor wall shortcode.

## Additional Context

For peer to peer fundraising, it would be useful to show each form's donors when the form is displayed.

For similar reasons it would be very useful to associate an email address with each form and be able to send a separate donation notification to that address for completed donations only and to be able to control which fields are included in the messages. Letting peer to peer fundraisers know who donated through their form so they can thank them personally is a very requested capability from our peer to peer fundraisers. 

If both of these needs are being addressed in the formal peer to peer fundraising capabilities in development, this issue report can be merged into that effort or ignored.

## Acceptance Criteria

There are two ways to solve this:

1) Enable the existing donor wall shortcode with a parameter that tells it to show the donor wall for the current form

OR

2) Add a parameter to the donor form shortcode and / or donor form block and / or form settings to enable / disable a donor wall that shows below the form and shows donors to the current form only. 

Both methods need the ability to exclude anonymous donations.

**Comment by kjohnson** [comment]
@slewisma thanks for reaching out with the suggestion. As you have suggested this is something that we are working on in formal peer-to-peer fundraising work. Therefor, I would say that your suggested use case would be covered by future development work.
