### ISSUE TITLE
Monthly, Weekly, Daily reports are sending every minute since May 1

### ISSUE THREAD

**Issue by love4dogs** [impress-org/givewp#5814]
## User Story

AS of May 1st we started receiving Monthly, Weekly, Daily reports every minute accumulating to hundreds of emails to recipients not even on the recipient list.  

## Details

reports show $0 and are sending every minute.  We have disabled the Give Reports Plugin, WP Crontrol and cleared the cache.

## Expected Behavior

Reports should be only sent to recipients on the list and at the scheduled time with the correct donations. This is definitely a bug.

## Steps to Reproduce

1. Go to...
2. Select...
3. Scroll down to...
4. View error

## System Information

<details><summary>Details</summary>

</details>

## Acceptance Criteria

-   [ ] Something happens when an action is taken.
-   [ ] Something does not happen when an action is taken.
-   [ ] Fixing behavior in Component A does not affect existing behavior in Component B.

**Comment by JasonTheAdams** [comment]
Hi @love4dogs! That doesn't sound good! Honestly, the best way for us to help you is to [reach out to our support](https://givewp.com/support/) so they can dive into the issue with you. If an underlying bug can be found, they'll coordinate with the dev team to get a fix.

**Comment by love4dogs** [comment]
Already have
Matheus isn’t much help

**Comment by Benunc** [comment]
Hi @love4dogs I'm taking a look and will reply via the support ticket. Thanks for looping us in. 

Also, for the record, Matheus is a top notch technician and we'll definitely be able to resolve this for you.
