### ISSUE TITLE
The multi-step donation form should allow decimal numbers for the custom donation amount 

### ISSUE THREAD

**Issue by alaca** [impress-org/givewp#5815]
## User Story

As a donor, I want to use decimal numbers in my new multi-step donation form, such as `$14.70`

## Details

If a donor enters a custom donation amount `$14.70`, the donation amount will be rounded up to `$15`. This happens only when the multi-step form template is being used. The legacy form template is not affected by this bug. 

**UPDATE:**
This behavior of the donation amount input is created on purpose to satisfy the design requirements of the multi-step form template. 

## Expected Behavior

The donor should be able to make donations using decimal numbers for donation amounts when the multi-step form template is being used.

## Steps to Reproduce

1. Create a new donation form that uses the multi-step template
2. Navigate to that form on the front-end 
3. Enter 14.90 for the donation amount, or any other decimal number and click somewhere else outside the form. 
4. Donation amount should be rounded up or down

## Visuals

![deepin-screen-recorder_Select area_20210505174355](https://user-images.githubusercontent.com/4222590/117169609-86691f00-adc9-11eb-9625-80f71df329a1.gif)

## Acceptance Criteria

-   [x] Donor can use decimal numbers for the donation amount when donating

**Comment by henryholtgeerts** [comment]
@alaca I believe this is done primarily so that decimal places are not displayed in the buttons, but that also creeps into the custom amount input. The approach of preventing custom decimal amounts was used to satisfy design requirements (which asked that decimals not be shown in the buttons), but was always meant to be revisited since it is really just a stop gap solution.

**Comment by alaca** [comment]
Thanks, @henryholtgeerts. Yeah, I'm not sure how should I handle this. The ideal situation would be to allow decimal numbers only in donation amount input. But as soon I remove the decimal number restriction, all numbers in the donation form will be shown as decimal numbers. I'm not sure is there an easy way how we can add support for decimal numbers and satisfy design requirements. Any ideas?
