### ISSUE TITLE
Add email opt-in into the onboarding wizard and settings area

### ISSUE THREAD

**Issue by mathetos** [impress-org/givewp#5852]
## Details

We need to allow GiveWP core users to opt into our valuable email marketing. When we built the on-boarding wizard, we lost the ability for free users to opt-in, and that has been detrimental to our email list. 

Goals for implementing this:
* Surface the opportunity in an intuitive and informative way
* For CAN-SPAM concerns, and .org guidelines, ensure they are opted-out by default
* But make opting-in as easy as possible. 
* Do not cloud the general plugins area or the WP Dashboard in any way. Limit all of this to GiveWP-specific screens. 

## Implementation Details

The current recommendation is to surface the email marketing opt-in, in 3 different places:

### GiveWP Onboarding Wizard

New users of GiveWP are walked through an onboarding wizard. We ask them specific information about their organization and how they will be doing fundraising. This is a good place to add a little more information for email marketing purposes. 

After the wizard is done they won't see this area again, so it's important that there are additional areas for users to opt into our email list. 

If they opt-in here, then they will get a user_meta key called "givewp_marketing" == true.

**CRITERIA**
None. All new users will see this opportunity regardless.

**CONCEPT**
![Wizard Step 1 with opt-in-2](https://user-images.githubusercontent.com/930724/122490862-c52cf000-cf97-11eb-8e02-be8dff51d17e.png)

**ADDITIONAL DETAILS**
You'll notice there is now also a "Your Cause Name" field in addition to the "Cause Type" field (which already exists in the wizard). The info from all three fields will be passed into our email marketing platform if they provide their email address. 

### GiveWP Set-up Screen
After the Onboarding wizard, they are dropped into a Setup screen. This should reflect whether they opted in or not during the wizard. If they did not opt-in, then they will have the chance to opt-in here as well. 

**CRITERIA**
This appears only if the "givewp_marketing" user meta is still "false".

**CONCEPT**
If they did not opt-in during the wizard, they'll see this:
![image](https://user-images.githubusercontent.com/930724/122305907-6e061d00-cebc-11eb-9662-d7c0ca0c8478.png)

If they did opt-in, or after they do directly from the setup screen, they'll see this:
![image](https://user-images.githubusercontent.com/930724/122305944-7f4f2980-cebc-11eb-9306-39c758199359.png)

### GiveWP Settings Screen
After going through the wizard and the setup screen, they will most likely land on the Settings screen in a short amount of time. So if they have not opted in at the Wizard, or at the Setup screen, then the Settings screen should have an opt-in ability with a stronger incentive, like a free premium add-on. 

**CRITERIA**
This appears only if:
1. They don't have any paid add-ons installed
2. AND the "givewp_marketing" user meta is still "false"

**CONCEPT**
If they did not opt-in at the wizard or the Setup screen, then on the Settings page they'll see this notice with a stronger incentive to opt-in:
![image](https://user-images.githubusercontent.com/930724/122306239-f08edc80-cebc-11eb-9a25-a92e9dfaf0cc.png)

If they opt-in on this CTA, then they'll see this confirmation message only while they are on the page. When they return to the settings page, no CTA will be there at all. 
![image](https://user-images.githubusercontent.com/930724/122306331-17e5a980-cebd-11eb-9933-f69e95dc03d2.png)

## ACTIVECAMPAIGN API INFORMATION*

Here's docs on creating contacts:
https://developers.activecampaign.com/reference#create-or-update-contact-new

In the case of optin-in during the wizard, we want to pass the following:
* Contact Name (default contact field, populated from user first name)
* Contact email (default contact field, populated from email field)
* Account (default contact field, populated from "Organization Name")
* Organization Website (Custom contact field, auto-populated from website url)
* Type of Fundraising (Customer contact field, populated from the wizard "Cause Type" field) 

## Acceptance Criteria

-   [x] The wizard onboarding opt-in is present.
-   [ ] The Setup screen email opt-in status is present and it shows the correct status based on whether the user opted in during the wizard or not.
-   [ ] The settings screen CTA is present if there are no paid add-ons installed and the "givewp_marketing" user meta is set to `false`. 
-  [ ] If they opt-in at the Setup page, there is a confirmation message
-  [ ] If they opt-in at the Settings screen, there is a confirmation message
-  [ ] The contact is added to our marketing list at each opt-in form correctly. 
-  [ ] The contact custom meta is added in our marketing list correctly from all three opt-in forms

**Comment by JasonTheAdams** [comment]
Thanks for writing up this thorough Issue, @mathetos!

I'm ok with being told, "Just do it!", but I did want to at least share my opinion that the onboarding opt-in is a borderline dark pattern. It's a highly implicit opt-in wherein the user has to interact with help text hover to even know that they're consenting to something. I'm not even sure this would qualify as GDPR compliant.

What if we have a checkbox which says, "I would like to receive articles and information and how to get the most out of GiveWP". If they check that then an email field appears, which is required (since they're opting in).

What do you think?
