### ISSUE TITLE
Custom Amount field on Donor Dashboard Manage Subscription should allow emptying the input

### ISSUE THREAD

**Issue by knowler** [impress-org/givewp#5896]
## Details

Right now, a user is not able to clear this input. It will always at least display the minimum value. While this might seem like it's the intended behaviour, it's actually overly zealous and creates a bad user experience, since user input in this type of field is at points partial as they are typing in the value.

## Expected Behavior

The user should be allowed to clear the input. I don’t even think this field should be correcting the value on change or on blur. One reason is that it is currency and that is deceiving. We do not want to be responsible for changing an intended amount. It would be better to explicitly notify them that the intended (or unintended) amount they enter was invalid, instead of changing it as they type it in.

## Steps to Reproduce

1. Create a recurring donation.
2. Go to the Donor Dashboard.
3. In "Recurring Donations" find the donation.
4. In the subscription management, try clearing out the amount field (for custom amount).

## Additional Context

The problem for this is all in the frontend. Looks like either the `AmountControl` or the `CurrencyControl` are the culprit.

## Acceptance Criteria

- [x] Allow empty values in for `AmountControl` or `CurrencyControl` (i.e. do not zealously mask the input).
- [x] Users can adequately change their subscription amount.
- [x] If a value less than the minimum or more than the maximum is provided, either frontend or backend validation notifies the user they need to adjust the value.

**Comment by knowler** [comment]
@JasonTheAdams @DevinWalker I don't think we should be "masking" this input to enforce a minimum or a maximum value (see the PR’s "Expected Behaviour" description for more reasoning). Instead the user should receive an explicit notification of sorts saying that the amount is either too little or too much. I believe this will provide the best user experience.

**Comment by knowler** [comment]
I’m just rubber ducking this out so I can understand it...

This is the form partial where the issue is taking place: [`<SubscriptionManager
/>`](https://github.com/impress-org/givewp/blob/baf28c0ea5277b9850f68eb397cca13e9550e8ec/src/DonorDashboards/resources/js/app/components/subscription-manager/index.js).

This is the particular field that is an issue:

https://github.com/impress-org/givewp/blob/baf28c0ea5277b9850f68eb397cca13e9550e8ec/src/DonorDashboards/resources/js/app/components/subscription-manager/index.js#L39-L43

The field is using our [`<AmountControl />`]. This control’s user interface is a
select (from [`react-select`] via our [`<SelectControl />`]) and text input for
a custom amount (from [`react-currency-input-field`] via our [`<CurrencyControl />`]). 

This is how the [`<AmountControl />`] works:

1. The component keeps track of four pieces of state:
    1. `customAmount`: The custom amount.
    2. `selectValue`: The selected value.
    3. `prevSelectedValue`: The previously selected value.
    4. `amountOptions`: This is an array of objects which represent predefined amounts to choose from.
2. On mount an effect runs which ultimately sets the initial amount options:  
   https://github.com/impress-org/givewp/blob/baf28c0ea5277b9850f68eb397cca13e9550e8ec/src/DonorDashboards/resources/js/app/components/subscription-manager/amount-control/index.js#L14-L30
    - This could be refactored to be set via a closure in the `useState` call (see ["Lazy initial state"](https://reactjs.org/docs/hooks-reference.html#lazy-initial-state)).
        - Maybe not since other states are being set here too via the affect
          that’s watching `amountOptions`.
        - I actually see that there are few things that are going on here which
          should probably be taken care of in the parent component which would
          make tracking this as state to be unnecessary.
    - It is a bit strange that the control is being given the entire `form` object. It would be better if the amount options were just a prop.
        - I see that the `form` prop is also used to set the `min` and `max` for
          the `<CurrencyControl />` ([code](https://github.com/impress-org/givewp/blob/baf28c0ea5277b9850f68eb397cca13e9550e8ec/src/DonorDashboards/resources/js/app/components/subscription-manager/amount-control/index.js#L78-L79)). I think that those should probably be props
          on the [`<AmountControl />`] as well.
3. The custom amount field is only displayed when the [`<SelectControl />`] is
   set to `custom_amount`.  
   https://github.com/impress-org/givewp/blob/baf28c0ea5277b9850f68eb397cca13e9550e8ec/src/DonorDashboards/resources/js/app/components/subscription-manager/amount-control/index.js#L75-L83
4. When the `amountOptions` change, 

Now that the problem is broken down, what should we focus on?

- I think most of my refactoring comments are outside of the scope of this fix.

[`<AmountControl />`]: https://github.com/impress-org/givewp/blob/baf28c0ea5277b9850f68eb397cca13e9550e8ec/src/DonorDashboards/resources/js/app/components/subscription-manager/amount-control/index.js
[`<CurrencyControl />`]: https://github.com/impress-org/givewp/blob/baf28c0ea5277b9850f68eb397cca13e9550e8ec/src/DonorDashboards/resources/js/app/components/currency-control/index.js
[`<SelectControl />`]: https://github.com/impress-org/givewp/blob/baf28c0ea5277b9850f68eb397cca13e9550e8ec/src/DonorDashboards/resources/js/app/components/select-control/index.js
[`react-select`]: https://www.npmjs.com/package/react-select
[`react-currency-input-field`]: https://www.npmjs.com/package/react-currency-input-field

**Comment by knowler** [comment]
The `react-currency-input-field` package provides sufficient text masking for this field to work how we want it to. We don’t need to be enforcing the minimum and maximum values through text masking, since while maximums are easy, minimums are a real pain. Instead we should be validating the amount either on `input` or on `blur` and providing feedback to the user, so they can change it. Allowing this field to be in an invalid state means that we need to be gating the submission in someway. Maybe setting `disable` to the submit button (I’ve heard negative opinions about that sort of thing) or just preventing submission and highlighting the invalid field. Either way, there currently is no front-end form validation outside of the text masking on this field (which I am removing) so I'll need to think of some way to do that. I think even if we had the field controlling its own error message, that would be sufficient. Not sure what the server does as far as validation, but if we aren't handling server errors for this form, we probably should be.

**Comment by JasonTheAdams** [comment]
@knowler I'm fine with removing the masking as it often causes more issues than it helps, as you're pointing out. So long as we properly validate that's enough.

**Comment by knowler** [comment]
Two scenarios:

1. The user adds a blank custom amount and presses submit. The server responds with a 200 status, but doesn’t update the subscription amount.
2. The user adds an incorrect custom amount (i.e. an amount outside of the minimum or maximum allowed). The server responds with a 200 status and **does** change the subscription amount to the value.

Both of these are not ideal and both of these are server-side, so that will need to be taken care of. On the front-end, I think I will also add some front-end validation that simply compares the value to its constraints and doesn’t submit if there are issues. I can make it show a helpful error message. In fact, maybe I can just make it add the error message/tip on the `blur` event.

**Comment by knowler** [comment]
https://user-images.githubusercontent.com/6908001/135341836-27b4bb50-0e6b-46ca-8cf9-3dbb1735c767.mp4

Here’s what I have for the validation error messaging. Obviously, gotta make it look prettier, but I think the flow is good. As far as UI goes, I think I’m going to highlight the input’s border in red and then use a popover sort of thing, if that's not more work than it’s worth. Otherwise, I’ll add the highlighted borders and then just add the message below.

cc: @JasonTheAdams @DevinWalker

**Comment by JasonTheAdams** [comment]
Aside from the styling you already mentioned, that looks like a good flow to me. The flow likes nice and intuitive, while also providing immediate validation feedback. 👍

**Comment by ravinderk** [comment]
@knowler Error notices look good to me. One thing I was to say is that in my suggestion if a donor enters an empty custom amount then consider that as the minimum amount and show a notice related to minimum donation. Most of the time admin keeps the default maximum amount and this is a really huge number. We must reveal the maximum donation amount only when the donor enters more than the maximum donation amount because it is rare that a donor will cross the maximum donation amount limit, so revealing it easily does not deliver value.

cc: @JasonTheAdams @DevinWalker

**Comment by DevinWalker** [comment]
@knowler this looks like an optimal solution. I think the text color for the Custom Amount field should be darkened but that's the only thing I noticed. The flow looks good 👍
