### ISSUE TITLE
Fields API: allow fields to be repeatable

### ISSUE THREAD

**Issue by knowler** [impress-org/givewp#5904]
## Details

A user might want to have an array like field, where the field input is repeated and it collects multiple values. This is different than the multiple functionality the Fields API already provides, since in this case we are creating distinct fields for each input whereas the multiple functionality just indicates that the single input is able to collect multiple values.

As far as I can tell, this is functionality that will just be added to the `Field` abstract class and so all idiomatically defined fields (i.e. field type created by extending `Field`) will have this functionality. This means that there is no need for any extra contracts to aid consumers.

As far as how it is implemented, it probably will just be a trait with a setter method and a getter method. Consumers will be responsible for how this is implemented.

## Acceptance Criteria

- [x] Implement repeatable functionality for `Text`
- [x] Legacy consumer needs to support repeating fields

**Comment by kjohnson** [comment]
Closing as stale and allowing the idea to resurface organically when needed.
