### ISSUE TITLE
Support date field in Legacy Consumer

### ISSUE THREAD

**Issue by knowler** [impress-org/givewp#5906]
## Details

Right now, the legacy consumer just renders an `input` element with the `type` attribute set to `text` for a Fields API `date` node type. This works, however, it’s not ideal. We want this to render the jQuery UI datepicker widget along with support for picking time as implemented in the Form Field Manager addon.

## Acceptance Criteria

- [ ] Use datepicker for rendering Fields API `date` field in legacy consumer.

**Comment by kjohnson** [comment]
Closing in favor of v3 development, which deprecates `\Give\Form\LegacyConsumer`.
