### ISSUE TITLE
Notice: FieldsAPI\Group could not be converted to int 

### ISSUE THREAD

**Issue by Khadreal** [impress-org/givewp#5911]
## Details
After updating core plugin and the addon to the latest version, This error has flood my error log 
**Notice: Object of class Give\Framework\FieldsAPI\Group could not be converted to int in wp-includes/class-wp-post.php on line 234**

I have checked my settings but can't seem to figure out what the issue is.

## Additional Context
This is showing on both the admin and the frontend. 

## Acceptance Criteria
-   [ ] This shouldn't happen

**Comment by JasonTheAdams** [comment]
Hi @Khadreal!

Thanks for letting us know! Is there any further information you can provide? A stack trace, perhaps? I'm not sure where the `WP_Post::get_instance` method would be called and passed a `Group` off-hand.

**Comment by JasonTheAdams** [comment]
Since we haven't heard back in quite some time, please reach out to our [support team](https://givewp.com/support) for help with this if it happens again. They will look into the issue with you and bring clear steps to the dev team if there's a bug.
