### ISSUE TITLE
Issue with 2.13.0 release

### ISSUE THREAD

**Issue by rodsotdia** [impress-org/givewp#5923]
I installed the last version `2.13.0` from `2.12.3`. I have several blocks that use WYSIWYG as editor (they are not related with Give), and now all those blocks are not working.

If I edit them, I get the following message:
![image](https://user-images.githubusercontent.com/58403142/130169886-fff4a5f4-1696-4298-a7f1-5503f4a5f568.png)

In the console, I'm getting this error:
![image](https://user-images.githubusercontent.com/58403142/130169991-e2950fb2-641c-41cc-94fc-b8bf86b91790.png)

If I roll back to version `2.12.3` the issue is fixed.

I'm using:
WordPress `5.8.0`
Give - Donation Plugin `2.13.0`
Give - Annual Receipts `1.1.0`
Give - Currency Switcher `1.5.0`
Give - Donation Upsells for WooCommerce `1.1.6`
Give - Fee Recovery `1.9.2`
Give - Form Field Manager `1.6.0`
Give - Manual Donations `1.5.0`
Give - PDF Receipts `2.3.11`
Give - Recurring Donations `1.12.6`
Give - Tributes `1.5.8`
WooCommerce `5.6.0`
WooCommerce Stripe Gateway `5.4.0`

**Comment by DevinWalker** [comment]
@rodsotdia can you try using WP-Rollback to see if using the previous version `2.12.3` fixes your issue? This will hopefully fix your issue and also narrow it down to this latest version causing the issue with TinyMCE. 

https://wordpress.org/plugins/wp-rollback/

**Comment by rodsotdia** [comment]
@DevinWalker Thanks! Yeah, I installed the version `2.12.3` and the problem is resolved.

**Comment by ravinderk** [comment]
WP 5.8.0 new page javascript error on localhost:

![Add New Page ‹ GiveWP Test Site — WordPress 2021-08-20 at 9 38 13 AM](https://user-images.githubusercontent.com/1784821/130177683-c775b595-d893-45e4-aa0b-a21a95731efb.jpg)

**Comment by ravinderk** [comment]
This has been solved: https://github.com/impress-org/givewp/pull/5925
