### ISSUE TITLE
Legacy consumer: textarea field should feature to render as editor

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#5928]
## Details

Legacy consumer does not render textrarea field with `Rich Textarea` or `Small Rich Textarea`

## Acceptance Criteria

-   [x] Add feature to Legacy consumer to render textarea field as editor.

**Comment by knowler** [comment]
@ravinderk Can you confirm that this actually worked in FFM before we move forward with it. When I tried it, it wasn’t working, but I’m a n00b so it might have been how I was using it that was wrong.

**Comment by ravinderk** [comment]
@ravinderk Can you confirm that this actually worked in FFM before we move forward with it. When I tried it, it wasn’t working, but I’m a n00b so it might have been how I was using it that was wrong.

@knowler Yes, it is working fine for me.

![Edit Donation Form ‹ give — WordPress 2021-08-24 at 10 06 37 AM](https://user-images.githubusercontent.com/1784821/130556487-74277881-34d6-42fd-a757-dcddb5f8c445.jpg)

![Help Feed America – give 2021-08-24 at 10 06 06 AM](https://user-images.githubusercontent.com/1784821/130556456-79eb35fc-0912-4065-9781-f988e8fbd0a4.jpg)
