### ISSUE TITLE
Test Emails for Donor Emails send to the "From Email" rather than the user that initiated the test

### ISSUE THREAD

**Issue by d4mation** [impress-org/givewp#5939]
## User Story

As a site admin, when running an email test I would like for it to be sent to me rather than to the email address set as the "From Email" within the settings.

Since I was not receiving the emails myself, I assumed that something was broken within the plugin or the site as a whole. It wasn't until I installed an email logging plugin that I realized they were going to the wrong user. 

## Details

Sending Test Emails under the Donations -> Settings -> Emails -> Donor Emails screen sends to the email address stored under Donations -> Settings -> Emails -> Email Settings rather than to the email address of the logged in user.

## Expected Behavior

Sending Test Emails under the Donations -> Settings -> Emails -> Donor Emails screen should send an email to the logged in user. 

## Steps to Reproduce

1. Go to the Donations -> Settings -> Emails -> Donor Emails screen
2. Click "Send Test Email" for any of the options
3. Wait for an email in the inbox of the logged in user
4. It arrives in the inbox of the email address stored under Donations -> Settings -> Emails -> Email Settings instead.

## System Information

<details><summary>Details</summary>

### WordPress Environment ###

Home URL: https://goodshepherdcatholicradio.org
Site URL: https://goodshepherdcatholicradio.org
WP Version: 5.8
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: page
Page on Front: Home (#694)
Page for Posts: Blog (#22827)
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, tribe-ea-success, tribe-ea-failed, tribe-ea-schedule, tribe-ea-pending, tribe-ea-draft, tribe-ignored, radioshow-occurrence, radioshow-draft, wp_stream_enabled, wp_stream_disabled, give_subscription

### Server Environment ###

Hosting Provider: WP Engine
TLS Connection: Connection uses TLS 1.3
TLS Connection: Probably Okay
Server Info: Apache
PHP Version: 7.4.22
PHP Post Max Size: 100 MB
PHP Time Limit: 3600
PHP Max Input Vars: 10000
PHP Max Upload Size: 50 MB
cURL Version: 7.58.0, OpenSSL/1.1.1
SUHOSIN Installed: –
MySQL Version: 5.7.34
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### GiveWP Configuration ###

GiveWP Version: 2.13.1
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Updates: All Database Migrations Completed.
Database Tables: ✔ wp_give_donors✔ wp_give_donormeta✔ wp_give_comments✔ wp_give_commentmeta✔ wp_give_sessions✔ wp_give_formmeta✔ wp_give_sequential_ordering✔ wp_give_donationmeta✔ wp_give_revenue
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt❌New Offline Donation❌Offline Donation Instructions✔New User Registration✔User Registration Information✔Donation Note❌Email access❌Renewal Receipt Email❌Renewal Receipt Email❌Subscription Cancelled Email❌Subscription Cancelled Email❌Subscription Completed Email❌Subscription Reminder Email❌Subscriptions Email Access✔Subscription Payment Failed Email
Upgraded From: 2.12.3
Test Mode: Disabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://goodshepherdcatholicradio.org/donation-complete/
Failure Page: https://goodshepherdcatholicradio.org/donation-failed/
Donation History Page: https://goodshepherdcatholicradio.org/donor-dashboard-4/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Authorize.net, PayPal Standard
Default Payment Gateway: Authorize.net
PayPal IPN Verification: Enabled
PayPal IPN Notifications: IPN received for #61789 ( 7G2373409L926330M ) on 08/27/2021 at 15:16. Status VERIFIED
Donor Email Access: Disabled
Stripe Webhook Notifications: N/A

### Active GiveWP Add-ons ###

Give - Authorize.net Gateway: ✔ Licensed – by GiveWP – 1.4.6
Give - Recurring Donations: ✔ Licensed – by GiveWP – 1.12.6

### Other Active Plugins ###

AddToAny Share Buttons: by AddToAny – 1.7.46
Advanced Post Manager: by Modern Tribe, Inc. – 4.5
Akismet Anti-Spam: by Automattic – 4.1.11
Check & Log Email: by WPChill – 1.0.2
Classic Editor: by WordPress Contributors – 1.6.2
CPT Newsletters: by Eric Defore – 1.0.0
CPT On-Air Personalities: by Eric Defore – 1.0.1
CPT Radio Shows: by Eric Defore – 2.0.2
CPT Staff: by Eric Defore – 1.0.1
CPT Underwriters: by Eric Defore – 1.0.0
Easy FancyBox: by RavanH – 1.8.18
Email Log: by Sudar – 2.4.5
EWWW Image Optimizer: by Exactly WWW – 6.2.3
Git Updater: by Andy Fragen – 10.4.2
Gravity Forms: by Gravity Forms – 2.5.9
GSCR Scheduled Banners: by Eric Defore – 1.0.1
ManageWP - Worker: by GoDaddy – 4.9.9
RBM Custom Post Types: by Real Big Marketing – 1.2.1
RBM Field Helpers Wrapper: by Eric Defore – 1.1.4
Rewrite Rules Inspector: by Automattic, Daniel Bachhuber – 1.3.1
Stop Donor Spam: by Matt Cromwell – 1.2.0
Stream: by XWP – 3.7.0
The Events Calendar: by The Events Calendar – 5.9.0
The Events Calendar: Community Events: by The Events Calendar – 4.8.7
The Events Calendar PRO: by The Events Calendar – 5.9.0
User Submitted Posts: by Jeff Starr – 20210719
User Switching: by John Blackbourn & contributors – 1.5.7
Which Template File: by Gilles Dumas – 4.6.0
WP Crontrol: by John Blackbourn & crontributors – 1.10.0
WP Mail SMTP: by WPForms – 3.0.3

### Active MU Plugins ###

Force Strong Passwords - WPE Edition: by Jason Cosper – 1.6.4
ManageWP - Worker Loader: by GoDaddy –
WPE ElasticPress Autosuggest Logger: by WP Engine – 1.0.0
WP Engine Seamless Login Plugin: by WP Engine – 1.5.5
WP Engine Security Auditor: by wpengine – 1.0.10
WP Engine System: by WP Engine – 4.1.0

### Theme ###

Name: Good Shepherd Catholic Radio - Theme 2017
Version: 1.1.9
Author URL: http://realbigmarketing.com/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

</details>

## Acceptance Criteria

-   [x] Something happens when an action is taken.
-   [ ] Something does not happen when an action is taken.
-   [ ] Fixing behavior in Component A does not affect existing behavior in Component B.

**Comment by Benunc** [comment]
Hey @d4mation 

That's some great product feedback, and I've logged it [on our product feedback site](https://feedback.givewp.com/feature-requests/p/test-emails-should-go-to-the-user-who-is-currently-logged-in) for others to vote on and ultimately for the team to decide on.

Please vote and comment there to be notified when we prioritize this issue.

Github is not the best place to determine how many folks are experiencing an issue, so that's why we instituted the feedback site. 

We'll monitor it over there, and if it makes the cut, the team will then move it over to GitHub once it's added to a product roadmap.

Thanks!
