### ISSUE TITLE
Donation level id should store as string in database for donation form which generate in onboarding process

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#5940]
## Details

I find out that donation level id stores in integer format for donation form which generated in onboarding.
https://github.com/impress-org/givewp/blob/757e11895c8fd87cfa42d11d9eb8aa6ba1135a57/src/Onboarding/DefaultFormFactory.php#L150

Correct donation level id format is `string`. If we store donation level id as integer then, it is possible then at few place we will get wrong donation amount for that donation level ( if we are using strict type comparision ).

## Expected Behavior

Donation level id must store in integer format.

## Steps to Reproduce

1. Complete GiveWP plugin onboarding process.
2. Check `_give_donation_levels` meta key for  donation form.

## Visuals

Expected
![image](https://user-images.githubusercontent.com/1784821/131492211-3c53b7c6-4d66-4d9b-b619-28a7a47f067b.png)

Result
![image](https://user-images.githubusercontent.com/1784821/131492240-b0a3e2e2-ef8e-4b03-aef3-fabb1b1045f2.png)

## Acceptance Criteria

-   [x] Donation level id and level amount store as string in database.

**Comment by JasonTheAdams** [comment]
@ravinderk, why does it ultimately matter? Isn't the string ultimately being cast as an integer? Or the integer as a string? Why does this break things?

**Comment by ravinderk** [comment]
> @ravinderk, why does it ultimately matter? Isn't the string ultimately being cast as an integer? Or the integer as a string? Why does this break things?

I discuss this with @JasonTheAdams in Slack and on the pull request.
