### ISSUE TITLE
Legacy Consumer: default values not used for multi-select

### ISSUE THREAD

**Issue by knowler** [impress-org/givewp#5951]
## Details

I noticed that default values are not set in the select template when `multiple` is set to true. It needs to be able to set the default value for multiple options.

## Acceptance Criteria

- [x] Select template should set `selected` on `<option>` elements whose `value` corresponds to a value in the `Select::$defaultValue` array.

**Comment by ravinderk** [comment]
this has been fixed: https://github.com/impress-org/givewp/compare/abbe5ff369a2...919a525d79e0

**Comment by knowler** [comment]
Thank you, @ravinderk!
