### ISSUE TITLE
Sending a test admin template email results in fatal error

### ISSUE THREAD

**Issue by mrpatg** [impress-org/givewp#5952]
## User Story

Trying to send a test email from the donor/admin emails page in plugin settings screen.

## Details

Clicking the link results in the WordPress fatal error page reading: 

`There has been a critical error on this website. Please check your site admin email inbox for instructions.

Learn more about troubleshooting WordPress.`

PHP Error Log Reads:

`PHP Fatal error:  Uncaught TypeError: strtolower(): Argument #1 ($string) must be of type string, array given in /var/www/html/wp-content/plugins/give/includes/admin/admin-pages.php:136\nStack trace:\n#0 [internal function]: strtolower()\n#1 /var/www/html/wp-content/plugins/give/includes/admin/admin-pages.php(136): array_map()\n#2 /var/www/html/wp-content/plugins/give/includes/class-give-scripts.php(196): give_is_admin_page()\n#3 /var/www/html/wp-includes/class-wp-hook.php(303): Give_Scripts->admin_enqueue_scripts()\n#4 /var/www/html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()\n#5 /var/www/html/wp-includes/plugin.php(470): WP_Hook->do_action()\n#6 /var/www/html/wp-admin/admin-header.php(102): do_action()\n#7 /var/www/html/wp-admin/admin.php(239): require_once('...')\n#8 /var/www/html/wp-admin/edit.php(10): require_once('...')\n#9 {main}\n  thrown in /var/www/html/wp-content/plugins/give/includes/admin/admin-pages.php on line 136, referer: https://HOST/wp-admin/edit.php?post_type=give_forms&page=give-settings&tab=emails`

Possible relation to fix in https://github.com/impress-org/givewp/pull/2954

## Expected Behavior

Test email should be sent

## Steps to Reproduce

Go to GiveWP Settings
Go to Emails
Go to donor or admin emails
Hover over a template link
Click "send test email"

## Visuals

![image](https://user-images.githubusercontent.com/751233/132277153-bd10b91b-a3f5-4b34-a4ce-98bfb2939839.png)

## System Information

<details><summary>Details</summary>
WP Version: |   | 5.8
Server Info: |   | Apache/2.4.29 (Ubuntu)
PHP Version: |   | 8.0.9
GiveWP Version: |   | 2.13.4

</details>

## Acceptance Criteria

-   [ ] Able to send template test emails

**Comment by mrpatg** [comment]
Quick (and verbose) fix if anyone else is running into this:
admin-pages.php line 136:

	// $get_query_args = ! empty( $_GET ) ? @array_map( 'strtolower', $_GET ) : [];
	if(!empty($_GET)){
		foreach($_GET as $key=>$value){
			if(!is_array($value)){
				$get_query_args[strtolower($key)] = strtolower($value);
			}
		}
	}else{
		$get_query_args = [];
	}

**Comment by JasonTheAdams** [comment]
@mrpatg I just tried to reproduce this on the latest release and I'm getting this error. Would you mind reaching out to our [Amazing Support Team](https://givewp.com) so they can dig into the issue further with you?
