### ISSUE TITLE
Stripe Critical Admin Error after Updating to 2.13

### ISSUE THREAD

**Issue by Akwaduk** [impress-org/givewp#5953]
## User Story

As a user, I would like to have the admin accessible after updating a plugin.

## Details

After updating to the plugin version 2.13 the admin was longer accessible for the site.

## Expected Behavior

The critical error is shown on site after updating from version 2.12 to 2.13.

## Steps to Reproduce

1. Upgrade from 2.12 to 2.13
2. (Sounds like this may be configuration dependant, so set the appropriate configuration first. Or create a form with a specific configuration before upgrading)
3. log in as an administrator

## Visuals

This is the fatal error that is shown after logging in as an admin

Fatal error: Uncaught Error: Call to undefined function Give\PaymentGateways\Stripe\give_stripe_is_any_payment_method_active() in /siteroot/public_html/wp-content/plugins/give/src/PaymentGateways/Stripe/DonationFormSettingPage.php:82 Stack trace: #0 /siteroot/public_html/wp-content/plugins/give/src/PaymentGateways/Stripe/DonationFormSettingPage.php(25): Give\PaymentGateways\Stripe\DonationFormSettingPage->canRegisterTab() #1 [internal function]: Give\PaymentGateways\Stripe\DonationFormSettingPage->__invoke(Array, NULL) #2 /siteroot/public_html/wp-content/plugins/give/src/Helpers/Hooks.php(73): call_user_func_array(Array, Array) #3 /siteroot/public_html/wp-includes/class-wp-hook.php(292): Give\Helpers\Hooks::Give\Helpers\{closure}(Array, NULL) #4 /siteroot/public_html/wp-includes/plugin.php(212): WP_Hook->apply_filters(Array, Array) #5 /siteroot/public_html/wp-content/plugins/give/includes/admin/forms/class-metabox-form-data.php(592): apply_filters('give_metabox_fo...', Array, NULL) #6 /siteroot in /siteroot/public_html/wp-content/plugins/give/src/PaymentGateways/Stripe/DonationFormSettingPage.php on line 82

## Additional Context

Once I change the function in this file
/public_html/wp-content/plugins/give/src/PaymentGateways/Stripe/DonationFormSettingPage.php

	private function canRegisterTab() {
		return give_stripe_is_any_payment_method_active();
               return "true";
	}

To return true, it seems to allow me to log into the admin.

## System Information

PHP 7.3.30
WordPress 5.8

## Acceptance Criteria

Would like to get the site admin to not break upon login when upgrading the plugin to 2.13.4

Thank you

**Comment by JasonTheAdams** [comment]
Hi @Akwaduk!

Would you mind reaching out to our awesome [Support Team](https://givewp.com/support)? There are some things not making sense to me, and they'll be able to dig deeper into the issue with you. For example, the class which loads the file that defines that function should always be loaded unless running an old version of the GiveWP Stripe add-on, or if it's not installed. The fact that it's not defined for you is odd, and I'm not able to quickly reproduce this.

I'm going to close this, but they will make sure the right folks hear about it once they've had a chance to dig a bit more.

Thank you!
