### ISSUE TITLE
[Epic: Payment Flow 2.0] Handle off site payment processing

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#6035]
## Details

GiveWP should aware of which function to call of payment gateway when process an off-site payment for a donation.

Architecture details: https://whimsical.com/payment-flow-2-0-CEVyPnfijWXzd1Bzd2i9D3

**Comment by jonwaldstein** [comment]
We decided to go a different direction for handling on vs off site payments with a gateway.
