### ISSUE TITLE
[Epic: Payment Flow 2.0] Handle payment gateway hosted payment fields

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#6036]
## Details

GiveWP should aware of which function to call of payment gateway when loading/setup payment gateway hosted fields like credit card fields, smart buttonsetc.

Architecture details: https://whimsical.com/payment-flow-2-0-CEVyPnfijWXzd1Bzd2i9D3

**Comment by jonwaldstein** [comment]
In https://github.com/impress-org/givewp/pull/6048 there is a method on the gateway to handle this called `getLegacyFormFieldMarkup()`
