### ISSUE TITLE
Babel Polyfill is missing after switch to Laravel Mix

### ISSUE THREAD

**Issue by knowler** [impress-org/givewp#6077]
## Details

I noticed 404s for the Babel Polyfill after switching to Laravel Mix. It seems to have been missed during the switch.

## Expected Behavior

It should be there...

Or maybe not since it’s outdated and we no longer support IE 11. This might be the time to remove the feature.

## Acceptance Criteria

- [ ] The fate of our Babel Polyfill feature is decided upon and the solution has been implemented.

**Comment by JasonTheAdams** [comment]
@knowler Here's the documentation stating that it's deprecated: https://babeljs.io/docs/en/babel-polyfill.html

I'm thinking we're fine to proceed as babel will handle the main changes, and we don't need to add extra bloat for a browser we no longer support.

Let's decide on this quickly and move on. I don't want this to dangle.

**Comment by knowler** [comment]
@JasonTheAdams I definitely agree and it’s not like this is something that we’ve made. Users can always add the script themselves. With that said, let's make sure we provide support with a snippet that pulls the script from a CDN or something.

**Comment by JasonTheAdams** [comment]
Cool. @Benunc, if for some reason folks start raising issues regarding IE 11 or older, they can try adding https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/7.8.7/polyfill.min.js as a script. But really, we just don't support IE 11.

**Comment by knowler** [comment]
@JasonTheAdams We should probably follow this up with a PR to remove the option in the admin settings as well.
