### ISSUE TITLE
Developer should be able to run PHPUnit tests

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#6157]
## Details

When running PHPUnit tests than in bootstrap process Give plugin initiate twice (`give_init` fires twice) because `give.php` also loading in `uninstall.php`:
https://github.com/impress-org/givewp/blob/2a7f671f6d499ffc52bc7a462b511d8625ea169f/uninstall.php#L18 

PHPUnit tests fail if we process something on `give_init` which means to be run only once. For example, a new payment gateway registers default payment gateways.

![give Shell 2021-12-27 at 1 42 51 PM](https://user-images.githubusercontent.com/1784821/147450436-7a550b1e-1b03-414d-9d76-415d39887c8c.jpg)
I was getting this error in pull request https://github.com/impress-org/givewp/pull/6154

## Solution

Find a way to load only required files in `uninstall.php` instead of loading the entire Give plugin.

## Acceptance Criteria

- [ ] Only required files load in `uninstall.php`.
- [ ] Plugin uninstall functionality working fine.
- [x] PHPUnit tests are running fine.

**Comment by kjohnson** [comment]
@ravinderk this should be resolved here: https://github.com/impress-org/givewp/pull/6135
