### ISSUE TITLE
Admin defined recurring donation form with set price should reflect summary

### ISSUE THREAD

**Issue by jonwaldstein** [impress-org/givewp#6165]
## User Story

As a donor, I want to see my accurate donation frequency in the summary so that I can confirm my donation details.

## Details

The donation form settings are not displaying the right details.

## Expected Behavior

The summary should reflect the frequency defined in the form settings.

## Steps to Reproduce

1. Go to donation form settings
2. Set "Donation Option" = "Set Donation"
3. Set "Recurring Donations" = "Yes - Admin Defined"
4. Publish form
5. Now donate up to the summary and see how it still says "one-time" not "monthly" or w/e your frequency is

## Visuals

**Settings**

![Screen Shot 2022-01-05 at 12 14 15 PM (1)](https://user-images.githubusercontent.com/10138447/148284215-aa675605-4618-48a7-b979-56251603ac2b.png)

**Donation Summary**

![Screen Shot 2022-01-05 at 12 14 43 PM](https://user-images.githubusercontent.com/10138447/148284158-ddfdb406-6a6b-45db-9bc7-004f829dcfd5.png)

**Donation Receipt**

![Screen Shot 2022-01-05 at 12 14 56 PM](https://user-images.githubusercontent.com/10138447/148284196-17115d5f-be9e-4b0a-8088-be6059305372.png)

## System Information

<details><summary>Details</summary>

Mac / Chrome based browser

</details>

## Acceptance Criteria

-   [x] The donation summary accurately reflects the donation frequency

**Comment by jonwaldstein** [comment]
### Status Update

I started debugging and discovered this:

**The _admin-defined_ js observer is looking for a price ID...**

![Screen Shot 2022-01-05 at 3 29 43 PM](https://user-images.githubusercontent.com/10138447/148284925-4c9b760a-f4df-4a66-85f5-19aa2ebc3633.png)

**But the Price ID is only added when multi-level is set.**

![Screen Shot 2022-01-05 at 3 30 07 PM](https://user-images.githubusercontent.com/10138447/148284894-4e7e76c8-4db5-4525-8184-140b765fff45.png)

**Furthermore, It looks like inside the check for `name="give-recurring-period` we are checking for a donor option again which leads me to think some other kind of admin-defined check was supposed to happen here for the set price.**
 
![Screen Shot 2022-01-05 at 3 36 06 PM](https://user-images.githubusercontent.com/10138447/148285626-9ada1319-f359-4e2c-b713-2cea19376222.png)

I'm not exactly sure what the best approach for this fix would be until I understand what these moving pieces are intended to do.  Greatly appreciated if anyone has any insight into this @impress-org/give-team

**Comment by JasonTheAdams** [comment]
Good catch, @jonwaldstein. Since the amount and recurrence are defined on the server, do you think it would be a big deal to simply add the expected hidden field(s), even though they won't be dynamically adjusted?
