### ISSUE TITLE
“All Forms” admin UI should be refreshed

### ISSUE THREAD

**Issue by knowler** [impress-org/givewp#6175]
The donation forms list page should be updated to use the new GiveWP Admin UI. The page should be a single page application that doesn’t need to refresh for new data or different views. We will be starting simple so some existing feature will not be implemented until further scopes related to other list pages.

## Acceptance Criteria

- [x] Visual design is updated to match new Admin styles
- [x] Admin API endpoint is created for donation forms
- [x] Data is paginated

**Comment by LMNTL** [comment]
Resolved by #6241.
