### ISSUE TITLE
Gateway route should validate donation id and payment gateway ID

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#6187]
## Details

Gateway route (new gateway api) should validate donation id and payment gateway Id. Currently, we are validating them. It will add help to tighten security on the gateway route.

https://github.com/impress-org/givewp/blob/498227b76278c899d83e62ba42a50495f9635fda/src/Framework/PaymentGateways/Routes/GatewayRoute.php#L30

## Acceptance Criteria

-   [ ] Donation and payment gateway ID validate before calling payment gateway method.

**Comment by jonwaldstein** [comment]
@ravinderk the gateway ID is already being validated here.  I guess we can validate the `donationId` as well to make sure it exits. We also have a white-list of allowed method to be called which are defined by the gateway. So even if someone was trying to be malicious, they will be gated by the actual gateway requests.

**Comment by ravinderk** [comment]
> @ravinderk the gateway ID is already being validated here. I guess we can validate the `donationId` as well to make sure it exits. We also have a white-list of allowed method to be called which are defined by the gateway. So even if someone was trying to be malicious, they will be gated by the actual gateway requests.

@jonwaldstein Yes, we are validating gateway id but I am suggesting validating gateway id with a donation. Is donation donate with the same gateway?

**Comment by jonwaldstein** [comment]
@ravinderk ah I see what you're saying now. I like that idea.

**Comment by ravinderk** [comment]
In meeting with @jonwaldstein @kjohnson @JasonTheAdams, we decided to add nonce protection to the gateway redirect route URL. This makes url secure and we do not need to validate donation and gateway id.
