### ISSUE TITLE
Plugin deactivation link "Skip and deactivate" should not open in a new window

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#6190]
## Details

I'm not sure how this link got `target="_blank"` put on it, but it should not open a new window/tab when deactivating. It's a strange UX and should be remedied by removing this attribute.

## Expected Behavior

Plugin is deactivated and no window is opening. The modal is closed.

## Steps to Reproduce

1. Deactivate plugin
2. See modal
3. Click link

## Visuals

<img width="727" alt="2022-01-28_09-50-00" src="https://user-images.githubusercontent.com/1571635/151597028-5f1a2ea9-25d7-4048-9dd9-e31c53376e3e.png">

**Comment by JasonTheAdams** [comment]
Looks like back in July the reused JS modal was updated such that this link was `target="_blank"`, which makes sense for many use cases. We'll want to add an option to the modal for this to open in a new tab or not.
