### ISSUE TITLE
[Scope: Form Admin UI] donation form should link to correct donation form report page

### ISSUE THREAD

**Issue by ravinderk** [impress-org/givewp#6225]
## Details

The donation form should link to the correct donation form report page on the admin donation form page. The current link takes me to the report page which shows me data for all forms but I was expecting data only for the selected donation form.

We support reports on a per form basis in the legacy report. I was expecting page 👇 
![Donation Reports ‹ GiveWP Playground — WordPress 2022-02-10 at 10 42 33 AM](https://user-images.githubusercontent.com/1784821/153341867-daef358d-ad85-46d5-a1c7-0da400e364e1.jpg)

## Acceptance Criteria

-   [x] Admin see a report of specific donation form when clicking on total revenue in on admin donation form page.

**Comment by LMNTL** [comment]
This was resolved here:
https://github.com/impress-org/givewp/commit/08e99841dfc8d2be54f95624b34d3107cd201e62
