### ISSUE TITLE
[Existing functionality] should integrate with [some application]

### ISSUE THREAD

**Issue by mrpritchett** [impress-org/givewp#6229]
## User Story

As a SendWP user, I want to see an integration with SendWP so that SendWP and Give customers can automatically sign up if needed.

## Details

Other plugins in the space allow users to sign up for SendWP within their app when they have trouble with email deliverability. I believe on the email settings page would be a good place to integrate.

## Additional Context

To be clear, I own SendWP. 

## Acceptance Criteria

-   [ ] Can automatically download and connect SendWP by clicking button.
-   [ ] Can disconnect if needed.

**Comment by JasonTheAdams** [comment]
Closing per https://github.com/impress-org/givewp/pull/6230#issuecomment-1039276699
