### ISSUE TITLE
Elementor panel resize bar positioned off screen due to GiveWP rtl css

### ISSUE THREAD

**Issue by danieliser** [impress-org/givewp#6231]
## User Story

Editing a page when GiveWP is active makes it impossible to resize the Elementor panel on the side.

## Details

This CSS rule is setting left to -5px on the Elementor Panel. I'm guessing your sharing a class on that element, but your left rule is overruling theirs.

Secondly I don't know why the RTL stuff is loading in the first place, this site is in english and LTR.

## Expected Behavior

Shouldn't set left positioning of elements with a clearly generic class name. Or should set it in a context to not apply globally? Not sure as Elementor is clearly setting positions using that class too.

## Steps to Reproduce

Edit any page and try to resize the panel on the left.

## Visuals

![image](https://user-images.githubusercontent.com/847818/153799823-8dd54c9e-65ba-44cf-9eaf-2c098c94e9c0.png)

Your rules in Yellow, theirs in Orange
![image](https://user-images.githubusercontent.com/847818/153799918-43735a56-fdc1-4cb8-886f-90644b1021b8.png)

Shoulnd't be on the red side, but rather green.

![image](https://user-images.githubusercontent.com/847818/153800024-2b69d041-532f-4b76-95c9-966f4e6c93c7.png)

**Comment by kjohnson** [comment]
Hey @danieliser - from what I can tell this issue has been resolved. I'm unable to reproduce this with a combination of GiveWP and Elementor.
