### ISSUE TITLE
Goal progress on the new form list table should work for percentages

### ISSUE THREAD

**Issue by JoshuaHungDinh** [impress-org/givewp#6380]
## Details

Currently, if you set the goal of a form to “Percentage Raised” the display will show the progress dollar amount with a trailing % symbol. For example, if the total amount of donations for a form is $300, it will display 300%.

## Expected Behavior

While using the “Percentage Raised” option to display your progress for a form goal it should calculate and display the proper percentage amount to the goal.

## Steps to Reproduce

1. Edit a form
2. Select Donation Goal under Donation Form Options
3. Enable Donation Goal
4. Set Goal Format to “Percentage Raised” 
5. Set Goal amount 
6. Process a donation 
7. View Donations > All Forms
 

## Visuals

![image](https://user-images.githubusercontent.com/75056371/164768915-c5a26e93-1194-42b4-a27f-a9dc9fadcb8c.png)

## Acceptance Criteria

-   [x] Donation Percentage Raised displays the correct percentage to goal
-   [x] Other Goal formats still display correctly

**Comment by LMNTL** [comment]
Fixed in #6383.
