### ISSUE TITLE
Plugin causes deprecation warnings on PHP8

### ISSUE THREAD

**Issue by G-Rath** [impress-org/givewp#6462]
While #5871 fixed a few instances, there are still a number of uses of deprecated syntax in this plugin:

![image](https://user-images.githubusercontent.com/3151613/173921011-953ab49c-d461-420e-bee0-5bb1517bb7df.png)

![image](https://user-images.githubusercontent.com/3151613/173921174-fa340e8f-9457-4b2a-82ad-4d03355a6057.png)

We're using v2.19.3 currently, but I've found at least one instance of the deprecated syntax in the latest code: https://github.com/impress-org/givewp/blob/develop/includes/class-give-donor.php#L1089

I would recommend using something like https://github.com/PHPCompatibility/PHPCompatibility to try and identify other uses of deprecated syntax.

**Comment by robrecord** [comment]
I'm getting a white screen on local development site with WP_DEBUG_DISPLAY enabled, and this output on the screen:

```

Deprecated: Required parameter $meta_value follows optional parameter $meta_key in /srv/www/example.com/current/web/app/plugins/give/includes/class-give-donor.php on line 1089

Deprecated: Required parameter $meta_value follows optional parameter $meta_key in /srv/www/example.com/current/web/app/plugins/give/includes/class-give-donor.php on line 1105

Deprecated: Required parameter $form_id follows optional parameter $nonce in /srv/www/example.com/current/web/app/plugins/give/includes/formatting.php on line 794

Deprecated: Required parameter $payment_id follows optional parameter $form_id in /srv/www/example.com/current/web/app/plugins/give/includes/deprecated/deprecated-functions.php on line 488

Deprecated: Required parameter $payment_id follows optional parameter $give_form_id in /srv/www/example.com/current/web/app/plugins/give/includes/deprecated/deprecated-functions.php on line 549

Deprecated: Required parameter $amount follows optional parameter $form_id in /srv/www/example.com/current/web/app/plugins/give/includes/deprecated/deprecated-functions.php on line 780

Warning: Cannot modify header information - headers already sent by (output started at /srv/www/example.com/current/web/app/plugins/give/includes/class-give-donor.php:1089) in /srv/www/example.com/current/web/wp/wp-includes/pluggable.php on line 1421

Warning: Cannot modify header information - headers already sent by (output started at /srv/www/example.com/current/web/app/plugins/give/includes/class-give-donor.php:1089) in /srv/www/example.com/current/web/wp/wp-includes/pluggable.php on line 1424
```

**Comment by G-Rath** [comment]
This is still relevant

**Comment by treysea** [comment]
experiencing the same issue

**Comment by G-Rath** [comment]
This is still relevant

**Comment by G-Rath** [comment]
This is still relevant

**Comment by JasonTheAdams** [comment]
We're now doing [automated compatibility checking](https://github.com/impress-org/givewp/pull/6781) with the package mentioned above, and have added quite a few fixes. Would you mind checking again from your end? Perhaps you're still seeing something we're not — in which case I'd like to know how so we can improve out automated checking. 😄

**Comment by JasonTheAdams** [comment]
We haven't heard back and currently have the checks in place, so I'm going to close this out. Please open a [discussion](https://github.com/impress-org/givewp/discussions) if you run into further compatibility issues!
