### ISSUE TITLE
Generate API Key checkbox does not have a label

### ISSUE THREAD

**Issue by TimothyBJacobs** [impress-org/givewp#6465]
## User Story

As a site admin, I want to be able to click the "Generate API Key" text to check/uncheck the checkbox on my profile page.

## Details

The description is a `span`, not a `label`.

https://github.com/impress-org/givewp/blob/8072aba1bdc9932c6818f06bb205ec56564c2deb/includes/api/class-give-api.php#L1922

## Expected Behavior

For the checkbox to have an associate label

## Steps to Reproduce

1. Go to your Profile page as an administrator of a Give instance.
2. Click on "Generate API Key"
3. Expect the checkbox to be toggled.

## Acceptance Criteria

-   [x] Clicking the "Generate API Key" or "GiveWP API Keys" text should toggle the checkbox.

**Comment by kjohnson** [comment]
@TimothyBJacobs the related PR has been approved and merged into `develop`, which will be included in the next release.
