### ISSUE TITLE
[Preview email] should...

### ISSUE THREAD

**Issue by Genevieve-K** [impress-org/givewp#6502]
## User Story

As an admin, I want to preview emails with a donation ID and there is an error.

## Details

On the email list, I want to preview an email. I see the email no associated to a donation. I choose a donation, and there is the error, the session is not recognized.

## Expected Behavior

The email must be displayed for a donation.

## Steps to Reproduce

1. Go to Settings > Emails
2. Choose an email(e.g. Donation Receipt) and click Preview
3. Select a donation to preview
4. Error: We're unable to recognize your session. Please refresh the screen to try again; otherwise contact your website administrator for assistance.

## Visuals
![image](https://user-images.githubusercontent.com/34507086/176774957-c99caa26-ace8-48a4-b5ff-3357c59609a4.png)

## Additional Context
The URL is escaped, The '&' are replaced by '&' and the nonce is not regognized.
Example with localhost:
Escaped URL: `https://localhost/test-give/?give_action=preview_email&#038;email_type=donation-receipt&#038;_wpnonce=cdfe35823e&preview_id=134`
Expected URL: `https://localhost/test-give?give_action=preview_email&email_type=donation-receipt&_wpnonce=cdfe35823e&preview_id=134`

**Comment by JasonTheAdams** [comment]
Hi @Genevieve-K!

Thank you for reporting this! I just threw together a PR to fix this: https://github.com/impress-org/givewp/pull/6508

Would you be so kind as to test that and make sure it resolves the issue for you as well? You can also download a zip here if you'd prefer to do that: https://github.com/impress-org/givewp/actions/runs/2619432075

Much appreciated!
