### ISSUE TITLE
The donation total should display rounded values when the "decimal amounts" option is disabled

### ISSUE THREAD

**Issue by glaubersilva** [impress-org/givewp#6544]
## User Story

When using a multi-step form with the "decimal amounts" option disabled, the custom decimal amounts get rounded, but the "donation total" keeps displaying the decimal amount without rounded it.

## Details

To disable decimal amounts go to: 
`Your Form > Form Template > Visual Appearance > Decimal amounts`

## Expected Behavior

The same rounded value from the custom amount should be displayed on the donation total 

## Steps to Reproduce

1. Setup a multi-step form with the "decimal amounts" option disabled
2. Make a test donation with a custom decimal amount and exit from the input to see the rounded value
3. Go to the next step in the form and before finishing the donation, on the "donation total" you should see the NOT rounded value

## Visuals

![decimal-values rounded-bug](https://user-images.githubusercontent.com/16308864/185387661-1931e39a-af86-4a23-b226-20a2faacfbee.gif)

## Acceptance Criteria

-   [ ] The value in the “donation total” accurately reflects the rounded custom decimal amount.

**Comment by ash2osh** [comment]
same issue here is there a fix ??

**Comment by ma-ilsi** [comment]
Hello! I believe the error is caused by `fee-recovery` frontend code. However, after tracking down everything in dev tools, I came to look at the source file but cannot find the `fee-recovery` code nor from where it may be generated. Any ideas?
