### ISSUE TITLE
From [3339] Fees visible in give_total - Bug reappeared in version 1.9.8

### ISSUE THREAD

**Issue by Gecrator996** [impress-org/givewp#6620]
@kjohnson So glad you answered, just checked - i am on version 1.9.8, so interesting i have lifetime tendency on stepping on bugs wherever i go, its my luck, i guess that's what led me into Development,

So yeah i am telling you i have this issue in version 1.9.8, let's dig in, who knows how many people have it as well, hope it's just device specific.

_Originally posted by @Gecrator996 in https://github.com/impress-org/givewp/issues/3339#issuecomment-1338950783_

**Comment by Gecrator996** [comment]
WordPress Environment
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: heavy_check_mark
Language: en_US
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: page
Page on Front: Home page (https://github.com/impress-org/givewp/issues/73)
Page for Posts: Blog (https://github.com/impress-org/givewp/issues/100)
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, hidden, expired, preview, spam, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, new, interviewed, offer, hired, rejected, archived

Server Environment
Hosting Provider: DBH: localhost, SRV: [redacted for privacy]
TLS Connection: Connection uses TLS 1.3
TLS Connection: Probably Okay
Server Info: LiteSpeed
PHP Version: 8.1.9
PHP Post Max Size: 64 MB
PHP Time Limit: 360
PHP Max Input Vars: 1000
PHP Max Upload Size: 64 MB
cURL Version: 7.81.0, OpenSSL/3.0.2
SUHOSIN Installed: –
Default Timezone is UTC: heavy_check_mark
fsockopen/cURL: heavy_check_mark
SoapClient: heavy_check_mark
DOMDocument: heavy_check_mark
gzip: heavy_check_mark
GD Graphics Library: heavy_check_mark
Multibyte String: heavy_check_mark
Remote Post: heavy_check_mark
Remote Get: heavy_check_mark

GiveWP Configuration
GiveWP Version: 2.23.2
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Updates: All Database Migrations Completed.
Database Tables: heavy_check_mark wp_give_donorsheavy_check_mark wp_give_donormetaheavy_check_mark wp_give_commentsheavy_check_mark wp_give_commentmetaheavy_check_mark wp_give_sessionsheavy_check_mark wp_give_formmetaheavy_check_mark wp_give_sequential_orderingheavy_check_mark wp_give_donationmetaheavy_check_mark wp_give_revenueheavy_check_mark wp_give_migrationsheavy_check_mark wp_give_log
GiveWP Cache: Enabled
GiveWP Cache: heavy_check_markNew Donationheavy_check_markDonation ReceiptxNew Offline DonationxOffline Donation Instructionsheavy_check_markNew User Registrationheavy_check_markUser Registration Informationheavy_check_markDonation Noteheavy_check_markEmail accessheavy_check_markDaily Email Reportheavy_check_markWeekly Email Reportheavy_check_markMonthly Email Report
Upgraded From: 2.23.2
Test Mode: Disabled
Currency Code: USD
Currency Position: Before
Decimal Separator: .
Thousands Separator: ,
Success Page: https://visionecorp.com/donation-confirmation/
Failure Page: https://visionecorp.com/donation-failed/
Donation History Page: https://visionecorp.com/donor-dashboard/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Stripe - Apple Pay, Stripe - Google Pay, Stripe - Checkout
Default Payment Gateway: Stripe - Apple Pay
PayPal IPN Notifications: N/A
Donor Email Access: Enabled
Stripe Webhook Notifications: December 6, 2022 3:50 am

Active GiveWP Add-ons
Give - Annual Receipts: heavy_check_mark Licensed – by GiveWP – 1.1.0
Give - BitPay: Free addon – by GiveWP – 1.0.0
Give - Currency Switcher: heavy_check_mark Licensed – by GiveWP – 1.5.2
Give - Email Reports: heavy_check_mark Licensed – by GiveWP – 1.1.4
Give - Fee Recovery: heavy_check_mark Licensed – by GiveWP – 1.9.8
Give - Form Field Manager: heavy_check_mark Licensed – by GiveWP – 2.0.3
Give - Funds and Designations: heavy_check_mark Licensed – by GiveWP – 1.1.0
Give - Google Analytics Donation Tracking: heavy_check_mark Licensed – by GiveWP – 2.1.0
Give - Manual Donations: heavy_check_mark Licensed – by GiveWP – 1.6.1
Give - PayPal Pro Gateway: heavy_check_mark Licensed – by GiveWP – 1.3.0
Give - PDF Receipts: heavy_check_mark Licensed – by GiveWP – 2.3.13
Give - Per Form Gateways: heavy_check_mark Licensed – by GiveWP – 1.0.2
Give - Stripe Gateway: heavy_check_mark Licensed – by GiveWP – 2.5.0
Give - Text-to-Give: heavy_check_mark Licensed – by GiveWP – 1.0.2

Other Active Plugins
Akismet Anti-Spam: by Automattic – 5.0.2
Breadcrumb NavXT: by John Havlik – 7.1.0
Burst Statistics - Privacy-Friendly Analytics for WordPress: by Really Simple Plugins – 1.3.1
CMB2: by CMB2 team – 2.10.1
CMB2 Field Slider: by Matt Krupnik – 1.1.2
Coming Soon Page, Maintenance Mode, Landing Pages & WordPress Website Builder by SeedProd: by SeedProd – 6.15.6
Contact Form 7: by Takayuki Miyoshi – 5.6.4
Cookie Notice & Compliance for GDPR / CCPA: by Hu-manity.co – 2.4.2
Elementor: by Elementor.com – 3.8.1
Envato Market: by Envato – 2.0.7
Jetpack: by Automattic – 11.6-a.5
LiteSpeed Cache: by LiteSpeed Technologies – 5.3
MAS Companies For WP Job Manager: by MadrasThemes – 1.0.6
MAS Company Reviews For WP Job Manager: by MadrasThemes – 1.0.2
Purethemes.net CPT: by Purethemes.net – 1.1
Regions for WP Job Manager: by Astoundify – 1.18.2
Slider Revolution: by ThemePunch – 6.5.31
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com, DavidAnderson – 2.22.23.1
WorkScout-Core - WorkScout WPJM Plugin by Purethemes: by Purethemes.net – 1.5.11
WorkScout Activator: by purethemes – 1.0
WorkScout Elementor: by Purethemes.net – 1.0.6
WP-PageNavi: by Lester 'GaMerZ' Chan – 2.94.0
WP File Manager: by mndpsingh287 – 7.1.6
WPForms: by WPForms – 1.7.8
WP Job Manager: by Automattic – 1.38.1
WP Job Manager - Alerts: by Automattic – 1.5.4
WP Job Manager - Application Deadline: by Automattic – 1.2.5
WP Job Manager - Applications: by Automattic – 2.5.2
WP Job Manager - Bookmarks: by Automattic – 1.4.2
WP Job Manager - Job Tags: by Automattic – 1.4.2
WP Job Manager - Resume Manager: by Automattic – 1.18.4
WP Job Manager - WooCommerce Paid Listings: by Automattic – 2.9.4
WP Mail SMTP Pro: by WPForms – 3.6.1

Inactive Plugins
All-in-One WP Migration: by ServMask – 7.68
All in One SEO: by All in One SEO Team – 4.2.7.1
Complianz - Terms and Conditions: by Really Simple Plugins – 1.1.3
Complianz | GDPR/CCPA Cookie Consent: by Really Simple Plugins – 6.3.5
DoLogin Security: by WPDO – 3.5.1
Google Analytics for WordPress by MonsterInsights: by MonsterInsights – 8.10.1
Hello Dolly: by Matt Mullenweg – 1.7.2
RafflePress Lite: by RafflePress – 1.11.0
Really Simple SSL: by Really Simple Plugins – 6.0.11
WooCommerce: by Automattic – 7.1.0
WPForms Lite: by WPForms – 1.7.8

Theme
Name: WorkScout
Version: 3.0.11
Author URL: http://purethemes.net/
Child Theme: No – If you're modifying GiveWP on a parent theme you didn't build personally, then we recommend using a child theme. See: How to Create a Child Theme

**Comment by Gecrator996** [comment]
Currently have 3 donations - for 1$ + 34 cents (fees) and it shows:
Hey! We've raised $4.02 of the $25,000.00 we are trying to raise for this campaign!

But it suppose to be:
Hey! We've raised $3.00 of the $25,000.00 we are trying to raise for this campaign!

Short code i am using:

[give_totals give_form="282" total_goal="25000" link="example.com"]
Will provide best of my knowledge and assistance, if you have any ideas let me know,

**Comment by kjohnson** [comment]
@Gecrator996 I would suggest reaching out to the [support team](https://givewp.com/support/) for troubleshooting this issue. They are best equipped to help you get to the bottom of the issue and then partner with the development team to write, test, and release a possible fix.
