### ISSUE TITLE
[Tributes addon] should display the tribute even if only its last name is given

### ISSUE THREAD

**Issue by pulsovi** [impress-org/givewp#6720]
## User Story

As a webmaster, I want `[give_donor_wall show_tributes=1]` shortcode to display tributes even when only the last name of the tribute is filled in form.

## Details

When a donation has a tribute with first name empty and last name filled, the tribute does not appear on the donor wall.

## Expected Behavior

The initial of the name of the tribute should appear.

**Comment by kjohnson** [comment]
Hey @pulsovi - thanks for the bug report. I'm reviewing the PR now.
