### ISSUE TITLE
Bitcoin support in Donations page and All Forms page

### ISSUE THREAD

**Issue by brunoferreiralkn** [impress-org/givewp#6744]
## User Story
When Bitcoin is defined as currency for Give, I can't see the donations on the new table (only on the legacy) and I can't access the "All  Forms" page due to a PHP error caused by moneyphp dependency.

## Expected Behavior

Give should be able to handle all the currencies it lists on the Currency tab.

## Steps to Reproduce

1. Go to Give settings on General > Currency and set Bitcoin as currency.
2. Go to a multi step form a make a donation with Bitcoin.
3. Then, go to Give "Donations" page and the new version of the table will show "There was a problem retrieving the donations".
4. Switch to the legacy view, and you will be able to see the donations.
5. Then, try to access the Give "All Forms" page, you will see a PHP error if you have your debugging enabled.

### Error in Donations page:
![image](https://user-images.githubusercontent.com/84975603/226416984-ff09d558-c01d-468a-9ca8-3a586ce546df.png)

With legacy view, I can see the donations:
![image](https://user-images.githubusercontent.com/84975603/226417146-3cc53312-5dce-4c47-a998-8ee4d18f47f0.png)

### Error in "All Forms" page
![image](https://user-images.githubusercontent.com/84975603/226417222-e1cf9e18-763d-428d-b3cb-424418c7b0d0.png)

## System Information

<details><summary>Environment</summary>
WordPress: 6.1.1, from offical WP image for Docker (wordpress:php7.4-apache)
PHP: 7.4
Give: 2.52.2
</details>

## Acceptance Criteria

-   [x] Support for Bitcoin in Donations page
-   [x] Support for Bitcoin in All Forms page

**Comment by JoshuaHungDinh** [comment]
H @brunoferreiralkn, we appreciate you taking the time to write a detailed issue report. I'll confirm the issue and pass it along to be prioritized. Thanks!

**Comment by JoshuaHungDinh** [comment]
Hi @brunoferreiralkn @souzadavi, we are currently wrapping up prior work on exciting new things for Give. We are aiming to address this specific issue in the next 1-2 weeks.
