### ISSUE TITLE
Support: Issue connecting to the PayPal SDK

### ISSUE THREAD

**Issue by Lombardoc4** [impress-org/givewp#6767]
## User Story

As a dev, I want to connect to Paypal sdk so that I can process payments.

## Details

Loading failed for the <script> with source “https://www.paypal.com/sdk/js?client-id=AcRK72f0m_m2e7VGhXWg_n4J8urN2kuTp_ORkY_z1hbUdF31g3R2eG852zO5mp3QIYZVBLc2bbjnAEfA&merchant-id=D5G6JNXWT5CTY&components=hosted-fields,buttons&locale=en&disable-funding=credit&vault=false&enable-funding=venmo&intent=capture&currency=USD”.

## Expected Behavior

Load the script with proper Locale variable
“https://www.paypal.com/sdk/js?client-id=AcRK72f0m_m2e7VGhXWg_n4J8urN2kuTp_ORkY_z1hbUdF31g3R2eG852zO5mp3QIYZVBLc2bbjnAEfA&merchant-id=D5G6JNXWT5CTY&components=hosted-fields,buttons&locale=**en_US**&disable-funding=credit&vault=false&enable-funding=venmo&intent=capture&currency=USD”

## Steps to Reproduce

Apply PayPal Payment gateway
Connect Account
Load a test form
View error : "A problem has occurred with the connection between this site and PayPal, preventing donations. Please contact site administrators if reloading the page does not fix the issue. This is usually the result of some JavaScript conflict on the page."

## Visuals

<img width="589" alt="Screen Shot 2023-04-06 at 10 01 53 AM" src="https://user-images.githubusercontent.com/36197748/230401189-21fe8afa-f0e1-4924-9be0-7caaa68f5d30.png">

PayPal Docs for Locale
https://developer.paypal.com/sdk/js/configuration/#link-locale

## System Information

<details><summary>Details</summary>

MacBook Pro (Retina, 15-inch, Mid 2015)
2.8 GHz Quad-Core Intel Core i7
16 GB 1600 MHz DDR3

</details>

## Acceptance Criteria

Not sure... 
-   [ **X** ] Something happens when an action is taken.
-   [x] Something does not happen when an action is taken.
-   [ ] Fixing behavior in Component A does not affect existing behavior in Component B.

**Comment by jonwaldstein** [comment]
@Lombardoc4 looks like the locale variable is coming from the WP [function](https://developer.wordpress.org/reference/functions/get_locale/) `get_locale()` 

Maybe something is hooking into that filter instead of using the WP settings?
