### ISSUE TITLE
Plaid/Stripe api error

### ISSUE THREAD

**Issue by jacobnoah** [impress-org/givewp#6799]
## User Story

As a user of GiveWP I should be able to use the Plaid/Stripe integration without an api error in production

## Details

When I load the plaid iFrame I immediately get an api error when in production for Plaid/Stripe. The main issue as noted by the Plaid team is when doing the /link/token/create method, giveWP is using the 'Transactions' product which the plaid team is claiming is not needed. We have tried enabling the product which ends up going into manual review by the plaid team only for them to tell us three different times that we need to just remove the transactions product call on link/token/create endpoint. Is Transactions actually needed by any users of giveWP? I would love if we could possibly remove this so we could get the integration to work.

## Expected Behavior

I click plaid as an option at donate checkout. I am directed to the plaid iFrame as normal.

## Acceptance Criteria

-   [ ] Plaid production works when I click checkout.
-   [ ] Development mode for plaid works when I process a donation (same issue just occurs later in the process and plaid logs says inavlid_product_id -> for transactions product call)

**Comment by kjohnson** [comment]
Hey @jacobnoah, have you reached out to the support team about this? They have a process to troubleshoot and then get the change into the development workload outside of our regularly scheduled work.
