### ISSUE TITLE
Styles produced in gutenberg.js interfere with important editor features.

### ISSUE THREAD

**Issue by troyvassalotti** [impress-org/givewp#6843]
## User Story

As an author, I want to use filters in the Query Loop block and be able to read the labels of the fields I'm filtering on.

## Details

Field labels are being hidden with CSS coming from `gutenberg.js` in a way that makes it impossible to know what field I'm filling out.

```css
.components-form-token-field label {
  display: none !important;
}
```

## Expected Behavior

Styles generated with this plugin should not hide irrelevant content from the editor.

## Steps to Reproduce

1. Go to any page and edit it.
2. Add a Query Loop block and check off a filtering option.
3. The filter field will appear in the filtering section but no labels are present.

## Visuals

![image](https://github.com/impress-org/givewp/assets/45142012/7345f770-95c5-45df-9c01-8d9011d7c2eb)

## Additional Context

I found the classes are coming from the file `gutenberg.js` in `give/assets/dist/js`.

## Acceptance Criteria

- [ ] I should be able to see these field labels while keeping the plugin active.

**Comment by kjohnson** [comment]
It look like we should have added this style rule under the `.give-donor-wall-inspector` rules, so that it is prefixed (like with `.give-form-grid-inspector`).
