### ISSUE TITLE
Conditionally shown fields do not apply default values

### ISSUE THREAD

**Issue by kjohnson** [impress-org/givewp#6891]
## Details

When a field is show conditionally (after initially being hidden) the default value for that field is not applied.

## Expected Behavior

Default values should be applied when a field is conditionally shown, since the

## Steps to Reproduce

1. Add a Radio field
2. Add another Radio Field with a default value
3. Conditionally show the second Radio field based on the first

## Visuals

![image](https://github.com/impress-org/givewp/assets/10858303/14835f45-f5b2-4bee-abb0-e4ec5b1ac53d)

**Comment by JasonTheAdams** [comment]
All set, @kjohnson! Thanks so much for making the Issues to help improve conditions as you use them in Tributes! Love seeing this feature get battle tested! 💪
