### ISSUE TITLE
[New functionality] allow recurring subscriptions with crypto

### ISSUE THREAD

**Issue by krasi-georgiev** [impress-org/givewp#6980]
## User Story

As a crypto enthusiast, I want an automated way to donate monthly.

## Details

I think bitpay doesn't allow automated crypto subscriptions and just sends email reminders.
I think crypto.com allow fully automated crypto subscriptions.

**Comment by JasonTheAdams** [comment]
Hi @krasi-georgiev! Thanks for sharing your idea! The best place to share feedback is at feedback.givewp.com — which allows us to aggregate everyone's ideas and see which are in highest demand. Our Github is only reviewed by the engineering team, not the product team, so this wouldn't get considered for the roadmap. As such, I'm going to close this out, but encourage you to hop over and provide your idea over there!

**Comment by krasi-georgiev** [comment]
https://feedback.givewp.com/feature-requests/p/allow-recurring-subscriptions-with-crypto
