### ISSUE TITLE
FontAwesome inclusion in frontend should be optional in GiveWP v3

### ISSUE THREAD

**Issue by fidoboy** [impress-org/givewp#7010]
Right now all Font Awesome css and font are being included in /give/build/baseFormDesignCss.css but may be the WordPress theme or other plugins already includes Font Awesome, so this becomes unnecessary and duplicate resources loading into the browser. My suggestion is to add a switch in GiveWP v3 settings to allow disable Font Awesome CSS and font files in front end. This way, if FA is being loaded by another methods GiveWP doesn't need to load them again and it still could keep using symbols and styles from this font. It should display an advert to the user into the settings where it says that it leaves the responsability into the user hands because disabling FA load assumes that it's being loaded by other ways.

**Comment by kjohnson** [comment]
Hey @fidoboy, thanks for providing feedback.

To keep with the workflow to make sure that the right people see this feedback, I have migrated your feedback to https://feedback.givewp.com.

See https://feedback.givewp.com/feature-requests/p/fontawesome-inclusion-in-frontend-should-be-optional-in-givewp-v3

**Comment by fidoboy** [comment]
> Hey @fidoboy, thanks for providing feedback.
> 
> To keep with the workflow to make sure that the right people see this feedback, I have migrated your feedback to https://feedback.givewp.com.
> 
> See https://feedback.givewp.com/feature-requests/p/fontawesome-inclusion-in-frontend-should-be-optional-in-givewp-v3
> 
> Please add yourself as a _voter_ to help prioritize the feedback.

Thanks. I believe that this is a must have for any wordpress plugin because Font Awesome usage is very extended and it's not always necessary to load it again and again with every plugin. With a single switch into the settings page many resources duplicated can be avoided easily. So in GiveWP v3 this should be done. Just separate the CSS and fonts files and make a conditional call to the enqueue if the option is activated, that's all.

**Comment by jonwaldstein** [comment]
For context, the included font-awesome css is the free one which is pretty slim.  It was intended for backwards compatibility with v2 form's [classic](https://github.com/impress-org/givewp/blob/develop/src/Views/Form/Templates/Classic/resources/css/form.scss) & multistep template styles which used a mix of font awesome class names and unicodes.  The challenge comes with consistency of icons used in the framework vs offloading to an unknown external resource.

However, in v3 forms scripts and styles are isolated inside the form, so not sure if a theme loading font-awesome would actually have an effect inside the form.

The most notable place we're using font-awesome classnames n v3 forms (that I can think of) is for gateway icons [here](https://github.com/impress-org/givewp/blob/58e2f07aa3c95b2ed89427d7493df4539be6cd4e/src/DonationForms/resources/registrars/templates/fields/Gateways.tsx#L154) - but there are other instances using unicodes as well as people using custom css - we would need to think about before changing how this works.

**Comment by fidoboy** [comment]
> For context, the included font-awesome css is the free one which is pretty slim. It was intended for backwards compatibility with v2 form's [classic](https://github.com/impress-org/givewp/blob/develop/src/Views/Form/Templates/Classic/resources/css/form.scss) & multistep template styles which used a mix of font awesome class names and unicodes. The challenge comes with consistency of icons used in the framework vs offloading to an unknown external resource.
> 
> However, in v3 forms scripts and styles are isolated inside the form, so not sure if a theme loading font-awesome would actually have an effect inside the form.
> 
> The most notable place we're using font-awesome classnames n v3 forms (that I can think of) is for gateway icons [here](https://github.com/impress-org/givewp/blob/58e2f07aa3c95b2ed89427d7493df4539be6cd4e/src/DonationForms/resources/registrars/templates/fields/Gateways.tsx#L154) - but there are other instances using unicodes as well as people using custom css - we would need to think about before changing how this works.

I was talking about the frontend only, not backend. So the issue is a redundant loading of the fonts in frontend. This issue can be easily solved by letting the user to decide if load the font or not. If it is already loaded by another plugin / theme, then it has no sense to load it again. 

In GiveWP advanced settings you only need to add a switch to activate/ deactivate the font loading in frontend pages.

**Comment by jonwaldstein** [comment]
@fidoboy to clarify, our v3 forms that are created using our visual form builder are completely isolated on their own route inside an iframe.  This was intentional to avoid conflicts upstream from themes and plugins.  So, if a theme or plugin is loading font-awesome, it would have no affect on the donation form.

However, I do think a more reliable approach for our forms is to use the SVG icons directly from their js package, instead of using their web fonts and classnames.  It would help preserve the integrity of the icons and [avoid conflicting](https://fontawesome.com/docs/web/use-with/wordpress/install-manually#icon-design-changes) with other versions of font-awesome.

**Comment by fidoboy** [comment]
> @fidoboy The (v3) donation forms will not accept scripts from external plugins or themes unless they specifically hook into the donation form enqueue process. So if a theme loads font-awesome for example, the fonts will not be loaded into the donation form. The only way to load any script, including font-awesome into the donation form would be to physically hook into `givewp_donation_form_enqueue_scripts` and load the script.
> 
> When I talked about using svg icons directly, it was from an internal framework perspective - so we are only loading what we need to use for specific purposes.

I understand it now. So then the GiveWP needs to load the same FontAwesome version than the already included into the theme (or other plugins) to benefit from the browser caching OR it will be better to load only the needed glyphs in SVG format to save bandwidth.

**Comment by jonwaldstein** [comment]
@fidoboy yes, exactly.
