### ISSUE TITLE
Avoid issues with CSS minification processes

### ISSUE THREAD

**Issue by fidoboy** [impress-org/givewp#7011]
The file names like eg, this one: baseFormDesignCss.css should be renamed to standard: baseFormDesignCss.min.css to skip external minification processes in WP cache plugins or Cloudflare. This file baseFormDesignCss.css gives errors if Cloudflare minify it again and it stops working. But it has no problems if the name is baseFormDesignCss.min.css because the .min into the name is universally recognized by almost all plugin and external code minificators. If there is a .min particle, the minificator script skips the file.

It shouldn't be difficult to solve, just adding .min to all filenames where CSS or JS code is already minified.

**Comment by kjohnson** [comment]
Hey @fidoboy, thanks for providing feedback.

To keep with the workflow to make sure that the right people see this feedback, I have migrated your feedback to https://feedback.givewp.com.

See https://feedback.givewp.com/feature-requests/p/avoid-issues-with-css-minification-processes

Please add yourself as a _voter_ to help prioritize the feedback.

**Comment by fidoboy** [comment]
> Hey @fidoboy, thanks for providing feedback.
> 
> To keep with the workflow to make sure that the right people see this feedback, I have migrated your feedback to https://feedback.givewp.com.
> 
> See https://feedback.givewp.com/feature-requests/p/avoid-issues-with-css-minification-processes
> 
> Please add yourself as a _voter_ to help prioritize the feedback.

Thanks for adding it into the to-do list. I do not want to register myself as a voter, but any case this shouldn't be very difficult to accomplish. It's almost mandatory to follow the coding standards.
