### ISSUE TITLE
The give_get_ip() method should return a single IP address by default

### ISSUE THREAD

**Issue by glaubersilva** [impress-org/givewp#7015]
## User Story

As an advanced user and also a general user, I want the `give_get_ip()` function to return only one IP address by default so we can ensure that payments using gateways that rely on this function's return (expecting only one IP address) don't fail.

## Details

Currently, the `give_get_ip()` function searching for any empty values, packs all the IP addresses back into a comma separated string again.

This can cause some payments to fail.  For example, Stripe + Plaid mandate fails when given multiple IP addresses in a string.

Sites using CloudFlare, by default are going to return two IP addresses in the HTTP_X_FORWARDED_FOR where the first is the user's IP and the second is the CloudFlare proxy IP (e.g. "127.0.0.1,172.70.133.31")

The `give_get_ip()` function should only return one IP address.

## Expected Behavior

In all places in the codebase where this function is used, we are expecting a single value. 

This fact can be checked here: https://github.com/search?q=org%3Aimpress-org%20give_get_ip&type=code

So, is expected that this function returns only one IP address by default.

## Steps to Reproduce

1. Setup Cloudflare and Stripe + Plaid in a test site
2. Try to do a test donation and check it will work as expected
3. The test donation should fail

## Acceptance Criteria

-   [ ] Something happens when an action is taken.
-   [ ] Something does not happen when an action is taken.
-   [ ] Fixing behavior in Component A does not affect existing behavior in Component B.

**Comment by jonwaldstein** [comment]
Resolved in #7016
