### ISSUE TITLE
[WP_Background_Process] does not support custom `cron_interval` property

### ISSUE THREAD

**Issue by nk-o** [impress-org/givewp#7064]
We are using the WP_Background_Process library in our plugins (Visual Portfolio, Ghost Kit, etc...), and when your plugin is installed, we see the error:

```
Fatal error: Uncaught TypeError: Unsupported operand types: string * int in .../wp-content/plugins/give/includes/libraries/wp-background-process.php:425
```

This happens when we use the WP_Background_Process with the custom `cron_interval` property. Example from Ghost Kit - https://github.com/nk-crew/ghostkit/blob/58ed4cfe21afb00786603d26983bd07fcff3b2d4/src/classes/class-breakpoints-background.php#L34-L39

To solve this issue, you have to fix your code here - https://github.com/impress-org/givewp/blob/33cffa1cc6a2d64f820411eac1d0b65058d4ed85/includes/libraries/wp-background-process.php#L419-L421

Or use the updated version of the library. Example from the updated library with the fix - https://github.com/deliciousbrains/wp-background-processing/blob/ebbed762c42e70e76573ffbd36e591378ba5f2ee/classes/wp-background-process.php#L648-L650

**Comment by JoshuaHungDinh** [comment]
Hello @nk-o,

Thank you for taking the time to write a detailed report and for bringing it to our attention. I was able to reproduce this error and will discuss it with the team for prioritization.

**Comment by EuropeanWilderness** [comment]
Hi,

we are still running into the error on our website. Once we activate the Give plugin we get the same critical error. Could there be an additional issue. we can give you access to our site to test this yourself.
