### ISSUE TITLE
Notice: Undefined index: post in give/src/Promotions/InPluginUpsells/LegacyFormEditor.php on line 59

### ISSUE THREAD

**Issue by flack** [impress-org/givewp#7092]
## User Story

As an admin, I go to `/wp-admin/nav-menus.php` to edit menus

## Details

above the page content, I get the following notices:

```
( ! ) Notice: Undefined index: post in give/src/Promotions/InPluginUpsells/LegacyFormEditor.php on line 59
Call Stack
#	Time	Memory	Function	Location
1	0.0000	370824	{main}( )	.../nav-menus.php:0
2	0.0001	371560	require_once( 'wp-admin/admin.php )	.../nav-menus.php:13
3	0.0001	372040	require_once( 'wp-load.php )	.../admin.php:34
4	0.0001	372736	require_once( 'wp-config.php )	.../wp-load.php:50
5	0.0001	374168	require_once( 'wp-settings.php )	.../wp-config.php:93
6	0.0260	5754848	do_action( $hook_name = 'plugins_loaded' )	.../wp-settings.php:495
7	0.0260	5755224	WP_Hook->do_action( $args = [0 => ''] )	.../plugin.php:517
8	0.0260	5755224	WP_Hook->apply_filters( $value = '', $args = [0 => ''] )	.../class-wp-hook.php:334
9	0.0261	5810000	Give->init( '' )	.../class-wp-hook.php:310
10	0.0263	5813856	Give->loadServiceProviders( )	.../give.php:271
11	0.0353	7425264	Give\Promotions\ServiceProvider->boot( )	.../give.php:355
12	0.0353	7425264	Give\Promotions\ServiceProvider->bootPluginUpsells( )	.../ServiceProvider.php:35
13	0.0355	7433104	Give\Promotions\InPluginUpsells\LegacyFormEditor::isShowing( )	.../ServiceProvider.php:71

( ! ) Notice: Undefined index: post in give/src/DonationForms/V2/DonationFormsAdminPage.php on line 139
Call Stack
#	Time	Memory	Function	Location
1	0.0000	370824	{main}( )	.../nav-menus.php:0
2	0.3521	29371792	require_once( 'wp-admin/admin-header.php )	.../nav-menus.php:694
3	0.3525	29374120	do_action( $hook_name = 'admin_enqueue_scripts', ...$arg = variadic('nav-menus.php') )	.../admin-header.php:118
4	0.3525	29374496	WP_Hook->do_action( $args = [0 => 'nav-menus.php'] )	.../plugin.php:517
5	0.3525	29374496	WP_Hook->apply_filters( $value = '', $args = [0 => 'nav-menus.php'] )	.../class-wp-hook.php:334
6	0.3532	29392720	Give\Helpers\Hooks::Give\Helpers\{closure:give/src/Helpers/Hooks.php:32-44}( 'nav-menus.php' )	.../class-wp-hook.php:310
7	0.3534	29394232	call_user_func_array:{give/src/Helpers/Hooks.php:43}( $function_name = [0 => class Give\DonationForms\V2\DonationFormsAdminPage { protected $apiRoot = 'http://rfp/wp-json/give-api/v2/admin/forms'; protected $apiNonce = '59b010d09b'; protected $adminUrl = 'http://rfp/wp-admin/'; private $bannerActionUrl = 'http://rfp/wp-admin/admin-ajax.php?action=givewp_show_onboarding_banner'; private $tooltipActionUrl = 'http://rfp/wp-admin/admin-ajax.php?action=givewp_show_upgraded_tooltip'; protected $migrationApiRoot = 'http://rfp/wp-json/give-api/v2/admin/forms/migrate' }, 1 => 'loadEditFormScripts'], $parameters = [0 => 'nav-menus.php'] )	.../Hooks.php:43
8	0.3534	29394328	Give\DonationForms\V2\DonationFormsAdminPage->loadEditFormScripts( 'nav-menus.php' )	.../Hooks.php:43
```

## Expected Behavior

There should be no notices

## Steps to Reproduce

1. Go to WP Admin > Design > Menus

## System Information

<details><summary>Details</summary>

### WordPress Environment ###

Home URL: http://rfp
Site URL: http://rfp
WP Version: 6.3.2
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: de_CH_informal
Permalink Structure: /%year%/%monthnum%/%day%/%postname%/
Show on Front: page
Page on Front: frontpage.com (#9)
Page for Posts: Medienmitteilungen (#2469)
Table Prefix Length: wp_
Table Prefix Length: 3
Table Prefix Status: Acceptable
Admin AJAX: Accessible
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, acf-disabled, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, upgraded

### Server Environment ###

Hosting Provider: DBH: localhost, SRV: rfp
TLS Connection: Connection uses TLS 1.3
TLS Connection: Probably Okay
Server Info: Apache/2.4.55 (Ubuntu)
PHP Version: 7.4.33
PHP Post Max Size: 208 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
PHP Max Upload Size: 200 MB
cURL Version: 7.88.1, OpenSSL/3.0.8
SUHOSIN Installed: –
MySQL Version: 8.0.35
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌Your server does not have the SoapClient class enabled - some gateway plugins which use SOAP may not work as expected.
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ❌wp_remote_get() failed. The GiveWP plugin updater won't work with your server. Contact your hosting provider. Error: cURL error 28: Operation timed out after 5001 milliseconds with 0 bytes received

### GiveWP Configuration ###

GiveWP Version: 3.1.1
GiveWP Cache: Enabled
Database Updates: All DB Updates Completed.
Database Updates: All Database Migrations Completed.
Database Tables: ✔ wp_give_donors✔ wp_give_donormeta✔ wp_give_comments✔ wp_give_commentmeta✔ wp_give_sessions✔ wp_give_formmeta✔ wp_give_sequential_ordering✔ wp_give_donationmeta✔ wp_give_revenue✔ wp_give_migrations✔ wp_give_log
GiveWP Cache: Enabled
GiveWP Cache: ✔New Donation✔Donation Receipt✔Donation Processing Receipt✔New Offline Donation✔Offline Donation Instructions❌New User Registration✔User Registration Information❌Donation Note✔Email access✔Starte dein Projekt Email✔ProjektUpdate✔Erlaubnis des/der Erziehungsberechtigten✔V. Spendenwunsch Organisation✔V. Spendenwunsch Privat✔Gebotwunsch✔Gebot wird gespendet✔Gebot wird nicht gespendet✔Gewinnendes Gebot bezahlt✔Versteigerung endet bald✔V. Spenden einholen Organisation✔V. Spenden einholen Privat✔V. Spendenbestätigung Organisation✔V. Spendenbestätigung Privat✔Benutzer Identifizierung Email
Upgraded From: 3.0.1
Test Mode: Enabled
Currency Code: CHF
Currency Position: After
Decimal Separator: ,
Thousands Separator: '
Success Page: http://rfp/spenden-bestaetigung/
Failure Page: http://rfp/spende-gescheitert/
Donation History Page: http://rfp/donor-dashboard-3/
GiveWP Forms Slug: /donations/
Enabled Payment Gateways: Offline Donation, Virtual payment, payrexx payment method
Default Payment Gateway: payrexx payment method
PayPal IPN Notifications: IPN received for #5851 ( 6VL290535B483072U ) on 07/28/2021 at 16:23. Status VERIFIED
Donor Email Access: Enabled
Stripe Webhook Notifications: 18.08.2021 1:14

### Other Active Plugins ###

Advanced Custom Fields: by WP Engine – 6.2.2
CCB Extras: by CONTENT CONTROL GmbH – 1.0.0
Health Check & Troubleshooting: by The WordPress.org community – 1.7.0
ProfilePress: by ProfilePress Membership Team – 4.13.4
Public Post Preview: by Dominik Schilling – 2.10.0
Redirection: by John Godley – 5.3.10
Smush: by WPMU DEV – 3.14.2
Stop Spammers: by Trumani – 2023.4.1
WP Fastest Cache: by Emre Vona – 1.2.1
WPForms Lite: by WPForms – 1.8.4.1
WP Mail SMTP Pro: by WP Mail SMTP – 3.8.2
WP Multilang: by Valentyn Riaboshtan – 2.4.1
WP Reroute Email: by Sajjad Hossain – 1.5.0
Yoast SEO: by Team Yoast – 21.5

### Inactive Plugins ###

Akismet Anti-spam: Spam Protection: by Automattic - Anti-spam Team – 5.3
Nextend Social Login: by Nextendweb – 3.1.11
WP Mail SMTP: by WP Mail SMTP – 3.9.0

### Theme ###

Name: Custom Theme
Version: 
Author URL: https://contentcontrol.berlin/
Child Theme: Yes
Parent Theme Name: Shapely
Parent Theme Version: 1.2.15
Parent Theme Author URL: https://colorlib.com/

</details>

## Acceptance Criteria

-   [ ] Something happens when an action is taken.
-   [ ] Something does not happen when an action is taken.
-   [ ] Fixing behavior in Component A does not affect existing behavior in Component B.

**Comment by JoshuaHungDinh** [comment]
@flack This issue been added to our task list for prioritization. Thank you for bringing this to our attention!

**Comment by jonwaldstein** [comment]
Resolved via https://github.com/impress-org/givewp/pull/7135
