### ISSUE TITLE
Update ACF Field

### ISSUE THREAD

**Issue by lenunu** [impress-org/givewp#7104]
Hello, I need help updating a field in ACF from custom data fields I have added in the donation form. How can I hook in to the donation submission to call the ACF Update Function?

// Get Give Custom Fields
$ACFPostID = give_get_meta( $data->donationId, 'acf_ID', true );
$myCustomFieldValue = give_get_meta( $data->donationId, 'my_custom_value', true );

//ACF Update function

update_field( 'my_field', $myCustomFieldValue, $ACFPostID );

Thank you!

Miguel Blandon
Lenunu

**Comment by jonwaldstein** [comment]
HI @lenunu 

Are you saying _after_ the donation form creates the donation, you want to update an ACF field?

How are you currently creating your custom GiveWP fields?

**Comment by lenunu** [comment]
I'm using hidden fields in the form, passing the values via via URL Parameters using the This jQuery snippet to auto-populate. 

So yes, after the form submits, I want to update my ACF record with a value.

The Auto Populate Snippet was provided by your support team and I added some additional fields.

See below:

/**
 * AUTO-POPULATE AMOUNT, NAME, and EMAIL FROM URL STRING
 *
 * This jQuery snippet will auto-populate the Give form amount,
 * first and last name, and email address from a URL you provide
 * EXAMPLE: https://example.com/donations/give-form/?amount=46.00&first=Peter&last=Joseph&email=testing@givewp.com
 *
 * Hooking into the single form view.
 *
 * CAVEATS:
 * -- Your form must support custom amounts
 * -- This snippet only supports one form per page as-is
 */
function my_custom_give_populate_amount_name_email() {
	?>
	<script>
		( function( window, document, $, undefined ) {
			'use strict';
			var giveCustom = {};

			giveCustom.init = function() {

				// Are we passed a form ID?
				var form_id = giveCustom.getQueryVariable( 'form_id' ) !== false ? decodeURI( giveCustom.getQueryVariable( 'form_id' ) ) : '';

				if ( form_id !== '' ) {
					// Make to jQuery object.
					var giveForm = $( '.give-form' + giveCustom.getQueryVariable( 'form_id' ) )
				} else {
					// Fallback.
					giveForm = $( '.give-form' );
				}

				// Get the amount from the URL
				var amount = giveCustom.getQueryVariable( 'amount' ) !== false ? decodeURI( giveCustom.getQueryVariable( 'amount' ) ) : '';

				// Update the amount
				var formattedAmount = Give.fn.formatCurrency( amount, {
					symbol: Give.form.fn.getInfo( 'currency_symbol', giveForm ),
					position: Give.form.fn.getInfo( 'currency_position', giveForm )
				}, giveForm );

				// Unformatted amount (for data).
				var unformattedAmount = Give.fn.unFormatCurrency( amount, Give.form.fn.getInfo( 'decimal_separator', giveForm ) );

				// Update the total amount.
				if ( amount ) {
					giveForm.find( '.give-final-total-amount' ).attr( 'data-total', unformattedAmount )
						.text( formattedAmount );
					giveForm.find( '.give-amount-top' ).val(unformattedAmount);
				}

				// Fill personal info fields.

				var firstNamePassedVal = giveCustom.getQueryVariable( 'first' ) !== false ? decodeURIComponent( giveCustom.getQueryVariable( 'first' ) ) : '';
				var lastNamePassedVal = giveCustom.getQueryVariable( 'last' ) !== false ? decodeURIComponent( giveCustom.getQueryVariable( 'last' ) ) : '';
				var emailPassedVal = giveCustom.getQueryVariable( 'email' ) !== false ? decodeURIComponent( giveCustom.getQueryVariable( 'email' ) ) : '';
				var studentPassedVal = giveCustom.getQueryVariable( 'student' ) !== false ? decodeURIComponent( giveCustom.getQueryVariable( 'student' ) ) : '';
				var studentIdPassedVal = giveCustom.getQueryVariable( 'studentid' ) !== false ? decodeURIComponent( giveCustom.getQueryVariable( 'studentid' ) ) : '';

				var firstNameInput = giveForm.find( '#give-first-name-wrap input.give-input' );
				var lastNameInput = giveForm.find( '#give-last-name-wrap input.give-input' );
				var emailInput = giveForm.find( '#give-email-wrap input.give-input' );
				var studentInput = giveForm.find( '.student_c input' );
				var studentIdInput = giveForm.find( 'input#give-studentid-3921-1' );

				if ( firstNamePassedVal !== false && firstNameInput.length > 0 ) {
					firstNameInput.val( firstNamePassedVal );
				}
				if ( lastNamePassedVal !== false && lastNameInput.length > 0 ) {
					lastNameInput.val( lastNamePassedVal );
				}
				if ( emailPassedVal !== false && emailInput.length > 0 ) {
					emailInput.val( emailPassedVal );
				}
				if ( studentPassedVal !== false && studentInput.length > 0 ) {
					studentInput.val( studentPassedVal );
				}
				if ( studentIdPassedVal !== false && studentIdInput.length > 0 ) {
					studentIdInput.val( studentIdPassedVal );
				}
			};

			/**
			 * Get Query Variable from URL.
			 *
			 * @param variable
			 * @returns {string|boolean}
			 */
			giveCustom.getQueryVariable = function( variable ) {
				var query = window.location.search.substring( 1 );
				var vars = query.split( '&' );
				for ( var i = 0; i < vars.length; i ++ ) {
					var pair = vars[ i ].split( '=' );
					if ( pair[ 0 ] == variable ) {
						return pair[ 1 ];
					}
				}
				return false;
			};

			giveCustom.init();

		} )( window, document, jQuery );
	</script>
	<?php
}

add_action( 'give_post_form_output', 'my_custom_give_populate_amount_name_email' );

**Comment by jonwaldstein** [comment]
You can try the hook `do_action('givewp_donation_created', $donation)`.  

I believe custom fields get saved within this action with a priority of the default 10 so you would need to set the priority higher so you are hooking in later when the custom fields are available.

Example:

```
add_action('givewp_donation_created', function(\Give\Donations\Models\Donation $donation) {
    // Get Give Custom Fields
    $ACFPostID = give_get_meta( $donation->id, 'acf_ID', true );
    $myCustomFieldValue = give_get_meta( $donation->id, 'my_custom_value', true );

    //ACF Update function
    update_field( 'my_field', $myCustomFieldValue, $ACFPostID );
}, 11, 1);
```

**Comment by jonwaldstein** [comment]
@lenunu for further discussions please open a new discussion thread via https://github.com/impress-org/givewp/discussions.
