### ISSUE TITLE
[Broken functionality] Paypal connection not working. Neither PayPal Standard nor PayPal Donations

### ISSUE THREAD

**Issue by fidoboy** [impress-org/givewp#7110]
I've tried with old method called PayPal Standard, by manually adding the three required params and also with PayPal Donations and I get a wrong response from PayPal server. It's not working

**Comment by jonwaldstein** [comment]
@fidoboy thanks for reporting this.

We have identified your issue as a support request and encourage you to open a tick via [priority support](https://givewp.com/priority-support) or [support forum ](https://wordpress.org/plugins/give) so our team can help you in more depth and ensure prioritization.
