### ISSUE TITLE
[Broken functionality] Issue with Styling/Missing CC Fields When Fee Recovery Add-On is enabled

### ISSUE THREAD

**Issue by seanannnigans** [impress-org/givewp#7128]
## Details

There is an issue with ALL 3.0 Builder Built Forms when the Fee Recovery Add-On (current stable release - Version 2.1.2) is enabled. It prevents donations or forward motion due to the fields disappearing and styles being wonky.

## Expected Behavior

ALL fields (including the selecting of Donation Frequency should display properly.

## Steps to Reproduce

Installing Fee Recovery Add-On (current stable release - Version 2.1.2)

### How it SHOULD display...
<img width="911" alt="Screenshot 2023-12-06 at 12 17 01 AM" src="https://github.com/impress-org/givewp/assets/11653983/b95099cd-9ba9-4ce1-a27b-5cf5091d7149">
<img width="845" alt="Screenshot 2023-12-06 at 12 17 09 AM" src="https://github.com/impress-org/givewp/assets/11653983/4c18ebda-57fb-411c-af1c-dbef730de05f">

### How it's displaying now...
<img width="904" alt="Screenshot 2023-12-06 at 12 09 54 AM" src="https://github.com/impress-org/givewp/assets/11653983/69641950-d711-4408-9709-25420f8c13e3">
<img width="904" alt="Screenshot 2023-12-06 at 12 09 54 AM" src="https://github.com/impress-org/givewp/assets/11653983/69641950-d711-4408-9709-25420f8c13e3">
<img width="782" alt="Screenshot 2023-12-06 at 12 17 44 AM" src="https://github.com/impress-org/givewp/assets/11653983/290fef43-8222-4c55-8de4-f352def3ddf9">
<img width="803" alt="Screenshot 2023-12-06 at 12 17 29 AM" src="https://github.com/impress-org/givewp/assets/11653983/f8b5a4f8-7a6a-4b79-8827-5b726a9c3649">

## System Information

<details><summary>Details</summary>

- WordPress Core - Version: 6.4.1
- Give Core - Version 3.1.1
- Give Recurring Donations - Version 2.5.1
- Give Fee Recovery - Version 2.1.2
- Give Tributes - Version 2.0.1
- Give Stripe Gateway - Version 2.5.0

</details>

## Acceptance Criteria

-   [ ] Conflict when installing Fee Recovery need to be fixed.

**Comment by JoshuaHungDinh** [comment]
Hi @seanannnigans, thanks for bringing this to our attention. We appreciate your efforts in reporting the issue. I've notified our team for confirmation. In the mean time If you any additional information that may help us identify the error, please dont hesitate to share.

Rest assured, once confirmed we will prioritize fixing this as soon as we can and keep you updated on our progress. Thanks again!

**Comment by jonwaldstein** [comment]
@seanannnigans thanks for reporting this.  

We have identified your issue as a support request and encourage you to open a tick via [priority support](https://givewp.com/priority-support ) or [support forum ](https://wordpress.org/plugins/give) so our team can help you in more depth and ensure prioritization.

**Comment by jonwaldstein** [comment]
@seanannnigans thanks for reporting this.  

We have identified your issue as a support request and encourage you to open a tick via [priority support](https://givewp.com/priority-support ) or [support forum ](https://wordpress.org/plugins/give) so our team can help you in more depth and ensure prioritization.
