### ISSUE TITLE
Legacy form button not changing label

### ISSUE THREAD

**Issue by emanuellopess** [impress-org/givewp#7150]
## User Story

As a website admin, I want the continue button from the Legacy template to change it's label according to the form settings so that our donors can have the button in the language preferred.

## Details

We set the option for the continue button label in the form setting for the legacy template and it doesn't change the front-end label for the button.

## Expected Behavior

The continue button in the front-end form should have the label defined in the settings of the donation form.

## Steps to Reproduce

1. Create a donation form with the Legacy template;
2. Select the "reveal" option for the form;
3. Change the continue button label to anything you wish;
4. On the donation form the continue button remains with the default label "Donate now".

## Visuals

![err-1](https://github.com/impress-org/givewp/assets/74307223/013bdfd2-df8f-4542-a0eb-24e959402fa2)
![err-2](https://github.com/impress-org/givewp/assets/74307223/5ce0e14c-7460-4c44-80a0-9d87d95dc57b)

## Additional Context

This error appeared after update 3.1.2

## System Information

<details><summary>Details</summary>

### WordPress Environment ###

WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: pt_BR
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp7q_
Table Prefix Length: 5
Table Prefix Status: Acceptable
Admin AJAX: Acessível
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, upgraded

### Server Environment ###

Hosting Provider: DBH: localhost
TLS Connection: Conexão usa TLS 1.3
TLS Connection: Probably Okay
Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 512 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
PHP Max Upload Size: 200 MB
cURL Version: 7.87.0, OpenSSL/1.1.1w
SUHOSIN Installed: –
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Post remoto: ✔
Requisição remota do tipo GET: ✔

### GiveWP Configuration ###

GiveWP Version: 3.2.1
GiveWP Cache: Ativado
Database Updates: Todas as atualizações de banco de dados foram concluídas.
Database Updates: All Database Migrations Completed.
Database Tables: ✔ wp7q_give_donors✔ wp7q_give_donormeta✔ wp7q_give_comments✔ wp7q_give_commentmeta✔ wp7q_give_sessions✔ wp7q_give_formmeta✔ wp7q_give_sequential_ordering✔ wp7q_give_donationmeta✔ wp7q_give_revenue✔ wp7q_give_migrations✔ wp7q_give_log
GiveWP Cache: Ativado
GiveWP Cache: ✔Nova doação✔Recibo de doação✔Donation Processing Receipt✔Nova doação off-line✔Instruções de Doação Offline✔Novo cadastro usuário✔Informações de cadastro do usuário✔Observação de doação✔Acesso por e-mail
Upgraded From: 3.2.0
Test Mode: Ativado
Currency Code: BRL
Currency Position: Antes
Decimal Separator: ,
Thousands Separator: .
GiveWP Forms Slug: /donations/

### Theme ###

Name: Twenty Twenty-Two
Version: 1.6
Author URL: https://br.wordpress.org/
Child Theme: não – Se você estiver modificando o GiveWP em um tema ascendente que você não criou pessoalmente, então recomendamos usar um tema descendente. Veja: como criar um tema descendente

</details>

## Acceptance Criteria

-   [ ] After changing the label in donation form settings the donation form label should have the new label.

**Comment by JoshuaHungDinh** [comment]
Hey @emanuellopess, we appreciate your report! We're looking into the issue and working to fix it. Thanks for your patience!
