### ISSUE TITLE
New donation listing amount should have the correct currency

### ISSUE THREAD

**Issue by emanuellopess** [impress-org/givewp#7157]
## User Story

As a website administrator, I want that donations to have the correct currency in the new donations listing so that I can view donations from different currencies more clearly.

## Details

When we have donations with different currencies the donation listing only shows the list with the default currency from the configuration.

## Expected Behavior

Each donation from the listing show the correct donation currency for better view.

## Steps to Reproduce

1. Make a donation with any currency;
2. Change the currency and make another donation;
3. Go to the donation listing with the new view.

## Visuals

![erro-form-values-1](https://github.com/impress-org/givewp/assets/74307223/dbeeb548-5c99-43e1-86e0-71b10c8311ea)
![error-form-values-2](https://github.com/impress-org/givewp/assets/74307223/5c39ab91-b468-43dc-8d1d-787a0505d3bd)

## Additional Context

It didn't happen in the older releases, maybe it started at 3.1.0

## System Information

<details><summary>Details</summary>

### WordPress Environment ###

WP Version: 6.4.2
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: pt_BR
Permalink Structure: /%postname%/
Show on Front: posts
Table Prefix Length: wp7q_
Table Prefix Length: 5
Table Prefix Status: Acceptable
Admin AJAX: Acessível
Registered Post Statuses: publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, refunded, failed, revoked, cancelled, abandoned, processing, preapproval, upgraded

### Server Environment ###

Hosting Provider: DBH: localhost
TLS Connection: Conexão usa TLS 1.3
TLS Connection: Probably Okay
Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 512 MB
PHP Time Limit: 300
PHP Max Input Vars: 1000
PHP Max Upload Size: 200 MB
cURL Version: 7.87.0, OpenSSL/1.1.1w
SUHOSIN Installed: –
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
gzip: ✔
GD Graphics Library: ✔
Multibyte String: ✔
Post remoto: ✔
Requisição remota do tipo GET: ✔

### GiveWP Configuration ###

GiveWP Version: 3.2.2
GiveWP Cache: Ativado
Database Updates: Todas as atualizações de banco de dados foram concluídas.
Database Updates: All Database Migrations Completed.
Database Tables: ✔ wp7q_give_donors✔ wp7q_give_donormeta✔ wp7q_give_comments✔ wp7q_give_commentmeta✔ wp7q_give_sessions✔ wp7q_give_formmeta✔ wp7q_give_sequential_ordering✔ wp7q_give_donationmeta✔ wp7q_give_revenue✔ wp7q_give_migrations✔ wp7q_give_log
GiveWP Cache: Ativado
GiveWP Cache: ✔Nova doação✔Recibo de doação✔Donation Processing Receipt✔Nova doação off-line✔Instruções de Doação Offline✔Novo cadastro usuário✔Informações de cadastro do usuário✔Observação de doação✔Acesso por e-mail
Upgraded From: 3.2.0
Test Mode: Ativado
Currency Code: BRL
Currency Position: Antes
Decimal Separator: ,
Thousands Separator: .
GiveWP Forms Slug: /donations/

### Theme ###

Name: Twenty Twenty-Two
Version: 1.6
Author URL: https://br.wordpress.org/
Child Theme: não – Se você estiver modificando o GiveWP em um tema ascendente que você não criou pessoalmente, então recomendamos usar um tema descendente. Veja: como criar um tema descendente

</details>

## Acceptance Criteria

-   [ ] The new donation listing should show the correct currency.

**Comment by JoshuaHungDinh** [comment]
Hi @emanuellopess,

Thank you for bringing this to our attention. I have notified our team to prioritize this item. In the meantime, if any additional information or insights come up, please don't hesitate to share.
