### ISSUE TITLE
Donation Reports: Payment Methods widget

### ISSUE THREAD

**Issue by Usama-Bin-Khalid-98** [impress-org/givewp#7160]
## Details
Payment methods widget in donation report's overview page is showing all transactions instead of just successful ones, all other widgets on that page however do only show successful ones.

## Expected Behavior
Payment Methods widget should also only show successful donations

## Visuals
actual revenue:
<img width="408" alt="Screenshot 2023-12-27 at 12 46 29 PM" src="https://github.com/impress-org/givewp/assets/121162049/b8f0c1a3-8403-44e8-b306-256a4a76ab25">

shown on payment methods:
<img width="522" alt="Screenshot 2023-12-27 at 12 46 48 PM" src="https://github.com/impress-org/givewp/assets/121162049/8d00e9fc-3c55-45de-8e5e-2b83c9669035">

**Comment by JoshuaHungDinh** [comment]
Hey @Usama-Bin-Khalid-98 

We appreciate you bringing this to our attention and providing us with detailed information. I have confirmed your report on the payment method widget and have notified the team.  

Please feel free to reach out if you have any additional information or insights that might assist us in resolving this more efficiently. Thanks!
