### ISSUE TITLE
Issue on Hook

### ISSUE THREAD

**Issue by ThemeAZ** [impress-org/givewp#7357]
Hi Support team,

Why I use this hook for check donate submit form: when use **one time donate form** is working fine, but on **recurring form** is not work?

`add_action('givewp_donation_updated', 'custom_after_donation', 10, 1);`

Any help en this issue?

Thanks,
Lai

**Comment by JoshuaHungDinh** [comment]
Closing in favor of: https://github.com/impress-org/givewp/discussions/7358
