### ISSUE TITLE
403 error while exporting donations: too long URL

### ISSUE THREAD

**Issue by Genevieve-K** [impress-org/givewp#7420]
### Discussed in https://github.com/impress-org/givewp/discussions/7419

<div type='discussions-op-text'>

<sup>Originally posted by **Genevieve-K** June 20, 2024</sup>
As an administrator, I would like to export donations. For several sites, I get a 403 error. After investigation, I understand that it's due a URL containing too many characters. When we export all fields, the Javascripts `window.location = t.url` failed with an 403 error. If I uncheck some fields, the URL is shorter and the donation file is downloaded.

A idea: the label `give_give_donations_export_option` is used many times. It's difficult to change it because it is used by other plugins.Maybe change it to a short name before creating the URL?

**Comment by kjohnson** [comment]
Closing in favor of #7419 .
