### ISSUE TITLE
[Broken functionality] Entering currency amount in cs_CZ locale does not behave correctly

### ISSUE THREAD

**Issue by weinfurt** [impress-org/givewp#7537]
## User Story

I am using GiveWP plugin in the Czech Republic (cs_CZ locale) and currency is CZK (Czech Koruna) which is placed after the amount value. I'd like to type in the desired amount normally (digit by digit) without any issues.

## Details

Currently, when I type in first digit, then the cursor immediately moves to the end of the input field string. That is after the "Kč" currency label. Then next digit pressed immediately generates NaN error.
Other weird issue is, that when I enter the currency field with some value already there (like the predefined amounts in the Builder), and then just leave the field by clicking elsewhere, the field value is updated with extra "000" ... so from "1 000 Kč" string is suddenly "1 000 000 Kč". The same happens when pressing Delete button. 
I've seen this behavior so far in the Builder under the Donation Options and also in the Custom Amount field
 
## Expected Behavior

The currency input fields should work correctly in all locales no matter if the currency name is before or after the value.

## Steps to Reproduce

Use the latest Give WP plugin with the locale where its currency name is after the value. In my case it is czech locale (cs_CZ).

## Visuals

https://github.com/user-attachments/assets/f9e7d2ba-e11c-4fa8-910f-12fbd5e99700

## System Information

<details><summary>Details</summary>

Give WP 3.16.1

</details>

**Comment by dvlprlat** [comment]
I'm getting the same error, but 6 zeros are added at the end of any amount. So if someone's trying to donate 100 USD the field will be updated with 6 additional zeros resulting in 100,000,000. I've been trying to debug the issue, deactivating all of my other plugins, changing theme and nothing seems to be working. Help please

**Comment by kjohnson** [comment]
@weinfurt @dvlprlat we've identified a similar issue with the Swedish langauge/currency.

The input is parsing the letter `k` in the abbreviation to mean `thousand` (`1k` as `1,000`).

We have a fix currently being tested, see https://github.com/impress-org/givewp/pull/7625.
