### ISSUE TITLE
feat: improve usefulness and performance of the dashboard widget

### ISSUE THREAD

**Issue by DevinWalker** [impress-org/givewp#839]
Right now the dashboard widget is just OK. I propose we add additional functionality:
1. The ability to toggle stats within widget based on time period (today, last week, last month, etc).
2. The stats within the widget should be up to date to the minute - right now it caches for 1 hour and it is confusing
3. Make the display of data and widget design more pleasing (icons, mini-graphs, etc) - see Woos for a good example

**Comment by ravinderk** [comment]
@DevinWalker Can you create a wireframe of dashboard widget? I need you help on this.

**Comment by DevinWalker** [comment]
@ravinderk yeah np I can mock it up.

**Comment by kevinwhoffman** [comment]
Closing since the dashboard widget has been overhauled since this issue was created.
